### ISSUE TITLE
running mask rcnn with 7 gpus throws IndexError

### ISSUE THREAD

**Issue by larroy** [dmlc/gluon-cv#1011]
```
(py3) piotr@54-198-120-41:0:~/gluon-cv (master)+$ python scripts/instance/mask_rcnn/train_mask_rcnn.py --batch-size 32 --gpus 0,1,2,3,4,5,6 --epochs 1 --lr 0.04 --amp --lr-decay-epoch 8,10
--log-interval 10 --val-interval 12 --lr-warmup-factor 0.001 --lr-warmup 250 --executor-threads 8 --kv-store device
[23:49:45] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
[23:49:48] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
[23:49:51] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
[23:49:54] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
[23:49:57] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
[23:50:00] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
[23:50:03] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
loading annotations into memory...
Done (t=14.63s)
creating index...
index created!
loading annotations into memory...
Done (t=0.43s)
creating index...
index created!
/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/parameter.py:678: UserWarning: Constant parameter "maskrcnn0_rpn0_rpnanchorgenerator0_anchor_" does not support grad_req other than "null", and new value "write" is ignored.
  'is ignored.'.format(self.name, req))
INFO:root:Namespace(amp=True, batch_size=32, clip_gradient=-1.0, dataset='coco', disable_hybridization=False, epochs=1, executor_threads=8, gpus='0,1,2,3,4,5,6', horovod=False, kv_store='device', log_interval=10, lr=0.04, lr_decay=0.1, lr_decay_epoch='8,10', lr_warmup='250', lr_warmup_factor=0.001, momentum=0.9, network='resnet50_v1b', norm_layer=None, num_workers=4, resume='', save_interval=1, save_prefix='mask_rcnn_resnet50_v1b_coco', seed=233, start_epoch=0, static_alloc=False, use_fpn=False, val_interval=12, verbose=False, wd=0.0001)
INFO:root:Start training from [Epoch 0]
WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 400, in _worker_fn
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/home/piotr/gluon-cv/gluoncv/data/batchify.py", line 488, in __call__
    self._faster_batchify([ele[:5] for ele in data])
  File "/home/piotr/gluon-cv/gluoncv/data/batchify.py", line 416, in __call__
    sharded_img = self._img_pad(data[0])
  File "/home/piotr/gluon-cv/gluoncv/data/batchify.py", line 249, in __call__
    self._num_shards, True)
  File "/home/piotr/gluon-cv/gluoncv/data/batchify.py", line 59, in _pad_arrs_to_max_length
    ret[i // ret[0].shape[0]][i % ret[0].shape[0]] = arr
  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 449, in __setitem__
    self._set_nd_basic_indexing(key, value)
  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 696, in _set_nd_basic_indexing
    % (key, shape[0]))
IndexError: index 4 is out of bounds for axis 0 with size 4
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/instance/mask_rcnn/train_mask_rcnn.py", line 546, in <module>
    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
  File "scripts/instance/mask_rcnn/train_mask_rcnn.py", line 435, in train
    next_data_batch = next(train_data_iter)
  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 451, in __next__
    batch = pickle.loads(ret.get()) if self._dataset is None else ret.get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: index 4 is out of bounds for axis 0 with size 4
WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
```

**Comment by nikparmar** [comment]
> ```
> (py3) piotr@54-198-120-41:0:~/gluon-cv (master)+$ python scripts/instance/mask_rcnn/train_mask_rcnn.py --batch-size 32 --gpus 0,1,2,3,4,5,6 --epochs 1 --lr 0.04 --amp --lr-decay-epoch 8,10
> --log-interval 10 --val-interval 12 --lr-warmup-factor 0.001 --lr-warmup 250 --executor-threads 8 --kv-store device
> [23:49:45] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
> [23:49:48] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
> [23:49:51] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
> [23:49:54] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
> [23:49:57] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
> [23:50:00] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
> [23:50:03] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
> loading annotations into memory...
> Done (t=14.63s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=0.43s)
> creating index...
> index created!
> /home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/parameter.py:678: UserWarning: Constant parameter "maskrcnn0_rpn0_rpnanchorgenerator0_anchor_" does not support grad_req other than "null", and new value "write" is ignored.
>   'is ignored.'.format(self.name, req))
> INFO:root:Namespace(amp=True, batch_size=32, clip_gradient=-1.0, dataset='coco', disable_hybridization=False, epochs=1, executor_threads=8, gpus='0,1,2,3,4,5,6', horovod=False, kv_store='device', log_interval=10, lr=0.04, lr_decay=0.1, lr_decay_epoch='8,10', lr_warmup='250', lr_warmup_factor=0.001, momentum=0.9, network='resnet50_v1b', norm_layer=None, num_workers=4, resume='', save_interval=1, save_prefix='mask_rcnn_resnet50_v1b_coco', seed=233, start_epoch=0, static_alloc=False, use_fpn=False, val_interval=12, verbose=False, wd=0.0001)
> INFO:root:Start training from [Epoch 0]
> WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
> WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
> WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 400, in _worker_fn
>     batch = batchify_fn([_worker_dataset[i] for i in samples])
>   File "/home/piotr/gluon-cv/gluoncv/data/batchify.py", line 488, in __call__
>     self._faster_batchify([ele[:5] for ele in data])
>   File "/home/piotr/gluon-cv/gluoncv/data/batchify.py", line 416, in __call__
>     sharded_img = self._img_pad(data[0])
>   File "/home/piotr/gluon-cv/gluoncv/data/batchify.py", line 249, in __call__
>     self._num_shards, True)
>   File "/home/piotr/gluon-cv/gluoncv/data/batchify.py", line 59, in _pad_arrs_to_max_length
>     ret[i // ret[0].shape[0]][i % ret[0].shape[0]] = arr
>   File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 449, in __setitem__
>     self._set_nd_basic_indexing(key, value)
>   File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 696, in _set_nd_basic_indexing
>     % (key, shape[0]))
> IndexError: index 4 is out of bounds for axis 0 with size 4
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "scripts/instance/mask_rcnn/train_mask_rcnn.py", line 546, in <module>
>     train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
>   File "scripts/instance/mask_rcnn/train_mask_rcnn.py", line 435, in train
>     next_data_batch = next(train_data_iter)
>   File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 451, in __next__
>     batch = pickle.loads(ret.get()) if self._dataset is None else ret.get()
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
> IndexError: index 4 is out of bounds for axis 0 with size 4
> WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
> WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
> WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
> WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
> WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
> WARNING:root:Batch size cannot be evenly split. Trying to shard 32 items into 7 shards
> ```

did you find a solution?
