### ISSUE TITLE
When training yolov3 with coco, how to merge dog and cat into animal categories?

### ISSUE THREAD

**Issue by YeShangyuan** [dmlc/gluon-cv#1014]
When training yolov3 with coco, how to merge dog and cat into animal categories? Thx.

**Comment by lgov** [comment]
Hi. 

As these classes have been trained separately and have therefore dedicated weights in the last layer, AFAIK you can't just merge two classes.
What I would do is keep the two classes separated in the network. Then, when the inference step returns you 'dog' or 'cat' you map them both to the same class 'animal'.

hth,
Lieven

**Comment by douglas125** [comment]
In my opinion, a more effective approach in terms of mean average precision would be to remap cat and dog into one class in the training set and fine tune on that.

**Comment by dai-ichiro** [comment]
This is sample code.

```
from gluoncv import model_zoo, data, utils
from matplotlib import pyplot as plt

net = model_zoo.get_model('yolo3_darknet53_coco', pretrained=True)


im_fname = utils.download('https://farm2.staticflickr.com/1141/1331801476_ffdb15a173_z.jpg',
                          path='dog_and_cat.jpg')

net.classes[15] = 'animal' #cat->animal
net.classes[16] = 'animal' #dog->animal

x, img = data.transforms.presets.yolo.load_test(im_fname)

class_IDs, scores, bounding_boxs = net(x)

ax = utils.viz.plot_bbox(img, bounding_boxs[0], scores[0],
                         class_IDs[0], class_names=net.classes)

plt.show()
```
