### ISSUE TITLE
Data Parallel Fails with Single GPU for Evaluate in Segmentation Training Script

### ISSUE THREAD

**Issue by mylxiaoyi** [dmlc/gluon-cv#102]
When evaluating in segmentation training script  `train.py`, I get the following error:

```python
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    trainer.validation(args.start_epoch)
  File "train.py", line 162, in validation
    for (correct, labeled, inter, union) in outputs:
TypeError: 'numpy.float32' object is not iterable
```

I think the reason is the following line

https://github.com/dmlc/gluon-cv/blob/c9d5b7952a1a6026b042e225d3ab53e6a777b91e/gluoncv/model_zoo/segbase.py#L82

the above line return a tuple, and you make a conversion at the following line

https://github.com/dmlc/gluon-cv/blob/c9d5b7952a1a6026b042e225d3ab53e6a777b91e/gluoncv/utils/parallel.py#L53

I think it makes no change for the returned result.

Related Issue: https://github.com/dmlc/gluon-cv/issues/95

**Comment by zhanghang1989** [comment]
Addressed in https://github.com/dmlc/gluon-cv/pull/103. Please let me know how it works.  Thanks

**Comment by mylxiaoyi** [comment]
Now it works fine.

But the `test.py` script caused TypeError

```python

Traceback (most recent call last):
  File "test.py", line 59, in <module>
    test(args)
  File "test.py", line 47, in test
    predicts = evaluator.parallel_forward(data)
  File "/home/mylxiaoyi/.local/lib/python3.5/site-packages/gluoncv-0.2.0-py3.5.egg/gluoncv/model_zoo/segbase.py", line 161, in parallel_forward
TypeError: __call__() takes 2 positional arguments but 4 were given

```

**Comment by zhanghang1989** [comment]
Thanks for pointing out. It is fixed in https://github.com/dmlc/gluon-cv/pull/110

**Comment by mylxiaoyi** [comment]
Now it works fine, but there is another problem.

The shape of the output of the `test.py` script is width x 21, it is not the correct result obviously.

I think the reason is the following line

https://github.com/dmlc/gluon-cv/blob/c587dd3099c644eb08436be88175846bff4fb805/scripts/segmentation/test.py#L48

Before the line, the shape of the predicts is e.g. (1,21,366,500), but after the line, the shape of predict is (21,366,500),  so use `mx.nd.argmax(predict, 1)` will get the wrong result.
