### ISSUE TITLE
Does HardSwish cost much more memory than ReLU6?

### ISSUE THREAD

**Issue by ShoufaChen** [dmlc/gluon-cv#1021]
I just change the `ReLU6()` to `HardSwish()`  based on MobileNetv2. 

The already wored program (which left almost 1G gpu memory) now out of memory?

I'm wondering does Does HardSwish cost much more memory than ReLU6 in theory
or
I just have some bug in my code?

I also test the `ReLU` relative to the `ReLU6`;  and the  `nn.Activation('relu')` costs 2G memory less than `ReLU6`.   Maybe the implementation of the `ReLU6` of Gluoncv can be improved?

**Comment by zhreshold** [comment]
Cudnn implemented relu and naively implemented Relu6 can be different. The recently added fuse operations by nvidia can be a good alternative.

**Comment by ShoufaChen** [comment]
Thank you for your reply. @zhreshold
