### ISSUE TITLE
An suggestion for gluoncv next version

### ISSUE THREAD

**Issue by dbsxdbsx** [dmlc/gluon-cv#1024]
Personally, I pay attention to computer vision, like object detection(OD) and  image caption(IC). According to what I've know about GluonCV, here are some advice:
1.please update OD model, like corner network or center network, if possible, maybe matrix network is better.
2.I hope there would be some models for (single) object tracking,like PySOT, with maskrcnn and so on.
3.I hope there would be a section for IC.
4. sometimes,  a model is anticipated to be not only for OD, but also for IC or other CV tasks.I am not pretty sure, but just come up that maybe there would be something to do to make gluon CV more flexible and more interractive with gluonNLP or other modules.

**Comment by bryanyzhu** [comment]
Hi, thank you for your suggestions. 

1. CenterNet is on the way @zhreshold 

2. There will be tracking models included soon. 

For 3 and 4, there is no roadmap yet due to bandwidth, but they are definitely good directions to go.
