### ISSUE TITLE
SE layers are ignored when constructing se_resnets

### ISSUE THREAD

**Issue by ifeherva** [dmlc/gluon-cv#1027]
`gluoncv.model_zoo.get_model('se_resnet50_v1')`

and

`gluoncv.model_zoo.get_model('resnet50_v1')`

returns the same model since the use_se flag is never used. The error is here:

https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnet.py#L555

**Comment by ifeherva** [comment]
@hetong007

**Comment by ifeherva** [comment]
Interestingly, the code does not work even if I force the use_se flag. In particular I get an error here:

`https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnet.py#L190`

 Check failed: l == 1 || r == 1: operands could not be broadcast together with shapes [2,256,56,56] [2,1024,1,1]

**Comment by ifeherva** [comment]
I believe here

https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnet.py#L163

the correct statement is

`self.se.add(nn.Dense(channels, use_bias=False))`

instead of `self.se.add(nn.Dense(channels * 4, use_bias=False))`

**Comment by bryanyzhu** [comment]
@ifeherva Thank you for pointing this out. We will fix it soon.

**Comment by bryanyzhu** [comment]
Already fixed the issue in PR #1115 , close the issue for now.
