### ISSUE TITLE
Transfer Learning on the Gluon model (Urgent!!!!!!!!!!)

### ISSUE THREAD

**Issue by SirishaRella** [dmlc/gluon-cv#1031]
Hi, 
I have trained a model with my own custom dataset in Gluon using faster_rcnn_resnet50_v1b_voc and saved this model with name model_one.params. (model_one has only one class)

Now, I'm trying to load model_one.params as my pre-trained model and train a different model. However, I'm facing an incompatible shape error. (The new model I'm trying to train has two classes.)

The error says as following:
**AssertionError: Failed loading Parameter 'fasterrcnn0_dense0_weight' from saved params: shape incompatible expected (3, 0) vs saved (2, 2048)**

Please let me know what can I do at this point in time. Any help will be appreciated

Thank you in advance.

**Comment by zhreshold** [comment]
You can load the pretrained weight first with 1 class
```
net = gluoncv.model_zoo.get_model('faster_rcnn_resnet50_v1b_custom', classes=['a'])
net.load_parameters('model_one.params')
```
and then reset the class while preserve the previous weights

```
net.reset_class(['b', 'c'], reuse_weights=['a'])
```

**Comment by SirishaRella** [comment]
It worked. Thank you so much, Zhi Zhang. Appreciate it.
