### ISSUE TITLE
NMS code question

### ISSUE THREAD

**Issue by Edwardmark** [dmlc/gluon-cv#1032]
I am a fresher of gluon-cv, I want to know how you implement nms in ssd model.
Anyone can tell me where the code is? I see there is a tvm convert tutorials of gluon-cv ssd models which includes nms and post-processing operations which can be converted to tvm model directly, I want to know how it works so as to use it in pytorch detection model to conver to tvm.

Thank you very much.
Best,
Edward

**Comment by zhreshold** [comment]
It's written in C++ code in mxnet operators.
TVM can recognize mxnet operators while this may not be true for pytorch because it may be written in pure python otherwise.

**Comment by Edwardmark** [comment]
@zhreshold so can you tell me where the nms code is? I just want to have a look. Thanks.

**Comment by zhreshold** [comment]
@Edwardmark https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/bounding_box-inl.h
