### ISSUE TITLE
yolov3_mobilenet training epoch

### ISSUE THREAD

**Issue by ShoufaChen** [dmlc/gluon-cv#1033]
I found in the training [script](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/yolo3_mobilenet1.0_coco.sh) of the yolov3_mobilenet1.0,  the training epoch is 280, which is a so big number. 

What's the least number of training epoch?

**Comment by zhreshold** [comment]
My best guess is to enlarge learning rate while reduce the epoch to around 150 for example.
