### ISSUE TITLE
Is TSN implemented in ActionRecInceptionV3 ?

### ISSUE THREAD

**Issue by wmlba** [dmlc/gluon-cv#1044]
Hi,
     The use of TSN network is False by default and I cannot see anywhere where you pass the variable use_tsn. Is the TSN network implemented?

If so, how can I specify modality when training on my own dataset?

Regards,

**Comment by bryanyzhu** [comment]
Hi, sorry for the confusion. The `use_tsn` variable is deprecated. If you want to train a TSN model on your dataset, just specify `num_segments` > 1, it will be TSN training.

If `num_segments`=1, it will be standard network.

**Comment by bryanyzhu** [comment]
@wmlba  Just checking, does TSN work on your side?

**Comment by wmlba** [comment]
> Hi, sorry for the confusion. The `use_tsn` variable is deprecated. If you want to train a TSN model on your dataset, just specify `num_segments` > 1, it will be TSN training.
> 
> If `num_segments`=1, it will be standard network.

@bryanyzhu Thanks for your reply. I am assuming that the num_segments matches the concept of segments mentioned in the TSN paper? Also, what's the default modality and how can I specify one? Based on the paper, Optical Flow + Warped Flow + RGB gave the best performance so I am keen on testing them.

Regards.

**Comment by bryanyzhu** [comment]
Hi

1. Yes, the `num_segments` matches the concept of segments in TSN. It's just how many segments we divide the video into. 

2. The default modality is RGB and we only support RGB modality. We don't have flow or warped flow yet at this moment since most recent work focus on 3D conv.

**Comment by wmlba** [comment]
> Hi
> 
> 1. Yes, the `num_segments` matches the concept of segments in TSN. It's just how many segments we divide the video into.
> 2. The default modality is RGB and we only support RGB modality. We don't have flow or warped flow yet at this moment since most recent work focus on 3D conv.

Thanks a lot, that was very useful.
