### ISSUE TITLE
Using Faster RCNN model, one car is detected as Two Cars

### ISSUE THREAD

**Issue by santhapurharsha** [dmlc/gluon-cv#1048]
I copied an image from this link

[https://www.google.com/imgres?imgurl=https%3A%2F%2Fmomentummag.com%2Fwp-content%2Fuploads%2F2015%2F06%2FExplore_Bike_To_Work_Todd_Mecklem.jpg&imgrefurl=https%3A%2F%2Fmomentummag.com%2Ftop-10-reasons-you-should-bike-to-work%2F&docid=0b-eo5A35RA7OM&tbnid=64NfYre6DX8PJM%3A&vet=10ahUKEwimr8HGzPrlAhVKu48KHQg5DN8QMwh0KA4wDg..i&w=850&h=542&bih=1297&biw=2560&q=cars%20andbicycles&ved=0ahUKEwimr8HGzPrlAhVKu48KHQg5DN8QMwh0KA4wDg&iact=mrc&uact=8](url)

I ran the following code 
```
![download](https://user-images.githubusercontent.com/48676275/69312778-e3b0f500-0c55-11ea-9de8-fcfb243d416a.jpg)
![Fcnn](https://user-images.githubusercontent.com/48676275/69312801-f0cde400-0c55-11ea-9aff-9209776001a1.png)

x, orig_img = data.transforms.presets.rcnn.load_test(im_fname)
```

The model detects Two cars, instead of One car.

**Comment by lordfjw** [comment]
It's possible for two reasons: 1. the model is not perfect and makes mistake; 2. the non maximal suppression of the detector doesn't completely remove the redundant bounding boxes. If it's 1, there's nothing much to do without changing models. If it's 2, you can adjust the parameters of non maximal suppression.

**Comment by bryanyzhu** [comment]
@santhapurharsha Just checking, does lordfjw's suggestion solve your problem?
