### ISSUE TITLE
Unsuitable **kwargs passed into gluon.HybridBlock in DarknetV3

### ISSUE THREAD

**Issue by EletronicElephant** [dmlc/gluon-cv#1050]
https://github.com/dmlc/gluon-cv/blob/1e3b71ad51db9a78984e3cdb631b6e0396832169/gluoncv/model_zoo/yolo/darknet.py#L81

In this line, **kwargs is passed into mxnet's `HybridBlock`, whose `__init__` function is
```
class HybridBlock(Block):
    def __init__(self, prefix=None, params=None):
```
and does not accept `**kwargs` as its parameter.

In this situation, as long as `**kwargs` contains anything customed other than `prefix` or `params`, a `TypeError` will be throwed.

In my suggestion, you can consider change the line into 
```
        super(DarknetV3, self).__init__(kwargs.get('prefix', None), kwargs.get('params', None))
```
, passing only necessary parameters into the parent class.

Thank you.

**Comment by zhreshold** [comment]
@EletronicElephant Sounds good to me, can you contribute a PR to resolve it?

**Comment by EletronicElephant** [comment]
> @EletronicElephant Sounds good to me, can you contribute a PR to resolve it?

OK. You can check
https://github.com/dmlc/gluon-cv/pull/1054

Thank you!

**Comment by EletronicElephant** [comment]
Merged.
