### ISSUE TITLE
Pretrained model of mobilenetv3_small contain nan weight

### ISSUE THREAD

**Issue by xiaodaxia** [dmlc/gluon-cv#1052]
Load the pretrained weights, and the first layer has one channel whose weights are all nan.
**import mxnet as mx
params = mx.nd.load(“mobilenetv3_small-33c100a7.params”)
print(params[‘features.0.weight’][8,:,:,:])**
would print out an all nan array.
So Is this an error or am I missing something?

**Comment by zhreshold** [comment]
It's not a bug or something, simply because of the training with that particular hyper-parameter caused some weights to be nan but the outputs are handled correctly to ignore those nans. Have you met any issue so far?

**Comment by xiaodaxia** [comment]
I used mobilenetv3_small as a base network to train a ssd, and then load the network using mxnet. And I found that from the second layer output, 'hardswish1_mul0', all I get is nan, which I think is quite reasonable, as one channel in the first convolution layer all gives 'nan' weight. So I do not know how to solve this issue. I will check how gluon-cv ignored these nan values. Also if they are finally ignored, why not just set it to zero?

**Comment by zhreshold** [comment]
You can rewrite 0 to all NANs, we could possibly handle these during loading the weights, since rewrite the original model file will need to reupload the models on s3.

**Comment by bryanyzhu** [comment]
@xiaodaxia Just a quick check, has your problem being solved?

**Comment by xiaodaxia** [comment]
I later trained a mobilenetv3_ssd from scratch, without loading the default weight. But I still find that the batch_norm layer contains nan value, "expand_bn2_moving_var" layer or "expand_bn3_moving_var". But the model seems work fine. When I have time I will check the uploaded mobilenet_v3 model.
