### ISSUE TITLE
Share benchmark scripts

### ISSUE THREAD

**Issue by djaym7** [dmlc/gluon-cv#1053]
Can anyone share benchmarking scripts used for model_zoo (to reproduce the same throughput results)?
https://gluon-cv.mxnet.io/model_zoo/detection.html    
https://gluon-cv.mxnet.io/model_zoo/segmentation.html

My results with code below have very high variations (MaskRCNN performing much better than yolo3, deeplabV3 performing much better then maskRCNN) while tested mx.gpu(0) on p3.8x large having Tesla v100: 

x=mx.nd.random.randn(...)
net.hybridize()
start=time.time()
for _ in range(1000)
      _ = net(x)
final_time = time.time()-start

**Comment by djaym7** [comment]
@zhreshold anyone you know wrote the scripts ?

For these results ?
![image](https://user-images.githubusercontent.com/12378820/69751761-9d034500-1104-11ea-93fc-5e8a4a0d3b84.png)

**Comment by zhreshold** [comment]
@djaym7 
You need to warm up before doing the real benchmark.
Here's an example repo but it's not up to date: https://github.com/zhreshold/dlmark/tree/gluoncv

**Comment by djaym7** [comment]
Temporarily closing this, will reopen once i am working on it again. Thanks
