### ISSUE TITLE
Using the provided script train.py gives error

### ISSUE THREAD

**Issue by NamTran838P** [dmlc/gluon-cv#1071]
Windows 8, Python 3.8, no GPU

I have looked online for solutions and tried:

```python
for param in self.net.collect_params().values():
    if param._data is None:       
        param.initialize()
```
However, the error remains still. Please advise. Thanks for your help.

### Terminal output (Powershell) for running train.py
PS C:\Users\Nam\Desktop\elen 331 final project> **python train.py --dataset ade20k --model psp --backbone resnet50 --syncbn --epochs 120 --lr 0.01 --checkname mycheckpoint**
Number of GPUs: 0
Namespace(aux=False, aux_weight=0.5, backbone='resnet50', base_size=520, batch_size=16, checkname='mycheckpoint', crop_size=480, ctx=[], dataset='ade20k', dtype='float32', epochs=120, eval=False, kvstore='device', lr=0.01, model='psp', model_zoo=None, momentum=0.9, ngpus=0, no_cuda=False, no_val=False, no_wd=False, norm_kwargs={'num_devices': 0}, norm_layer=<class 'mxnet.gluon.contrib.nn.basic_layers.SyncBatchNorm'>, resume=None, start_epoch=0, syncbn=True, test_batch_size=16, train_split='train', weight_decay=0.0001, workers=16)
self.crop_size 480
PSPNet(
  (conv1): HybridSequential(
    (0): Conv2D(3 -> 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_syncbatchnorm0_', in_channels=64)
    (2): Activation(relu)
    (3): Conv2D(64 -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (4): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_syncbatchnorm1_', in_channels=64)
    (5): Activation(relu)
    (6): Conv2D(64 -> 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  )
  (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_syncbatchnorm2_', in_channels=128)
  (relu): Activation(relu)
  (maxpool): MaxPool2D(size=(3, 3), stride=(2, 2), padding=(1, 1), ceil_mode=False, global_pool=False, pool_type=max, layout=NCHW)
  (layer1): HybridSequential(
    (0): BottleneckV1b(
      (conv1): Conv2D(128 -> 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers1_syncbatchnorm0_', in_channels=64)
      (relu1): Activation(relu)
      (conv2): Conv2D(64 -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers1_syncbatchnorm1_', in_channels=64)
      (relu2): Activation(relu)
      (conv3): Conv2D(64 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers1_syncbatchnorm2_', in_channels=256)
      (relu3): Activation(relu)
      (downsample): HybridSequential(
        (0): Conv2D(128 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_down1_syncbatchnorm0_', in_channels=256)
      )
    )
    (1): BottleneckV1b(
      (conv1): Conv2D(256 -> 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers1_syncbatchnorm3_', in_channels=64)
      (relu1): Activation(relu)
      (conv2): Conv2D(64 -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers1_syncbatchnorm4_', in_channels=64)
      (relu2): Activation(relu)
      (conv3): Conv2D(64 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers1_syncbatchnorm5_', in_channels=256)
      (relu3): Activation(relu)
    )
    (2): BottleneckV1b(
      (conv1): Conv2D(256 -> 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers1_syncbatchnorm6_', in_channels=64)
      (relu1): Activation(relu)
      (conv2): Conv2D(64 -> 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers1_syncbatchnorm7_', in_channels=64)
      (relu2): Activation(relu)
      (conv3): Conv2D(64 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers1_syncbatchnorm8_', in_channels=256)
      (relu3): Activation(relu)
    )
  )
  (layer2): HybridSequential(
    (0): BottleneckV1b(
      (conv1): Conv2D(256 -> 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm0_', in_channels=128)
      (relu1): Activation(relu)
      (conv2): Conv2D(128 -> 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm1_', in_channels=128)
      (relu2): Activation(relu)
      (conv3): Conv2D(128 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm2_', in_channels=512)
      (relu3): Activation(relu)
      (downsample): HybridSequential(
        (0): Conv2D(256 -> 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_down2_syncbatchnorm0_', in_channels=512)
      )
    )
    (1): BottleneckV1b(
      (conv1): Conv2D(512 -> 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm3_', in_channels=128)
      (relu1): Activation(relu)
      (conv2): Conv2D(128 -> 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm4_', in_channels=128)
      (relu2): Activation(relu)
      (conv3): Conv2D(128 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm5_', in_channels=512)
      (relu3): Activation(relu)
    )
    (2): BottleneckV1b(
      (conv1): Conv2D(512 -> 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm6_', in_channels=128)
      (relu1): Activation(relu)
      (conv2): Conv2D(128 -> 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm7_', in_channels=128)
      (relu2): Activation(relu)
      (conv3): Conv2D(128 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm8_', in_channels=512)
      (relu3): Activation(relu)
    )
    (3): BottleneckV1b(
      (conv1): Conv2D(512 -> 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm9_', in_channels=128)
      (relu1): Activation(relu)
      (conv2): Conv2D(128 -> 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm10_', in_channels=128)
      (relu2): Activation(relu)
      (conv3): Conv2D(128 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers2_syncbatchnorm11_', in_channels=512)
      (relu3): Activation(relu)
    )
  )
  (layer3): HybridSequential(
    (0): BottleneckV1b(
      (conv1): Conv2D(512 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm0_', in_channels=256)
      (relu1): Activation(relu)
      (conv2): Conv2D(256 -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm1_', in_channels=256)
      (relu2): Activation(relu)
      (conv3): Conv2D(256 -> 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm2_', in_channels=1024)
      (relu3): Activation(relu)
      (downsample): HybridSequential(
        (0): Conv2D(512 -> 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_down3_syncbatchnorm0_', in_channels=1024)
      )
    )
    (1): BottleneckV1b(
      (conv1): Conv2D(1024 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm3_', in_channels=256)
      (relu1): Activation(relu)
      (conv2): Conv2D(256 -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm4_', in_channels=256)
      (relu2): Activation(relu)
      (conv3): Conv2D(256 -> 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm5_', in_channels=1024)
      (relu3): Activation(relu)
    )
    (2): BottleneckV1b(
      (conv1): Conv2D(1024 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm6_', in_channels=256)
      (relu1): Activation(relu)
      (conv2): Conv2D(256 -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm7_', in_channels=256)
      (relu2): Activation(relu)
      (conv3): Conv2D(256 -> 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm8_', in_channels=1024)
      (relu3): Activation(relu)
    )
    (3): BottleneckV1b(
      (conv1): Conv2D(1024 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm9_', in_channels=256)
      (relu1): Activation(relu)
      (conv2): Conv2D(256 -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm10_', in_channels=256)
      (relu2): Activation(relu)
      (conv3): Conv2D(256 -> 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm11_', in_channels=1024)
      (relu3): Activation(relu)
    )
    (4): BottleneckV1b(
      (conv1): Conv2D(1024 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm12_', in_channels=256)
      (relu1): Activation(relu)
      (conv2): Conv2D(256 -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm13_', in_channels=256)
      (relu2): Activation(relu)
      (conv3): Conv2D(256 -> 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm14_', in_channels=1024)
      (relu3): Activation(relu)
    )
    (5): BottleneckV1b(
      (conv1): Conv2D(1024 -> 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm15_', in_channels=256)
      (relu1): Activation(relu)
      (conv2): Conv2D(256 -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm16_', in_channels=256)
      (relu2): Activation(relu)
      (conv3): Conv2D(256 -> 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers3_syncbatchnorm17_', in_channels=1024)
      (relu3): Activation(relu)
    )
  )
  (layer4): HybridSequential(
    (0): BottleneckV1b(
      (conv1): Conv2D(1024 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers4_syncbatchnorm0_', in_channels=512)
      (relu1): Activation(relu)
      (conv2): Conv2D(512 -> 512, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers4_syncbatchnorm1_', in_channels=512)
      (relu2): Activation(relu)
      (conv3): Conv2D(512 -> 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers4_syncbatchnorm2_', in_channels=2048)
      (relu3): Activation(relu)
      (downsample): HybridSequential(
        (0): Conv2D(1024 -> 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_down4_syncbatchnorm0_', in_channels=2048)
      )
    )
    (1): BottleneckV1b(
      (conv1): Conv2D(2048 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers4_syncbatchnorm3_', in_channels=512)
      (relu1): Activation(relu)
      (conv2): Conv2D(512 -> 512, kernel_size=(3, 3), stride=(1, 1), padding=(4, 4), dilation=(4, 4), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers4_syncbatchnorm4_', in_channels=512)
      (relu2): Activation(relu)
      (conv3): Conv2D(512 -> 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers4_syncbatchnorm5_', in_channels=2048)
      (relu3): Activation(relu)
    )
    (2): BottleneckV1b(
      (conv1): Conv2D(2048 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers4_syncbatchnorm6_', in_channels=512)
      (relu1): Activation(relu)
      (conv2): Conv2D(512 -> 512, kernel_size=(3, 3), stride=(1, 1), padding=(4, 4), dilation=(4, 4), bias=False)
      (bn2): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers4_syncbatchnorm7_', in_channels=512)
      (relu2): Activation(relu)
      (conv3): Conv2D(512 -> 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0_resnetv1s_layers4_syncbatchnorm8_', in_channels=2048)
      (relu3): Activation(relu)
    )
  )
  (head): _PSPHead(
    (psp): _PyramidPooling(
      (conv1): HybridSequential(
        (0): Conv2D(2048 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0__pyramidpooling0_hybridsequential0_syncbatchnorm0_', in_channels=512)
        (2): Activation(relu)
      )
      (conv2): HybridSequential(
        (0): Conv2D(2048 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0__pyramidpooling0_hybridsequential1_syncbatchnorm0_', in_channels=512)
        (2): Activation(relu)
      )
      (conv3): HybridSequential(
        (0): Conv2D(2048 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0__pyramidpooling0_hybridsequential2_syncbatchnorm0_', in_channels=512)
        (2): Activation(relu)
      )
      (conv4): HybridSequential(
        (0): Conv2D(2048 -> 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0__pyramidpooling0_hybridsequential3_syncbatchnorm0_', in_channels=512)
        (2): Activation(relu)
      )
    )
    (block): HybridSequential(
      (0): Conv2D(4096 -> 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (1): SyncBatchNorm(eps=1e-05, momentum=0.9, fix_gamma=False, use_global_stats=False, ndev=0, key='pspnet0__psphead0_syncbatchnorm0_', in_channels=512)
      (2): Activation(relu)
      (3): Dropout(p = 0.1, axes=())
      (4): Conv2D(512 -> 150, kernel_size=(1, 1), stride=(1, 1))
    )
  )
)
C:\Users\Nam\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\gluon\parameter.py:862: UserWarning: Parameter 'pspnet0_resnetv1s_conv0_weight' is already initialized, ignoring. Set force_reinit=True to re-initialize.
  v.initialize(None, ctx, init, force_reinit=force_reinit)
Traceback (most recent call last):
  File "train.py", line 224, in <module>
    trainer = Trainer(args)
  File "train.py", line 138, in __init__
    self.evaluator = DataParallelModel(SegEvalModel(model), args.ctx)
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python37\lib\site-packages\gluoncv\utils\parallel.py", line 170, in __init__
    module.collect_params().reset_ctx(ctx=ctx_list)
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\gluon\parameter.py", line 879, in reset_ctx
    i.reset_ctx(ctx)
  File "C:\Users\Nam\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\gluon\parameter.py", line 464, in reset_ctx
    "has not been initialized."%self.name)
**ValueError: Cannot reset context for Parameter 'pspnet0_resnetv1s_conv0_weight' because it has not been initialized.**

**Comment by hetong007** [comment]
Could you please specify which `train.py`, and what command-line call you worked with?

**Comment by NamTran838P** [comment]
I got that file from GluonCV's website (screenshot attached). I used Windows Powershell.
![Capture (1)](https://user-images.githubusercontent.com/26189749/70119178-94d46980-161e-11ea-8707-e6b2a80219b4.PNG)

**Comment by hetong007** [comment]
@bryanyzhu your kind help can be useful here

**Comment by bryanyzhu** [comment]
Can you try without `--syncbn`? Because you don't have GPU, there is no need to use synchronized batch normalization.  

If it doesn't work, please first go through the [tutorial](https://gluon-cv.mxnet.io/build/examples_segmentation/train_psp.html) line by line in your terminal  This tutorial only use CPU, so you should be able to train your model. 

If you still have difficulty training, please let me know.

**Comment by bryanyzhu** [comment]
@NamTran838P  Any update on the training? and also your issue #1074

**Comment by chenliu0831** [comment]
I'm encountering the same issue for semantic segmentation. Here's some runtime info:

- OSX
- Python 3.7.5
- mxnet: mxnet-1.5.1.post0; gluoncv 0.5.0
- Command line: python3 train.py --dataset pascal_aug --model deeplab --backbone resnet50 --lr 0.001 --crop-size 350

The training script is from https://github.com/dmlc/gluon-cv/blob/v0.5.0/scripts/segmentation/train.py. 

Thanks.

**Comment by chenliu0831** [comment]
FWIW, when "--no-cuda" flag is added the training starts.

`python3 train.py --dataset pascal_aug --model deeplab --backbone resnet50 --lr 0.001 --crop-size 350 --no-cuda`.

Looks like an issue in the training script when it detect CPU/GPUs

**Comment by NamTran838P** [comment]
Hi Yi Zhu,

Sorry I have been so busy so could not respond earlier. I am no longer working on this project. Last I know, the issue was still there. If it could be resolved for other users, that would be great. Thanks a lot.

Best regards,

Nam

**Comment by bryanyzhu** [comment]
@chenliu0831 If there is no GPU, we expect `--no-cuda` is specified, so that the context is correct. 

You can see more details at here,
https://github.com/dmlc/gluon-cv/blob/v0.5.0/scripts/segmentation/train.py#L91-L97

**Comment by chenliu0831** [comment]
Cool. Yea I noticed this when inspecting the the training script. Ideally the documentation should be updated if extra flag is required for CPU only mode. Feel free to close this issue since the extra flag suffice to resolve the issue I encountered (as well as the original issue i think).

**Comment by bryanyzhu** [comment]
Thank you for the feedback, I will update the documentation and close this issue.
