### ISSUE TITLE
Cannot export when using train_psp.py

### ISSUE THREAD

**Issue by NamTran838P** [dmlc/gluon-cv#1074]
Since the script train.py does not work for me #1071, I am using the demo train_psp.py script on GluonCV website to perform training. I have tried two export methods but none suceeded. I am using Windows 10, Python 3.8, CPU only. 

First method:

`model.module.hybridize()`
`model.module.export('psp')`

![2](https://user-images.githubusercontent.com/26189749/70025508-190ceb00-1552-11ea-8d46-fc286596c8c3.PNG)

Second method:

`model.module.hybridize()
export_block('psp', model.module, layout = 'HWC', preprocess = None) `

![1](https://user-images.githubusercontent.com/26189749/70025243-45743780-1551-11ea-89c1-c34d1b8e9046.PNG)

I am training the pspnet model from scratch with only 1 iteration for demo purposes. Please advise how I can proceed to export my trained model successfully.

**Comment by zhreshold** [comment]
When preprocess is none, you should use CHW instead.

export_block('psp', model.module, layout = 'CHW', preprocess = None)

**Comment by bryanyzhu** [comment]
#1071 is fixed. Close this issue as well due to lack of activity.
