### ISSUE TITLE
How to get score for all classes ?

### ISSUE THREAD

**Issue by dangmanhtruong1995** [dmlc/gluon-cv#1076]
Hi, how do I get scores for all classes? For example, there is a dog object, with score 0.9. However I also want the cat score for the same object (0.1). How do I get them ? Thank you very much.

**Comment by bryanyzhu** [comment]
Which application are you referring to, image classification or object detection? 

For image classification, you can find the example [here](https://github.com/dmlc/gluon-cv/blob/master/scripts/classification/imagenet/demo_imagenet.py#L30-L42). You can set `topK` to any other number and find the score you want. 

For object detection, is there an off-the-shelf example? @zhreshold Thank you.

**Comment by bryanyzhu** [comment]
Just a quick check, has your problem fixed?

**Comment by pranav6670** [comment]
@bryanyzhu Can we do the same in JavaScript using tensorflow.js?

**Comment by bryanyzhu** [comment]
@pranav6670 I'm not familiar with tensorflow.js, but as long as you have the final prediction vector, you can do the same to get scores for any class you want.

**Comment by dangmanhtruong1995** [comment]
Hi, my problem is still not fixed, as I do not understand the example very much.

**Comment by bryanyzhu** [comment]
Can you specify more details about your problem? Are you doing image classification or object detection? What is your input and what is your desired output? Thank you.

**Comment by dangmanhtruong1995** [comment]
Hi, I'm doing object detection. My input is an image. My desired output would be a list of bounding boxes, with each bounding box accompanied by a probability vector indicating the probability that box containing a specific object. For example, a bounding box with {cat:0.9, dog:0.1}.

**Comment by bryanyzhu** [comment]
Take SSD model as an example, you can obtain the probability of all classes from this line of [code](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/ssd/ssd.py#L207). We use this function [`MultiPerClassDecoder`](https://github.com/dmlc/gluon-cv/blob/d498543b4f958ba93c551591da6927363999a9e6/gluoncv/nn/coder.py#L375) to get the prediction results. 

However, there is no direct demo or example for your use case. You have to modify the code yourself. This is because non-maximum suppression (NMS) is performed per class. The original results' structure is destroyed after NMS. That's why you will only have a bbox with `cat:0.9`.

**Comment by dangmanhtruong1995** [comment]
Hi, is it possible to get the result before non maximum suppression so that I can do it manually to get the full result ? Also, how did you do NMS ? Tks a lot.

**Comment by zhreshold** [comment]
@dangmanhtruong1995 I am not sure which object detection algorithm you are referring to , SSD/YOLOv3/Faster-RCNN?
They have different intermediate results so there might be different ways to extract full results as you requested.

**Comment by dangmanhtruong1995** [comment]
@zhreshold I want to use YoloV3.

**Comment by zhreshold** [comment]
@dangmanhtruong1995 
I assume you know how to modify the code in gluoncv.
Here's how I would do it to retrieve the intermediate results from yolo3:
Modify line: https://github.com/dmlc/gluon-cv/blob/c9777f674db31853f6c0d206e318657a9bd8e711/gluoncv/model_zoo/yolo/yolo3.py#L419

to 
```python
return ids, scores, bboxes, F.concat(*all_objectness, dim=1)
```
and change nms to disabled by
```python
net.set_nms(-1)
```
