### ISSUE TITLE
model center_net_resnet101_v1b_dcnv2_coco cannt download

### ISSUE THREAD

**Issue by ou525** [dmlc/gluon-cv#1080]
python3.7 and python2
gluoncv            0.6.0b20191126
mxnet-cu100mkl     1.6.0b20191013
CUDA Version 10.0.166
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 3
#define CUDNN_PATCHLEVEL 1
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

when run demo_center_net.py with model center_net_resnet101_v1b_dcnv2_coco, error happen, as follow:
Traceback (most recent call last):
  File "demo_center_net.py", line 23, in <module>
    net = model_zoo.get_model('center_net_resnet101_v1b_dcnv2_coco', pretrained=True)
  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/model_zoo.py", line 314, in get_model
    net = _models[name](**kwargs)
  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/center_net/center_net.py", line 579, in center_net_resnet101_v1b_dcnv2_coco
    base_network = resnet101_v1b_deconv_dcnv2(pretrained=pretrained_base, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/center_net/deconv_resnet.py", line 266, in resnet101_v1b_deconv_dcnv2
    return get_deconv_resnet('resnet101_v1b', **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/center_net/deconv_resnet.py", line 189, in get_deconv_resnet
    use_dcnv2=use_dcnv2, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/center_net/deconv_resnet.py", line 96, in __init__
    self.deconv = self._make_deconv_layer(deconv_filters, deconv_kernels)
  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/center_net/deconv_resnet.py", line 130, in _make_deconv_layer
    "No ModulatedDeformableConvolution found in mxnet, consider upgrade..."
AssertionError: No ModulatedDeformableConvolution found in mxnet, consider upgrade...

@zhreshold can you help me?

**Comment by zhreshold** [comment]
It's the deformable version centernet and your mxnet is not up to date so it's complaining.
You can either use non dcnv2 version or update mxnet to nightly builds

**Comment by ou525** [comment]
my mxnet is the nightly version.
xxx@OptiPlex-7050:~$ sudo pip3 install --pre --upgrade mxnet-cu100mkl
[sudo] password for xxx: 
WARNING: The directory '/home/ou/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/ou/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already up-to-date: mxnet-cu100mkl in /usr/local/lib/python3.7/site-packages (1.6.0b20191013)
Requirement already satisfied, skipping upgrade: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.7/site-packages (from mxnet-cu100mkl) (0.8.4)
Requirement already satisfied, skipping upgrade: numpy<1.15.0,>=1.8.2 in /usr/local/lib/python3.7/site-packages (from mxnet-cu100mkl) (1.14.6)
Requirement already satisfied, skipping upgrade: requests>=2.20.0 in /usr/local/lib/python3.7/site-packages (from mxnet-cu100mkl) (2.22.0)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.20.0->mxnet-cu100mkl) (2.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.20.0->mxnet-cu100mkl) (1.25.6)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.20.0->mxnet-cu100mkl) (2019.9.11)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=2.20.0->mxnet-cu100mkl) (3.0.4)

**Comment by zhreshold** [comment]
You are using 1.6.0b20191013 which is more than 1 month old. The nightly builds are somehow paused to update recently.

**Comment by ou525** [comment]
So recently can I only use non dcnv2 version？

**Comment by zhreshold** [comment]
Or you can build from source

**Comment by ou525** [comment]
Compile which version of the source code to generate the python interface

**Comment by hetong007** [comment]
@ou525 You may compile the latest version of the source code, with guidance on this page: https://mxnet.apache.org/get_started?version=v1.5.1&platform=linux&language=python&environ=build-from-source&processor=gpu

**Comment by zhreshold** [comment]
The nightly builds are now served on s3, you can use

```
pip install https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/2019-12-07/dist/mxnet-cu100mkl-1.6.0b20191207-py2.py3-none-manylinux1_x86_64.whl
```
