### ISSUE TITLE
python 3.6 fails to build gluon-cv: 'ascii' codec can't decode byte 0xf0

### ISSUE THREAD

**Issue by yurivict** [dmlc/gluon-cv#1095]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 45, in <module>
    long_description = open('README.md').read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 6475: ordinal not in range(128)
```

**Comment by bryanyzhu** [comment]
Hi, I can't reproduce your error on my end. I built a python 3.6 environment on Ubuntu 16.04, with CUDA 10. I built gluon-cv from source successfully using

```
conda create -n gluoncv python=3.6
conda activate gluoncv
pip install --pre --upgrade mxnet-cu100
git clone https://github.com/dmlc/gluon-cv
cd gluon-cv && python setup.py install --user
```

Can you report more details, like your system, cuda version, command line you use, etc? Thank you.

**Comment by yurivict** [comment]
It has to do with python-3.6 having ascii as a default codec and non-ascii in README.md

**Comment by bryanyzhu** [comment]
@yurivict Any luck on your end? I use python 3.6 and observe no problem.

**Comment by yurivict** [comment]
I just cleared the README.md file for the port in order for it to build.
You need to set the utf8 codec in python in your project.

**Comment by bryanyzhu** [comment]
@zhreshold  What do you think?

**Comment by zhreshold** [comment]
@yurivict Probably due to your localization setting? 
The README file is in UTF-8 without BOM as the default setting, which is common for many editors.

**Comment by zhreshold** [comment]
@yurivict Can you verify if this solves the problem for you?

```python
# replace long_description = open('README.md').read() in setup.py to 
long_description = open('README.md', encoding="utf-8").read()
```
