### ISSUE TITLE
yolov3. Why is the inference time after int8 quantization on the CPU longer than the unquantized model?

### ISSUE THREAD

**Issue by DuZzzs** [dmlc/gluon-cv#1097]
environment：
```
Ubuntu 16.04.5 LTS
 Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
 CPU(s):  4

pip install gluoncv --upgrade
pip install mxnet-cu100mkl==1.6.0b20191013
```
Modify the code to print out the time（ms/pic） during validation。The command and output are as follows：
 unquantized model:
```
python eval_yolo.py --network=mobilenet1.0 --dataset=coco --batch-size=1 --gpus=''

time cost:  0.3125333786010742
time cost:  0.3112642765045166
time cost:  0.3123941421508789
```
after int8 quantization:
```
python eval_yolo.py --network=mobilenet1.0 --gpus='' --deploy --model-prefix=./model/yolo3_mobilenet1.0_coco-quantized-naive  --dataset=coco --batch-size=1

time cost:  0.5255234241485596
time cost:  0.5221781730651855
time cost:  0.5260343551635742
```
Hello, has anyone encountered this situation?  Why is the inference time longer? Thanks.

**Comment by bryanyzhu** [comment]
@wuxun-zhang @xinyu-intel Can you help with this issue? Thank you.

**Comment by wuxun-zhang** [comment]
@DuZzzs Thank you for trying int8 models. Recently we have one PR being merged into mxnet master, which will bring further speedup for int8 yolo models. Could you please try with latest [mxnet master](https://github.com/apache/incubator-mxnet/commit/a01ded2a04d0736d88dd421b2e2c548bb603a917) or [nightly build](https://repo.mxnet.io/dist/2019-12-17/dist/mxnet_cu100mkl-1.6.0b20191217-py2.py3-none-manylinux1_x86_64.whl) via`pip install https://repo.mxnet.io/dist/2019-12-17/dist/mxnet_cu100mkl-1.6.0b20191217-py2.py3-none-manylinux1_x86_64.whl`?

**Comment by DuZzzs** [comment]
@wuxun-zhang  Thank you. I will try this.

**Comment by DuZzzs** [comment]
@wuxun-zhang  I tried this and the results are as follows:
```
python eval_yolo.py --network=mobilenet1.0 --dataset=coco --batch-size=1 --gpus=''
time cost:  0.20819664001464844
time cost:  0.20491981506347656
time cost:  0.20055627822875977
```

```
python eval_yolo.py --network=mobilenet1.0 --gpus='' --deploy --model-prefix=./model/yolo3_mobilenet1.0_coco-quantized-naive  --dataset=coco --batch-size=1

time cost:  4.688729763031006
time cost:  4.725362777709961
time cost:  4.693424940109253
```
Things got worse.

**Comment by wuxun-zhang** [comment]
How about increasing the `--batch-size`, like `32, or 64`? Trying with different `--num-workers`?

**Comment by DuZzzs** [comment]
No improvement was observed. Thank you.

**Comment by wuxun-zhang** [comment]
Looks that `avx512` instruction set is not supported in your desktop (check `lscpu|grep avx` ). In my opinion, now much of performance benefits brought by int8 models require the support of `avx512` and Intel DL boost. 
@xinyu-intel any suggestion?

**Comment by xinyu-intel** [comment]
Currently, only xeon cpu with avx512_bw and avx512_vnni instructions support int8 acceleration, you can try C5.12 instance on AWS EC2.

**Comment by DuZzzs** [comment]
ok. Thank you very much.
