### ISSUE TITLE
train_recognizer.py

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [dmlc/gluon-cv#1110]
about line 464:
>print(X.shape)
   #Got (25, 1, 3, 224, 224)
   X = X.reshape((-1,) + X.shape[2:])
   print(X.shape)
   #Got (25, 3, 224, 224)
   pred = net(X.astype(opt.dtype, copy=False))

the code make input dim become 4D,but i got wrong:
>Check failed: dshp.ndim() == 5U (4 vs. 5) : Input data should be 5D in batch-num_filter-depth-y-x

is the code have bug?or is my wrong?

急急急！
thank you!

**Comment by ZHEQIUSHUI** [comment]
the model is "i3d_resnet50_v1_custom"

**Comment by bryanyzhu** [comment]
If you want to use i3d_resnet50_v1_custom, which is a 3D CNN, your input needs to be 5D. Something in the form of `batch_size x channel x depth x height x width`.

You need a data volume, which are multiple video frames. So you have to specify `new_length` to be a number larger than 1.

**Comment by ZHEQIUSHUI** [comment]
thank you so much!! this attributes default is "1"...thank you again!!!
