### ISSUE TITLE
about train centernet

### ISSUE THREAD

**Issue by mahxn0** [dmlc/gluon-cv#1125]
when I train centernet,
`python3 train_center_net.py --dataset mydata --dataset-root /home/yd/watch_data --batch-size 8`
pretrain_model is centrenet_dla34_coco.

 i get error AssertionError: HybridBlock requires the first argument to forward be either Symbol or NDArray, but got <class 'list'>
then i add print(x) in /usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py line929
i get  [Symbol relu1_fwd, Symbol relu2_fwd, Symbol level2_root_relu0_fwd, Symbol level3_tree_2_root_relu0_fwd, Symbol level4_tree_2_root_relu0_fwd, Symbol level5_root_relu0_fwd]
<class 'list'>

/home/yd/watch_data train
/home/yd/watch_data test
INFO:root:Namespace(batch_size=4, center_reg_weight=1.0, data_shape=512, dataset='mydata', dataset_root='/home/yd/watch_data', epochs=50, flip_validation=False, gpus='0', log_interval=100, lr=0.000125, lr_decay=0.1, lr_decay_epoch='90,120', lr_mode='step', momentum=0.9, network='resnet18_v1b', num_samples=13044, num_workers=4, resume='', save_interval=10, save_prefix='center_net_dla34_coco', seed=233, start_epoch=0, val_interval=1, warmup_epochs=0, warmup_lr=0.0, wd=0.0001, wh_weight=0.1)
INFO:root:Start training from [Epoch 0]
start train
<Symbol data>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol data>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol data>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol data>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol batchnorm1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol relu1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol relu1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol conv2_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol batchnorm2_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol relu2_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol relu2_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol relu2_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_proj_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol relu2_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol relu2_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_1_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_1_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_1_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_1__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_2_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_2_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_2_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_2__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_concat0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_proj_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_1_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_1_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_1_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_1__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_2_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_2_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_2_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_2__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_root_concat0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_root_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_root_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_1_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_1_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_1_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_1__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_2_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_2_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_2_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_2__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_concat0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_proj_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level3_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_1_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_1_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_1_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_1__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_2_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_2_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_2_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_2__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_root_concat0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_root_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_root_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_1_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_1_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_1_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_1_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_1__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_2_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_2_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_2_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_2__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_root_concat0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_root_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_root_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_maxpoolfwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_proj_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level4_tree_2_root_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_1_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_1_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_1_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_1__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_1_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_2_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_2_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_2_conv1_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_2__plus0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_block_tree_2_relu0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_root_concat0>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_root_conv0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
<Symbol level5_root_batchnorm0_fwd>
<class 'mxnet.symbol.symbol.Symbol'>
222
[[Symbol relu1_fwd, Symbol relu2_fwd, Symbol level2_root_relu0_fwd, Symbol level3_tree_2_root_relu0_fwd, Symbol level4_tree_2_root_relu0_fwd, Symbol level5_root_relu0_fwd]]
<class 'list'>
Traceback (most recent call last):
  File "train_center_net.py", line 307, in <module>
    train(net, train_data, val_data, eval_metric, ctx, args)
  File "train_center_net.py", line 238, in train
    heatmap_pred, wh_pred, center_reg_pred = net(x)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py", line 915, in forward
    return self._call_cached_op(x, *args)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py", line 805, in _call_cached_op
    self._build_cache(*args)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py", line 757, in _build_cache
    data, out = self._get_graph(*args)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py", line 749, in _get_graph
    out = self.hybrid_forward(symbol, *grouped_inputs, **params)  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.5/dist-packages/gluoncv/model_zoo/center_net/center_net.py", line 170, in hybrid_forward
    y = self.base_network(x)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py", line 933, in forward
    return self.hybrid_forward(symbol, x, *args, **params)
  File "/usr/local/lib/python3.5/dist-packages/gluoncv/model_zoo/center_net/deconv_dla.py", line 225, in hybrid_forward
    x = self.dla_up(x)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py", line 930, in forward
    "Symbol or NDArray, but got %s"%type(x)
AssertionError: HybridBlock requires the first argument to forward be either Symbol or NDArray, but got <class 'list'>

**Comment by zhreshold** [comment]
might be related to the `mydata` implementation, did you check the outputs of Dataset that specified for `mydata`?

**Comment by mahxn0** [comment]
@zhreshold  thank you, I have solved it by update mxnet to 1.6.0
