### ISSUE TITLE
 Segmentation fault: 11   libmxnet.so                         

### ISSUE THREAD

**Issue by xxlest** [dmlc/gluon-cv#1129]
I tried  yolov3 train mode with cpu to understand code ,l but reported segmentation fault 
i was block hear for several days didnt get any clue, any one meet this issue?? i tried ssd same isse also

NFO:root:Namespace(batch_size=64, data_shape=416, dataset='voc', epochs=200, gpus='0', label_smooth=False, log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,180', lr_decay_period=0, lr_mode='step', mixup=False, momentum=0.9, network='darknet53', no_mixup_epochs=20, no_random_shape=False, no_wd=False, num_samples=16551, num_workers=1, resume='', save_interval=10, save_prefix='yolo3_darknet53_voc', seed=233, start_epoch=0, syncbn=False, val_interval=1, warmup_epochs=0, warmup_lr=0.0, wd=0.0005)
INFO:root:Start training from [Epoch 0]

Segmentation fault: 11

Stack trace:
  [bt] (0) 1   libmxnet.so                         0x000000010ee782b0 mxnet::Storage::Get() + 4880
  [bt] (1) 2   libsystem_platform.dylib            0x00007fff66bca42d _sigtramp + 29
  [bt] (2) 3   libmxnet.so                         0x000000010f864018 guard variable for dmlc::ThreadLocalStore<mxnet::engine::ThreadedEngine::BulkStatus>::Get()::inst + 686304
  [bt] (3) 4   libmxnet.so                         0x000000010f1b3751 mxnet::Storage::Get() + 3393457
  [bt] (4) 5   libmxnet.so                         0x000000010f050dd5 mxnet::Storage::Get() + 1941045
  [bt] (5) 6   libmxnet.so                         0x000000010f051dba mxnet::Storage::Get() + 1945114
  [bt] (6) 7   libmxnet.so                         0x000000010f03899f mxnet::Storage::Get() + 1841663
  [bt] (7) 8   libmxnet.so                         0x000000010e7d8e61 mxnet::io::ImdecodeImpl(int, bool, void*, unsigned long, mxnet::NDArray*) + 3073
  [bt] (8) 9   libmxnet.so                         0x000000010e7366c7 std::__1::enable_if<(__is_forward_iterator<mxnet::NDArray**>::value) && (is_constructible<mxnet::NDArray*, std::__1::iterator_traits<mxnet::NDArray**>::reference>::value), void>::type std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> >::assign<mxnet::NDArray**>(mxnet::NDArray**, mxnet::NDArray**) + 30295

Segmentation fault: 11

**Comment by zhreshold** [comment]
There might be some bug related to the mxnet build, can you switch to non-mkl version and have a try?

**Comment by xxlest** [comment]
> There might be some bug related to the mxnet build, can you switch to non-mkl version and have a try?

i installed mxnet & gluoncv with "pip install gluoncv --upgrade",  then run the code  prompt  fail check "gcv.utils.check_version('0.6.0')" , and then update  with "pip install gluoncv --pre --upgrade" . anyway,  i set --num-work=0 trainning can be success run,  i debug the code ,looks was pending  in  code line "for i, batch in enumerate(train_data):"  to get next batch data which use event multithreading and pending on wait() thread.   maybe debug status can't trigger event on time.  my install method is any proplem?

**Comment by xinyu-intel** [comment]
which version of mxnet are you using? Can you try `pip install https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/2020-01-05/dist/mxnet_cu92mkl-1.6.0b20200105-py2.py3-none-manylinux1_x86_64.whl` to see if there still bugs?

**Comment by xxlest** [comment]
> which version of mxnet are you using? Can you try `pip install https://apache-mxnet.s3-us-west-2.amazonaws.com/dist/2020-01-05/dist/mxnet_cu92mkl-1.6.0b20200105-py2.py3-none-manylinux1_x86_64.whl` to see if there still bugs?

ok, i will try it later, currenttly i use 1.5.1 mxnet which just install by pip install

**Comment by henrikmatzen** [comment]
If you try it on your local machine use --num-workers=0
This solved the same issue for me
