### ISSUE TITLE
Please add a comment describing what adepallete is and where it is pasted from or how was it generated

### ISSUE THREAD

**Issue by yurivict** [dmlc/gluon-cv#1134]
There are several numeric arrays here without any explanation:

https://github.com/dmlc/gluon-cv/blob/master/gluoncv/utils/viz/segmentation.py#L74

**Comment by bryanyzhu** [comment]
These are the colors corresponding to each class in the dataset. Take Cityscapes palette as an example, the first [128,64,128] is the RGB color of class 0 (road), and the color is purple.

For ADE20K, you can refer to this color encoding table for more information,
https://docs.google.com/spreadsheets/d/1se8YEtb2detS7OuPE86fXGyD269pMycAWe2mtKUj2W8/edit#gid=0

For Cityscapes, you can refer to the official table for more information.
https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py

Thank you for bringing this up, we will add more comments to these numeric arrays later.

**Comment by bryanyzhu** [comment]
We have added the comments in this pull request #1136 . Please let me know if you have more questions.

**Comment by yurivict** [comment]
Thank you.
