### ISSUE TITLE
mAP and recall metrics for VOC dataset

### ISSUE THREAD

**Issue by GMahdi** [dmlc/gluon-cv#1146]
Hi, I want to use Pascal VOC dataset for object detection; at the end I want to get:
1. Get mAP and recall metrics for overall and for each class 
2. Bounding boxes values and score for top 100 bounding boxes
Can anyone suggest how to get them? Thanks

**Comment by oneluckypic** [comment]
Here is a full example:
https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/yolo/train_yolo3.py

gluoncv.utils.metrics.voc_detection.VOC07MApMetric keeps the metrics.

See the line in train_yolo3.py:
ids, scores, bboxes = net(x)

ids will be the predicted class labels, scores the predicted scores and bboxes the predicted bounding boxes.  You can use the scores to get the top 100.
