### ISSUE TITLE
[Regression]Semantic Segmentation Train script failing with `Incompatible input shape` when crop_size=350 since 0.4.0+ 

### ISSUE THREAD

**Issue by chenliu0831** [dmlc/gluon-cv#1173]
Hi, we recently detected a possible regression of the semantic segmentation when used with deeplab/PSP model and `crop_size` = 350 since GluonCV 0.4.0+. Interestingly, when `crop_size` is 352/360 (basically anything divisible by 8) this failure does not happen at all. 

 See the following for failure details:

- **Env**: MxNet 1.4.1/1.5.1-post0, GluonCV 0.4.0+, training script from matching github revision. 
- **Command**: ` python3 train.py --dataset pascal_aug --model psp --backbone resnet50 --lr 0.001 --crop-size 350 --no-cuda`
- Stack trace:
```
Total Epochs: 50
  0%|                                                                                                                                                      | 0/709 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 232, in <module>
    trainer.training(epoch)
  File "train.py", line 181, in training
    outputs = self.net(data.astype(args.dtype, copy=False))
  File "/usr/local/lib/python3.7/site-packages/gluoncv/utils/parallel.py", line 181, in __call__
    return tuple([tuple_map(self.module(*inputs[0], **kwargs[0]))])
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 917, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/pspnet.py", line 54, in hybrid_forward
    x = self.head(c4)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 917, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/pspnet.py", line 140, in hybrid_forward
    x = self.psp(x)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/usr/local/lib/python3.7/site-packages/mxnet/gluon/block.py", line 917, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/pspnet.py", line 110, in hybrid_forward
    return F.concat(x, feat1, feat2, feat3, feat4, dim=1)
  File "<string>", line 68, in concat
  File "/usr/local/lib/python3.7/site-packages/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/usr/local/lib/python3.7/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:29:03] src/operator/nn/concat.cc:66: Check failed: shape_assign(&(*in_shape)[i], dshape) Incompatible input shape: expected [16,0,44,44], got [16,512,43,43]

Stack trace returned 8 entries:
[bt] (0) 0   libmxnet.so                         0x00000001145a5e60 mxnet::op::NDArrayOpProp::~NDArrayOpProp() + 3024
[bt] (1) 1   libmxnet.so                         0x00000001145a5c0f mxnet::op::NDArrayOpProp::~NDArrayOpProp() + 2431
[bt] (2) 2   libmxnet.so                         0x0000000114891e98 mxnet::op::SupportMKLDNNConcat(std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&) + 8152
[bt] (3) 3   libmxnet.so                         0x0000000115cc38b9 mxnet::imperative::SetShapeType(mxnet::Context const&, nnvm::NodeAttrs const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&, mxnet::DispatchMode*) + 1577
[bt] (4) 4   libmxnet.so                         0x0000000115cc2206 mxnet::Imperative::Invoke(mxnet::Context const&, nnvm::NodeAttrs const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&) + 726
[bt] (5) 5   libmxnet.so                         0x0000000115c1521e SetNDInputsOutputs(nnvm::Op const*, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> >*, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> >*, int, void* const*, int*, int, int, void***) + 1774
[bt] (6) 6   libmxnet.so                         0x0000000115c15f40 MXImperativeInvokeEx + 176
[bt] (7) 7   _ctypes.cpython-37m-darwin.so       0x0000000113b163af ffi_call_unix64 + 79
```
Thanks.

**Comment by chenliu0831** [comment]
Possible related PR: https://github.com/dmlc/gluon-cv/pull/847

**Comment by bryanyzhu** [comment]
Yes, the crop size needs to be multiples of 8 during training.

**Comment by chenliu0831** [comment]
@bryanyzhu thanks for the answer 👍. Since this is a new behavior that's not backwards compatible, if this is intended would you mind explain in more details? Also we probably document this behavior somewhere.

**Comment by bryanyzhu** [comment]
Hybridization is a powerful tool in MXNet to reduce memory usage and improve model speed. So we try to make every model in GluonCV hybridizable. 

However, in order to make the model hybridizable, we can't read shape inside `hybrid_forward` function, such as `data.shape` is not allowed. In this case, we can't get the shape of tensor in later stages of a CNN to do the correct resizing in segmentation heads. Usually segmentation head involves resizing and concatenation, which requires the feature map size to be the same. 

In order to make the model hybridizable, PR #604 and PR #638 try to pass the shape information as arguments to later stages instead of reading tensor shape. But one disadvantage of this is the input shape has to be a multiple of 8, otherwise the round operation and striding in each stage will make the final feature maps having different sizes. Then the concatenation will fail. 

I agree it is not backwards compatible, but it is faster when you do inference in hybrid mode, and it doesn't effect inference. For now, I think we will stick to this behavior, and you can just resize your input to the nearest multiples of 8 to start training.

**Comment by chenliu0831** [comment]
@bryanyzhu It'll be great to add an assertion in the training script for this extra constraint of crop_size on deeplab/psp model. Thanks a lot for the detailed explanation and feel free to close this issue.

**Comment by bryanyzhu** [comment]
@chenliu0831 It is a great suggestion, I will add the assertion now. Thank you.
