### ISSUE TITLE
action recognizer script can't reproduce training result

### ISSUE THREAD

**Issue by jiawensong** [dmlc/gluon-cv#1180]
i want to reproduce the result on this setting:
dataset:ucf101
network：vgg16
All results are tested by test.py with parameters in train command.
My reproduced result is acc 82.483553, acc in the log https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/action_recognition/ucf101/vgg16_ucf101_tsn.log  is 81.549035，acc written at https://gluon-cv.mxnet.io/model_zoo/action_recognition.html is 83.4，acc of hashtag d6dc1bba is 98.6842. There are three different acc in your project. May i have some detail about how to reproduce them?

**Comment by bryanyzhu** [comment]
Hi, the accuracy of hashtag `d6dc1bba` is 83.4, may I ask where you see this number 98.6842? 

And for the difference, it is because we use the standard evaluation strategy following 
`
Limin Wang, Yuanjun Xiong, Zhe Wang and Yu Qiao. “Towards Good Practices for Very Deep Two-Stream ConvNets.” arXiv preprint arXiv:1507.02159, 2015.
`

Basically, it means for a video, we will evenly select 25 frames. For each frame, we do 10-crop evaluation. In the end, we average the scores from 25x10=250 crops and obtain the final prediction. Due to this multi-crop multi-segment evaluation strategy, the final test number is usually 2 to 3 percent better than your training accuracy. For example, I have a training accuracy of 81.54. After the test strategy, my accuracy will jump up to 83.4. 

The test command should be

```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python ./scripts/action-recognition/test_recognizer.py \
  --dataset ucf101 \
  --data-dir ROOT/rawframes \
  --val-list ROOT/ucfTrainTestlist/ucf101_val_split_1_rawframes.txt \
  --model vgg16_ucf101 \
  --use-pretrained \
  --num-classes 101 \
  --mode hybrid \
  --prefetch-ratio 2.0 \
  --dtype float32 \
  --batch-size 1 \
  --num-gpus 8 \
  --num-data-workers 32 \
  --new-height 256 \
  --new-width 340 \
  --new-length 1 \
  --ten-crop \
  --input-size 224 \
  --num-segments 25 \
  --log-interval 10
```

If you want to test your models, then remove `--use-pretrained ` and add `--resume-params YOURMODEL`. Let me know how it goes.

**Comment by bryanyzhu** [comment]
@jiawensong  Any luck in reproducing the numbers?

**Comment by jiawensong** [comment]
i have not enough gpus now. So i test your setting by two titanv, then it logs cudaMalloc failed: out of memory. And which type of gpu you use in your test?
acc 98.6842 was tested by setting below:
 python3 test_recognizer.py \
--dataset 'ucf101' \
--data-dir ROOT/rawframes \
--train-list ROOT/ucfTrainTestlist/ucf101_train_split_1_rawframes.txt \
--val-list ROOT/ucfTrainTestlist/ucf101_val_split_1_rawframes.txt \
--val-data-dir ROOT/rawframes \
--batch-size 48 \
--num-segments 3 \
--use-tsn \
--num-gpus 4 \
--mode hybrid \
--model vgg16_ucf101 \
--hashtag d6dc1bba
There are many differences between my setting and yours. Maybe you have some idea why the results have big gaps.

**Comment by bryanyzhu** [comment]
I use 8 V100s. For simple debugging, please set `batch_size` to 1 to see what is the performance. 

It is very strange though, you don't use ten_crop and but you can achieve 98.68% top-1 acuracy. I don't think any network can achieve this kind of accuracy by using RGB data of UCF101 alone. I highly suspect you test on the training set. 

Can I see your test log? I mean how many samples you are testing, usually it should be about 3.8K samples for UCF101 split 1.

**Comment by bryanyzhu** [comment]
Any luck in finding the reason? or reproduce the results?

**Comment by jiawensong** [comment]
Sorry for the late reply. I have tested again use two titanv. This time my environment is :
mxnet-cu100      1.5.1.post0
gluoncv          0.6.0
And the output log is : 
Namespace(batch_norm=False, batch_size=48, crop_ratio=0.875, data_dir='/mnt/workspace/datasets/ucf101/rawframes', dataset='ucf101', dtype='float32', eval=False, fast_temporal_stride=2, hard_weight=0.5, hashtag='d6dc1bba', input_5d=False, input_size=224, label_smoothing=False, last_gamma=False, log_interval=50, logging_file='train.log', lr=0.1, lr_decay=0.1, lr_decay_epoch='40,60', lr_decay_period=0, lr_mode='step', mixup=False, mixup_alpha=0.2, mixup_off_epoch=0, mode='hybrid', model='vgg16_ucf101', momentum=0.9, new_height=256, new_length=1, new_step=1, new_width=340, no_wd=False, num_classes=101, num_crop=1, num_epochs=3, num_gpus=2, num_segments=3, num_workers=4, prefetch_ratio=2.0, resume_epoch=0, resume_params='', resume_states='', save_dir='params', save_frequency=10, slow_temporal_stride=16, slowfast=False, teacher=None, temperature=20, ten_crop=False, three_crop=False, train_list='/mnt/workspace/datasets/ucf101/ucfTrainTestlist/ucf101_train_split_1_rawframes.txt', use_amp=False, use_decord=False, use_gn=False, use_pretrained=False, use_se=False, use_softmax=False, use_tsn=True, val_data_dir='/mnt/workspace/datasets/ucf101/rawframes', val_list='/mnt/workspace/datasets/ucf101/ucfTrainTestlist/ucf101_val_split_1_rawframes.txt', video_loader=False, warmup_epochs=0, warmup_lr=0.0, wd=0.0001)
Total batch size is set to 96 on 2 GPUs
Pre-trained model is successfully loaded from the model zoo.
Load 3783 test samples in 39 iterations.
Test accuracy: acc-top1=0.961538 acc-top5=4.433761
Total evaluation time is 0.36 minutes.

**Comment by bryanyzhu** [comment]
You didn't specify `use_pretrained ` to True, so you are just using a random initialized model. Actually your accuracy is 0.96%, not 96%. 

Please add `--use_pretrained` in your command line.

**Comment by jiawensong** [comment]
this time the log is like this:
Namespace(batch_norm=False, batch_size=48, crop_ratio=0.875, data_dir='/mnt/workspace/datasets/ucf101/rawframes', dataset='ucf101', dtype='float32', eval=False, fast_temporal_stride=2, hard_weight=0.5, hashtag='d6dc1bba', input_5d=False, input_size=224, label_smoothing=False, last_gamma=False, log_interval=50, logging_file='train.log', lr=0.1, lr_decay=0.1, lr_decay_epoch='40,60', lr_decay_period=0, lr_mode='step', mixup=False, mixup_alpha=0.2, mixup_off_epoch=0, mode='hybrid', model='vgg16_ucf101', momentum=0.9, new_height=256, new_length=1, new_step=1, new_width=340, no_wd=False, num_classes=101, num_crop=1, num_epochs=3, num_gpus=2, num_segments=3, num_workers=4, prefetch_ratio=2.0, resume_epoch=0, resume_params='', resume_states='', save_dir='params', save_frequency=10, slow_temporal_stride=16, slowfast=False, teacher=None, temperature=20, ten_crop=False, three_crop=False, train_list='/mnt/workspace/datasets/ucf101/ucfTrainTestlist/ucf101_train_split_1_rawframes.txt', use_amp=False, use_decord=False, use_gn=False, use_pretrained=True, use_se=False, use_softmax=False, use_tsn=True, val_data_dir='/mnt/workspace/datasets/ucf101/rawframes', val_list='/mnt/workspace/datasets/ucf101/ucfTrainTestlist/ucf101_val_split_1_rawframes.txt', video_loader=False, warmup_epochs=0, warmup_lr=0.0, wd=0.0001)
Total batch size is set to 96 on 2 GPUs
Downloading /root/.mxnet/models/vgg16_ucf101-d6dc1bba.zip from https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/vgg16_ucf101-d6dc1bba.zip...
Pre-trained model is successfully loaded from the model zoo.
Load 3783 test samples in 39 iterations.
Test accuracy: acc-top1=81.891027 acc-top5=96.073718
Total evaluation time is 0.36 minutes
Is this result the same to yours?

**Comment by bryanyzhu** [comment]
Your log looks much better.

Mine is 83.4, please add `--ten-crop` to your command line as well. This is the standard evaluation strategy.

**Comment by jiawensong** [comment]
titanv has not enough memory to test add --ten-crop, it will cause cudaMalloc failed: out of memory.

**Comment by bryanyzhu** [comment]
Just use smaller batch size. For me, I always use batch-size=1 per GPU during evaluation.

**Comment by jiawensong** [comment]
set batch size=1, log is:
Namespace(batch_norm=False, batch_size=1, crop_ratio=0.875, data_dir='/mnt/workspace/datasets/ucf101/rawframes', dataset='ucf101', dtype='float32', eval=False, fast_temporal_stride=2, hard_weight=0.5, hashtag='d6dc1bba', input_5d=False, input_size=224, label_smoothing=False, last_gamma=False, log_interval=50, logging_file='train.log', lr=0.1, lr_decay=0.1, lr_decay_epoch='40,60', lr_decay_period=0, lr_mode='step', mixup=False, mixup_alpha=0.2, mixup_off_epoch=0, mode='hybrid', model='vgg16_ucf101', momentum=0.9, new_height=256, new_length=1, new_step=1, new_width=340, no_wd=False, num_classes=101, num_crop=1, num_epochs=3, num_gpus=2, num_segments=3, num_workers=4, prefetch_ratio=2.0, resume_epoch=0, resume_params='', resume_states='', save_dir='params', save_frequency=10, slow_temporal_stride=16, slowfast=False, teacher=None, temperature=20, ten_crop=True, three_crop=False, train_list='/mnt/workspace/datasets/ucf101/ucfTrainTestlist/ucf101_train_split_1_rawframes.txt', use_amp=False, use_decord=False, use_gn=False, use_pretrained=True, use_se=False, use_softmax=False, use_tsn=True, val_data_dir='/mnt/workspace/datasets/ucf101/rawframes', val_list='/mnt/workspace/datasets/ucf101/ucfTrainTestlist/ucf101_val_split_1_rawframes.txt', video_loader=False, warmup_epochs=0, warmup_lr=0.0, wd=0.0001)
Total batch size is set to 2 on 2 GPUs
Pre-trained model is successfully loaded from the model zoo.
Load 3783 test samples in 1891 iterations.
0050/1891 is done: acc-top1=83.333333 acc-top5=100.000000
0100/1891 is done: acc-top1=85.643564 acc-top5=100.000000
0150/1891 is done: acc-top1=82.781457 acc-top5=98.013245
0200/1891 is done: acc-top1=86.815920 acc-top5=98.507463
0250/1891 is done: acc-top1=86.653386 acc-top5=98.406375
0300/1891 is done: acc-top1=85.714286 acc-top5=98.006645
0350/1891 is done: acc-top1=87.321937 acc-top5=98.290598
0400/1891 is done: acc-top1=86.658354 acc-top5=98.379052
0450/1891 is done: acc-top1=84.035477 acc-top5=97.893570
0500/1891 is done: acc-top1=85.029940 acc-top5=98.103792
0550/1891 is done: acc-top1=85.117967 acc-top5=98.094374
0600/1891 is done: acc-top1=85.108153 acc-top5=98.169717
0650/1891 is done: acc-top1=84.331797 acc-top5=98.156682
0700/1891 is done: acc-top1=82.952924 acc-top5=97.931526
0750/1891 is done: acc-top1=81.225033 acc-top5=97.336884
0800/1891 is done: acc-top1=82.022472 acc-top5=97.503121
0850/1891 is done: acc-top1=82.432432 acc-top5=97.473561
0900/1891 is done: acc-top1=81.187569 acc-top5=97.225305
0950/1891 is done: acc-top1=81.072555 acc-top5=97.055731
1000/1891 is done: acc-top1=80.419580 acc-top5=96.653347
1050/1891 is done: acc-top1=79.543292 acc-top5=95.908658
1100/1891 is done: acc-top1=79.019074 acc-top5=95.549500
1150/1891 is done: acc-top1=79.843614 acc-top5=95.742832
1200/1891 is done: acc-top1=80.682764 acc-top5=95.920067
1250/1891 is done: acc-top1=81.294964 acc-top5=96.083133
1300/1891 is done: acc-top1=81.706380 acc-top5=96.233666
1350/1891 is done: acc-top1=81.569208 acc-top5=96.113990
1400/1891 is done: acc-top1=81.655960 acc-top5=96.074233
1450/1891 is done: acc-top1=81.598897 acc-top5=96.209511
1500/1891 is done: acc-top1=81.145903 acc-top5=96.269154
1550/1891 is done: acc-top1=81.399097 acc-top5=96.228240
1600/1891 is done: acc-top1=81.698938 acc-top5=96.346034
1650/1891 is done: acc-top1=82.162326 acc-top5=96.456693
1700/1891 is done: acc-top1=82.422105 acc-top5=96.443269
1750/1891 is done: acc-top1=82.238721 acc-top5=96.316391
1800/1891 is done: acc-top1=82.593004 acc-top5=96.418656
1850/1891 is done: acc-top1=82.549973 acc-top5=96.434360
Test accuracy: acc-top1=82.707562 acc-top5=96.377578
Total evaluation time is 2.11 minutes

**Comment by bryanyzhu** [comment]
Oh, sorry, forgot to mention, please change num_segments to 25. 

Here is my test command as reference, 

```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python ./scripts/action-recognition/test_recognizer.py \
  --dataset ucf101 \
  --data-dir /UCF101/rawframes \
  --val-list /UCF101/ucfTrainTestlist/ucf101_val_split_1_rawframes.txt \
  --model vgg16_ucf101 \
  --use-pretrained \
  --num-classes 101 \
  --mode hybrid \
  --prefetch-ratio 2.0 \
  --dtype float32 \
  --batch-size 1 \
  --num-gpus 8 \
  --num-data-workers 32 \
  --new-height 256 \
  --new-width 340 \
  --new-length 1 \
  --ten-crop \
  --input-size 224 \
  --num-segments 25 \
  --log-interval 10
```

**Comment by jiawensong** [comment]
change num_segments to 25 will cause out of memory. In fact, I just need a way to evaluate if my reproduced params can achieve the same result as yours. If the setting above is correct, I can compare my result to yours using the same setting.

**Comment by bryanyzhu** [comment]
I think  you reproduced params can achieve the same results. 

I use your setting which is num_sements=3, my results is
```
Test accuracy: acc-top1=82.759534 acc-top5=96.398305
```
which is very close to your `Test accuracy: acc-top1=82.707562 acc-top5=96.377578`.

**Comment by jiawensong** [comment]
I have trained again to get another params which is not d6dc1bba. The test log for this params is :
Namespace(batch_norm=False, batch_size=1, crop_ratio=0.875, data_dir='/mnt/workspace/datasets/ucf101/rawframes', dataset='ucf101', dtype='float32', eval=False, fast_temporal_stride=2, hard_weight=0.5, hashtag='', input_5d=False, input_size=224, label_smoothing=False, last_gamma=False, log_interval=50, logging_file='train.log', lr=0.1, lr_decay=0.1, lr_decay_epoch='40,60', lr_decay_period=0, lr_mode='step', mixup=False, mixup_alpha=0.2, mixup_off_epoch=0, mode='hybrid', model='vgg16_ucf101', momentum=0.9, new_height=256, new_length=1, new_step=1, new_width=340, no_wd=False, num_classes=101, num_crop=1, num_epochs=3, num_gpus=2, num_segments=3, num_workers=4, prefetch_ratio=2.0, resume_epoch=0, resume_params='models/params_action_recognizer_vgg16_ucf101-ucf101-vgg16_ucf101-79.params', resume_states='models/params_action_recognizer_vgg16_ucf101-ucf101-vgg16_ucf101-79.states', save_dir='params', save_frequency=10, slow_temporal_stride=16, slowfast=False, teacher=None, temperature=20, ten_crop=True, three_crop=False, train_list='/mnt/workspace/datasets/ucf101/ucfTrainTestlist/ucf101_train_split_1_rawframes.txt', use_amp=False, use_decord=False, use_gn=False, use_pretrained=False, use_se=False, use_softmax=False, use_tsn=True, val_data_dir='/mnt/workspace/datasets/ucf101/rawframes', val_list='/mnt/workspace/datasets/ucf101/ucfTrainTestlist/ucf101_val_split_1_rawframes.txt', video_loader=False, warmup_epochs=0, warmup_lr=0.0, wd=0.0001)
Total batch size is set to 2 on 2 GPUs
Pre-trained model models/params_action_recognizer_vgg16_ucf101-ucf101-vgg16_ucf101-79.params is successfully loaded.
Load 3783 test samples in 1891 iterations.
0050/1891 is done: acc-top1=89.215686 acc-top5=100.000000
0100/1891 is done: acc-top1=87.623762 acc-top5=100.000000
0150/1891 is done: acc-top1=83.112583 acc-top5=98.013245
0200/1891 is done: acc-top1=87.064677 acc-top5=98.507463
0250/1891 is done: acc-top1=87.649402 acc-top5=98.804781
0300/1891 is done: acc-top1=87.209302 acc-top5=98.172757
0350/1891 is done: acc-top1=87.891738 acc-top5=98.433048
0400/1891 is done: acc-top1=86.658354 acc-top5=98.503741
0450/1891 is done: acc-top1=84.257206 acc-top5=97.671840
0500/1891 is done: acc-top1=85.229541 acc-top5=97.904192
0550/1891 is done: acc-top1=85.117967 acc-top5=98.003630
0600/1891 is done: acc-top1=85.108153 acc-top5=98.169717
0650/1891 is done: acc-top1=83.794163 acc-top5=98.079877
0700/1891 is done: acc-top1=83.095578 acc-top5=97.646220
0750/1891 is done: acc-top1=81.225033 acc-top5=97.203728
0800/1891 is done: acc-top1=81.960050 acc-top5=97.378277
0850/1891 is done: acc-top1=82.373678 acc-top5=97.356052
0900/1891 is done: acc-top1=81.243063 acc-top5=97.169811
0950/1891 is done: acc-top1=81.282860 acc-top5=97.003155
1000/1891 is done: acc-top1=80.469530 acc-top5=96.853147
1050/1891 is done: acc-top1=79.495718 acc-top5=96.051380
1100/1891 is done: acc-top1=78.746594 acc-top5=95.594914
1150/1891 is done: acc-top1=79.452650 acc-top5=95.786273
1200/1891 is done: acc-top1=80.308077 acc-top5=95.961699
1250/1891 is done: acc-top1=80.935252 acc-top5=96.123102
1300/1891 is done: acc-top1=81.360492 acc-top5=96.233666
1350/1891 is done: acc-top1=81.088083 acc-top5=96.150999
1400/1891 is done: acc-top1=81.156317 acc-top5=96.109921
1450/1891 is done: acc-top1=81.185389 acc-top5=96.243970
1500/1891 is done: acc-top1=80.912725 acc-top5=96.269154
1550/1891 is done: acc-top1=81.270148 acc-top5=96.260477
1600/1891 is done: acc-top1=81.511555 acc-top5=96.377264
1650/1891 is done: acc-top1=81.980618 acc-top5=96.486978
1700/1891 is done: acc-top1=82.157554 acc-top5=96.560847
1750/1891 is done: acc-top1=82.095945 acc-top5=96.516276
1800/1891 is done: acc-top1=82.509717 acc-top5=96.612993
1850/1891 is done: acc-top1=82.576985 acc-top5=96.596434
Test accuracy: acc-top1=82.601798 acc-top5=96.589106
Total evaluation time is 2.16 minutes
If this result means this params reproduce yours successful?

**Comment by bryanyzhu** [comment]
Yes, I think so. It is very close to mine, just 0.1% diff. I would say you reproduce our results successfully.

**Comment by jiawensong** [comment]
ok，thank you a thousand times！
