### ISSUE TITLE
CUDA 10.2 support

### ISSUE THREAD

**Issue by MangoCats** [dmlc/gluon-cv#1194]
Is there any plan/timeline to build a support package for CUDA 10.2?

I just finished my MXNET install based on 10.2 and would like to use GluonCV with it, but the latest version I find supported in GluonCV is 10.1...

Thanks,

**Comment by zhreshold** [comment]
If you have MXNET with CUDA10.2 then  you are already good to go. You are fine using whatever version of CUDA with gluoncv, the GPU bridge is provided by mxnet not gluoncv.

**Comment by MangoCats** [comment]
Two things led me to post this.  One, when I: "pip install --upgrade mxnet-cu101mkl gluoncv" that installs apparently successfully, but when I: "pip install --upgrade mxnet-cu102mkl gluoncv" that gives me a failure message to the effect of mxnet-cu102mkl is not available to install.

Second, when I try something like: "python test.py --dataset ade20k --model-zoo fcn_resnet50_ade --eval" from [here](https://gluon-cv.mxnet.io/model_zoo/segmentation.html), I get a failure message complaining that the mxnet 10.1 library is not available.

**Comment by zhreshold** [comment]
You can install mxnet from these links for cuda 10.2: https://dist.mxnet.io/python/cu102mkl
 Simply install gluoncv after that, since mxnet is just a dependency of gluoncv, so we don't care what cuda version it is.

**Comment by MangoCats** [comment]
Thanks, the pip install knew about 10.0 and 10.1 but not 10.2

The tests are getting further now... no longer complaining about missing
10.1 libraries.  Thanks.
