### ISSUE TITLE
How to modify SSDDefaultTrainTransform

### ISSUE THREAD

**Issue by TorRient** [dmlc/gluon-cv#1198]
I saw in the code that SSDDefaultTrainTransform provides various augmentation mechanisms like:
random color jitter, random cropping, random flip but i don't want to use random flip.
So how to modify it?

**Comment by ElectronicElephant** [comment]
oops, I think simply comment these lines will do the job
```
        # random horizontal flip
        h, w, _ = img.shape
        img, flips = timage.random_flip(img, px=0.5)
        bbox = tbbox.flip(bbox, (w, h), flip_x=flips[0])
```

**Comment by TorRient** [comment]
> oops, I think simply comment these lines will do the job
> 
> ```
>         # random horizontal flip
>         h, w, _ = img.shape
>         img, flips = timage.random_flip(img, px=0.5)
>         bbox = tbbox.flip(bbox, (w, h), flip_x=flips[0])
> ```

thank you, so how to add rotate image?

**Comment by ElectronicElephant** [comment]
> 
> 
> > oops, I think simply comment these lines will do the job
> > ```
> >         # random horizontal flip
> >         h, w, _ = img.shape
> >         img, flips = timage.random_flip(img, px=0.5)
> >         bbox = tbbox.flip(bbox, (w, h), flip_x=flips[0])
> > ```
> 
> thank you, so how to add rotate image?

Well, I don't think it's easy.
