### ISSUE TITLE
Center_net not available

### ISSUE THREAD

**Issue by shersoni610** [dmlc/gluon-cv#1205]
Hello,
While running the demo_center_net I get the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-a83108d1ce58> in <module>
----> 1 net = model_zoo.get_model('center_net_resnet18_v1b_voc', pretrained=True)

~/Disk/Software/Anaconda3/lib/python3.7/site-packages/gluoncv/model_zoo/model_zoo.py in get_model(name, **kwargs)
    261         err_str = '"%s" is not among the following model list:\n\t' % (name)
    262         err_str += '%s' % ('\n\t'.join(sorted(_models.keys())))
--> 263         raise ValueError(err_str)
    264     net = _models[name](**kwargs)
    265     return net

ValueError: "center_net_resnet18_v1b_voc" is not among the following model list:
	alexnet
	alpha_pose_resnet101_v1b_coco
	cifar_residualattentionnet452
	cifar_residualattentionnet56
	cifar_residualattentionnet92
	cifar_resnet110_v1
	cifar_resnet110_v2

**Comment by gachiemchiep** [comment]
@shersoni610 
Please check whether your gluoncv package's version is larger than 0.6.0

See the definition of center_net here.
https://github.com/dmlc/gluon-cv/blob/v0.6.0/gluoncv/model_zoo/center_net/center_net.py
