### ISSUE TITLE
Transfer learning Gluoncv Type 

### ISSUE THREAD

**Issue by roy6324** [dmlc/gluon-cv#1213]
Hello @zhreshold ,

When doing Transfer Learning using Gluoncv ( classification , semantic segmentation , instance segmentation ), do we reinitialize the last layer , and also finetune the whole network's weights ? or do we reinitialize the last layer, and treat the rest of the network as a fixed feature extractor for the new dataset ( only update weights for the last layer) ? 

Thanks :)

**Comment by zhreshold** [comment]
It depends, but for most transfered tasks, we don't reinit base filters, but keep them learnable
