### ISSUE TITLE
slowfast network for hmdb51 dataset

### ISSUE THREAD

**Issue by yezqNLP** [dmlc/gluon-cv#1229]
I tried to train slowfast network in hmdb51 dataset, I can run the program successfully but the accuracy is pretty low about 0.2. The work that I have done is follwing:

1. I added a method
 
```
def slowfast_8x8_resnet50_hmdb51(nclass=51, pretrained=False, pretrained_base=True,
                                      use_tsn=False, num_segments=1, num_crop=1,
                                      partial_bn=False, feat_ext=False,
                                      root='~/.mxnet/models', ctx=cpu(), **kwargs):
    model = SlowFast(nclass=nclass,
                     layers=[3, 4, 6, 3],
                     pretrained=pretrained,
                     pretrained_base=pretrained_base,
                     feat_ext=feat_ext,
                     num_segments=num_segments,
                     num_crop=num_crop,
                     partial_bn=partial_bn,
                     alpha=4,
                     beta_inv=8,
                     fusion_conv_channel_ratio=2,
                     fusion_kernel_size=7,
                     width_per_group=64,
                     num_groups=1,
                     slow_temporal_stride=8,
                     fast_temporal_stride=2,
                     slow_frames=8,
                     fast_frames=32,
                     ctx=ctx,
                     **kwargs)
    if pretrained:
        from ..model_store import get_model_file
        model.load_parameters(get_model_file('slowfast_8x8_resnet50_hmdb51',
                                             tag=pretrained, root=root), ctx=ctx)
        from ...data import HMDB51Attr
        attrib = HMDB51Attr()
        model.classes = attrib.classes
    model.collect_params().reset_ctx(ctx)
    return model
```

2. I modified the train-dataset and val-dataset to add some slowfast paramters, like `video_loader=opt.video_loader, use_decord=opt.use_decord,
                                slowfast=opt.slowfast, slow_temporal_stride=opt.slow_temporal_stride, fast_temporal_stride=opt.fast_temporal_stride` :
https://github.com/dmlc/gluon-cv/blob/874f783fa57dadbfd38607ad58f4309141a9479b/scripts/action-recognition/train_recognizer.py#L204 

```
        train_dataset = HMDB51(setting=opt.train_list, root=data_dir, train=True,
                                new_width=opt.new_width, new_height=opt.new_height, new_length=opt.new_length, new_step=opt.new_step,
                                target_width=input_size, target_height=input_size, video_loader=opt.video_loader, use_decord=opt.use_decord,
                                slowfast=opt.slowfast, slow_temporal_stride=opt.slow_temporal_stride, fast_temporal_stride=opt.fast_temporal_stride,
                                num_segments=opt.num_segments, transform=transform_train)

```

And the program can run successfully, and the namespace is:

```
Namespace(accumulate=1, batch_norm=False, batch_size=6, clip_grad=0, crop_ratio=0.875, data_dir='/home/xxx/.mxne
t/datasets/hmdb51/videos', dataset='hmdb51', dtype='float32', eval=False, fast_temporal_stride=2, freeze_bn=Fals
e, hard_weight=0.5, hashtag='', input_5d=False, input_size=224, kvstore=None, label_smoothing=False, last_gamma=
False, log_interval=50, logging_file='slowfast_8x8_resnet50_hmdb51.log', lr=0.01, lr_decay=0.1, lr_decay_epoch='
15,25,35', lr_decay_period=0, lr_mode='step', mixup=False, mixup_alpha=0.2, mixup_off_epoch=0, mode='hybrid', mo
del='slowfast_8x8_resnet50_hmdb51', momentum=0.9, new_height=256, new_length=64, new_step=1, new_width=340, no_w
d=False, num_classes=51, num_crop=1, num_epochs=80, num_gpus=2, num_segments=1, num_workers=8, partial_bn=False,
 prefetch_ratio=1.0, resume_epoch=0, resume_params='', resume_states='', save_dir='./hmdb51_slowfast_logs/', sav
e_frequency=20, scale_ratios='1.0,0.8', slow_temporal_stride=8, slowfast=True, teacher=None, temperature=20, tra
in_list='/home/xxx/.mxnet/datasets/hmdb51/testTrainMulti_7030_splits/hmdb51_train_split_1_rawframes.txt', use_am
p=False, use_decord=True, use_gn=False, use_pretrained=False, use_se=False, use_tsn=False, val_data_dir=None, va
l_list='/home/xxx/.mxnet/datasets/hmdb51/testTrainMulti_7030_splits/hmdb51_val_split_1_rawframes.txt', video_loa
der=True, warmup_epochs=0, warmup_lr=0.0, wd=0.0001)
```
The acc is pretty slow, so there is wrong with my modification. Can u look at it?
@bryanyzhu

**Comment by bryanyzhu** [comment]
Hi, it seems that you are not using any pretrained weights, so you are actually training HMDB51 from scratch. I think that's the reason why the performance is low. 

I suggest you add the method as

```
def slowfast_4x16_resnet50_hmdb51(nclass=51, pretrained=False, pretrained_base=True,
                                  use_tsn=False, num_segments=1, num_crop=1,
                                  partial_bn=False, feat_ext=False, use_kinetics_pretrain=True,
                                  root='~/.mxnet/models', ctx=cpu(), **kwargs):
  
    model = SlowFast(nclass=nclass,
                     layers=[3, 4, 6, 3],
                     pretrained=pretrained,
                     pretrained_base=pretrained_base,
                     feat_ext=feat_ext,
                     num_segments=num_segments,
                     num_crop=num_crop,
                     partial_bn=partial_bn,
                     alpha=8,
                     beta_inv=8,
                     fusion_conv_channel_ratio=2,
                     fusion_kernel_size=5,
                     width_per_group=64,
                     num_groups=1,
                     slow_temporal_stride=16,
                     fast_temporal_stride=2,
                     slow_frames=4,
                     fast_frames=32,
                     init_std=0.001,
                     ctx=ctx,
                     **kwargs)

    if use_kinetics_pretrain and not pretrained:
        from gluoncv.model_zoo import get_model
        kinetics_model = get_model('slowfast_4x16_resnet50_kinetics400', nclass=400, pretrained=True)
        source_params = kinetics_model.collect_params()
        target_params = model.collect_params()
        assert len(source_params.keys()) == len(target_params.keys())

        pretrained_weights = []
        for layer_name in source_params.keys():
            pretrained_weights.append(source_params[layer_name].data())

        for i, layer_name in enumerate(target_params.keys()):
            if i + 2 == len(source_params.keys()):
                # skip the last dense layer
                break
            target_params[layer_name].set_data(pretrained_weights[i])

    model.collect_params().reset_ctx(ctx)

    return model
```

In this way, you are using Kinetcs400 pretrained weights, which should give you a good result.

In addition, maybe set lr to a smaller value is better, you can try both 0.01 and 0.001 to see which one performs better. And the number of epochs can be smaller, such as 50.

**Comment by yezqNLP** [comment]
Thanks, I will try it.

**Comment by yezqNLP** [comment]
I get puzzled about some details about `slow-temporal-stride` and `fast-temporal-stride`. In `slowfast_4x16_resnet50_kinetics400`, you set `slow-temporal-stride` and `fast-temporal-stride` as 16 and 2 in https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/action_recognition/kinetics400/slowfast_4x16_resnet50_kinetics400.sh.
However in `slowfast_8x8_resnet50_kinetics400`,  you set `slow-temporal-stride` and `fast-temporal-stride` as 8 and 2, which suggests the `slow-temporal-stride` is not changed. This is not right according to https://github.com/dmlc/gluon-cv/issues/1187#issuecomment-585355952.

**Comment by bryanyzhu** [comment]
I didn't quite follow, why it is not correct? In #1187, we are talking about slowfast_4x16, so the slow stride is 16 and fast stride is 2. 

Now you are asking slowfast_8x8, the slow stride should be 8 and fast stride should be 2. You can confirm this in the original paper, as well as in their official implementation. For example, if you see Fig 1 in slowfast paper, the input to slow branch is T, which should be 8. The input to fast branch is alpha*T, which should be 4*8=32. So the slow stride is 64/8=8, and fast stride is 64/32=2.

Again, these two parameters indicate the `T` and `\tau`, not `alpha` and `beta`.

**Comment by yezqNLP** [comment]
> I didn't quite follow, why it is not correct? In #1187, we are talking about slowfast_4x16, so the slow stride is 16 and fast stride is 2.
> 
> Now you are asking slowfast_8x8, the slow stride should be 8 and fast stride should be 2. You can confirm this in the original paper, as well as in their official implementation. For example, if you see Fig 1 in slowfast paper, the input to slow branch is T, which should be 8. The input to fast branch is alpha_T, which should be 4_8=32. So the slow stride is 64/8=8, and fast stride is 64/32=2.
> 
> Again, these two parameters indicate the `T` and `\tau`, not `alpha` and `beta`.

Now I understand , I should read the paper carefully. Thanks!

**Comment by bryanyzhu** [comment]
No problem, glad I can help.

**Comment by yezqNLP** [comment]
Using pretrained weights did improve the accuracy a lot. In UCF101, acc reaches ~0.96; in HMDB51, acc reaches ~0.75. While without pretrained weights, accuracy is fairly low. which suggests good initialization(pretrained weights) is very important for small dataset like UCF101 and HMDB51. 
Thanks! And you can close this issue now.

**Comment by ooguz166** [comment]
Hello, I am also trying to train Slow Fast with pretrained function you guyz mentioned above, so far this snippet is what I have tried to understand the procedure:
`num_gpus = 1`

```
net= slowfast_4x16_resnet50_hmdb51(nclass=51)
transform_train = transforms.Compose([video.VideoCenterCrop(size=224),video.VideoToTensor()])

train_dataset = HMDB51(setting=cfg.HMDB.SETTING, root=cfg.HMDB.ROOT, train=cfg.HMDB.TRAIN_MODE,video_loader=cfg.HMDB.VID_LOADER,
                       use_decord=cfg.HMDB.USE_DECORD,slowfast=cfg.HMDB.SLOWFAST,video_ext=cfg.HMDB.EXT, transform=transform_train)

train_data = DataLoader(train_dataset, batch_size=25, shuffle=True)

for x, y in train_data:
    print('Video frame size (batch, extra, channel, height, width):', x.shape)
    print('Video label:', y.shape)
    break
```



where 

```
__C.HMDB.CLASSES                = 51
__C.HMDB.ROOT                   = os.path.expanduser('~/.mxnet/datasets/hmdb51/videos')
__C.HMDB.VID_LOADER             = True
__C.HMDB.USE_DECORD             = False
__C.HMDB.SLOWFAST               = True
__C.HMDB.TEST_MODE              = False
__C.HMDB.TRAIN_MODE             = True
__C.HMDB.EXT                    = "avi"
__C.HMDB.SETTING                = os.path.expanduser('~/.mxnet/datasets/hmdb51/testTrainMulti_7030_splits/hmdb51_train_split_1_rawframes.txt')
```
If I turned off the slowfast, dataloader works just fine but whenever it is on I get this error: 

```
python3.6/site-packages/gluoncv/data/video_custom/classification.py", line 184, in __getitem__
    clip_input = self._video_TSN_decord_slowfast_loader(directory, decord_vr, duration, segment_indices, skip_offsets)
UnboundLocalError: local variable 'decord_vr' referenced before assignment
```
I do installed the decord, however cant find any solution to this. Any recommendations ?

**Comment by ooguz166** [comment]
Is there any example about traning HMDB with these pre trained slow fast ?
