### ISSUE TITLE
Input data should be 4D in batch-num_filter-y-x

### ISSUE THREAD

**Issue by nicholasguimaraes** [dmlc/gluon-cv#1231]
Hello, I am trying to run inference.py but I am encountering this error:

File "C:\Users\Windows\AppData\Roaming\Python\Python36\site-packages\mxnet\base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:58:50] C:\Jenkins\workspace\mxnet-tag\mxnet\src\operator\nn\convolution.cc:152: Check failed: dshp.ndim() == 4U (5 vs. 4) : Input data should be 4D in batch-num_filter-y-x

This is what I'm running on command line:

python inference.py --data-list ucfTrainTestlist/inference.txt --model resnet101_v1b_kinetics400 --resume-params params/ucf101-resnet101_v1b_kinetics400-059.params

This is the input shape I'm passing 1x3x32x224x224 

I know it should be only 4D. What should be removed from the input data?

**Comment by bryanyzhu** [comment]
Yes, the input should be 4D for 2D CNN models. The shape should be 1x3x224x224, which is a single frame. 

If you want to use the idea of TSN, e.g., load 5 frames from 5 segments of a single video,  you can set num_segments to 5 in this line of code.

https://github.com/dmlc/gluon-cv/blob/master/scripts/action-recognition/inference.py#L199.

**Comment by bryanyzhu** [comment]
Any follow-up questions? If not, I will close the issue.

**Comment by mnakhaeecourse** [comment]
I wanna convert a mxnet pretrained model into tensorflow but by passing the below command I got Error. How can I overcome it?
mmtoir -f mxnet -n mxnet/models/mnet.25-symbol.json -w mxnet/models/mnet.25-0000.params -d retmobv2 --inputShape 3,112,112

mxnet.base.MXNetError: Error in operator mobilenet0_conv0_fwd: [00:14:27] C:\Jenkins\workspace\mxnet-tag\mxnet\src\operator\nn\convolution.cc:152: Check failed: dshp.ndim() == 4U (2 vs. 4) : I
nput data should be 4D in batch-num_filter-y-x
