### ISSUE TITLE
Prepare PASCAL VOC datasets

### ISSUE THREAD

**Issue by uz-amd** [dmlc/gluon-cv#1238]
Hi guys, I have been trying to do this tutorial [06. Train Faster-RCNN end-to-end on PASCAL VOC](https://gluon-cv.mxnet.io/build/examples_detection/train_faster_rcnn_voc.html#sphx-glr-download-build-examples-detection-train-faster-rcnn-voc-py) 
It asks to prepare dataset and run a script that prepares all for you but when I ran there was an issue with mxnet library. To fix issue I installed mxnet version 1.2.0 and now I am facing another issue:

AppData\Local\Programs\Python\Python36-32\lib\site-packages\gluoncv\model_zoo\faster_rcnn\faster_rcnn.py", line 10, in <module>
    from mxnet.gluon.contrib.nn import SyncBatchNorm
ImportError: cannot import name 'SyncBatchNorm'

I have no idea how to fix this issue, I could not find any solution to fix this problem. 
I would greatly appreciate if you can help fix it

**Comment by bryanyzhu** [comment]
Hi, synchronized batch norm was introduced in MXNet 1.3, that's why you can't import it in MXNet 1.2. 

May I know why you need to downgrade MXNet to 1.2.0?

**Comment by uz-amd** [comment]
> Hi, synchronized batch norm was introduced in MXNet 1.3, that's why you can't import it in MXNet 1.2.
> 
> May I know why you need to downgrade MXNet to 1.2.0?

Thank you for your reply. With the latest MXnet 1.6.0 I am getting the following error:
RuntimeError: Cannot find the MXNet library.
List of candidates:
AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\libmxnet.dll
AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../lib/libmxnet.dll
AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../build/libmxnet.dll
AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../build\libmxnet.dll
AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../build\Release\libmxnet.dll
AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../windows\Release\libmxnet.dll

Regarding why I downgraded, it's because a user from [here](https://discuss.mxnet.io/t/mxnet-installation-cannot-find-the-mxnet-library/5713) suggested downgrading as the latest 1.6.0 was creating this issue.

I tried to install a version above 1.2.0 but pip3 does not offer 
![image](https://user-images.githubusercontent.com/53828837/78012831-7e74bb00-733d-11ea-9aa9-5c1c21f228b5.png)

**Comment by zhreshold** [comment]
@uz-amd  GluonCV works with mxnet >=1.4.0, what's the system on your machine?
