### ISSUE TITLE
Add super-resolution models and tutorials

### ISSUE THREAD

**Issue by la-cruche** [dmlc/gluon-cv#1242]
Hi,

Creating this issue to track interest in having models and tutorials for image and video super-resolution in gluoncv. 
This seems to be an active field of computer vision, for example:
- _Image Super-Resolution Using Deep Convolutional Networks_ https://arxiv.org/pdf/1501.00092.pdf (Dong et al)
- _Deep Learning for Single Image Super-Resolution:A Brief Review_ https://arxiv.org/pdf/1808.03344.pdf (Yang et al)
- _Deep Learning for Image Super-resolution:A Survey_ https://arxiv.org/pdf/1902.06068.pdf (Wang et al)

I'd love gluoncv to make this domain of vision more accessible by providing pre-trained models and tutos. Looking forward to learn the SOTA from you !

**Comment by zhreshold** [comment]
We are considering adding super resolution models, stay tuned.

**Comment by YigitAytac** [comment]
any news?

**Comment by zhreshold** [comment]
There's SRGAN implementation in scripts
