### ISSUE TITLE
Strange training accuracy in the logs shown in the Classification page

### ISSUE THREAD

**Issue by stgzr** [dmlc/gluon-cv#1245]
I read some training logs in the [Classification page](https://gluon-cv.mxnet.io/model_zoo/classification.html) and found some strange results.
- As the training log [resnet50_v1d.log](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/resnet50_v1d.log) shows, the training accuracy is nearly 80%+ at the very early stage. 
- But in this log [resnet101_v1.log](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/resnet101_v1.log), the training accuracy looks normal(1% at first 50 iterations).
I can't understand why at the very beginning, the training accuracy could reach 80%+ in the first 50 iterations as resnet50_v1d training even with a warmup stage.
Is there anything I missed?

**Comment by Aktcob** [comment]
1-error=accuracy
