### ISSUE TITLE
Is Mixup really work in Detection?

### ISSUE THREAD

**Issue by yuhao318** [dmlc/gluon-cv#1248]
I tried to train YoloV3 in PascalVoc with this command:
 `python train_yolov3.py --batch-size=64 --gus=0,1,2,3 '--epochs=200 --lr=0.001 --warmup-epochs=4 --lr-decay-epoch=160,180 --syncbn --mixup --no-mixup-epochs=0 ` , and I gained the mAP=0.81266, but without mixup the mAP is 0.81331.
It seems that mixup don't improve the baseline at all. I'm worndering if my code setup is wrong or mixup didn't work in detection?
The code is in [https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/yolo/train_yolo3.py](https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/yolo/train_yolo3.py)

**Comment by zhreshold** [comment]
You need to increase the training epoch for mixup

**Comment by difftime** [comment]
I  tried to double the epochs and gain the mAP=0.8101, it was even worse.

**Comment by chinakook** [comment]
It's not general enough to use this trick to deal with all kind of datasets. As I've tested, for easy data, it decrease accuracy, but for hard data, it improve accuracy.
