### ISSUE TITLE
Limit Number of core utilization

### ISSUE THREAD

**Issue by KapoorHitesh** [dmlc/gluon-cv#1253]
I am trying example programs of Gluoncv. However I am restricted to use just 2 cores for my application for inferencing. How can I achieve the same?
I Tried the following it works but this will set for the complete script I want to set for just for inferencing
import os
os.environ["OMP_NUM_THREADS"] = 1 # export OMP_NUM_THREADS=1

**Comment by zhreshold** [comment]
Try `subprocess` then?
