### ISSUE TITLE
Pruned resnet networks

### ISSUE THREAD

**Issue by roy6324** [dmlc/gluon-cv#1260]
Hello @zhreshold , 

Whenever we load a model to train from scratch , we use the **model_zoo.get_model( model_name,pretrained=False,classes=classes)** method , hence we specify the number of classes here. 

When using pruned resnet networks (resnet18_v1b_0.89 for example ) , after we load the network , the shape of the weights are re-initialized (in the prune method) , therefore the dense0_weight for example is shaped [ 1000,512 ] which messes with our infered shape [ 2,512 ] (2 is our number of classes for example) .. Is there a way to avoid this ? or should we re-initialize the last layer like we do for transfer learning ?

**Comment by zhreshold** [comment]
@roy6324  It's recommended to re-initialize the last layer as a post step when load pruned resnet as there's no existing utility function to do so

**Comment by roy6324** [comment]
@zhreshold when I load pretrained weights, I usually reinititialize the net.fc layer for transfer learning doing **net.fc=nn.Dense(classes)** , but when loading it from scratch, the simple re-initialization of this layer doesnt do the job, it generates this error when trying to train : 

**ValueError: Deferred initialization failed because shape cannot be inferred. Expected shape (16,) is incompatible with given shape (32,).**

So it works when loading pre-trained weights and then re-initializing the **net.fc** layer, but not when loading it from scratch , I think this is due to this block of code from the resnetv1b_pruned (prune_gluon_block)  : 

**          
if pretrained:
            if isinstance(layer, nn.BatchNorm):
                params_layer = layer._collect_params_with_prefix()
                for param_name in ['beta', 'gamma', 'running_mean', 'running_var']:
                    param_val = params[layer.name.replace(prefix, "resnetv1d") + "_" + param_name]
                    layer.params.get(param_name)._shape = param_val.shape
                    params_layer[param_name]._load_init(param_val, ctx=ctx)**

So for the pretrained networks, we are re-initializing the shape of the parameters for all the BatchNorm layers correspondingly to the online weights. But with an untrained network, we're leaving them the way they are, which is causing some problems.

Is there an easy way or a standard to re-initialize the batchnorm layers so they work on a specific dataset ? or if I'm wrong, what would be a solution to this error ? 

Thanks ! :)

**Comment by zhreshold** [comment]
@roy6324 you can reinit the last layer directly.
```python
net.fc.initialize()
```

For BN, I don't think it's a good idea to reinit BN layers directly, since they will affect the model quite dramatically, you can allow it to transfer gradually by finetuning.

**Comment by roy6324** [comment]
@zhreshold 
In a resnet network , usually it's a Convolutional Layer , followed by a BN layer , followed by an Activation Layer. 

The BN layer takes the number of feature maps of its input as parameter (in_channels) to be built. However when pruning a resnet network that is loaded from scratch , the convolutional layer's weights shape are being re-initialized , which is changing the input shape given to the BN layer (since the BN layer takes the output of the convolutional layer as input) , therefore causing an error.

When building a pretrained resnet network,Both the convolutional layer and BN layer's weights shape are being re-initialized ,so they match, therefore no error is being caused.

The only way the training worked for me (from scratch) is by removing this block from the pruned function:

`        if isinstance(layer, nn.Conv2D):
            param_shape = params_shapes[layer.name.replace(prefix, "resnetv1d") + "_weight"]
            layer._channels = param_shape[0]
            layer._kwargs['num_filter'] = param_shape[0]

            params_layer = layer._collect_params_with_prefix()
            for param_name in ['weight']:
                param_shape = params_shapes[
                    layer.name.replace(prefix, "resnetv1d") + "_" + param_name]
                layer.params.get(param_name)._shape = param_shape
                if pretrained:
                    param_val = params[layer.name.replace(prefix, "resnetv1d") + "_" + param_name]
                    params_layer[param_name]._load_init(param_val, ctx=ctx)`

This is not a permanent solution since I'm not pruning the convolutional layers. But it worked because this way the input shape of the BN layer doesn't change (output of convolutional layer).

**Comment by zhreshold** [comment]
It will be really tricky to handle pruned layers, do you have any concern or suggestion then?

**Comment by roy6324** [comment]
@zhreshold 
Yes actually I've already fixed it. 

Before I start explaining, please note that the batchnorm layer has 4 weights : beta , gamma, running_mean and running_variance.

Explanation : 
Let's take an example , the pruned **resnet18_v1b_0.89** network,  the convolutional layers weights are being reshaped based on the json files, therefore we need to reshape the batchnorm layer weights as well. There's 20 batchnorm layer in this network , 4 weights for each batchnorm layer (beta,gamma,running_mean and running_variance) , therefore there is 80 weights in total that need to be reshaped.

Below are the shapes for the 80 batchnorm weights consecutively :

```
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(8,)
(120,)
(120,)
(120,)
(120,)
(56,)
(56,)
(56,)
(56,)
(56,)
(56,)
(56,)
(56,)
(128,)
(128,)
(128,)
(128,)
(56,)
(56,)
(56,)
(56,)
(256,)
(256,)
(256,)
(256,)
(208,)
(208,)
(208,)
(208,)
(208,)
(208,)
(208,)
(208,)
(256,)
(256,)
(256,)
(256,)
(208,)
(208,)
(208,)
(208,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)
(512,)

``` 
Each 4 lines are for one batchnorm layer ( 4 weights shapes).

I pasted those shapes in a file ,put it in the same directory as the json files , so , when going through the pruning function , I refer to this file to reshape all the batchnorm layers weights shapes consecutively everytime I encounter a batchnorm layer.
