### ISSUE TITLE
question about action recognition dataset precessing?

### ISSUE THREAD

**Issue by yezqNLP** [dmlc/gluon-cv#1262]
Hey, it's me again. I have 1 question about `VideoClsCustom`, which has 3 sample_indices method:
`_sample_train_indices, _sample_val_indices, _sample_test_indices`.
I notice `_sample_val_indices, _sample_test_indices`  has only one different line code.
In `_sample_val_indices`:
https://github.com/dmlc/gluon-cv/blob/18f8ab526ffb97660e6e5661f991064c20e2699d/gluoncv/data/video_custom/classification.py#L257
In `_sample_test_indices`:
https://github.com/dmlc/gluon-cv/blob/18f8ab526ffb97660e6e5661f991064c20e2699d/gluoncv/data/video_custom/classification.py#L274
I have been wondering why we got this difference? Can you explain about it?
@bryanyzhu

**Comment by bryanyzhu** [comment]
Actually `_sample_test_indices` is the right function to go. Just use it will be fine. 

`_sample_val_indices` is designed for something else. I shouldn't use it here. But usually `num_segments` is a small number, or just 1. So it doesn't matter.

**Comment by yezqNLP** [comment]
> Actually `_sample_test_indices` is the right function to go. Just use it will be fine.
> 
> `_sample_val_indices` is designed for something else. I shouldn't use it here. But usually `num_segments` is a small number, or just 1. So it doesn't matter.

OK，thanks!
