### ISSUE TITLE
can't open hyper link of 'shell script' or 'trainning log'

### ISSUE THREAD

**Issue by ritaiask** [dmlc/gluon-cv#1264]
'https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/resnet18_v1.log'
can't find service ip address of ' raw.githubusercontent.com'

**Comment by zhreshold** [comment]
I am ok with the link. Check with your isp see if github is blocked.

**Comment by ritaiask** [comment]
> I am ok with the link. Check with your isp see if github is blocked.

it's been solved ,thank you~~~
