### ISSUE TITLE
Unable to export I3D Inception v1 model

### ISSUE THREAD

**Issue by hasanp87** [dmlc/gluon-cv#1269]
export_block('model/i3d_inceptionv1_kinetics400', net,preprocess=None,layout='CTHW',data_shape=(3, 32, 224, 224))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gluoncv/utils/export_helper.py", line 153, in export_block
    raise RuntimeError(str(last_exception).splitlines()[0])
RuntimeError: Error in operator resnetv10_conv0_fwd: [15:29:26] src/operator/nn/convolution.cc:152: Check failed: dshp.ndim() == 4U (5 vs. 4) : Input data should be 4D in batch-num_filter-y-x

**Comment by Aktcob** [comment]
layout='CTHW',data_shape should be (1,  3, 32, 224, 224).  And why u use CTHW?

**Comment by bryanyzhu** [comment]
Because I3D is a 3D network, the input should be a video clip, not a single video frame. So it has an additional temporal dimension, which is T. That's why we use CTHW. 

For 2D networks, we can just use CHW.
