### ISSUE TITLE
Convert trained yolov3 Darknet-53 custom model to weights/tensorflow model

### ISSUE THREAD

**Issue by rohit167** [dmlc/gluon-cv#1287]
I have trained a custom yolov3 Darknet-53 model (yolo3_darknet53_custom.params)

More generally, Is it possible to inference models trained using gluon-cv in tensorflow?

Is there any utility by which I can convert the yolo3_darknet53_custom.params model to-
1) yolo3_darknet53_custom.weights (yolov3 weights)
2) yolo3_darknet53_custom.pb (tensorflow graph)

Any leads would be great! 
Thanks

**Comment by Aktcob** [comment]
The yolov3(gluoncv version) is a little bit complicate, containing post-processing. I suggest that u may firstly convert the inference model without any post-processing ops, cause there is no params in post-processing ops. U can rewrite directly it with TensorFlow.

**Comment by rohit167** [comment]
@Aktcob Thanks. Could you please give more details. Is there any link I can follow or read in detail?
I also came across mmdnn and openvino toolkit for conversion but couldn't get working yet. seems like both don't support yolo3 darknet (mxnet). I am still looking for work around.

**Comment by Aktcob** [comment]
actually, u can follow the openvino tutorials directly. But the full model with post processing can not be converted to openvino model directly since the openvino does not support NMS op which contains in yolov3(mxnet). Delete the NMS layer and u can convert it successfully. I have done it before.
