### ISSUE TITLE
export classification model for c++ api

### ISSUE THREAD

**Issue by junl21** [dmlc/gluon-cv#1290]
I have trained a classification model(resnest101), and export it to json and params file by export_json.py. 
But I got an wrong predict results by both c++ predict demo and python predict script.
And I also try to train a densenet model, but it also make an wrong results. 

I use the same code to export the faster rcnn model, it worked and c++ load the model and gives a right results.

**Comment by Aktcob** [comment]
did u export the model with the defaultpreprocess layer?
