### ISSUE TITLE
Model Zoo comparison plots source data points.

### ISSUE THREAD

**Issue by RuRo** [dmlc/gluon-cv#1292]
Hi, I would like to use the model zoo Accuracy vs Throughput comparison plots ([classification](https://gluon-cv.mxnet.io/model_zoo/classification.html)). Is there some easy way to get the raw data points used in the plot (other than hovering over each point and manually copying the data)?

P.S. I am assuming from the [citation section](https://github.com/dmlc/gluon-cv#citation) in the readme, that `gluon-cv` is okay with me using this data, as long as I properly credit `gluoncvnlp2020` and `he2018bag` as sources since this is publicly available information.

**Comment by RuRo** [comment]
Also, on some further inspection, the current plot says that `densenet161` has accuracy `0.776` and throughput of `500.489`, while `densenet201` has lower accuracy of `0.773` and higher throughput of `679.986`, which doesn't make much sense to me. And I can't find `densenet161` anywhere in the original paper. Did you perhaps mean `densenet264`?

**Comment by zhreshold** [comment]
@RuRo We use https://github.com/zhreshold/dlmark/tree/gluoncv to generate the benchmarks. 
Densenet161 which is actually a BC variant(DenseNet-BC in comparison with Densenet-C) that was used to compress the model in the original paper.
