### ISSUE TITLE
Semantic Segmentation FCN Training

### ISSUE THREAD

**Issue by shachargluska** [dmlc/gluon-cv#1293]
I have a few issues/questions regarding training FCN using gluoncv:
- The training script defines crop_size & base_size, but it's not documented what these are.
   So what do these mean?
- crop_size & base_size accept a single integer value, but for inference we would potentially want to use an asymmetrical size, such as 2048x1024 (cityscapes) or 1920x1080 (full hd camera). Is there a way around this?
- Looking at fcn.py, I don't see a way to combine the heads as in [the original paper](https://arxiv.org/abs/1411.4038)
The paper uses upsampling (either bilinear or deconvolution) and then element-wise add in order to combine the heads.
![image](https://user-images.githubusercontent.com/57857737/81494687-82d4b200-92b3-11ea-9552-8c8ae2350808.png)
It also distinguishes FCN-32, FCN-16 & FCN-8, depending on the heads.
Did I misunderstand the code?

**Comment by Aktcob** [comment]
Q1: crop_size & base_size:  https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/segbase.py
Q2: Usually, the result is close with symmetrical or asymmetrical size. 
Q3: The code is FCN32 model. If u want to use FCN16 or FCN8, u should do it by yourself. Change the code about head.

**Comment by bryanyzhu** [comment]
@Aktcob Thank you for your answer, they are great. Just to add a few more details.

Q1: As shown by Aktcob@, base size is a size used during data augmentation for random short side jittering. Crop size is the final input to the network. So for Cityscapes with a resolution of 1024x2048. The base size is the short side, which is 1024. And most people use 768x768 patches to train the network, which makes the crop size of 768.

Q2: If you want to do inference on asymmetrical size, just specify height and width [here](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/segbase.py#L69). Crop size only works when you didn't specify height and width.
