### ISSUE TITLE
Mapillary Vistas dataset support

### ISSUE THREAD

**Issue by shachargluska** [dmlc/gluon-cv#1294]
Is it possible to support this dataset?
I believe it's a prerequisite of completing https://github.com/dmlc/gluon-cv/issues/944.

**Comment by bryanyzhu** [comment]
Mapillary Vistas dataset has strict license. Its research edition only allows pure academic research, no commercial use. So we can't support it here. If you want to use this dataset, you can use the dataloader at

https://github.com/NVIDIA/semantic-segmentation/blob/master/datasets/mapillary.py

**Comment by shachargluska** [comment]
Thank you for your response and proposed solution.
I am not sure how this is different from other datasets, such as cityscapes.
Isn't it possible to provide a loader similar to what you suggsted, and have the users prepare the dataset themselves?

**Comment by bryanyzhu** [comment]
You are right, it is not that different form other datasets, such as Cityscapes. But let me confirm with legal and respond to you at a later time.
