### ISSUE TITLE
CenterNetDefaultValTransform bug fix

### ISSUE THREAD

**Issue by chinakook** [dmlc/gluon-cv#1295]
This class would cause the ```val_loader``` of ```train_center_net.py``` to load data incorrectly after the second epoch, so we'll get the wrong mAP and the mAP will be changed epoch over epoch. I've test without any train code, only with validate code in the for loop.
To fix this, we should copy the src and label pair as needed.
```
import copy
class CenterNetDefaultValTransform(object):
    def __call__(self, src, label):
        img, bbox = copy.copy(src), copy.copy(label)
```
@zhreshold

**Comment by chinakook** [comment]
I think that some other places will get this error too.

**Comment by zhreshold** [comment]
The labels are returned as copies in dataset: for example:  https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/mscoco/detection.py#L149 or https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/pascal_voc/detection.py#L89

**Comment by chinakook** [comment]
Thanks, I used a old copy version with vocdataset for my own data. It don't contain this label.copy.
