### ISSUE TITLE
SyncBN  causes the memory to gradually increase with iteration

### ISSUE THREAD

**Issue by wy3406** [dmlc/gluon-cv#1298]
- I have a few issues/questions regarding SyncBN
When using BN training in custom image segmentation, the memory is normal. But when I replaced BN with SyncBN, I found that the GPU memory gradually increased with iteration until it occupied the entire GPU memory,then the training is stuck. I try to use a smaller batch than BN, which also takes up all the GPU memory.
Note there is no warning when I use SyncBN.
Is there something I have missed?

- Environments: Python 3.6.9 ; TITAN RTX × 8;CUDA 10.1

- Framework: mxnet-mkl-1.6.0 and gluoncv-0.8.0

**Comment by bryanyzhu** [comment]
Hi, can you try mxnet-mkl-1.4.1? SyncBN seems to have memory issues with MXNet version higher than 1.4.1.

**Comment by wy3406** [comment]
Thanks for your reply
According to your reminder, I solved this problem.
