### ISSUE TITLE
minc-2500-tiny.zip file issue

### ISSUE THREAD

**Issue by cemsaz** [dmlc/gluon-cv#1300]
[minc-2500-tiny.zip](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/classification/minc-2500-tiny.zip) file in [this tutorial](https://github.com/dmlc/gluon-cv/blob/8360e2edc18589248a37e12eb8109cdb7ffc9024/docs/tutorials/classification/transfer_learning_minc.py) has .DS_Store files under training, validation, test folders. 

```
creating: minc-2500-tiny/train/
creating: minc-2500-tiny/train/.DS_Store/
creating: minc-2500-tiny/train/brick/
inflating: minc-2500-tiny/train/brick/brick_000216.jpg  
inflating: minc-2500-tiny/train/brick/brick_000228.jpg  
inflating: minc-2500-tiny/train/brick/brick_000519.jpg
.........
creating: minc-2500-tiny/test/.DS_Store/
creating: minc-2500-tiny/test/brick/
inflating: minc-2500-tiny/test/brick/brick_001968.jpg  
inflating: minc-2500-tiny/test/brick/brick_001981.jpg  
creating: minc-2500-tiny/test/carpet/
inflating: minc-2500-tiny/test/carpet/carpet_000632.jpg  
inflating: minc-2500-tiny/test/carpet/carpet_000891.jpg  
......
```

They are treated as a new class and the model sees/uses one more extra class.  
.DS_Store files should be removed from the zip file.

**Comment by zhreshold** [comment]
@cemsaz Thanks for catching the issue! This should be fixed by https://github.com/dmlc/web-data/pull/253
