### ISSUE TITLE
Typos on the tutorials page of Object Tracking.

### ISSUE THREAD

**Issue by dai-ichiro** [dmlc/gluon-cv#1301]
01. Single object tracking with pre-trained SiamRPN models

> You need to prepare two things to start a tracking demo, the video and its first frame object coordinates. The coordinates show the region of interest where to track, and in the format of (center_x, center_y, weight, height).

I think this is correct.

> (corner_x, corner_y, width, height)

Thanks.

**Comment by dai-ichiro** [comment]
Is (center_x, center_y)  right?
I think (min_x, min_y) is right.

Thanks.

**Comment by bryanyzhu** [comment]
@dai-ichiro Great catch, we will do a PR to fix it. Thank you.

**Comment by bryanyzhu** [comment]
The (min_x, min_y) typo will be fixed in this PR #1334 .

Will close this issue for now, thank you.
