### ISSUE TITLE
Got very low mAP when training yolov3 in my dataset with '-amp'

### ISSUE THREAD

**Issue by wanxinzzz** [dmlc/gluon-cv#1305]
Hello, when i finetune yolo3 in my dataset with amp
```
horovodrun -np 8 -H localhost:8 python3 -u train_yolo3.py  --horovod --amp --mixup --label-smooth --warmup-epochs 5 -j 8 --epochs 15 --no-random-shape --no-wd
```
I got very low mAP in the first epoch, it even worse then random initialize.
```
mAP=2.490964450103864e-05
```
And then i forbidden amp
```
horovodrun -np 8 -H localhost:8 python3 -u train_yolo3.py  --horovod --mixup --label-smooth --warmup-epochs 5 -j 8 --epochs 15 --no-random-shape --no-wd
```
It seems good and i got mAP > 0.6, but this config need much more GPU memory, and i got this error when my gpu memory was all occupied, so amp is really needed to me.

> [2020-05-13 16:14:11.883985: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 

Anything wrong in my amp setting? 

My environment
```
Python  3.7.3
GPU  Tesla-V100-SXM2-32GB
NVIDIA Driver Version  418.116.00
CUDA  10.1

mxnet-cu101         1.6.0
gluoncv             0.7.0
horovod             0.19.0
numpy               1.18.1
```

**Comment by wanxinzzz** [comment]
Hello, when i finetune yolo3 in my dataset with amp
```
horovodrun -np 8 -H localhost:8 python3 -u train_yolo3.py  --horovod --amp --mixup --label-smooth --warmup-epochs 5 -j 8 --epochs 15 --no-random-shape --no-wd
```
I got very low mAP in the first epoch, it even worse then random initialize.
```
mAP=2.490964450103864e-05
```
And then i forbidden amp
```
horovodrun -np 8 -H localhost:8 python3 -u train_yolo3.py  --horovod --mixup --label-smooth --warmup-epochs 5 -j 8 --epochs 15 --no-random-shape --no-wd
```
It seems good and i got mAP > 0.6, but this config need much more GPU memory, and i got this error when my gpu memory was all occupied, so amp is really needed to me.

> [2020-05-13 16:14:11.883985: W horovod/common/stall_inspector.cc:105] One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 

Anything wrong in my amp setting? 

My environment
```
Python 3.7.3
NVIDIA Driver Version: 418.116.00
CUDA 10.1

mxnet-cu101         1.6.0
gluoncv             0.7.0
horovod             0.19.0
numpy               1.18.1
```

**Comment by chinakook** [comment]
I think ```--amp```  is not well tested with yolo training. I've got ```FP16 gemm on cpu not implemented!``` error when using amp with yolo but normal with ssd.

**Comment by zhreshold** [comment]
As commented by @chinakook YOLO with AMP is still experimental and had limited test so far. You may need latest mxnet.
@Kh4L for more information.
