### ISSUE TITLE
How to suport Yolo V4 model ?

### ISSUE THREAD

**Issue by seebrand** [dmlc/gluon-cv#1306]
The Yolo v4 has released . When and how to support it? thanks very much.

**Comment by chinakook** [comment]
Actually, Yolo V4 is full of tricks and consume more memory and training more slower. I think https://github.com/ultralytics/yolov3 and https://github.com/PaddlePaddle/PaddleDetection/blob/master/docs/featured_model/YOLOv3_ENHANCEMENT.md variants will be better.
