### ISSUE TITLE
[Website] Gluon CV source Installation guide points to wrong MXNet nightly build

### ISSUE THREAD

**Issue by rondogency** [dmlc/gluon-cv#1307]
On https://gluon-cv.mxnet.io/install.html, the MXNet nightly package installation command is still 
"pip install --upgrade mxnet -f https://dist.mxnet.io/python/cu100", which installs a 1.6 CPU build of MXNet

It should be updated to "pip install --pre mxnet-cu100 -f https://dist.mxnet.io/python/all", according to MXNet website

**Comment by zhreshold** [comment]
Thanks for catching @rondogency I submitted a PR to fix this.
