### ISSUE TITLE
always out of memory when use syncbn in segmentation model

### ISSUE THREAD

**Issue by TomMao23** [dmlc/gluon-cv#1316]
environment： gluoncv 0.7 or 0.8， mxnet-cu90mkl 1.6， gtx1080Ti x 2

The training segmentation model icnet does not use syncbn when the batchsize reaches 16 or less can also be trained normally. After using syncbn, no matter how small the batchsize is, the memory consumption will increase with each batch of training until the out of memory
I have encountered this problem when trying to use syncbn in deeplab and pspnet

**Comment by bryanyzhu** [comment]
Hi, please use mxnet-1.4.1 or before for segmentation model training. There is a known conflict between mxnet recent versions and syncbn.

**Comment by TomMao23** [comment]
It works！Thanks！
