### ISSUE TITLE
Saving file with `?` on Windows machine

### ISSUE THREAD

**Issue by Ishitori** [dmlc/gluon-cv#132]
There is a [tutorial](https://gluon-cv.mxnet.io/build/examples_detection/demo_ssd.html#sphx-glr-build-examples-detection-demo-ssd-py) where a file is downloaded with a query string.

When trying to save it on Windows machine, one will receive an exception, because a question mark is a reserved char and cannot be used in a filename.

Here is the user complaining about that: https://discuss.mxnet.io/t/invalid-argument-street-small-jpg-raw-true/1065

**Comment by zhanghang1989** [comment]
This should be fixed by PR https://github.com/dmlc/gluon-cv/pull/133
