### ISSUE TITLE
[Feature Request] YOLOv4

### ISSUE THREAD

**Issue by austinmw** [dmlc/gluon-cv#1321]
Would love it if YOLOv4 could be included in the model zoo. 
https://arxiv.org/abs/2004.10934

For reference:
Original repo: https://github.com/AlexeyAB/darknet
PyTorch implementation: https://github.com/Tianxiaomo/pytorch-YOLOv4

**Comment by ninaraminelli** [comment]
I would appreciate that also.

**Comment by djaym7** [comment]
Does anyone have update on this ? Supporting yolo4/pp pytorch in gluoncv would be good too. (if that is faster)
