### ISSUE TITLE
About fine-tuning a pretrained faster_rcnn model

### ISSUE THREAD

**Issue by mehmetgur** [dmlc/gluon-cv#1325]
Hello,
Thanks again for your example about finetuning a ssd model for training Pikachus. I've followed this tutorial and it works like a charm : 
https://gluon-cv.mxnet.io/build/examples_detection/finetune_detection.html 
I would like to know if there is any guide or tutorial for doing the same finetuning process with faster_rcnn model? Because fine-tuning will be much efficient instead of  training a model from scratch.
Any reply will be appreciated. Best regards.

**Comment by mehmetgur** [comment]
any ideas??

**Comment by Aktcob** [comment]
you can refer to this script https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/faster_rcnn/train_faster_rcnn.py

And use the function reset_class in the model_zoo https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/rcnn/faster_rcnn/faster_rcnn.py#L233
