### ISSUE TITLE
Train any image classification network on custom dataset

### ISSUE THREAD

**Issue by rommanio** [dmlc/gluon-cv#1327]
Sorry, how can I train image classification network (ResNeXt is preferred) on my own dataset with 12 classes, **not** on ImageNet?

Any docs, posts and issues that I read, was about training on ImageNet dataset or about training custom object detection network (yolov3, for example), not about training any image classification network on custom (and completely different from ImageNet1k) dataset.

I was try adopt dive_deep_imagenet.py script for my needs, but no luck. Classification still based on ImageNet classes, even if I restrict number of classes from 1000 to 12 in load model script.

Thanks and sorry again.

**Comment by dai-ichiro** [comment]
This is the easy way.
http://mxnet.incubator.apache.org/versions/1.7.0/api/python/docs/api/gluon/data/vision/datasets/index.html#mxnet.gluon.data.vision.datasets.ImageFolderDataset
