### ISSUE TITLE
Train Yolov3 with custom dataset including images without label

### ISSUE THREAD

**Issue by MBocchi** [dmlc/gluon-cv#1332]
Hi,
I have created custom dataset and classes on VOC format. I have included **negative samples (images without label)** in the dataset to reduce false detection.

I used the train script from gluoncv tutorial [https://gluon-cv.mxnet.io/build/examples_detection/train_yolo_v3.html](url), but implementation **doesn't allow to include images without label**, so I add to the empty list of label one fake annotation at the end of method __load_label(self, idx)_ method in _data/pascal_voc/detection.py_ 
`label.append([-1, -1, -1, -1, -1, -1])`.

With this method the train can be done, but false detections on negative samples are **worst after training**.

If someone has any suggestions, I would be grateful!
Thank you

**Comment by chinakook** [comment]
It's same with:
https://github.com/dmlc/gluon-cv/issues/772
The official yolo/darknet can support negative samples training too, so I think we should add it to gluoncv. 
P.S. No-anchor detection method such as CenterNet will be easily to training without box targets.

**Comment by lynnwaters86** [comment]
also interested Mxnet support negative samples YOLO V3 training
