### ISSUE TITLE
Training hybrid hrnet imagenet Error: it != node2index_.end() && it->first == e.node.get():

### ISSUE THREAD

**Issue by firestonelib** [dmlc/gluon-cv#1341]
raceback (most recent call last):
  File "/root/gluon-cv/scripts/classification/imagenet/train_imagenet.py", line 400, in train
    outputs = [net(X.astype(opt.dtype, copy=False)) for X in data]
  File "/root/gluon-cv/scripts/classification/imagenet/train_imagenet.py", line 400, in <listcomp>
    outputs = [net(X.astype(opt.dtype, copy=False)) for X in data]
  File "/root/gluon-cv//3rdparty/mxnet/gluon/block.py", line 693, in __call__
    out = self.forward(*args)
  File "/root/gluon-cv//3rdparty/mxnet/gluon/block.py", line 1148, in forward
    return self._call_cached_op(x, *args)
  File "/root/gluon-cv//3rdparty/mxnet/gluon/block.py", line 1020, in _call_cached_op
    out = self._cached_op(*cargs)
  File "/root/gluon-cv//3rdparty/mxnet/_ctypes/ndarray.py", line 170, in __call__
    ctypes.byref(out_stypes)))
  File "/root/gluon-cv//3rdparty/mxnet/base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [03:07:59] ../3rdparty/tvm/nnvm/src/core/graph.cc:102: Check failed: it != node2index_.end() && it->first == e.node.get():
Stack trace:
  [bt] (0) /root/gluon-cv/3rdparty/mxnet/libmxnet.so(+0x40d98c2) [0x7f26e06588c2]
  [bt] (1) /root/gluon-cv/3rdparty/mxnet/libmxnet.so(nnvm::IndexedGraph::IndexedGraph(nnvm::Graph const&)+0x63c) [0x7f26e065d41c]
  [bt] (2) /root/gluon-cv/3rdparty/mxnet/libmxnet.so(nnvm::Graph::indexed_graph() const+0x2f) [0x7f26e065ea7f]
  [bt] (3) /root/gluon-cv/3rdparty/mxnet/libmxnet.so(mxnet::exec::FusePointwiseBackward(nnvm::Graph&&)+0xac) [0x7f26dde0fc8c]
  [bt] (4) /root/gluon-cv/3rdparty/mxnet/libmxnet.so(mxnet::OptimizeGraph(nnvm::Graph*, nnvm::Graph*, nnvm::Graph*, mxnet::Context const&, unsigned long, bool)+0x2d9) [0x7f26dde22f89]
  [bt] (5) /root/gluon-cv/3rdparty/mxnet/libmxnet.so(mxnet::CachedOp::CachedOpState::CachedOpState(mxnet::Context const&, nnvm::Graph const&, nnvm::Graph const&, bool)+0x4f9) [0x7f26dde47669]
  [bt] (6) /root/gluon-cv/3rdparty/mxnet/libmxnet.so(mxnet::CachedOp::GetCachedOpState(mxnet::Context const&)+0x100) [0x7f26dde27fa0]
  [bt] (7) /root/gluon-cv/3rdparty/mxnet/libmxnet.so(mxnet::CachedOp::Forward(std::shared_ptr<mxnet::CachedOp> const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&)+0x185) [0x7f26dde2ff55]
  [bt] (8) /root/gluon-cv/3rdparty/mxnet/libmxnet.so(MXInvokeCachedOp+0x6a0) [0x7f26ddccfa60]
hi, can u help me?
@mli @mjamroz @piiswrong @larroy @leezu

**Comment by mjamroz** [comment]
@firestonelib probably, but can you post data to reconstruct your case?

**Comment by firestonelib** [comment]
$gluon-cv python scripts/classification/imagenet/train_imagenet.py --model hrnet_w32_c --use-rec --mode hybrid
then it runs with error above. @mjamroz

**Comment by firestonelib** [comment]
This issue is solved. @mjamroz  Thanks.
