### ISSUE TITLE
Save parameters

### ISSUE THREAD

**Issue by Tingting-Lu** [dmlc/gluon-cv#1357]
hi, 
I found I couldn't save the model after I run all cell of train_fcn(https://gluon-cv.mxnet.io/build/examples_segmentation/train_fcn.html#sphx-glr-build-examples-segmentation-train-fcn-py. 
I try to use  model.save_parameters('model_params') to save model, but it show:"DataParallelModel object has no attribution save_parameters"

**Comment by bryanyzhu** [comment]
Because we are using dataparallel to train the model, the actual model parameters are actually in `model.module`. You can try `model.module.save_parameters(PATH)`

**Comment by Tingting-Lu** [comment]
> Because we are using dataparallel to train the model, the actual model parameters are actually in `model.module`. You can try `model.module.save_parameters(PATH)`

Thanks for your help

**Comment by Tingting-Lu** [comment]
I still have a question about the training loop. I want to train it at least 20 epoch, So I changed the code as follow:
`
train_loss = 0.0
for epoch in range(20):
    train_loss = 0.0             ## new added
    for i, (data, target) in enumerate(train_data):
        with autograd.record(True):
            outputs = model(data)
            losses = criterion(outputs, target)
            mx.nd.waitall()
            autograd.backward(losses)
        optimizer.step(batch_size)
        for loss in losses:
            train_loss += loss.asnumpy()[0] / len(losses)
    print('Epoch %d, training loss %.3f'%(epoch, train_loss/2913))     ##changed a little, as the number of training set is 2913
    # just demo for 2 iters
    #if i > 1:
     #   print('Terminated for this demo...')
     #  break
`
I am not sure if it's correct because the training loss become nan since epoch 10.
My environment is ubuntu 18.04, Cuda 10, Cudnn 7.4 , tensorflow-gpu 1.13
GPU:Geforce rtx 2060
and batch size is 2(it would out of memory when I set it to 4)

**Comment by bryanyzhu** [comment]
Hi, can you provide more details? Is your loss constantly increasing and become nan? Or it suddenly jumps to nan? 

Besides, are you training on VOC or your own dataset? Thanks.

**Comment by Tingting-Lu** [comment]
> Hi, can you provide more details? Is your loss constantly increasing and become nan? Or it suddenly jumps to nan?
> 
> Besides, are you training on VOC or your own dataset? Thanks.
I 
The loss constantly decrease then become nan, and the data is voc data(and I am going to replace it with my own data, hope I could do it successfully)
![Screenshot from 2020-07-08 19-31-06](https://user-images.githubusercontent.com/57180418/86951861-6093cf00-c152-11ea-83bb-92c7fdbc3681.png)

**Comment by bryanyzhu** [comment]
Hi, maybe the batch size of 2 is small. Can you try sync batchnorm to see if you still have the same problem? 

Besides, another trick you can do is to check the loss first before updating the model. I mean, you can add an if statement. If the loss is NaN, you just skip this iteration without updating the model. 

Sometimes when the input batches are really strange after the data augmentation, it may cause the network to produce NaN loss. In this case, you may want to just skip this batch.
