### ISSUE TITLE
Kernel dying on loading activity recognition model from gluon model zoo

### ISSUE THREAD

**Issue by ksindwan** [dmlc/gluon-cv#1362]
num_gpus = 1 ## number of  gpus to be used
ctx = [gpu(i) for i in range(num_gpus)]
net = get_model(name='vgg16_ucf101', nclass=101, num_segments=3)
net.collect_params().reset_ctx(ctx)

Kernel dies everytime I run this code. trying to follow this tutorial (https://gluon-cv.mxnet.io/build/examples_action_recognition/dive_deep_i3d_kinetics400.html)

mxnet_version : 1.6.0
gluoncv version : 0.7.0 

the same code works without the reset_ctx. I checked it on multiple instances.

**Comment by bryanyzhu** [comment]
Hi, I didn't observe this on my end. I use exactly the same code with you, and `net.collect_params().reset_ctx(ctx)` works fine. Let me try some other machines to see if I can reproduce your issue.

**Comment by ksindwan** [comment]
Hi,

I tried running the code in a Sagemaker notebook with mxnet pre installed . 
And I ran the following commands to install gluoncv

pip install gluoncv --upgrade
pip install -U --pre mxnet -f https://dist.mxnet.io/python/mkl
# if cuda 10.1 is installed
pip install -U --pre mxnet -f https://dist.mxnet.io/python/cu100mkl


I believe multiple versions of mxnet were installed and caused the issue. If you believe the same, please close the issue

**Comment by bryanyzhu** [comment]
Yes, I believe the same. 

You can try installing mxnet and gluoncv on a fresh ec2 instance. If the code works, then yes, it is the version problem. 

If you still encounter the issue in the fresh ec2 instance, please let me know and I will try to root cause the reason.
