### ISSUE TITLE
how to train YOLOv3 in FP16 or uint8?

### ISSUE THREAD

**Issue by never-to-never** [dmlc/gluon-cv#1364]
I read a blog (https://blog.csdn.net/bingpoyinhui/article/details/102782260) about this issue and found that it ran incorrectly

> mxnet.base.MXNetError: Error in operator yolov3loss0_broadcast_mul1: [10:11:00] src/operator/contrib/../elemwise_op_common.h:135: Check failed: assign(&dattr, vec.at(i)): Incompatible attr in node yolov3loss0_broadcast_mul1 at 1-th input: expected float16, got float32

Does anyone have a solution？thanks

**Comment by Aktcob** [comment]
Actually, gluoncv is supporting AMP(mixed precision training) right now. You can refer to the script https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/yolo/train_yolo3.py#L99

**Comment by enry12** [comment]
Hello,

Maybe you can find some useful information in this other issue: [https://github.com/dmlc/gluon-cv/issues/284](https://github.com/dmlc/gluon-cv/issues/284)

**Comment by snow6666667** [comment]
sorry,my bad. it is my blog but i forgot to remind that you need to delete '--syncbn'. I mentioned in comment section.
