### ISSUE TITLE
yolo: load param problem

### ISSUE THREAD

**Issue by KaiWang66** [dmlc/gluon-cv#1370]
Hi, I am a new one here. This is an awesome lib, **thanks for your great work**.
Now, I am encountering a problem that I **trained YOLOv3 on PASCAL VOC** based on Train YOLOv3 on this tutorial: https://gluon-cv.mxnet.io/build/examples_detection/train_yolo_v3.html
After training, I got a "**yolo3_darknet53_voc_best.params**" file. 
Then I tried to **load the parameters** and predict new images
The command I used as follows,
```
net = model_zoo.get_model('yolo3_darknet53_voc', pretrained=False)
net.load_parameters("yolo3_darknet53_voc_best.params")
```
and predict:
```
im_fname = "2007_000129.jpg"
x, img = data.transforms.presets.yolo.load_test(im_fname, short=512)
print('Shape of pre-processed image:', x.shape)
class_IDs, scores, bounding_boxs = net(x)
ax = utils.viz.plot_bbox(img, bounding_boxs[0], scores[0],
                         class_IDs[0], class_names=net.classes)
plt.show()
```

The result I got is the raw picture with **no bounding box and prediction**.

Also, I've tried another loading method:
```
c = ['aeroplane','bicycle','bird','boat','bottle','bus','car','cat','chair','cow','diningtable','dog','horse','motorbike','person','pottedplant','sheep','sofa','train','tvmonitor']
net = model_zoo.get_model('yolo3_darknet53_custom', pretrained=False, classes=c)
net.load_parameters("yolo3_darknet53_voc_best.params")
```
but the result is the same, **no bounding box and prediction**

Any suggestion?
**Thanks for any help.**

**Comment by Aktcob** [comment]
Did u know the MAP of the parameters ("yolo3_darknet53_voc_best.params")?

**Comment by KaiWang66** [comment]
I found out where is my problem: to save time, I only train for 5 epoch so that the detection score is lower than the threshold. And the loading is fine. **Thank you** @Aktcob
