### ISSUE TITLE
ModuleNotFoundError: No module named 'gluoncv.model_zoo.rcnn.faster_rcnn.data_parallel'

### ISSUE THREAD

**Issue by ShidiDaisy** [dmlc/gluon-cv#1373]
Hi,

I'm using CUDA 10.1. I have installed gluon-cv by using the command
`pip install --upgrade mxnet-cu101 gluoncv`
But when I run:
`>>> from gluoncv.model_zoo.rcnn.faster_rcnn.data_parallel import ForwardBackwardTask`
I got this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gluoncv.model_zoo.rcnn.faster_rcnn.data_parallel

Do I miss any step?

**Comment by Aktcob** [comment]
check out the gluoncv version or check whether this file(gluoncv.model_zoo.rcnn.faster_rcnn.data_parallel) exists in the python package. Or download the newest version of gluoncv directly.

Hope help~

**Comment by syedtahin** [comment]
I ran 'pip list' and see that GluonCV is at 0.7.0. I'm try to run the script from the hint here: https://gluon-cv.mxnet.io/build/examples_detection/train_faster_rcnn_voc.html.

There is an assert to check GluonCV version on line 22 which passes. But, on line 34, I'm getting the same error as OP.

**Comment by bryangreener** [comment]
In order to solve this problem I had to install the nightly build of gluoncv using
```pip install --pre --upgrade gluoncv```

**Comment by liangyimingcom** [comment]
pip install gluoncv --upgrade

# if you are eager to try new features, try nightly build instead
pip install gluoncv --pre --upgrade
