### ISSUE TITLE
Evaluating class (channel) 0 for segmentation metrics

### ISSUE THREAD

**Issue by zergzzlun** [dmlc/gluon-cv#1377]
Hi,

I've checked out the code and tested [gluoncv.utils.metrics.segmentation](https://gluon-cv.mxnet.io/_modules/gluoncv/utils/metrics/segmentation.html). It seems that there's a mismatch in class 0 for mIoU and pixAcc: When computing mIoU ` batch_intersection_union(output, target, nclass)` ignores class 0 while `batch_pix_accuracy(output, target)` ignores class -1 and takes class 0 as a valid class.
Is that right or am I using the metrics API in the wrong way?

Many thanks.

**Comment by Aktcob** [comment]
hi, in the file https://github.com/dmlc/gluon-cv/blob/master/gluoncv/utils/metrics/segmentation.py. 

Line 98/99, all labels add one. So, class -1 to class 0(ignore label), class 0 to class 1(first label).

Hope help

**Comment by zergzzlun** [comment]
> hi, in the file https://github.com/dmlc/gluon-cv/blob/master/gluoncv/utils/metrics/segmentation.py.
> 
> Line 98/99, all labels add one. So, class -1 to class 0(ignore label), class 0 to class 1(first label).
> 
> Hope help

Thanks a lot.
