### ISSUE TITLE
Scripts not working

### ISSUE THREAD

**Issue by mathephysicist** [dmlc/gluon-cv#1391]
A lot of the scripts seem to have conflicts when trying to train within that specific tag. 

For instance 0.7.0 has import paths that are incorrect in the Mask_RCNN script. I propose we update these scripts.

!pip install gluoncv==0.7.0 

then try and run the corresponding 0.7.0 mask_rcnn train script...
for just one example

**Comment by zhreshold** [comment]
These should be fixed in upcoming changes. For reference, please check the `estimator` branch.
