### ISSUE TITLE
[Website] API ref gluoncv.model_zoo doesn't include ResNEXT

### ISSUE THREAD

**Issue by ChaiBapchya** [dmlc/gluon-cv#1400]
While GluonCV -> Model Zoo -> Classification shows ResNEXT: https://gluon-cv.mxnet.io/model_zoo/classification.html

API reference guide, doesn't include `resnext` in 
```
gluoncv.model_zoo.get_model()
```
https://gluon-cv.mxnet.io/api/model_zoo.html#gluoncv-model-zoo-get-model

**Comment by zhreshold** [comment]
The API ref are generated from .md files, I will update this
