### ISSUE TITLE
gluoncv issue on windows 10

### ISSUE THREAD

**Issue by alighofrani95** [dmlc/gluon-cv#1402]
I have to switch my implementation of video classification based on i3d from ubuntu 18.04 to windows 10 by installation the same packages I faced with the below issue

python 3.8 , cudatoolkit 10.1, mxnet-cu101mkl  1.6.0b20191125, gluoncv            0.8.0b20200727

FileNotFoundError: Could not find module '.\Anaconda3\envs\ghofrani\lib\site-packages\mxnet\libmxnet.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by Neutron3529** [comment]
maybe the installation of mxnet is incorrect.
copy `libmxnet.dll` to the path it reported may help.

(Why you choose Windows? it takes me about 1 min to execute `import mxnet as mx` on my `windows 10`, and takes another 3~6min to load all the CIFAR data (and exhaust all my 64GB memory))

AFAIK, mxnet on win10 is much slower than it is in Linux.
why you choose windows?

**Comment by zhreshold** [comment]
Seems to be the exactly the same error as: https://github.com/dmlc/gluon-cv/issues/1409#issuecomment-672439097

Please try reinstall mxnet from the s3 hosted wheels

**Comment by dai-ichiro** [comment]
I think the problem can be solved using Python version 3.7.

**Comment by DB11051998** [comment]
i am still facing the problem while I am doing the pip/conda install of glunocv. need help!

**Comment by dogballlee** [comment]
guys im facing the same error too(win10, python3.8)... i've reinstalled mxnet twice but this error still occurred, really need ur help!
