### ISSUE TITLE
could you make the git tags consistent?

### ISSUE THREAD

**Issue by hubutui** [dmlc/gluon-cv#1411]
Glad to know 0.8.0 is released. Do not forget "v" in tag `v0.8.0`, just like what you use for older release, it helps me a lot for gluoncv auto packaging for ArchLinux.

**Comment by bryanyzhu** [comment]
Sure, of course. Thank you for pointing it out, just changed it to `v0.8.0`

**Comment by hubutui** [comment]
Thanks
