### ISSUE TITLE
Feature extraction using I3D

### ISSUE THREAD

**Issue by ysminabk** [dmlc/gluon-cv#1418]
I followed the same steps as the feature extraction tutorial using I3D, however, when I print the shape of the npy array I get, the shape is [1,2048]. My guess is this is what we get after flattening. After reading the documentation provided (gluoncv.model_zoo.action_recognition.i3d_resnet), it says that feat_ext: bool specifies whether or not to extract features before classification layer or do a complete forward pass. I tried setting bool to True and False, I still get the same shape [1,2048]. I want to generate the features without the flattening. Any insights on how to achieve that? Thank you

**Comment by bryanyzhu** [comment]
Right now, the code for feature extraction is here,

https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/action_recognition/i3d_resnet.py#L622-L623

As you can see, this feature is after flattening and temporal segment, which is the 1x2048 you get. 

If you want to get the features without flattening, you can return the `feat` here

https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/action_recognition/i3d_resnet.py#L612

But this changes the source code, so you can't use `pip install gluoncv`. You need to download gluoncv and compile it on your own, just do `pip install -e .` Let me know if you have further questions.

**Comment by bryanyzhu** [comment]
Close the issue due to inactive, feel free to reopen it if problem persists.

**Comment by mobraine** [comment]
Hello, thanks for the amazing work! 

What I want to achieve is similar to OP's, but I want the shape to be [x,4096], where x is a variable that depends on the length of the video. For example, I want to extract features for every 16 frames, so x=len(video)/16. Could you please tell me how to do that? As I understand it, usually x is the number of segments specified in the arguments and is fixed for all videos. And also how to generate 4096 columns?

Thank you very much!

**Comment by bryanyzhu** [comment]
@mobraine I think there are multiple ways to achieve this goal, I can suggest a most straightforward way IMO. Suppose you have a long video about 5 minutes (so that is 5 * 60 * 30 = 9000 frames), the pseudo code will look like

```
video = decord.video_reader(VIDEO_FILE)
model = get_model(MODEL_NAME, feat_ext=True)

extracted_features = []
for i in range(0, 9000, 16):
    input_clip = video[i:i+16]
    feature = model(input_clip)
    extracted_features.append(feature)
```
You will end up with a list of about 9000/16 = 562 features, each feature is 1x4096 dimension. Since 9000 is not divisible by 16, you can either discard the last few frames, or copy the last frame to make 9000 divisible by 16. Hope this helps.

**Comment by mobraine** [comment]
Thanks! I'll try it!

**Comment by mobraine** [comment]
I am new to this area, sorry if this is a silly question, however, I was wondering how to ensure there are 4096 columns? I mean, in the first place I don't know where 2048 comes from in the original source code, so can you explain please? I was trying to modify the i3d_resnet.py you posted.

**Comment by bryanyzhu** [comment]
If it is i3d_resnet, then the feature dimension is 2048. The dimension is defined in this line of code, https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/action_recognition/i3d_resnet.py#L524

**Comment by mobraine** [comment]
Hi @bryanyzhu I changed self.feat_dim = self.block.expansion * 64 * 2**(len(self.stage_blocks) - 1) to self.feat_dim = self.block.expansion * 128 * 2**(len(self.stage_blocks) - 1) but I'm getting this error 

`Traceback (most recent call last):
  File "feat_extract.py", line 235, in <module>
    main(logger)
  File "feat_extract.py", line 203, in main
    feat_ext=True, num_segments=duration//16, num_crop=opt.num_crop)
  File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/gluon_py36_real/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", line 409, in get_model
    net = _models[name](**kwargs)
  File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/gluon_py36_real/lib/python3.6/site-packages/gluoncv/model_zoo/action_recognition/i3d_resnet.py", line 682, in i3d_resnet50_v1_kinetics400
    tag=pretrained, root=root), ctx=ctx)
  File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/gluon_py36_real/lib/python3.6/site-packages/mxnet/gluon/block.py", line 556, in load_parameters
    params[name]._load_init(loaded[name], ctx, cast_dtype=cast_dtype, dtype_source=dtype_source)
  File "/home/share/wangzilong2/home/share/wangzilong2/anaconda3/envs/gluon_py36_real/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 281, in _load_init
    self.name, str(self.shape), str(data.shape))
AssertionError: Failed loading Parameter 'dense0_weight' from saved params: shape incompatible expected (400, 4096) vs saved (400, 2048)`

Do you know if I can do something to change the saved parameters? Thanks again!

**Comment by mobraine** [comment]
OK I realize I probably cannot change the pretrained parameters because it's pretrained! Thank you for your help tho @bryanyzhu!

**Comment by mobraine** [comment]
Hi! Another question, I used `python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 64 --new-length 16` to extract features [here](https://cv.gluon.ai/build/examples_action_recognition/feat_custom.html) 

and I found that my output npy arrays have the shape [64,2048,4,7,7]. When I merged all the npy files in hdf5 format and viewed them in a hdf5 viewer, they seem to be just as normal as [64, 2048], but when I used them to train, they still have the shape [64,2048,4,7,7]. I wonder how to remove the last three dimensions?

Here is the trace back of shape changing: 
Initially, my clip_input in line 95 `clip_input = video_utils._video_TSN_decord_batch_loader(video_name, decord_vr, duration, segment_indices, skip_offsets)` from feat_extract.py has shape [2048, 256, 340, 3], 
then it became [2048, 3, 224, 224] after line 101 `clip_input = transform(clip_input)`, 
then [64, 32, 3, 224, 224] after line 111 `clip_input = clip_input.reshape((-1,) + (opt.new_length, 3, opt.input_size, opt.input_size))`, 
then [64, 3, 32, 224, 224] after line 112 `clip_input = np.transpose(clip_input, (0, 2, 1, 3, 4))`
and remained this shape as input into i3d_resnet50_v1_kinetics400,
and finally the output of i3d network has shape [64, 2048, 4, 7, 7]

**Comment by bryanyzhu** [comment]
The output should have shape of 64x2048, there shouldn't be the last three dimensions. As you can see in this code snippet (https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/action_recognition/i3d_resnet.py#L614-L623), the last three dimensions are already squeezed out in line 616. 

But even you get the output like [64, 2048, 4, 7, 7], you can simply take the average of the last three dimensions and squeeze it like I did. 

```
st_avg = nn.GlobalAvgPool3D()
pooled_feat = st_avg(feat)
x = F.squeeze(pooled_feat, axis=(2, 3, 4))
```
This will eventually give you the right shape.

**Comment by mobraine** [comment]
Thank you so much Bryan @bryanyzhu!

**Comment by DungVo1507** [comment]
Hello @mobraine, I am new in this field, even newer than you. I'm following the instructions in section 8 [:](https://cv.gluon.ai/build/examples_action_recognition/feat_custom.html) like you mentioned.

I need the shape of each video's npy file to be (10, 32, 2048) respectively 10 is 10-crop augmentation, 32 is 32 segments of each video. Even though I have set --num-crop=10 and --num-segment=32 but the resulting shape of the npy files I get is (1, 2048).

Hope you can explain and guide me, thank you!

Below is my command line:
python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --num-crop 10

**Comment by mobraine** [comment]
Hi @DungVo1507, for 32 segmentations, you have to modify the original source code as @bryanyzhu pointed out here https://github.com/dmlc/gluon-cv/blob/f22650a5d31c31956d9392530a0e619689cdb3c5/gluoncv/model_zoo/action_recognition/i3d_resnet.py#L612 . You can just return outs[0] on that line, and that should give you feature shape [32, 2048]. This piece of code should be located in something like bin/gluoncv/model_zoo/action_recognition/i3d_resnet.py. I couldn't recall the exact path and I can't find it for now, so good luck!

for 10-crop, I am not very familiar with it but I think it is done on each frame (image)? Maybe @bryanyzhu can help!

**Comment by DungVo1507** [comment]
Hello @mobraine,
You mean I have to download the file i3d_resnet.py then return feat at line 623. Then run the files i3d_resnet.py and feat_extract.py, correct?
Thank you!

**Comment by DungVo1507** [comment]
Thank you @mobraine very much I got the shape (32, 2048, 2, 7, 7) but I still can't squeeze the last 3 dimensions, can you help me with detailed instructions?
Even though I've seen @bryanyzhu 's response, I still can't do it.
Thank you!

**Comment by bryanyzhu** [comment]
Hi, if you already get shape like (32, 2048, 2, 7, 7), you should be able to follow code below to squeeze it, 

```
st_avg = nn.GlobalAvgPool3D()
pooled_feat = st_avg(feat)
x = F.squeeze(pooled_feat, axis=(2, 3, 4))
```

Or if this doesn't work, you can turn `ndarray` to `numpy array`, and use numpy functions to take average/squeeze the feature, sth like

```
feat_np = feat.asnumpy()
feat_avg = numpy.mean(feat_np, axis=(2,3,4), keepdims=False)
```

**Comment by DungVo1507** [comment]
Thank you @bryanyzhu, 
I don't know if I'm doing what you say, but the shape I still haven't erased the last 3 dimensions of the shape?
I tried with the 2 ways you showed me, I don't know if it's because of the variable name mismatch?
`def hybrid_forward(self, F, x):
        """Hybrid forward of I3D network"""
        x = self.first_stage(x)
        outs = []
        for i, res_layer in enumerate(self.res_layers):
            x = res_layer(x)
            if i in self.out_indices:
                outs.append(x)
            if i == 0:
                x = self.pool2(x)

        feat = outs[0]

        # spatial temporal average
        pooled_feat = self.st_avg(feat)
        x = F.squeeze(pooled_feat, axis=(2, 3, 4))

        # feat_np = feat.asnumpy()
        # feat_avg = numpy.mean(feat_np, axis=(2,3,4), keepdims=False)

        # segmental consensus
        x = F.reshape(x, shape=(-1, self.num_segments * self.num_crop, self.feat_dim))
        x = F.mean(x, axis=1)

        if self.feat_ext:
            return feat
            # return x

        x = self.head(x)
        return x`
Hope you can patiently help me, sorry for not understanding too much.
Thank you!

**Comment by bryanyzhu** [comment]
You already squeeze `feat` to `x`, but you are still returning `feat`, that's why you still have those dimensions.  

The correct code should be
```
feat = outs[0]

# spatial temporal average
pooled_feat = self.st_avg(feat)
x = F.squeeze(pooled_feat, axis=(2, 3, 4))

if self.feat_ext:
        return x
```

You don't need segmental consensus.

**Comment by DungVo1507** [comment]
Sorry @bryanyzhu, if `return x` the result of the shape is (1, 2048), and if `return feat`, the result of the shape is (32, 2048, 2, 7, 7). I don't know why?

**Comment by DungVo1507** [comment]
Thank you @bryanyzhu, I got the shape (32, 2048).
I have 2 more questions that I hope you can help with:

- My initial aim is to have shape (10, some k, 2048) where 10 is 10-crop augmentation, some k is the number of segments (for example, if we specify each segment has 16 frames, then k is equal to the total number of frames. /16), do you know where to change the code to achieve this shape?

- I am in the process of solving an Anomaly Detection problem. Suppose I have 2 classes (directories): normal (contains normal videos) and abnormal (contains unusual videos), then after extracting I3D features on each class, when training the model, the model will automatically know which feature belongs to the input class right?

I'm feeling very happy about your help, thank you!

**Comment by bryanyzhu** [comment]
- I believe you are using 1-crop because the shape is 32. If you use 10-crop, the shape will be (320,2048). You just need to reshape it to (10,32, 2048), that should do the job. 

- As long as you put the features in two separate directories, then yes, the model will know the features are from two classes.

**Comment by DungVo1507** [comment]
@bryanyzhu, 
I don't know if I'm doing it exactly as you suggested, but the shape result is still (32, 2048) not (320, 2048). May I ask where else should I change?
Below is my command line:
`!python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --new-length 16 --num-crop 10`

and in the i3d_resnet.py file I keep the same:
feat = outs[0]

# spatial temporal average
pooled_feat = self.st_avg(feat)
x = F.squeeze(pooled_feat, axis=(2, 3, 4))

if self.feat_ext:
        return x

Thank you @bryanyzhu so much!

**Comment by DungVo1507** [comment]
@bryanyzhu,
I don't know if I'm doing it exactly as you suggested, but the shape result is still (1, 32, 2048) not (320, 2048). May I ask where else should I change?
Below is my command line:
`!python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --new-length 16 --num-crop 10`

and in the i3d_resnet.py file I reshaped :

```
feat = outs[0]

# spatial temporal average
pooled_feat = self.st_avg(feat)
x = F.squeeze(pooled_feat, axis=(2, 3, 4))

x = F.reshape(x, shape=(self.num_crop, self.num_segments, self.feat_dim))

if self.feat_ext:
        return x
```
Thank you @bryanyzhu so much!

**Comment by bryanyzhu** [comment]
Try append `--ten-crop` to your command and see,

```
python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --new-length 16 --num-crop 10 --ten-crop
```

**Comment by DungVo1507** [comment]
Yesterday I tried many times, from 1-crop, 3-crop to 10-crop but the result is still (1, 32, 2048) even though I reshape `x = F.reshape(x, shape=(self.num_crop, self.num_segments, self.feat_dim))` .
I wonder if at some step num_crop has been set back to the default of 1?

I am so grateful every time you help me, thank you @bryanyzhu!

**Comment by DungVo1507** [comment]
Yesterday I tried many times, from 1-crop, 3-crop to 10-crop but the result is still (1, 32, 2048) even though I reshape `x = F.reshape(x, shape=(self.num_crop, self.num_segments, self.feat_dim))` .
I wonder if at some step num_crop has been set back to the default of 1?

I am so grateful every time you help me, thank you @bryanyzhu!

**Comment by DungVo1507** [comment]
Yesterday I tried many times, from 1-crop, 3-crop to 10-crop but the result is still (1, 32, 2048) even though I reshape `x = F.reshape(x, shape=(self.num_crop, self.num_segments, self.feat_dim))` .
I wonder if at some step num_crop has been set back to the default of 1?

I am so grateful every time you help me, thank you @bryanyzhu!

**Comment by bryanyzhu** [comment]
Maybe you are right, this needs some investigation. You can print out `num_crop`, `num_segments`, etc to see how they change along the process. I believe it can be done with some simple changes.

**Comment by DungVo1507** [comment]
I also looked at the entire input parameter after running this command line:
`python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --new-length 16 --num-crop 10 --ten-crop`

And here is the full input parameter information:
`INFO:logger:Namespace(data_aug='v1', data_dir='', data_list='video.txt', dtype='float32', fast_temporal_stride=2, gpu_id=0, hashtag='', input_size=224, log_interval=10, mode=None, model='i3d_resnet50_v1_kinetics400', need_root=False, new_height=256, **new_length=16**, new_step=1, new_width=340, num_classes=400, **num_crop=10**, **num_segments=32**, resume_params='', save_dir='./i3d_feature_npy/1', slow_temporal_stride=16, slowfast=False, **ten_crop=True**, three_crop=False, use_decord=True, use_pretrained=True, video_loader=True)`

I tried to find out if there was a step after this that set num_crop=1 back but I didn't see it.
Thank you @bryanyzhu !

**Comment by DungVo1507** [comment]
I also looked at the entire input parameter after running this command line:
`python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --new-length 16 --num-crop 10 --ten-crop`

And here is the full input parameter information:
`INFO:logger:Namespace(data_aug='v1', data_dir='', data_list='video.txt', dtype='float32', fast_temporal_stride=2, gpu_id=0, hashtag='', input_size=224, log_interval=10, mode=None, model='i3d_resnet50_v1_kinetics400', need_root=False, new_height=256, new_length=16, new_step=1, new_width=340, num_classes=400, num_crop=10, num_segments=32, resume_params='', save_dir='./i3d_feature_npy/1', slow_temporal_stride=16, slowfast=False, ten_crop=True, three_crop=False, use_decord=True, use_pretrained=True, video_loader=True)`
I tried to find out if there was a step after this that set num_crop=1 back but I didn't see it.

I tried:
`x = F.reshape(x, shape=(self.num_crop, self.num_segments, self.feat_dim))`
`x = F.reshape(x, shape=(self.num_segments, self.feat_dim))`
I discovered one thing that whether this command line changes or not, the output shape will still be (1, 32, 2048)
And without this reshape command line, the resulting shape is (32, 2048)

Thank you @bryanyzhu!

**Comment by DungVo1507** [comment]
I also looked at the entire input parameter after running this command line:
`python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --new-length 16 --num-crop 10 --ten-crop`

And here is the full input parameter information:
`INFO:logger:Namespace(data_aug='v1', data_dir='', data_list='video.txt', dtype='float32', fast_temporal_stride=2, gpu_id=0, hashtag='', input_size=224, log_interval=10, mode=None, model='i3d_resnet50_v1_kinetics400', need_root=False, new_height=256, new_length=16, new_step=1, new_width=340, num_classes=400, num_crop=10, num_segments=32, resume_params='', save_dir='./i3d_feature_npy/1', slow_temporal_stride=16, slowfast=False, ten_crop=True, three_crop=False, use_decord=True, use_pretrained=True, video_loader=True)`
I tried to find out if there was a step after this that set num_crop=1 back but I didn't see it.

I tried:
`x = F.reshape(x, shape=(self.num_crop, self.num_segments, self.feat_dim))`
`x = F.reshape(x, shape=(self.num_segments, self.feat_dim))`
I discovered one thing that whether this command line changes or not, the output shape will still be (1, 32, 2048)
And without this reshape command line, the resulting shape is (32, 2048)

Thank you @bryanyzhu!

**Comment by DungVo1507** [comment]
I also looked at the entire input parameter after running this command line:
`python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --new-length 16 --num-crop 10 --ten-crop`

And here is the full input parameter information:
`INFO:logger:Namespace(data_aug='v1', data_dir='', data_list='video.txt', dtype='float32', fast_temporal_stride=2, gpu_id=0, hashtag='', input_size=224, log_interval=10, mode=None, model='i3d_resnet50_v1_kinetics400', need_root=False, new_height=256, new_length=16, new_step=1, new_width=340, num_classes=400, num_crop=10, num_segments=32, resume_params='', save_dir='./i3d_feature_npy/1', slow_temporal_stride=16, slowfast=False, ten_crop=True, three_crop=False, use_decord=True, use_pretrained=True, video_loader=True)`
I tried to find out if there was a step after this that set num_crop=1 back but I didn't see it.

I tried:
`x = F.reshape(x, shape=(self.num_crop, self.num_segments, self.feat_dim))`
`x = F.reshape(x, shape=(self.num_segments, self.feat_dim))`
I discovered one thing that whether this command line changes or not, the output shape will still be (1, 32, 2048)
And without this reshape command line, the resulting shape is (32, 2048)

Thank you @bryanyzhu!

**Comment by DungVo1507** [comment]
I also looked at the entire input parameter after running this command line:
`python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --new-length 16 --num-crop 10 --ten-crop`

And here is the full input parameter information:
`INFO:logger:Namespace(data_aug='v1', data_dir='', data_list='video.txt', dtype='float32', fast_temporal_stride=2, gpu_id=0, hashtag='', input_size=224, log_interval=10, mode=None, model='i3d_resnet50_v1_kinetics400', need_root=False, new_height=256, new_length=16, new_step=1, new_width=340, num_classes=400, num_crop=10, num_segments=32, resume_params='', save_dir='./i3d_feature_npy/1', slow_temporal_stride=16, slowfast=False, ten_crop=True, three_crop=False, use_decord=True, use_pretrained=True, video_loader=True)`
I tried to find out if there was a step after this that set num_crop=1 back but I didn't see it.

I tried:
`x = F.reshape(x, shape=(self.num_crop, self.num_segments, self.feat_dim))`
`x = F.reshape(x, shape=(self.num_segments, self.feat_dim))`
I discovered one thing that whether this command line changes or not, the output shape will still be (1, 32, 2048)
And without this reshape command line, the resulting shape is (32, 2048)

Thank you @bryanyzhu!
