### ISSUE TITLE
shape incompatible

### ISSUE THREAD

**Issue by ahchang2** [dmlc/gluon-cv#1427]
I got the same question as #844. The difference is that I'm using ssd model on my own dataset while he used yolo model.
The solution he found out is {change code in train_yolo3.py line 308 net_name = ''.join(('yolo3', args.network, args.dataset)) to net_name = ''.join(('yolo3', args.network, 'custom'))}. However, for train_ssd.py, the code is a little different: net_name = '_'.join(('ssd', str(args.data_shape), args.network, 'custom')). I've already changed the args.dataset to 'custom', but there's an additional argument of str(args.data_shape) that I don't know how to modify (I tried for multiple times but failed running the script). Here's the code and problem:

from gluoncv import model_zoo, data, utils
from matplotlib import pyplot as plt
import gluoncv as gcv

net = gcv.model_zoo.get_model('ssd_300_vgg16_atrous_custom', classes='bleeding_site', pretrained=False)
net.load_parameters('ssd_300_vgg16_atrous_custom_best.params')

AssertionError: Failed loading Parameter 'ssd3_convpredictor0_conv0_weight' from saved params: shape incompatible expected (56, 0, 3, 3) vs saved (8, 512, 3, 3)

**Comment by zhreshold** [comment]
for ssd the network has specific shape to deal with, while for yolo it's trained in a multi-resolution style so shape is more flexible.

But here I don't know what's `ssd_300_vgg16_atrous_custom_best.params` and how it comes from?
