### ISSUE TITLE
Inferencing on semantic segmentation task using the danet_resnet101_citys model

### ISSUE THREAD

**Issue by amil-rp-work** [dmlc/gluon-cv#1429]
Hello!

I am trying to use a random image from the web for inferencing the `danet_resnet101_citys` model on the Semantic Segmentation task.
However I am facing the following error `AssertionError: Argument data must have NDArray type, but got tuple`.
I am using the following code
```
model = gluoncv.model_zoo.get_model('danet_resnet101_citys', pretrained=True, ctx= ctx)
img = image.imread('./target_images3/'+imag)
img = test_transform(img, ctx)
output = model.predict(img)
predict = mx.nd.squeeze(mx.nd.argmax(output, 1)).asnumpy()
mask = get_color_pallete(predict, 'citys')
```
Also I would like to know if there are

- Specific ordering of channels
- Image resizing to be done before inference
- Normalizing the values of the pixel
- Any other pre-processing that might hinder the outputs?

Thanks in advance !!!

**Comment by bryanyzhu** [comment]
@xdeng7 Any idea? Thank you.

**Comment by xdeng7** [comment]
It looks like the test_transform creates tuple not ndarray, the input should be just the transformed image which is ndarray. Could you please show me the test_transform function so that I can provide some help?

**Comment by amil-rp-work** [comment]
I have used the following function
`from gluoncv.data.transforms.presets.segmentation import test_transform`
The link to the code is here 
[https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/transforms/presets/segmentation.py#L6](url)

**Comment by dai-ichiro** [comment]
I think that is because danet returns tuple.
```
    def hybrid_forward(self, F, x):
        c3, c4 = self.base_forward(x)

        x = self.head(c4)
        x = list(x)
        x[0] = F.contrib.BilinearResize2D(x[0], **self._up_kwargs)
        x[1] = F.contrib.BilinearResize2D(x[1], **self._up_kwargs)
        x[2] = F.contrib.BilinearResize2D(x[2], **self._up_kwargs)

        outputs = [x[0]]
        outputs.append(x[1])
        outputs.append(x[2])

        return tuple(outputs)
```

**Comment by xdeng7** [comment]
Yes, that's correct. Since danet use a different loss from cross entropy, there are three outputs. I should fix the predict function to include just one output. Thanks for your feedback. So far, you can just call output, _, _=model(image) to perform inference. I'll let you know once I fix the predict function.
