### ISSUE TITLE
How should we understand the CAM mechanism in DANet

### ISSUE THREAD

**Issue by BebDong** [dmlc/gluon-cv#1444]
@xdeng7 In the implementation of the Channel Attention Module (CAM) in DANet lies ```energy_new = F.max(energy, -1, True).broadcast_like(energy) - energy```, how should we understand this?  Does it serve as normalization or something? Thanks very much!

**Comment by BebDong** [comment]
In the [original repository](https://github.com/junfu1115/DANet/issues/9), the author said "Prevent loss divergence during training". I am a little confused by this saying.

**Comment by bryanyzhu** [comment]
@xdeng7 Can you help to explain? Thank you.
