### ISSUE TITLE
train monodepth2 error

### ISSUE THREAD

**Issue by 791136190** [dmlc/gluon-cv#1460]
gluoncv==0.9.0b20200924
mxnet=1.6.0

https://github.com/dmlc/gluon-cv/blob/cf767a1297d67caf41577508aacc7cbc24ae8f14/gluoncv/model_zoo/monodepthv2/pose_decoder.py#L77

when use --hybridize, get errors:

mxnet.base.MXNetError: Invalid Parameter format for keep_highest expect boolean but value='6', in operator Reshape(name="", keep_highest="6", target_shape="1", reverse="2", shape="-1")

**Comment by bryanyzhu** [comment]
@KuangHaofei Can you look into this? Thanks.

**Comment by bryanyzhu** [comment]
We already fixed this issue in PR #1472 , please try it out and let us know if the problem still exists. Thank you.
