### ISSUE TITLE
Sample for transfer learning Mask-RCNN on custom COCO dataset

### ISSUE THREAD

**Issue by BernhardGlueck** [dmlc/gluon-cv#1461]
Hi !

I would like to take a pretrained Mask-RCNN model, and fit it to a custom dataset with custom classes in COCO format.
Are there any tutorials/samples on how to achieve this ? A bonus would be to export the network in symbolic format to perform training in Amazon DLJ

**Comment by zhreshold** [comment]
The COCOInstance dataset is able to take any dataset in coco format, you can feed in another split other than the default ones.

**Comment by BernhardGlueck** [comment]
Yeah ... but then the classes would not match ? As far as i can see those are hard coded in the COCOInstance class....

**Comment by zhreshold** [comment]
@BernhardGlueck  You can directly overwrite the classes 

```python
class MyCOCOInstance(COCOInstance):
CLASSES = [...]
def __init__(self, **kwargs):
    super().__init__(**kwargs)
```
