### ISSUE TITLE
iters_per_epoch error

### ISSUE THREAD

**Issue by 791136190** [dmlc/gluon-cv#1462]
https://github.com/dmlc/gluon-cv/blob/c10979273a40a1c2bfc546b6e8d82b86683445bc/scripts/depth/trainer.py#L124

maybe iters_per_epoch=self.train_loader.__len__() is right.because dataloader get batch_size >= 1.

**Comment by bryanyzhu** [comment]
@KuangHaofei Please have a look if you are available. Thank you.

**Comment by bryanyzhu** [comment]
@791136190 Thank you for catching this, we already fixed it in PR #1472 . Feel free to reopen this issue if you run into problems.

**Comment by pandyadhatri** [comment]
I am trying to train custom dataset for video classification but getting error in trainer function 
XNetError                                Traceback (most recent call last)
<ipython-input-70-72280502c8a8> in <module>()
     20         # AutoGrad
     21         with ag.record():
---> 22             output = [net(X) for X in data]
     23         #    loss = [loss_fn(yhat, y) for yhat, y in zip(output, label)]
     24             loss_fn = gluon.loss.SoftmaxCrossEntropyLoss(sparse_label=False)

8 frames
/usr/local/lib/python3.7/dist-packages/mxnet/base.py in check_call(ret)
    244     """
    245     if ret != 0:
--> 246         raise get_last_ffi_error()
    247 
    248 

MXNetError: MXNetError: Shape inconsistent, Provided = [64,784], inferred shape=(64,4816896)
