### ISSUE TITLE
Num_Class of MHPV1 dataset

### ISSUE THREAD

**Issue by baorave** [dmlc/gluon-cv#1475]
NUM_CLASS of class MHPV1Segmentation in data/mhp.py is 18, while num_class of mhpv1 dataset should be 19. And the comment behind denotes that the classes do not include background. But the first class should be background. And obviously the trained model is trained with 18 classes. Can somebody  help me out of my confusion？

**Comment by bryanyzhu** [comment]
@KuangHaofei Can you help to look into this? Thank you.

**Comment by bryanyzhu** [comment]
Thank you for pointing it out, the issue has been fixed in PR #1518. Our pretrained model is also updated. Feel free to reopen the issue if problem still exists.
