### ISSUE TITLE
Cpp inference and GPU memory management

### ISSUE THREAD

**Issue by MathildeSchnei** [dmlc/gluon-cv#1477]
Hi,

I am trying to run inferences of a yolov3 model. 
I tried 2 different ways: with an executor and with a predictor handler.
With the predictor handler, I observe a memory leak (the GPU consumption raises by around 52 MiB at each new inference) and with the executor the memory is stable but hudge (it uses 3 times more GPU RAM than the predictor)
I saw a lot of people saying that the GPU RAM is realesed when the program is exited but mine should not be left.
I already tried to set environment variables such as MXNET_GPU_MEM_POOL_RESERVE or to use MXStorageEmptyCache but nothing worked so far.
So what I need is running a lot of inferences without exiting the program but the memory leak ends up crashing it. 
Is there a way to avoid these memory issues?

**Comment by romqn1999** [comment]
I have the same memory leak issues.
I use model from model zoo:
`ctx = mx.gpu(0)`
`net = gluoncv.model_zoo.get_model('ssd_512_resnet50_v1_custom', pretrained_base=False, classes=['name1', 'name2'], ctx=ctx)`
`net.load_parameters('model_path', ctx=ctx)`
`net.set_nms(nms_thresh=0.2)`
and then run many inferences:
`mx_frame = mx.nd.array(image)`
`x, _ = gluoncv.data.transforms.presets.ssd.transform_test(mx_frame, short=512)`
`x = x.as_in_context(ctx)`
`labels, scores, bboxes = net(x)`
I also got the GPU consumption raises by around 10 MiB at each new inference. I tested on `gluoncv==0.10.1.post0` and `mxnet-cu101==1.8.0.post0`.
