### ISSUE TITLE
VOCDetection Dataset: Warning Invalid label 

### ISSUE THREAD

**Issue by bedilbek** [dmlc/gluon-cv#1481]
After the initialization of [`VOCDetection`](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/pascal_voc/detection.py#L20) Dataset object for training or validation, it was giving warning that `xmin` or `ymin` are not in the right range and that their value is -1.

Then I saw an interesting piece of [code](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/pascal_voc/detection.py#L124) where 1 was subtracted from the value of `xmin` and then the same for `ymin`. I could not get it, because I had some labels where minimum coordinates were at extremes. Is it the expected behavior?

**Comment by zhreshold** [comment]
This behavior of -1 is to accomodate the standard VOC2007/2012 datasets where bbox range from 1 to max width/height. If you have a custom dataset with different scale, try override this behavior or have a preprocess script to convert all objects to the right ranges.
