### ISSUE TITLE
Anyone working on yolov5 or yolov4 port ?

### ISSUE THREAD

**Issue by djaym7** [dmlc/gluon-cv#1487]
Someone previously commented yolov4 is full of tricks and trains slower .. Inference speed and accuracy matters more in my/most cases. It would be great if gluoncv supports one of two in model zoo.

**Comment by tlind** [comment]
Yes, the improvement in accuracy of YOLOv4 is quite large, while providing comparable inference speed. Would be great to have it! There is another issue requesting this feature here: https://github.com/dmlc/gluon-cv/issues/1321
