### ISSUE TITLE
Code Style Issues

### ISSUE THREAD

**Issue by piiswrong** [dmlc/gluon-cv#150]
- [x] Should be a metric class instead of a bunch of functions. BTW why is it specific to VOC? https://github.com/dmlc/gluon-cv/blob/master/gluoncv/utils/metrics/voc_segmentation.py
- [x] Why put nn under util?
- [ ] There is nn.BBoxCornerToCenter and utils.bbox.bbox_xyxy_to_xywh . Are they duplicates?
- [ ] data.transforms should be Block based transformers instead of functions
- [x] Why put test function in main codebase? https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/__init__.py#L12

**Comment by zhanghang1989** [comment]
About the last comment, that is a batchify function in dataset `test mode`, I will rename it to remove the ambiguity.

**Comment by zhreshold** [comment]
2. I will merge utils.nn into nn after faster rcnn PR
3. BBoxCornerToCenter is pure hybrid block, while bbox_xyxy_to_xywh is a numpy function specifically used for coco dataset(xyxy is different from corner format)

**Comment by piiswrong** [comment]
@zhanghang1989 any updates on 1?

**Comment by zhanghang1989** [comment]
Sorry for the delay. Will fix in next PR.

**Comment by hetong007** [comment]
@zhanghang1989 do you mean in PR #241

**Comment by zhanghang1989** [comment]
Yeah, thanks for pointing out. I will push a new commit soon in that PR.
