### ISSUE TITLE
export action recognition model fail

### ISSUE THREAD

**Issue by h030162** [dmlc/gluon-cv#1505]
code:export_block('i3d_resnet50_v1_ucf101', net, preprocess=True, layout='HWC')

  File "/usr/local/lib/python3.6/site-packages/gluoncv/utils/export_helper.py", line 153, in export_block
    raise RuntimeError(str(last_exception).splitlines()[0])
RuntimeError: MXNetError: Error in operator conv0_fwd: [08:33:06] src/operator/nn/convolution.cc:211: Check failed: dshp.ndim() == 5U (4 vs. 5) : Input data should be 5D in batch-num_filter-depth-y-x

what is it, please help?

**Comment by h030162** [comment]
Is this right?
export_block('i3d_resnet50_v1_ucf101', net, data_shape=(3,36,224,224), preprocess=False, layout='CTHW')

**Comment by bryanyzhu** [comment]
layout='CTHW' is correct. As for data shape, I'm not sure whether (3,36,224,224) or (1,3,36,224,224), please try it, one of them should be correct.
