### ISSUE TITLE
How can we train SlowFast model on subset Kinetics400

### ISSUE THREAD

**Issue by siriusmehta** [dmlc/gluon-cv#1524]
Hi,
Is there anyway we can train SlowFast model for action recognition on a subset of Kinetics400 dataset ?
Thanks

**Comment by bryanyzhu** [comment]
You can follow this tutorial, https://cv.gluon.ai/build/examples_action_recognition/dive_deep_slowfast_kinetics400.html

Actually, you only need to change two things. Assume you want to train a subset of 200 classes,

(1) Change number of classes to 200 in SlowFast model definition

(2) Generate a new train.txt and val.txt on this subset.

**Comment by siriusmehta** [comment]
Thanks @bryanyzhu  !

Also, I have tried finetune_custom for fintuning on cutom dataset. Is there anyway I can save the checpoints (trained model) and inference it ?

https://cv.gluon.ai/build/examples_action_recognition/finetune_custom.html

**Comment by bryanyzhu** [comment]
Yes, you can use standard `torch.save(model.state_dict(), PATH)` to save checkpoints.

In terms of inference, you can either modify this [file](https://github.com/dmlc/gluon-cv/blob/master/scripts/action-recognition/test_recognizer.py) to evaluate your model's performance or follow this [tutorial](https://cv.gluon.ai/build/examples_action_recognition/demo_custom.html) to inference on a list of videos. I think the modification is minimal, but let me know if you have further questions. Thank you.

**Comment by siriusmehta** [comment]
Thanks @bryanyzhu .

Also, I did some experiment with gluon export block post finetuning of slowfast_4x16_resnet50_custom. I tried exporting the trained model (architecture->json and the weights->.param) files where it throws an error:

from gluoncv.utils import export_block
export_block("slowfast_4x16_resnet50_custom", net)

**Error**:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-768c49892974> in <module>
      1 # #exporting the architecture and weights as well
      2 from gluoncv.utils import export_block
----> 3 export_block("slowfast_4x16_resnet50_custom", net)
      4 
      5 # net.export("slowfast_4x16_resnet50_custom", epoch=1)

~/anaconda3/envs/pyt1.7/lib/python3.6/site-packages/gluoncv/utils/export_helper.py in export_block(path, block, data_shape, epoch, preprocess, layout, ctx)
    151             last_exception = e
    152     if last_exception is not None:
--> 153         raise RuntimeError(str(last_exception).splitlines()[0])
    154 
    155 def export_tvm(path, block, data_shape, epoch=0, preprocess=True, layout='HWC',

RuntimeError: MXNetError: Error in operator slowfast2_slice1: [20:48:07] src/operator/tensor/./matrix_op-inl.h:786: Check failed: param_begin.ndim() <= dshape.ndim() (5 vs. 4) : Slicing axis exceeds data dimensions


But if I am exporting the same trained model using below:
# net.export("slowfast_4x16_resnet50_custom", epoch=1)

it sucessfully creates the .json and .params files. Am I missing anything here ?

Thanks

**Comment by siriusmehta** [comment]
@bryanyzhu 

Got it solved passing the other parameters of the export_block.

Thank you !

**Comment by bryanyzhu** [comment]
No problem, thank you for using GluonCV. Will close the issue for now. Feel free to reopen it if more problems come up.

**Comment by osamaibrahim13022** [comment]
> @bryanyzhu
> 
> Got it solved passing the other parameters of the export_block.
> 
> Also, In terms Inference I was able to deserialize the trained model with the inference tutorial
> 
> Appreciate your help 👍

can you please guide me as to what parameters you used after finetuning in the export_block function
