### ISSUE TITLE
SSD nms_topk params will be changed in validate() and will not be changed back in train() for train_ssd.py

### ISSUE THREAD

**Issue by WalterMa** [dmlc/gluon-cv#153]
Seems `net.set_nms()` only invoke in validate() for [train_ssd.py]( https://github.com/dmlc/gluon-cv/blob/4999f9795af7a21ca69adf5f72301b79f719498e/scripts/detection/ssd/train_ssd.py#L114) that change ssd nms_topk from default -1 to 400.
And those nms params will not be set back to default in train(). 

Is it expected function and will this influence training result？

**Comment by WalterMa** [comment]
Thanks.

May I ask one more question?

1. Can I define functions like set_nms() in my own detection network to change network parameter then call net.hybridize() again to make it work?

2. And will such this method that call net.hybridize() several times (normally two times for one epoch, change parameters in validate then change it back in train) involve some performance loss or any potential defects?

**Comment by zhreshold** [comment]
1. Yes
2. whenever you call net.hybridize(), the previous cached symbol will be removed and it start recording a new symbol, parameters won't be affected in this process. It is very unlikely you will encounter performance loss since you are not calling it frequently.

**Comment by WalterMa** [comment]
That‘s help me a lot. Thanks for your help!
I'd close this issue.
