### ISSUE TITLE
No module named 'gluoncv.torch'

### ISSUE THREAD

**Issue by ayanasser** [dmlc/gluon-cv#1538]
While working on getting features with pytorch and gluncv at this [script](https://cv.gluon.ai/build/examples_torch_action_recognition/extract_feat.html) 
I found this error
    from gluoncv.torch.utils.utils import build_log_dir
ModuleNotFoundError: No module named 'gluoncv.torch'

I installed mxnet and pytorch and I dn't know what else could be missing !

**Comment by ayanasser** [comment]
I solved it by installaing the nightly version of Gluoncv
with this line: pip install --pre --upgrade gluoncv

**Comment by bryanyzhu** [comment]
Yes, you are right. Since we haven't officially made a release, the pytorch models can only be accessed through nightly version.

**Comment by bryanyzhu** [comment]
Hi, GluonCV has released v0.9.0. Torch models are supported with native pip install now. I will close the issue for now, feel free to reopen if you encounter other issues.
