### ISSUE TITLE
No matching distribution found for decord

### ISSUE THREAD

**Issue by siriusmehta** [dmlc/gluon-cv#1539]
Hi, 

Trying to install decord on Jetson  as : 

pip install decord --user

**Error:**

ERROR: Could not find a version that satisfies the requirement decord (from versions: none)
ERROR: No matching distribution found for decord

Current version of mxnet : 1.7  Gluoncv: 0.8.0 installed in my environment

Thanks

**Comment by siriusmehta** [comment]
Hi,

Got it installed by building it from source.

Thanks

**Comment by bryanyzhu** [comment]
Glad to know, will close the issue for now. Feel free to reopen it if more problems come up.

**Comment by afzalex** [comment]
I don't understand, the issue of "No matching distribution found for decord" still exists. Why this issue is closed. Decord could be installed by building it, but 'pip install decord' does not work.

**Comment by jardabezdek** [comment]
I have downgraded python from 3.9 to 3.7. Then I was able to to install by pip.

```
pip install decord --user
```
