### ISSUE TITLE
Get Coordinates of joints in Pose Detection

### ISSUE THREAD

**Issue by mbs220** [dmlc/gluon-cv#1552]
hi
i followed this example: [demo_simple_pose](https://cv.gluon.ai/build/examples_pose/demo_simple_pose.html)
it works for me & is OK.

now i want to get the Coordinates of joints of body (for example 2 knees or 2 arms & etc.)  for some calculations. would you please help me guys?

thanks in advanced
Mohammad

**Comment by dai-ichiro** [comment]
Try to run this code.

```
from gluoncv import model_zoo, data, utils
from gluoncv.data.transforms.pose import detector_to_simple_pose, heatmap_to_coord

detector = model_zoo.get_model('yolo3_mobilenet1.0_coco', pretrained=True, root='./model')
pose_net = model_zoo.get_model('simple_pose_resnet18_v1b', pretrained=True, root='./model')
detector.reset_class(['person'], reuse_weights=['person'])

url = 'https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/segmentation/mhpv1_examples/1.jpg'
filename = 'sample.jpg'
utils.download(url, filename)

x, img = data.transforms.presets.ssd.load_test(filename, short=512)
class_IDs, scores, bounding_boxs = detector(x)
pose_input, upscale_bbox = detector_to_simple_pose(img, class_IDs, scores, bounding_boxs)
predicted_heatmap = pose_net(pose_input)
pred_coords, confidence = heatmap_to_coord(predicted_heatmap, upscale_bbox)

keypoints = data.mscoco.keypoints.COCOKeyPoints.KEYPOINTS
for keypoint_id in range(len(keypoints)):
    pred = pred_coords[:,keypoint_id,:]
    for i in range(pred.shape[0]):
        if (confidence[i,keypoint_id,:] > 0.2) == 1:
            print('%s:'%(keypoints[keypoint_id]))
            print(pred[i,:].asnumpy())
```

Hope this helps.

**Comment by mbs220** [comment]
hi dai-ichiro
thank you so much, it is what i was looking for.

i used PutText of cv2 to writing the labels on an image, the result was strange !
please take a look at these images below (with 3 labels and all labels )

[Image 1](https://s16.picofile.com/file/8416143118/RESULT_a577eed4_09c7_40b5_8448_8ce030478156_Tree_Pose1_01.jpg
)
[Image 2](https://s16.picofile.com/file/8416143150/RESULT_a577eed4_09c7_40b5_8448_8ce030478156_Tree_PoseALL.jpg)

![RESULT_a577eed4-09c7-40b5-8448-8ce030478156_Tree-Pose1_01](https://user-images.githubusercontent.com/13784609/100925395-31ae3900-34f7-11eb-8ba8-8dda52c03b3b.jpg)
![RESULT_a577eed4-09c7-40b5-8448-8ce030478156_Tree-PoseALL](https://user-images.githubusercontent.com/13784609/100925409-35da5680-34f7-11eb-842e-163e3470909f.jpg)


i put each label on the returned value of  **pred[i,:].asnumpy()** (x,y)

it seems the position of joints or other parts of body is different with the marked on heatmap

Do you have any idea ?

**Comment by dai-ichiro** [comment]
Try to run this code.
In my environment, it works fine.

```
from gluoncv import model_zoo, data, utils
from gluoncv.data.transforms.pose import detector_to_simple_pose, heatmap_to_coord

detector = model_zoo.get_model('yolo3_mobilenet1.0_coco', pretrained=True, root='./model')
pose_net = model_zoo.get_model('simple_pose_resnet18_v1b', pretrained=True, root='./model')
detector.reset_class(['person'], reuse_weights=['person'])

url = 'https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/segmentation/voc_examples/1.jpg'
filename = 'sample.jpg'
utils.download(url, filename)

x, img = data.transforms.presets.ssd.load_test(filename, short=512)
class_IDs, scores, bounding_boxs = detector(x)
pose_input, upscale_bbox = detector_to_simple_pose(img, class_IDs, scores, bounding_boxs)
predicted_heatmap = pose_net(pose_input)
pred_coords, confidence = heatmap_to_coord(predicted_heatmap, upscale_bbox)

import cv2
font = cv2.FONT_HERSHEY_SIMPLEX 
fontScale = 0.3
color = (0, 0, 255)
thickness = 1

keypoints = data.mscoco.keypoints.COCOKeyPoints.KEYPOINTS
for keypoint_id in range(len(keypoints)):
    pred = pred_coords[:,keypoint_id,:]
    for i in range(pred.shape[0]):
        if (confidence[i,keypoint_id,:] > 0.2) == 1:
            cv2.putText(img, keypoints[keypoint_id],
            (pred[i,0].asscalar(),pred[i,1].asscalar()),
            font,
            fontScale,
            color,
            thickness,
            cv2.LINE_AA)

img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
cv2.imwrite('result.png', img)

```

Hope this helps.

**Comment by mbs220** [comment]
thanks for sharing this code
i found the problem

i re-read the file using **imread**  (after all changes) and positions of points  has been changed by **plot_keypoints** method
i used the same return value of **data.transforms.presets.ssd.load_test(filename, short=512)** and works .

![RESULT_a577eed4-09c7-40b5-8448-8ce030478156_Tree-Pose1](https://user-images.githubusercontent.com/13784609/100970776-d73ec800-354a-11eb-8e34-b8b5e83bd8b9.jpg)

Now it is ok. i close the issue
Thanks Again
Regards
Mohammad
