### ISSUE TITLE
AttributeError: '_thread._local' object has no attribute 'value'

### ISSUE THREAD

**Issue by timonikkila** [dmlc/gluon-cv#156]
I have tried to use Gluoncv at grpc server side and Django server. In both cases I get the "AttributeError: '_thread._local' object has no attribute 'value'" error. Apparently has something to do with multi threading. For example this line gives the error:
net = model_zoo.get_model('ssd_512_resnet50_v1_voc', pretrained=True)

Example of stacktrace

Traceback (most recent call last):
  File "<path>/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "<path>/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "<path>/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "<path>/server/posts/views.py", line 28, in index
    net = model_zoo.get_model('ssd_512_resnet50_v1_voc', pretrained=True)
  File "<path>/venv/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", line 60, in get_model
    net = models[name](**kwargs)
  File "<path>/venv/lib/python3.6/site-packages/gluoncv/model_zoo/ssd/ssd.py", line 340, in ssd_512_resnet50_v1_voc
    pretrained_base=pretrained_base, **kwargs)
  File "<path>/venv/lib/python3.6/site-packages/gluoncv/model_zoo/ssd/ssd.py", line 236, in get_ssd
    pretrained=pretrained_base, classes=classes, **kwargs)
  File "<path>/venv/lib/python3.6/site-packages/gluoncv/model_zoo/ssd/ssd.py", line 92, in __init__
    super(SSD, self).__init__(**kwargs)
  File "<path>/venv/lib/python3.6/site-packages/mxnet/gluon/block.py", line 621, in __init__
    super(HybridBlock, self).__init__(prefix=prefix, params=params)
  File "<path>/venv/lib/python3.6/site-packages/mxnet/gluon/block.py", line 171, in __init__
    self._prefix, self._params = _BlockScope.create(prefix, params, self._alias())
  File "<path>/venv/lib/python3.6/site-packages/mxnet/gluon/block.py", line 53, in create
    prefix = _name.NameManager._current.value.get(None, hint) + '_'
AttributeError: '_thread._local' object has no attribute 'value'

**Comment by zhreshold** [comment]
I am not entirely sure what you are doing with server side, but there are some scope setting in gluon. Can you grab the model in main thread and pass the instance to thread workers?

**Comment by timonikkila** [comment]
Only thing I am doing on server side is to get image from request and then running basically this code:
```python
net = model_zoo.get_model('ssd_512_resnet50_v1_voc', pretrained=True)

to_tensor = transforms.Compose([transforms.ToTensor(), transforms.Normalize(0, 1)])
img_t = to_tensor(mx.nd.array(img))
img_t = img_t.expand_dims(axis=0)

class_IDs, scores, bounding_boxs = net(img_t)
```
Idea is to return boxes of persons. I was able to create `net` variable in main thread and pass it to subthread. It solved that problem.  Then creating `to_tensor` threw the same exception. Creating `to_tensor` in main thread did not help. It keeps throwing error when running it in subthread.

If I understood your answer right, then this is more feature than a bug, since gluon operates in a scope of particular thread. I will find some way to make my thing work. Thank you zhreshold for your answer!

**Comment by feevos** [comment]
I am getting exactly the same error message when I try using Gluon with ray distributed - see [this](https://discuss.mxnet.io/t/gluon-with-ray-distributed-problem/1235) thread for problem discription. I am not sure if this is a gluon problem or not. Even this trivial function: 
```Python
@ray.remote(num_gpus=4)
def f(x):
    loss = gluon.loss.L2Loss()
    return x
```
produces the error.

**Comment by zhreshold** [comment]
@piiswrong Is is related to scope overriding?

**Comment by feevos** [comment]
Dear all, @ThomasDelteil  gave me a solution [here](https://discuss.mxnet.io/t/gluon-with-ray-and-dask-distributed-problem/1235/2) (use ```prefix="something"```)

**Comment by timonikkila** [comment]
I read conversation behind the link @feevos posted. Based on that conversation I reinstalled gluoncv and cluon and "AttributeError: '_thread._local'" seemed to disappear. So this ticket can be closed. Thanks feevos!
