### ISSUE TITLE
ERROR: Could not build wheels for ConfigSpace which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by harleysteel** [dmlc/gluon-cv#1560]
Trying to install Gluoncv after getting mxnet-cu101 installed. Using conda and running python 3.7.9 as I had issues with mxnet installing on python >=3.8 due to errors numpy building. Currently struggling to get CongfigSpace to build
PS C:\Users\Harley> pip install --pre --upgrade gluoncv
Collecting gluoncv
  Using cached gluoncv-0.10.0b20201205-py2.py3-none-any.whl (997 kB)
Requirement already satisfied: Pillow in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (8.0.1)
Requirement already satisfied: requests in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (2.18.4)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting autocfg
  Using cached autocfg-0.0.6-py2.py3-none-any.whl (13 kB)
Collecting autogluon.core
  Using cached autogluon.core-0.0.15b20201205-py3-none-any.whl (241 kB)
Requirement already satisfied: requests in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (2.18.4)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from autogluon.core->gluoncv) (0.8.4)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting autograd>=1.3
  Using cached autograd-1.3-py3-none-any.whl
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Requirement already satisfied: future>=0.15.2 in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from autograd>=1.3->autogluon.core->gluoncv) (0.18.2)
Collecting boto3
  Using cached boto3-1.16.30-py2.py3-none-any.whl (129 kB)
Collecting botocore<1.20.0,>=1.19.30
  Using cached botocore-1.19.30-py2.py3-none-any.whl (7.0 MB)
Collecting ConfigSpace<=0.4.16
  Using cached ConfigSpace-0.4.16.tar.gz (964 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting cython
  Using cached Cython-3.0a6-cp37-cp37m-win_amd64.whl (1.8 MB)
Collecting dask>=2.6.0
  Using cached dask-2.30.0-py3-none-any.whl (848 kB)
Collecting decord
  Using cached decord-0.4.2-py2.py3-none-win_amd64.whl (25.5 MB)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting distributed>=2.6.0
  Using cached distributed-2.30.1-py3-none-any.whl (656 kB)
Requirement already satisfied: setuptools in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from distributed>=2.6.0->autogluon.core->gluoncv) (50.3.2.post20201201)
Collecting click>=6.6
  Using cached click-8.0.0a1-py3-none-any.whl (89 kB)
Collecting cloudpickle>=1.5.0
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting matplotlib
  Using cached matplotlib-3.3.3-cp37-cp37m-win_amd64.whl (8.5 MB)
Requirement already satisfied: Pillow in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (8.0.1)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp37-cp37m-win_amd64.whl (51 kB)
Collecting msgpack>=0.6.0
  Using cached msgpack-1.0.0-cp37-cp37m-win_amd64.whl (72 kB)
Collecting opencv-python
  Using cached opencv_python-4.4.0.46-cp37-cp37m-win_amd64.whl (33.5 MB)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting pandas
  Using cached pandas-1.1.4-cp37-cp37m-win_amd64.whl (8.7 MB)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting paramiko>=2.4
  Using cached paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
Collecting bcrypt>=3.1.3
  Using cached bcrypt-3.2.0-cp36-abi3-win_amd64.whl (28 kB)
Collecting cffi>=1.1
  Using cached cffi-1.14.4-cp37-cp37m-win_amd64.whl (178 kB)
Collecting cryptography>=2.5
  Using cached cryptography-3.2.1-cp37-cp37m-win_amd64.whl (1.5 MB)
Collecting portalocker
  Using cached portalocker-2.0.0-py2.py3-none-any.whl (11 kB)
Collecting psutil>=5.0
  Using cached psutil-5.7.3-cp37-cp37m-win_amd64.whl (243 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pynacl>=1.0.1
  Using cached PyNaCl-1.4.0-cp37-cp37m-win_amd64.whl (206 kB)
Collecting pyparsing
  Using cached pyparsing-3.0.0b1-py3-none-any.whl (83 kB)
Collecting pytest
  Using cached pytest-6.1.2-py3-none-any.whl (272 kB)
Collecting atomicwrites>=1.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting attrs>=17.4.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting importlib-metadata>=0.12
  Using cached importlib_metadata-3.1.1-py3-none-any.whl (9.6 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting packaging
  Using cached packaging-20.7-py2.py3-none-any.whl (35 kB)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.8.2
  Using cached py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.2
  Using cached pytz-2020.4-py2.py3-none-any.whl (509 kB)
Collecting pywin32!=226
  Using cached pywin32-300-cp37-cp37m-win_amd64.whl (9.2 MB)
Collecting pyyaml
  Using cached PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from requests->gluoncv) (2020.11.8)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from requests->gluoncv) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from requests->gluoncv) (3.0.4)
Collecting requests
  Using cached requests-2.25.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from requests->gluoncv) (2020.11.8)
Requirement already satisfied: idna<3,>=2.5 in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from requests->gluoncv) (2.6)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from requests->gluoncv) (3.0.4)
Collecting s3transfer<0.4.0,>=0.3.0
  Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
Collecting scikit-learn<0.24,>=0.22.0
  Using cached scikit_learn-0.23.2-cp37-cp37m-win_amd64.whl (6.8 MB)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting joblib>=0.11
  Using cached joblib-0.17.0-py3-none-any.whl (301 kB)
Collecting scikit-optimize
  Using cached scikit_optimize-0.8.1-py2.py3-none-any.whl (101 kB)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting pyaml>=16.9
  Using cached pyaml-20.4.0-py2.py3-none-any.whl (17 kB)
Collecting scipy
  Using cached scipy-1.4.1-cp37-cp37m-win_amd64.whl (30.9 MB)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting sortedcontainers!=2.0.0,!=2.0.1
  Using cached sortedcontainers-2.3.0-py2.py3-none-any.whl (29 kB)
Collecting tblib>=1.6.0
  Using cached tblib-1.7.0-py2.py3-none-any.whl (12 kB)
Collecting tensorboardx
  Using cached tensorboardX-2.1-py2.py3-none-any.whl (308 kB)
Requirement already satisfied: numpy in c:\users\harley\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Collecting protobuf>=3.8.0
  Using cached protobuf-3.14.0-cp37-cp37m-win_amd64.whl (798 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting toolz>=0.8.2
  Using cached toolz-0.11.1-py3-none-any.whl (55 kB)
Collecting tornado>=5.0.1
  Using cached tornado-6.1-cp37-cp37m-win_amd64.whl (422 kB)
Collecting tqdm
  Using cached tqdm-4.54.1-py2.py3-none-any.whl (69 kB)
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting yacs
  Using cached yacs-0.1.8-py3-none-any.whl (14 kB)
Collecting zict>=0.1.3
  Using cached zict-2.0.0-py3-none-any.whl (10 kB)
Collecting heapdict
  Using cached HeapDict-1.0.1-py3-none-any.whl (3.9 kB)
Collecting zipp>=0.5
  Using cached zipp-3.4.0-py3-none-any.whl (5.2 kB)
Building wheels for collected packages: ConfigSpace
  Building wheel for ConfigSpace (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\harley\anaconda3\envs\mxnet\python.exe' 'c:\users\harley\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Harley\AppData\Local\Temp\tmpsqtr491n'
       cwd: C:\Users\Harley\AppData\Local\Temp\pip-install-vffv65q9\configspace_41609cea166b4ba98c634993d483e39c
  Complete output (39 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\ConfigSpace
  copying ConfigSpace\exceptions.py -> build\lib.win-amd64-3.7\ConfigSpace
  copying ConfigSpace\__init__.py -> build\lib.win-amd64-3.7\ConfigSpace
  copying ConfigSpace\__version__.py -> build\lib.win-amd64-3.7\ConfigSpace
  creating build\lib.win-amd64-3.7\ConfigSpace\nx
  copying ConfigSpace\nx\exception.py -> build\lib.win-amd64-3.7\ConfigSpace\nx
  copying ConfigSpace\nx\release.py -> build\lib.win-amd64-3.7\ConfigSpace\nx
  copying ConfigSpace\nx\__init__.py -> build\lib.win-amd64-3.7\ConfigSpace\nx
  creating build\lib.win-amd64-3.7\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\irace.py -> build\lib.win-amd64-3.7\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\json.py -> build\lib.win-amd64-3.7\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\pcs.py -> build\lib.win-amd64-3.7\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\pcs_new.py -> build\lib.win-amd64-3.7\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\__init__.py -> build\lib.win-amd64-3.7\ConfigSpace\read_and_write
  creating build\lib.win-amd64-3.7\ConfigSpace\nx\algorithms
  copying ConfigSpace\nx\algorithms\cycles.py -> build\lib.win-amd64-3.7\ConfigSpace\nx\algorithms
  copying ConfigSpace\nx\algorithms\dag.py -> build\lib.win-amd64-3.7\ConfigSpace\nx\algorithms
  copying ConfigSpace\nx\algorithms\__init__.py -> build\lib.win-amd64-3.7\ConfigSpace\nx\algorithms
  creating build\lib.win-amd64-3.7\ConfigSpace\nx\classes
  copying ConfigSpace\nx\classes\digraph.py -> build\lib.win-amd64-3.7\ConfigSpace\nx\classes
  copying ConfigSpace\nx\classes\graph.py -> build\lib.win-amd64-3.7\ConfigSpace\nx\classes
  copying ConfigSpace\nx\classes\__init__.py -> build\lib.win-amd64-3.7\ConfigSpace\nx\classes
  creating build\lib.win-amd64-3.7\ConfigSpace\nx\algorithms\components
  copying ConfigSpace\nx\algorithms\components\strongly_connected.py -> build\lib.win-amd64-3.7\ConfigSpace\nx\algorithms\components
  copying ConfigSpace\nx\algorithms\components\__init__.py -> build\lib.win-amd64-3.7\ConfigSpace\nx\algorithms\components
  running build_ext
  skipping 'ConfigSpace\hyperparameters.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\forbidden.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\conditions.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\c_util.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\util.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\configuration_space.c' Cython extension (up-to-date)
  building 'ConfigSpace.hyperparameters' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for ConfigSpace
Failed to build ConfigSpace
ERROR: Could not build wheels for ConfigSpace which use PEP 517 and cannot be installed directly

**Comment by harleysteel** [comment]
Ran with --no-use-pep517 and solved the problem

**Comment by olguin** [comment]
If you are getting the above error in a MacOs, and part of the error log says "[macOS Catalina 10.15.7] Failed to install - Unsupported architecture" or many errors like these:
" unknown type name '__int32_t'; did you mean '__int128_t'?"  I could only fix it by upgrading to Python 3.8.6 (previously I had version 3.8.2)

**Comment by themmyloluwaa** [comment]
Hi @harleysteel I am getting this upon setting up a CI workflow on github for an ML model that uses auto-sklearn. Can you tell me where you included the  _--no-use-pep517_ command ? 

I am passing it through this command but I am not sure it's correct. 

_pip install -U -r requirements.txt  --no-use-pep517_

Thank you

**Comment by abhinand5** [comment]
I maybe a little late but running `sudo apt-get install python3-dev` before installing requirements solved this problem

**Comment by 1098994933** [comment]
> I maybe a little late but running `sudo apt-get install python3-dev` before installing requirements solved this problem
Thanks for your solution
