### ISSUE TITLE
Replacing the backbone of yolov3_mobilenet1.0_voc with mobilenetv3_large results in failure to train

### ISSUE THREAD

**Issue by Zhangxinnian** [dmlc/gluon-cv#1569]
When I imitate yolov3_mobilenet1.0_voc and implement yolov3_mobilenetv3_large_voc, after running train_yolov3.py file, "MXNetError: Check failed: ishape[axis] >= from_shape[axis] (128 vs. 160): Slice axis 2 with size 160exceeds limit of input with size 128".
I can train after modifying data_shape to 224 and turning off random-shape. The loss is low during training, but the map during training is always 0.
Please help me to solve this problem.
This is my training parameters and the modified yolo3_mobilenetv3_large_voc code
`--network  mobilenet_v3_large  --dataset  voc  --log-interval  100  --lr-decay-epoch  100,200  --epochs  280  --syncbn  --warmup-epochs  4  --batch-size  8  --data-shape  320  --no-random-shape  --dataset  voc  --gpus  0  -j  4  --lr  0.000125
`
`def yolo3_mobilenet_v3_large_voc(pretrained_base=True, pretrained=False,
                           norm_layer=BatchNorm, norm_kwargs=None, **kwargs):
    
    from ...data import VOCDetection

    pretrained_base = False if pretrained else pretrained_base
    base_net = get_mobilenet(
        multiplier=1,
        pretrained=pretrained_base,
        norm_layer=norm_layer, norm_kwargs=norm_kwargs,
        **kwargs)
    stages = [base_net.features[:9],
              base_net.features[9:15],
              base_net.features[15:18]]

    anchors = [[10, 13, 16, 30, 33, 23],
               [30, 61, 62, 45, 59, 119],
               [116, 90, 156, 198, 373, 326]]
    strides = [8, 16, 32]
    classes = VOCDetection.CLASSES
    return get_yolov3(
        'mobilenet_v3_large', stages, [512, 256, 128], anchors, strides, classes, 'voc',
        pretrained=pretrained, norm_layer=norm_layer, norm_kwargs=norm_kwargs, **kwargs)`

**Comment by Aktcob** [comment]
https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/yolo/yolo3.py#L390

maybe this line causes the error.
