### ISSUE TITLE
AVA pretrained models

### ISSUE THREAD

**Issue by nikky4D** [dmlc/gluon-cv#1588]
Would you have any models pretrained on the AVA, AVA-Kinetics, or ActivityNet datasets?

**Comment by bryanyzhu** [comment]
Right now, we don't have these models. But models pretrained on AVA and AVA-Kinetics will be provided in the next release (before the end of February).

**Comment by nikky4D** [comment]
Thank you very much.  I look forward to it. 

As an aside, could you point me to the finetuning procedure for finetuning a Kinetics model on AVA?

**Comment by bryanyzhu** [comment]
We have a simple tutorial on how to finetune models on other datasets (PyTorch tutorial is at https://cv.gluon.ai/build/examples_torch_action_recognition/finetune_custom.html, and MXNet tutorial is at https://cv.gluon.ai/build/examples_action_recognition/finetune_custom.html). Basically, once you prepare the training files in the right format, you are good to go. I understand that the tutorial may be short, so please let me know if you have any usage questions. Thank you.

**Comment by nikky4D** [comment]
Thanks. I'll check it out.

**Comment by alexzeng1206** [comment]
Are the models pretrained on AVA available now? Thanks
