### ISSUE TITLE
Difference between Resnet models created by gluoncv and gluon

### ISSUE THREAD

**Issue by anotinelg** [dmlc/gluon-cv#1589]
What is the difference if i use: 
 ``` 
from gluoncv.model_zoo import get_model
```
from 
```
from mxnet.gluon.model_zoo.vision import get_model
```

I understand that for cv tasks, gluoncv seems more accurate. Is there any optimization between the two models created? are they compatible?

**Comment by bryanyzhu** [comment]
I don't think there is any optimization between the two models created, they should be compatible. 

I just checked the model stores from GluonCV (https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/model_store.py) and the model stores from MXNet (https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/model_zoo/model_store.py). If you look at the shasum code, most of them are the same, which means they are using the same pretrained weights. Only Inception and MobileNet models have different shasum codes, but I think they are just different checkpoints, it doesn't effect compatibility. Let me know if you find them incompatible later.

**Comment by bryanyzhu** [comment]
Close due to inactivity, feel free to reopen the issue.
