### ISSUE TITLE
[Website] Link to unavailable MXNet web page.

### ISSUE THREAD

**Issue by xidulu** [dmlc/gluon-cv#1597]
https://cv.gluon.ai/api/data.datasets.html

![Screen Shot 2021-01-23 at 4 25 55 PM](https://user-images.githubusercontent.com/26022201/105573328-adaa5c00-5d97-11eb-8bd0-adff25e0c719.png)

The link for `GluonCV Datasets` is https://mxnet.incubator.apache.org/api/python/gluon/data.html#vision-datasets
which is not available

**Comment by yinweisu** [comment]
Close the issue as it has been fixed by https://github.com/dmlc/gluon-cv/pull/1638
