### ISSUE TITLE
Is there any train_rcnn.py can provide?

### ISSUE THREAD

**Issue by yunfanLu** [dmlc/gluon-cv#160]
Hello, I has ran the 
`https://github.com/dmlc/gluon-cv/blob/rcnn/docs/tutorials/detection/demo_faster_rcnn.py`
to inference the faster rcnn.

but is there any train_rcnn.py like `https://gluon-cv.mxnet.io/_downloads/train_ssd.py` ？

Do Gluon-cv have the official reference? or I should write by myself?

**Comment by zhreshold** [comment]
Please hold on for a few days, we are preparing for releasing related stuffs. 😸

**Comment by yunfanLu** [comment]
Thank you !
