### ISSUE TITLE
Sagemaker deeplab semantic segmentation endpoint is taking too long to run inference

### ISSUE THREAD

**Issue by jenitaex** [dmlc/gluon-cv#1604]
We have a Sagemaker endpoint running inference on GluonCV DeepLab Semantic Segmentation Marketplace model. 
The endpoint is taking more than 30s to process images of less than 1000 px. dimensions. and this is the case with almost all kinds of images that we run. The instance type is ml.m4.xlarge.

What are the ways we can optimise for the processing time here?

**Comment by austinmw** [comment]
You could select a GPU instance or add an elastic accelerator

**Comment by jenitaex** [comment]
@bryanyzhu We are not getting g4dn.xlarge option with this model. We are only getting `ml.m*` and `ml.c*` series of instance type options to choose from.

**Comment by bryanyzhu** [comment]
In this case, either reducing the input image resolution, or change to a fast segmentation network. For example, GluonCV has FastSCNN implementation, it is 10x times faster than deeplab models and have competitive performance.

**Comment by bryanyzhu** [comment]
Close the issue due to inactivity, feel free to reopen if anything comes up.
