### ISSUE TITLE
Grad-CAM for Gluon-CV SlowFast

### ISSUE THREAD

**Issue by Fritskee** [dmlc/gluon-cv#1608]
First of all, thanks for making things so easy with Gluon-CV. I've trained multiple SlowFast models on my personal dataset with Gluon-CV.

However, the FAIR (Facebook AI Research) implementation of SlowFast provides very useful features like Grad-CAM visualization, layer-activation visualization, tensorboard, ... and I cannot seem to find anything of this in the Gluon-CV documentation. Is there a possibility to do this, or is it possible to take the Gluon-CV model and use it with these features of the FAIR SlowFast implementation? (Because I think the Gluon-CV hybrid layers might clash with the original SlowFast implementation? please correct me if I'm wrong). 

If Gluon-CV does have these options, please point me in the right direction. I cannot find them.

**Comment by bryanyzhu** [comment]
We don't have these methods for visualization at this moment, and contributions are welcome. If more people +1 here, I can find time to do it at a later time.
