### ISSUE TITLE
torch.view() should be changed to torch.reshape()

### ISSUE THREAD

**Issue by ReGhane** [dmlc/gluon-cv#1618]
Greetings, thank you for your awesome work!

When I had to use gluoncv.torch.utils.task_utils for training my model, I had to torch.permute() my video to make the model work (it was not from the same dataset for that specific model) therefore, breaking its contiguity and this raised an error:

```
/gluoncv/torch/utils/utils.py in accuracy(output, target, took):
     90     res = []
     91     for k in topk:
---> 92         correct_k = correct[:k].view(-1).float().sum(0)
     93         res.append(correct_k.mul_(100.0 / batch_size))
     94     return res

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

for which changing view() to reshape() solved the problem.

Thanks in advance!

**Comment by bryanyzhu** [comment]
Thank you for pointing this out. I already fixed it in #1654. Will close the issue.
