### ISSUE TITLE
Release 0.10.0 breaks backward compatibility with SSD.

### ISSUE THREAD

**Issue by ifeherva** [dmlc/gluon-cv#1634]
I have an SSD model trained with an earlier version of gluoncv. 0.10.0 can load the saved parameters but the forward pass fails due to the new parameters introduced in this release.

**Comment by zhreshold** [comment]
Can you be more specific? I guess it's possibly related to the new operators in mxnet 1.6 or 1.7 in the bounding box encoder layer.

**Comment by ifeherva** [comment]
Calling model_zoo.ssd.get_ssd(..) will return the smot SSD which requires additional inputs in hybrid_forward(..) unlike the 'old' one.

**Comment by bryanyzhu** [comment]
Smot folder indeed has another `ssd.py` to match with the requirement of tracking, but it's supposed not to conflict with the original `ssd.py`. Let me double check.

**Comment by ifeherva** [comment]
Any update on this?
