### ISSUE TITLE
size mismatch for last layer: tpn_resnet50_f32s2_custom 

### ISSUE THREAD

**Issue by Edwardf0t1** [dmlc/gluon-cv#1635]
Followed tutorial https://cv.gluon.ai/build/examples_torch_action_recognition/finetune_custom.html to finetune tpn_resnet50_f32s2_custom  with my own data. Changed NUM_CLASSES from 400 to 18 in config yaml file, still get error when use train_ddp_pytorch.py to train (error appears when running this line: model = get_model(cfg)):

size mismatch for TPN_neck.aux_head.fc.weight: copying a param with shape torch.Size([400, 2048]) from checkpoint, the shape in current model is torch.Size([18, 2048])

Any hints? Thanks.

**Comment by am-shubh** [comment]
Hi @Edwardf0t1 were you able to resolve the issue? If yes, please share your approach. Thanks.
