### ISSUE TITLE
Pretrained zoo models for audio in GluonCV

### ISSUE THREAD

**Issue by douglas125** [dmlc/gluon-cv#1646]
Are there tutorials or models for audio processing in GluonCV or is it out of scope? Would it be useful? In the end, videos can have audio as well.

I am not aware of a repository for keyword spotting or ASR in gluon, for example.

Any ideas or plans to add it?

**Comment by zhreshold** [comment]
multimodal functionality may be supported in other toolkits, such as autogluon and multi-modal gluon package, both are TBD but we will not include them in gluoncv.
