### ISSUE TITLE
VOC07MApMetric will raise error when rec or prec is None

### ISSUE THREAD

**Issue by WalterMa** [dmlc/gluon-cv#165]
In VOC07MApMetric._average_precision(), codes don't consider the condition that  rec is None or prec is None. So that it'll cause error when come to this line.
https://github.com/dmlc/gluon-cv/blob/089b9c55e85cec2e23243b0e4153c7857618b532/gluoncv/utils/metrics/voc_detection.py#L278

How about add these following lines to the function:
```python
if rec is None or prec is None:
     return np.nan
```

**Comment by zhreshold** [comment]
Do you want to contribute a PR fixing this? We'd be very appreciated.

**Comment by WalterMa** [comment]
It is my pleasure！
I post a PR right now.
