### ISSUE TITLE
New requirements from "auto"

### ISSUE THREAD

**Issue by leotac** [dmlc/gluon-cv#1652]
It looks like, starting from 0.9, gluon-cv added a bunch of additional requirements that really increased a lot the amount and complexity of dependencies that are pulled.
It makes it really difficult to use a gluoncv model in any project with other non-trivial dependencies.
In one of my projects pip completely fails solving the dependencies, it starts looking at "multiple versions" of scipy and it just hangs after a while.

This is the dependency tree of 0.8

> gluoncv==0.8.0
>   - matplotlib [required: Any, installed: 3.4.1]
>     - cycler [required: >=0.10, installed: 0.10.0]
>       - six [required: Any, installed: 1.15.0]
>     - kiwisolver [required: >=1.0.1, installed: 1.3.1]
>     - numpy [required: >=1.16, installed: 1.17.4]
>     - pillow [required: >=6.2.0, installed: 8.2.0]
>     - pyparsing [required: >=2.2.1, installed: 2.4.7]
>     - python-dateutil [required: >=2.7, installed: 2.8.1]
>       - six [required: >=1.5, installed: 1.15.0]
>   - numpy [required: Any, installed: 1.17.4]
>   - Pillow [required: Any, installed: 8.2.0]
>   - portalocker [required: Any, installed: 2.3.0]
>   - requests [required: Any, installed: 2.25.1]
>     - certifi [required: >=2017.4.17, installed: 2020.12.5]
>     - chardet [required: >=3.0.2,<5, installed: 4.0.0]
>     - idna [required: >=2.5,<3, installed: 2.10]
>     - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.4]
>   - scipy [required: Any, installed: 1.5.2]
>     - numpy [required: >=1.14.5, installed: 1.17.4]
>   - tqdm [required: Any, installed: 4.60.0]

and this is for gluoncv 0.10.1

> gluoncv==0.10.1.post0
>   - autocfg [required: Any, installed: 0.0.8]
>     - pyyaml [required: Any, installed: 5.3.1]
>   - autogluon.core [required: Any, installed: 0.1.0]
>     - autograd [required: >=1.3, installed: 1.3]
>       - future [required: >=0.15.2, installed: 0.18.2]
>       - numpy [required: >=1.12, installed: 1.19.5]
>     - boto3 [required: Any, installed: 1.16.50]
>       - botocore [required: >=1.19.50,<1.20.0, installed: 1.19.52]
>         - jmespath [required: >=0.7.1,<1.0.0, installed: 0.10.0]
>         - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
>           - six [required: >=1.5, installed: 1.15.0]
>         - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.4]
>       - jmespath [required: >=0.7.1,<1.0.0, installed: 0.10.0]
>       - s3transfer [required: >=0.3.0,<0.4.0, installed: 0.3.7]
>         - botocore [required: >=1.12.36,<2.0a.0, installed: 1.19.52]
>           - jmespath [required: >=0.7.1,<1.0.0, installed: 0.10.0]
>           - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
>             - six [required: >=1.5, installed: 1.15.0]
>           - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.4]
>     - ConfigSpace [required: ==0.4.18, installed: 0.4.18]
>       - cython [required: Any, installed: 0.29.23]
>       - numpy [required: Any, installed: 1.19.5]
>       - pyparsing [required: Any, installed: 2.4.7]
>     - cython [required: Any, installed: 0.29.23]
>     - dask [required: >=2.6.0, installed: 2021.4.1]
>       - cloudpickle [required: >=1.1.1, installed: 1.6.0]
>       - fsspec [required: >=0.6.0, installed: 2021.4.0]
>       - partd [required: >=0.3.10, installed: 1.2.0]
>         - locket [required: Any, installed: 0.2.1]
>         - toolz [required: Any, installed: 0.11.1]
>       - pyyaml [required: Any, installed: 5.3.1]
>       - toolz [required: >=0.8.2, installed: 0.11.1]
>     - dill [required: ==0.3.3, installed: 0.3.3]
>     - distributed [required: >=2.6.0, installed: 2021.4.1]
>       - click [required: >=6.6, installed: 7.1.2]
>       - cloudpickle [required: >=1.5.0, installed: 1.6.0]
>       - dask [required: >=2021.03.0, installed: 2021.4.1]
>         - cloudpickle [required: >=1.1.1, installed: 1.6.0]
>         - fsspec [required: >=0.6.0, installed: 2021.4.0]
>         - partd [required: >=0.3.10, installed: 1.2.0]
>           - locket [required: Any, installed: 0.2.1]
>           - toolz [required: Any, installed: 0.11.1]
>         - pyyaml [required: Any, installed: 5.3.1]
>         - toolz [required: >=0.8.2, installed: 0.11.1]
>       - msgpack [required: >=0.6.0, installed: 1.0.2]
>       - psutil [required: >=5.0, installed: 5.8.0]
>       - pyyaml [required: Any, installed: 5.3.1]
>       - setuptools [required: Any, installed: 52.0.0.post20210125]
>       - sortedcontainers [required: !=2.0.1,!=2.0.0, installed: 2.3.0]
>       - tblib [required: >=1.6.0, installed: 1.7.0]
>       - toolz [required: >=0.8.2, installed: 0.11.1]
>       - tornado [required: >=5, installed: 6.1]
>       - zict [required: >=0.1.3, installed: 2.0.0]
>         - heapdict [required: Any, installed: 1.0.1]
>     - graphviz [required: >=0.8.1,<0.9.0, installed: 0.8.4]
>     - matplotlib [required: Any, installed: 3.4.1]
>       - cycler [required: >=0.10, installed: 0.10.0]
>         - six [required: Any, installed: 1.15.0]
>       - kiwisolver [required: >=1.0.1, installed: 1.3.1]
>       - numpy [required: >=1.16, installed: 1.19.5]
>       - pillow [required: >=6.2.0, installed: 8.2.0]
>       - pyparsing [required: >=2.2.1, installed: 2.4.7]
>       - python-dateutil [required: >=2.7, installed: 2.8.1]
>         - six [required: >=1.5, installed: 1.15.0]
>     - numpy [required: ==1.19.5, installed: 1.19.5]
>     - pandas [required: >=1.0.0,<2.0, installed: 1.2.4]
>       - numpy [required: >=1.16.5, installed: 1.19.5]
>       - python-dateutil [required: >=2.7.3, installed: 2.8.1]
>         - six [required: >=1.5, installed: 1.15.0]
>       - pytz [required: >=2017.3, installed: 2021.1]
>     - paramiko [required: >=2.4, installed: 2.7.2]
>       - bcrypt [required: >=3.1.3, installed: 3.2.0]
>         - cffi [required: >=1.1, installed: 1.14.5]
>           - pycparser [required: Any, installed: 2.20]
>         - six [required: >=1.4.1, installed: 1.15.0]
>       - cryptography [required: >=2.5, installed: 3.4.7]
>         - cffi [required: >=1.12, installed: 1.14.5]
>           - pycparser [required: Any, installed: 2.20]
>       - pynacl [required: >=1.0.1, installed: 1.4.0]
>         - cffi [required: >=1.4.1, installed: 1.14.5]
>           - pycparser [required: Any, installed: 2.20]
>         - six [required: Any, installed: 1.15.0]
>     - requests [required: Any, installed: 2.25.1]
>       - certifi [required: >=2017.4.17, installed: 2020.12.5]
>       - chardet [required: >=3.0.2,<5, installed: 4.0.0]
>       - idna [required: >=2.5,<3, installed: 2.10]
>       - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.4]
>     - scikit-learn [required: >=0.22.0,<0.25, installed: 0.23.2]
>       - joblib [required: >=0.11, installed: 1.0.0]
>       - numpy [required: >=1.13.3, installed: 1.19.5]
>       - scipy [required: >=0.19.1, installed: 1.5.4]
>         - numpy [required: >=1.14.5, installed: 1.19.5]
>       - threadpoolctl [required: >=2.0.0, installed: 2.1.0]
>     - scipy [required: ==1.5.4, installed: 1.5.4]
>       - numpy [required: >=1.14.5, installed: 1.19.5]
>     - tornado [required: >=5.0.1, installed: 6.1]
>     - tqdm [required: >=4.38.0, installed: 4.60.0]
>   - decord [required: Any, installed: 0.4.1]
>     - numpy [required: >=1.14.0, installed: 1.19.5]
>   - matplotlib [required: Any, installed: 3.4.1]
>     - cycler [required: >=0.10, installed: 0.10.0]
>       - six [required: Any, installed: 1.15.0]
>     - kiwisolver [required: >=1.0.1, installed: 1.3.1]
>     - numpy [required: >=1.16, installed: 1.19.5]
>     - pillow [required: >=6.2.0, installed: 8.2.0]
>     - pyparsing [required: >=2.2.1, installed: 2.4.7]
>     - python-dateutil [required: >=2.7, installed: 2.8.1]
>       - six [required: >=1.5, installed: 1.15.0]
>   - numpy [required: Any, installed: 1.19.5]
>   - opencv-python [required: Any, installed: 4.5.1.48]
>     - numpy [required: >=1.14.5, installed: 1.19.5]
>   - pandas [required: Any, installed: 1.2.4]
>     - numpy [required: >=1.16.5, installed: 1.19.5]
>     - python-dateutil [required: >=2.7.3, installed: 2.8.1]
>       - six [required: >=1.5, installed: 1.15.0]
>     - pytz [required: >=2017.3, installed: 2021.1]
>   - Pillow [required: Any, installed: 8.2.0]
>   - portalocker [required: Any, installed: 2.3.0]
>   - pyyaml [required: Any, installed: 5.3.1]
>   - requests [required: Any, installed: 2.25.1]
>     - certifi [required: >=2017.4.17, installed: 2020.12.5]
>     - chardet [required: >=3.0.2,<5, installed: 4.0.0]
>     - idna [required: >=2.5,<3, installed: 2.10]
>     - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.4]
>   - scipy [required: Any, installed: 1.5.4]
>     - numpy [required: >=1.14.5, installed: 1.19.5]
>   - tensorboardx [required: Any, installed: 2.2]
>     - numpy [required: Any, installed: 1.19.5]
>     - protobuf [required: >=3.8.0, installed: 3.15.8]
>       - six [required: >=1.9, installed: 1.15.0]
>   - tqdm [required: Any, installed: 4.60.0]
>   - yacs [required: Any, installed: 0.1.8]
>     - PyYAML [required: Any, installed: 5.3.1]

It's really a ton of dependencies, often multiple ones, and quite nasty ones that might be easily in conflict with other requirements: e.g., pandas >= 1, numpy pinned to a specific version, scipy pinned to a specific version, ConfigSpace pinned to a specific version.

Mainly the issue seems to be in the dependencies inherited from `autogluon.core`.
Would it be possible to make the installation of the "auto" component (or at least its dependencies) optional?

**Comment by zhreshold** [comment]
Yes, I am planning to release a minor version moving unrelated packages to optional dependencies
