### ISSUE TITLE
Make tutorial on how to train your own actions?

### ISSUE THREAD

**Issue by RonyR21** [dmlc/gluon-cv#1653]
is it possible to have a tutorial on how we can train the model to detect what exercise is being done based on actions that we do and add it to the data?
thank you.

**Comment by bryanyzhu** [comment]
Can you be more specific to your question? If it is finetuning, we have a pytorch tutorial on [finetuning](https://cv.gluon.ai/build/examples_torch_action_recognition/finetune_custom.html) and mxnet tutorial on [finetuning](https://cv.gluon.ai/build/examples_action_recognition/finetune_custom.html).

**Comment by RonyR21** [comment]
thank you for your reply, 
no I mean to have a tutorial on how to train on exercises/actions that you want.
ones that weren't available in the dataset when it was trained. like let's say handstand, and many other types of exercises.

**Comment by bryanyzhu** [comment]
You mean, you want to detect an exercise that is composed of multiple actions? The exercise is a new class, but the multiple actions are existing classes? I don't have much experience in this problem, maybe you can try to predict these basic atom actions first, then use graph neural network or some other temporal modeling technique to model the exercise.

**Comment by RonyR21** [comment]
it is one action: squat, or pushups or mountain climbers, or.... just like walking or sitting or hitting a baseball.
so it detects one exercise, the one being performed.
in the end, when you have the webcam on, and let's say you perform a squat, it will know that you did a squat.

**Comment by RonyR21** [comment]
is it possible to contact you by email or some telecommunication app please? it would speed everything and avoid misunderstanding
