### ISSUE TITLE
[ERROR] INT8 Inference in eval_yolo.py 

### ISSUE THREAD

**Issue by YasinFu** [dmlc/gluon-cv#1676]
use argument --gpu '0' during run eval_yolo.py ,get this error 
mxnet.base.MXNetError: [12:36:52] src/executor/attach_op_execs_pass.cc:318: Check failed: fcompute != nullptr: One of FStatefulCompute and FStatefulComputeEx must be registered for stateful operator _sg_mkldnn_conv

MXNET_mkl 1.6.0    CUDA9.2 
 or mxnet int8 inference not support gpu now?
thanks for your help

**Comment by TristonC** [comment]
@Kh4L Please help take a look.

**Comment by Kh4L** [comment]
@TristonC I don't think I can really help here because this is not TensorRT INT8.

The feature was added here https://github.com/dmlc/gluon-cv/commit/ce4384f44249d4910b421aa3ed0a5f1b38ca8212

@xinyu-intel and @wuxun-zhang to help.

**Comment by wuxun-zhang** [comment]
@YasinFu What exact command line you use to run this script?

**Comment by wuxun-zhang** [comment]
If you want to try on gpu device, perhaps you can try to install **mxnet_cu(version)mkl** or **mxnet_cu(version)** wheels.

**Comment by YasinFu** [comment]
> @YasinFu What exact command line you use to run this script?

python eval_yolo.py --gpus='0' --dataset=voc --batch-size=1 --classes_list ./class.txt --deploy --model-prefix=./model/yolo3_darknet53_voc-quantized-naive  --dataset=voc --batch-size=1

I replace part of  code with my code like this,my yolov3 params trained by train_yolo3.py （reset class）:

    if not args.deploy:
        # if args.pretrained.lower() in ['true', '1', 'yes', 't']:
            # net = gcv.model_zoo.get_model(net_name, pretrained=True)
        # else:
        net = gcv.model_zoo.get_model(net_name, pretrained=True)
        classes = [ 'truck', 'bus' , 'suv']
        net.reset_class(classes)
        net.collect_params().load('yolov3_0000_0.9000.params')
        #net = mx.gluon.SymbolBlock.imports('det.json',['data'], 'det.params')
        #net.set_nms(nms_thresh=0.45, nms_topk=400)
        net.hybridize()
        #net.save_parameters('{:s}_{:04d}_{:.4f}.params'.format('yolov3', 0, 0.9))
    else:
        net_name = 'deploy'
        net = mx.gluon.SymbolBlock.imports('{}-symbol.json'.format(args.model_prefix),
              ['data'], '{}-0000.params'.format(args.model_prefix))
        net.collect_params().reset_ctx(ctx)
        net.hybridize(static_alloc=True, static_shape=True)

**Comment by YasinFu** [comment]
> If you want to try on gpu device, perhaps you can try to install **mxnet_cu(version)mkl** or **mxnet_cu(version)** wheels.

I use mxnet-cu92mkl   1.6.0.post0，Does it support GPU?

**Comment by wuxun-zhang** [comment]
> > If you want to try on gpu device, perhaps you can try to install **mxnet_cu(version)mkl** or **mxnet_cu(version)** wheels.
> 
> I use mxnet-cu92mkl 1.6.0.post0，Does it support GPU?

Yes, I think it supports.

May I know how the file `./model/yolo3_darknet53_voc-quantized-naive` is generated? If it's generated by running on CPU, I suppose it will not be supported on GPU device.

**Comment by YasinFu** [comment]
@wuxun-zhang in eval_yolo.py : 

    if args.calibration and not args.quantized:
        exclude_layers = []
        exclude_operators = ['Concat']
        if ctx != [mx.cpu()] > 0:
            raise ValueError('currently only supports CPU with MKL-DNN backend')

It doesn't seem to support gpu during calibration

**Comment by wuxun-zhang** [comment]
> @wuxun-zhang in eval_yolo.py :
> 
> ```
> if args.calibration and not args.quantized:
>     exclude_layers = []
>     exclude_operators = ['Concat']
>     if ctx != [mx.cpu()] > 0:
>         raise ValueError('currently only supports CPU with MKL-DNN backend')
> ```
> 
> It doesn't seem to support gpu during calibration

Yes, only support calibration for CPU. This is the quantization pass for CPU. If you want to try int8 models on GPU, you may need refer to other approaches. @Kh4L Any idea?

**Comment by Kh4L** [comment]
A way to get INT8 for inference would be to use MXNet-TensorRT in with its INT8 mode.
But the INT8 mode is experimental, as all the features were not implemented yet.

However, you can try to speed up the inference with MXNet-TensorRT FP16, by adding a one-liner, as described here:

https://mxnet.apache.org/versions/1.8.0/api/python/docs/tutorials/performance/backend/tensorrt/tensorrt.html#MXNet-with-TensorRT-Integration-Performance


I will update this issue once the INT8 precision is fully available for the MXNet-TensorRT backend.
