### ISSUE TITLE
Image Segmentation: gluoncv.model_zoo.resnet50_v1b(pretrained=True) not available

### ISSUE THREAD

**Issue by ThomasDelteil** [dmlc/gluon-cv#168]
pretrained_net = gluoncv.model_zoo.resnet50_v1b(pretrained=True)

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-4bcb8b012a53> in <module>()
----> 1 pretrained_net = gluoncv.model_zoo.resnet50_v1b(pretrained=True)

AttributeError: module 'gluoncv.model_zoo' has no attribute 'resnet50_v1b'
```

Does the tutorial needs to be updated?

**Comment by hetong007** [comment]
Please wait for (or try) this PR: https://github.com/dmlc/gluon-cv/pull/161

**Comment by zhanghang1989** [comment]
I guess your gluoncv version is far behind the master branch. Please install from source and try again.

**Comment by ThomasDelteil** [comment]
@hetong007 ok thanks
@zhanghang1989 I had this error with latest gluoncv and gluoncv --pre
