### ISSUE TITLE
NameError: name '__version__' is not defined

### ISSUE THREAD

**Issue by ZiyanZhu1994** [dmlc/gluon-cv#1680]
I was running another GitHub repo which uses gluon-cv for preparing the dataset. The following error occurred:
```
  File "ingest_mot.py", line 196, in <module>
    dataset = main(args, mot17=mot17)
  File "ingest_mot.py", line 166, in main
    out_dataset.dump()
  File "/home/ziyan/anaconda3/envs/SiamMOT/lib/python3.8/site-packages/gluoncv/torch/data/gluoncv_motion_dataset/dataset.py", line 973, in dump
    save_json(self._to_dict(), filename, indent=indent, **kwargs)
  File "/home/ziyan/anaconda3/envs/SiamMOT/lib/python3.8/site-packages/gluoncv/torch/data/gluoncv_motion_dataset/dataset.py", line 1071, in _to_dict
    self._metadata[FieldNames.DATASET_VERSION] = self.version
  File "/home/ziyan/anaconda3/envs/SiamMOT/lib/python3.8/site-packages/gluoncv/torch/data/gluoncv_motion_dataset/dataset.py", line 879, in version
    return __version__
NameError: name '__version__' is not defined
```

**Comment by austinmw** [comment]
Same error came up for me when running siam-mot MOT17 ingestion

**Comment by lihanlin99** [comment]
@ZiyanZhu1994  @austinmw 
I have met the same problem. How do you solve it, please?

**Comment by CarsonLoong** [comment]
I also meet the problem, when I ingest MOT17 dataset in siam-mot.
The link is attached here: https://github.com/amazon-research/siam-mot

**Comment by CarsonLoong** [comment]
I modify the line166 in https://github.com/amazon-research/siam-mot/blob/main/siammot/data/ingestion/ingest_mot.py, and it works.
>     # out_dataset.dump()
    out_dataset._metadata[FieldNames.KEY_HASH] = FieldNames.get_key_hash()
    dump_dict = dict()
    dump_dict[FieldNames.DATASET_METADATA] = out_dataset._metadata
    all_samples_dict = {}
    for sample_id, sample in out_dataset._samples.items():
        sample_dict = sample.to_dict(lazy_load_format=True)
        if sample._lazy_loaded:
            sample._dump_for_lazy_load()
        all_samples_dict[sample_id] = sample_dict
    dump_dict[FieldNames.SAMPLE_DICT] = all_samples_dict
    save_json(dump_dict, out_filename)
