### ISSUE TITLE
action recognition implementation in pytorch

### ISSUE THREAD

**Issue by AndyDrill** [dmlc/gluon-cv#1682]
Hello everyone.
I was trying to train the action recognition models with kinectics dataset.
But I have following issues.

`
Traceback (most recent call last):    
  File "xxxxxx", line 113, in <module>
    spawn_workers(main_worker, cfg)   
  File "xxxxxx", line 27, in spawn_workers
    assert cfg.DDP_CONFIG.WORLD_RANK != -1
AssertionError
`

My environment is:

- Torch version:  1.8.0+cu111
- Configuration :  slowfast_8x8_resnet50_kinetics400.yaml
- GPU mode: Single GPU
- Dataset: kinectis400

Any hints would be helpful. Thank you

**Comment by ooguz166** [comment]
Instead of spawn_workers directly use main_worker with the cfg file

**Comment by AndyDrill** [comment]
Hi @ooguz166 
Thank you so much.
I will do

**Comment by ooguz166** [comment]
If anyone needed or interested, I wrote/modified a  gluocv-torch based finetuning script that works  on single gpu in  non distributed manner:

https://github.com/ooguz166/Finetune-Action-Recognition-with-GluonCV-Torch
