### ISSUE TITLE
How to extract I3D feature with 32 segments and 10-crop augmentation?

### ISSUE THREAD

**Issue by DungVo1507** [dmlc/gluon-cv#1698]
Hello, I'm following the instructions in section 8 of your website: Extracting video features from pre-trained models

I need the shape of each video's npy file to be (10, 32, 2048) respectively 10 is 10-crop augmentation, 32 is 32 segments of each video. Even though I have set --num-crop=10 and --num-segment=32 but the resulting shape of the npy files I get is (1, 2048).

Hope you can explain and guide me, thank you!

Below is my command line: 
python feat_extract.py --data-list video.txt --model i3d_resnet50_v1_kinetics400 --save-dir ./features --num-segments 32 --num-crop 10

**Comment by bryanyzhu** [comment]
Hi, I replied in another thread and attach the response here as well.

If you already get shape like (32, 2048, 2, 7, 7), you should be able to follow code below to squeeze it, 

```
st_avg = nn.GlobalAvgPool3D()
pooled_feat = st_avg(feat)
x = F.squeeze(pooled_feat, axis=(2, 3, 4))
```

Or if this doesn't work, you can turn `ndarray` to `numpy array`, and use numpy functions to take average/squeeze the feature, sth like

```
feat_np = feat.asnumpy()
feat_avg = numpy.mean(feat_np, axis=(2,3,4), keepdims=False)
```
