### ISSUE TITLE
person re-identification example

### ISSUE THREAD

**Issue by josefhernandez** [dmlc/gluon-cv#1699]
This is a feature request to create an example of the person re-identificacion algorithm

I'm executing YOLO in a live stream
And then when I try to execute the algorithm on each detected person:
```
reid = resnet50(ctx=ctx, pretrained = False)
reid.load_parameters('params/resnet50.params', ctx=ctx, allow_missing=True_, ignore_extra=True)

reid_normalizer = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
transform = transforms.Compose([
                    transforms.Resize(size=(128, 384), interpolation=1),
                    transforms.ToTensor(), 
                    reid_normalizer])
... YOLO ...
person = transform(person)
results = reid(person)    
```

I get the following error:
```
MXNetError: Check failed: dshp.ndim() == 4U (3 vs. 4) : Input data should be 4D in batch-num_filter-y-x
```

Who can I put multiple images (one for each person) into a 4D batch ?

**Comment by dai-ichiro** [comment]
if one image, you can use _expand_dims_.
if multiple images, you can use _gluoncv.data.batchify.Stack_.

hope this helps.
