### ISSUE TITLE
Unable to export GluonCV segmentation models

### ISSUE THREAD

**Issue by ksindwan** [dmlc/gluon-cv#1707]
`import gluoncv as gcv`
`from gluoncv.utils import export_block`
`net = gcv.model_zoo.get_model('psp_resnet101_voc', pretrained=True)`
`export_block('psp_resnet101_voc', net, preprocess=True, layout='HWC')`
`print('Done.')`

Running the above code to export segmentation models from gluoncv. But I am facing the following error

`RuntimeError: Error in operator pspnet15__pyramidpooling0_concat0: [03:52:20] src/operator/nn/concat.cc:67: Check failed: shape_assign(&(*in_shape)[i], dshape): Incompatible input shape: expected [1,-1,75,75], got [1,512,60,60]`

**Comment by dai-ichiro** [comment]
Try this script.

`export_block('psp_resnet101_voc', net, data_shape=(480, 480, 3), preprocess=True, layout='HWC')`
