### ISSUE TITLE
It is possible to execute Alpha Pose Estimation using GPU?

### ISSUE THREAD

**Issue by handreyeg** [dmlc/gluon-cv#1708]
I'm trying to execute the Alpha Pose estimation using GPU, but the following error is return:

`RuntimeError: Parameter 'conv0_weight' was not initialized on context cpu(0). It was only initialized on [gpu(0)].`

How can I fix this error? Or to run the Alpha Pose model using GPU do I need to run in another way?

Here it is a piece of my code:

    import mxnet as mx
    import gluoncv as gcv
    from gluoncv import data
    from gluoncv.model_zoo import get_model
    from gluoncv.data.transforms.pose import detector_to_alpha_pose, heatmap_to_coord_alpha_pose
    from gluoncv.utils.viz import cv_plot_image, cv_plot_keypoints
    
    ctx = mx.gpu(0)
    detector = get_model(''yolo3_mobilenet1.0_coco'', pretrained=True, ctx=ctx)
    detector.reset_class(classes=['person'], reuse_weights=['person'])
    net = get_model('alpha_pose_resnet101_v1b_coco', pretrained=True, ctx=ctx)
    cap = cv2.VideoCapture('video.mp4')
    fps = cap.get(cv2.CAP_PROP_FPS)
    success, frame = cap.read()
    height, width, _ = frame.shape
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    result = cv2.VideoWriter('output_filename.mp4',fourcc, fps, (width, height))

    while True:
	    success, frame = cap.read()
	    if success:
		    frame = mx.nd.array(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)).astype('uint8')
		    img = keypoint_detection(frame, detector, net, ctx=ctx)
		    cv_plot_image(img)
		    if  isinstance(img, mx.nd.NDArray):
			    img = img.asnumpy()
		    canvas = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
		    result.write(canvas)
	    else:
                break
	    if cv2.waitKey(1) == 27:
		    cv2.destroyAllWindows()
		    break
	cap.release()
	cv2.destroyAllWindows()
	result.release()

	def keypoint_detection(img, detector, pose_net, ctx=mx.gpu()):
		x, scaled_img = gcv.data.transforms.presets.yolo.transform_test(img, short=480, max_size=1024)
		x = x.as_in_context(ctx)
		class_IDs, scores, bounding_boxs = detector(x)
		pose_input, upscale_bbox = detector_to_alpha_pose(scaled_img, class_IDs, scores, bounding_boxs,ctx=ctx)
		if  len(upscale_bbox) > 0:
			predicted_heatmap = pose_net(pose_input)
			pred_coords, confidence = heatmap_to_coord_alpha_pose(predicted_heatmap, upscale_bbox)
			scale = 1.0 * img.shape[0] / scaled_img.shape[0]
			img = cv_plot_keypoints(img.asnumpy(), pred_coords, confidence, class_IDs, bounding_boxs, scores, box_thresh=0.5, keypoint_thresh=0.2, scale=scale)
		return img

If I use the Simple Pose Model it works perfecty.

**Comment by dai-ichiro** [comment]
It may hlep you.

https://github.com/dmlc/gluon-cv/issues/1289

**Comment by handreyeg** [comment]
I've done this. 

I didn't find another issue that would help me.

Is there anything else I can try?
