### ISSUE TITLE
VideoClsCustom can't load dataset with heterogeneous frame naming pattern

### ISSUE THREAD

**Issue by seraogianluca** [dmlc/gluon-cv#1709]
I am trying to execute the **Fine-tuning SOTA video models on your own dataset** tutorial with a custom dataset that collects videos from different datasets like UCF101 and HMDB51. 

The videos are already decoded in frames. However, the frames do not have a common naming pattern. Some videos may have the frames named "frameXXX.jpeg" and others simply "XXX.jpeg". With such a dataset, it is impossible to use `VideoClsCustom`. 

The [class doc](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/video_custom/classification.py) states:
```
name_pattern : str, default None.
	 The naming pattern of the decoded video frames.
	 For example, img_00012.jpg.
```
However, `name_pattern`is initialized by default at `'img_%05d.jpg'`. Thus, `VideoClsCustom` does not work if naming is different from the default and `name_pattern`is not set. Moreover, it does not work with a heterogeneous naming pattern like mine.

**Comment by bryanyzhu** [comment]
Unfortunately, there is no easy way to support heterogeneous naming pattern when you try to know the temporal order of frames. Maybe the easiest way is just to rename all the files to the same naming pattern for your experiment. Even for millions frames, renaming shouldn't take long.

**Comment by seraogianluca** [comment]
Thank you for your answer. Yes, I understand that. However, the point is that the class's doc is unclear. It should highlight that the default naming pattern is `img_%05d.jpg` (mandatory if argument is None) and, optionally, that a uniform naming pattern is required for the whole dataset.
