### ISSUE TITLE
SSD_512_mobilenet1_0: sd0_expand_bn3_gamma' has not been initialized

### ISSUE THREAD

**Issue by pribadihcr** [dmlc/gluon-cv#171]
Hi,

I got the following error when use my trained model in demo:

RuntimeError: Parameter 'ssd0_expand_bn3_gamma' has not been initialized. Note that you should initialize parameters and create Trainer with Block.collect_params() instead of Block.params because the later does not include Parameters of nested child Blocks

**Comment by nontas** [comment]
I get a similar error with `ssd_512_resnet50_v1_voc` when trying to use a model I trained on my data:

_RuntimeError: Parameter 'ssd0_expand_trans_conv0_weight' has not been initialized. Note that you should initialize parameters and create Trainer with Block.collect_params() instead of Block.params because the later does not include Parameters of nested child Blocks_

**Comment by zhreshold** [comment]
Do you guys have problem using pretrained models?

**Comment by nontas** [comment]
I my case, I have tested the pretrained `ssd_512_resnet50_v1_voc` and it works as expected. Also, the above error doesn't seem to be raised when using `ssd_512_vgg16_atrous_voc` trained on my data.

**Comment by pribadihcr** [comment]
@zhreshold,

Using pretrained, I got the following error:

RuntimeError: Parameter 'ssd0_expand_trans_bn1_moving_var' has not been initialized. Note that you should initialize parameters and create Trainer with Block.collect_params() instead of Block.params because the later does not include Parameters of nested child Blocks

**Comment by zhreshold** [comment]
Please update mxnet to latest build, it should fix the problem. Let me know if it still exists.

**Comment by pribadihcr** [comment]
@zhreshold 

Before I installed mxnet with pip install mxnet-cu90,
so I need update using pip or build it from source?

**Comment by zhreshold** [comment]
Yes, using pip install with `--pre` flag should be fine

**Comment by pribadihcr** [comment]
@zhreshold ,

pip install --pre mxnet-cu90  with conda version 4.5.4

I test using the following code:

```code```
from gluoncv import model_zoo, data, utils
from matplotlib import pyplot as plt
from gluoncv.model_zoo import get_model

data_shape = 512 
network = 'mobilenet1_0' 
dataset = 'voc'
net_name = '_'.join(('ssd', str(data_shape), network, dataset))
net = get_model(net_name, pretrained_base=True)
im_fname = ''test.jpg"

x, img = data.transforms.presets.ssd.load_test(im_fname, short=512)
print('Shape of pre-processed image:', x.shape)

class_IDs, scores, bounding_boxs = net(x)
print(class_IDs, scores, bounding_boxs)
ax = utils.viz.plot_bbox(img, bounding_boxs[0], scores[0],
                             class_IDs[0], class_names=net.classes)

plt.show()
```code```

Still got the following error:
RuntimeError: Parameter 'ssd0_expand_trans_conv0_weight' has not been initialized. Note that you should initialize parameters and create Trainer with Block.collect_params() instead of Block.params because the later does not include Parameters of nested child Blocks

**Comment by zhreshold** [comment]
@pribadihcr Okay, I just figured out that you are not using `pretrained=True`

```
# net = get_model(net_name, pretrained_base=True) is only downloading the backbone of network trained on ImageNet
# to get fully trained model, use the following
net = get_model(net_name, pretrained=True) 
```

**Comment by pribadihcr** [comment]
@zhreshold,

I have tried with pretrained=True, the problem was:
ValueError: Pretrained model for ssd_512_mobilenet1.0_voc is not available.
Have you tried it?

**Comment by pribadihcr** [comment]
@zhreshold,

I have us with my own trained model, and its work now. thanks
