### ISSUE TITLE
torch deploy_model() in model_utils.py buggy when cfg.DDP_CONFIG.DISTRIBUTED is False and running on GPU

### ISSUE THREAD

**Issue by singhalarchit** [dmlc/gluon-cv#1710]
The model dict keys are different when deploying model (eg: Slowfast) (`deploy_model()`) with and without `cfg.DDP_CONFIG.DISTRIBUTED`. When `cfg.DDP_CONFIG.DISTRIBUTED = False`, the keys are `odict_keys(['fast_conv1.weight', 'fast_bn1.weight', 'fast_bn1.bias', 'fast_bn1.running_mean'` and when it is set to `True`, the keys are `odict_keys(['module.fast_conv1.weight', 'module.fast_bn1.weight', 'module.fast_bn1.bias', 'module.fast_bn1.running_mean'`. Note that `module.` is missing when distributed is `False`. 

When loading the model from a checkpoint, the checkpoint keys always contain `module.`. I think the source of this issue is the absence of `model = torch.nn.DataParallel(model)` after this line: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/torch/utils/model_utils.py#L28. Adding this line works as expected.

**Comment by bryanyzhu** [comment]
Feel free to open a PR for this, thank you. Most of the time, we use DDP to train the model though.
