### ISSUE TITLE
Pip install ocr.utils is  not working 

### ISSUE THREAD

**Issue by A-lily** [dmlc/gluon-cv#1716]
<img width="1350" alt="Screen Shot 2021-11-17 at 16 41 22" src="https://user-images.githubusercontent.com/40887316/142243723-8fb2b23a-180b-42e7-9c09-5ec37511f1b0.png">

**Comment by bryanyzhu** [comment]
I don't think GluonCV has or uses this ocr module. Close this issue for now, but feel free to reopen it.
