### ISSUE TITLE
enhancement and contribute

### ISSUE THREAD

**Issue by 315386775** [dmlc/gluon-cv#1719]
Hello. My team has reproduced many new SOTA methods. I want to know how to contribute the code and how to become a contributor.

**Comment by bryanyzhu** [comment]
Hi, thank you for your interest in using and contributing GluonCV, you can find `how to contribute` in this [site](https://cv.gluon.ai/how_to/contribute.html). Once you make a pull request, we can review your code and merge it into master branch.
