### ISSUE TITLE
Image Segmentation Network, strange looking images

### ISSUE THREAD

**Issue by ThomasDelteil** [dmlc/gluon-cv#172]
Using `gluoncv 0.2` this is the output I get when running the image segmentation tutorial:
<img width="308" alt="screen shot 2018-06-20 at 8 05 40 am" src="https://user-images.githubusercontent.com/3716307/41667029-ca40eb18-7460-11e8-96a2-e473ab49fdbc.png">

Is this the expected output? The mask looks strange and the denormalized image has artefact.

**Comment by zhreshold** [comment]
@zhanghang1989

**Comment by ThomasDelteil** [comment]
The reason is because the training images are augmented by default. Discussed with @hetong007 about that and in my opinion, there should be a flag to disable the default augmentation, or default augmentation should be passed by default to the transform argument. Right now you would need to do
```
trainset = gluoncv.data.VOCSegmentation(split='train')
trainset.mode = 'test'
```
in order to get training images without data augmentation.

**Comment by ThomasDelteil** [comment]
the artefact happen also on validation set, root cause was a bug in denormalize

**Comment by zhanghang1989** [comment]
Thanks for reporting! There was a bug in denormalization.
