### ISSUE TITLE
need setup the dataset usingscripts/datasets/ade20k.py?

### ISSUE THREAD

**Issue by rikkudo** [dmlc/gluon-cv#1721]
so I try gluoncv for segmentation using ade20k dataset and then got error when I set path for the root. always show error massage Please setup the dataset usingscripts/datasets/ade20k.py

Here is my code :

from mxnet.gluon.data.vision import transforms as T
trf = T.Compose([T.Resize(256),
                 T.CenterCrop(224),
                 T.ToTensor(), 
                 T.Normalize(mean = [0.485, 0.456, 0.406], 
                             std = [0.229, 0.224, 0.225])])
trainset = gluoncv.data.ADE20KSegmentation(root='./ADEChallengeData2016/', split='train', transform=trf)

I making the code exactly same like in the example from this link : https://cv.gluon.ai/_modules/gluoncv/data/ade20k/segmentation.html#ADE20KSegmentation

I don't know why it getting error. I run that in Google Collab
`

**Comment by bryanyzhu** [comment]
If you look at this line (https://github.com/dmlc/gluon-cv/blob/ab03ca04c588342be5cd659c3f96011c0146ac4f/gluoncv/data/ade20k/segmentation.py#L103), the error indicates it cannot find your root directory. Please double check your data path, and try to use full path instead of relative path.

**Comment by rikkudo** [comment]
> If you look at this line (
> 
> https://github.com/dmlc/gluon-cv/blob/ab03ca04c588342be5cd659c3f96011c0146ac4f/gluoncv/data/ade20k/segmentation.py#L103
> 
> ), the error indicates it cannot find your root directory. Please double check your data path, and try to use full path instead of relative path.

Finally I ca fix the error, thanks a lot
