### ISSUE TITLE
Fcn-resnet pre-training model based on pytorch

### ISSUE THREAD

**Issue by weixj1998** [dmlc/gluon-cv#1723]
Hello, how can I obtain the current pytorch version of fcn-resnet101 pre-training model? Because it was placed on the wassabi server before, but it is no longer accessible, thank you!

**Comment by bryanyzhu** [comment]
To my knowledge, I don't know we had FCN pytorch models. If you need pytorch models for segmentation, you can refer to https://github.com/zhanghang1989/PyTorch-Encoding for more information.
