### ISSUE TITLE
How to push the new changes for PR?

### ISSUE THREAD

**Issue by kd610** [dmlc/gluon-cv#1749]
Hi there,

I have found errors and I fixed them. However, I couldn't push my commits to this repo... I followed the contribution document to set up for pushing commits. Below is what I got when I run `git push --set-upstream origin my_branch_name`.

```
ERROR: Permission to dmlc/gluon-cv.git denied to kd610.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Best regards,

Kohei

**Comment by bryanyzhu** [comment]
For me, usually I contribute like this

```
1. Fork GluonCV to your account
2. Git clone your fork to your local environment
3. Checkout a new branch like `git checkout -b newfeature`
4. Make your changes
5. Commit your changes like `git add .`, then `git commit -m 'new changes'`
6. Push your change to remote branch like `git push -u origin newfeature`
7. Go to GluonCV github, you will find a prompt to let you make a PR
```

**Comment by kd610** [comment]
I somehow faced a credential error when I tried to push my commits so that I thought there is some special credential stuff on this repo for PR... But it should work with just the usual way of making PR. Thank you for your comment!
