### ISSUE TITLE
Not working in Google Colab?   Old cuda libraries and not supported anymore?

### ISSUE THREAD

**Issue by karthik111** [dmlc/gluon-cv#1775]
Hi, 
  Is it possible to run Gluon CV on Google Colab?  Is this still in active use and supported? 

It looks like we use legacy libraries that are not supported anymore? 

RuntimeError: Legacy torch==2.1.0+cu121 detected, some modules may not work properly. torch>=1.4.0,<2.0.0 is required. You can use pip or conda to upgrade

**Comment by Ammar-BinMadi** [comment]
I also had the same problem while running Gluon CV on Google Colab I get the following error


RuntimeError: Legacy torch==2.3.1+cu121 detected, some modules may not work properly. torch>=1.4.0,<2.0.0 is required. You can use pip or conda to upgrade
