### ISSUE TITLE
Feedback on gluon ssd!

### ISSUE THREAD

**Issue by fighting-liu** [dmlc/gluon-cv#195]
gluon-cv commit id 411f61ce63a318100b14ac597e49eafe8da649b5
mxnet version: both 1.2 and 1.3
cuda-9.0, cudnn7.0
python 2.7
GPU: Tesla P100

Try gluon-ssd-vgg-300 on my own dataset with coco format input

1. **orig_height** and **orig_width** should be float type for python2.x
https://github.com/dmlc/gluon-cv/blob/c114f6c4b7d64e00ab2b5be747d5e46cfd68e04a/gluoncv/utils/metrics/coco_detection.py#L184:51

2. **TypeError: unicode argument expected, got 'str'**
change https://github.com/dmlc/gluon-cv/blob/c114f6c4b7d64e00ab2b5be747d5e46cfd68e04a/gluoncv/utils/metrics/coco_detection.py#L128:33   to `sys.stdout = io.BytesIO()` fix my error

3. **Error: num_slice does not evenly divide data.shape[batch_axis].**
In validation, `last_batch='keep'` is used for validation data loader, it will case error when num of you validation data can't be divided by batchsize.
add even_split=False to  https://github.com/dmlc/gluon-cv/blob/c114f6c4b7d64e00ab2b5be747d5e46cfd68e04a/scripts/detection/ssd/train_ssd.py#L123:23 fix my error.

4. Training speed is very unstable with mxnet 1.2,  sometimes 140-150 samples/s, and sometimes 10-20 samples/s, ungrade mxnet to 1.3 fix the problem, and training speed is always around 140-150 sample/s

5. Results for gluon-ssd is better than mxnet-ssd on my own dataset, 3-4 mAP more with coco-metric.

6. FPS for gluon-ssd-vgg-300 is 
b=1, fps=55
b=8, fps=117 
b=16, fps=148
and speed for mxnet-ssd is 
b=1, fps=65
b=8, fps=124
b=16, fps=156

Finally, thanks to gluon-cv team!

**Comment by zhreshold** [comment]
Awesome! I do appreciate the valuable feedbacks. 
BTW, would you like to submit a PR to fix those minor problems you mentioned?

**Comment by fighting-liu** [comment]
Ok, i will submit a PR later.

**Comment by zhreshold** [comment]
@fighting-liu Do you have any updates then?

**Comment by zhreshold** [comment]
Thanks for the feedbacks again, #255 fixes the problems mentioned.
