### ISSUE TITLE
Converting from numpy to ndarray slowdown...

### ISSUE THREAD

**Issue by cheperuiz-code** [dmlc/gluon-cv#199]
Hi, I'm capturing images from a webcam continuously (using cv2), transforming them into NDArrays and reshaping them to evaluate a mobilenet ssd network (from gluon model zoo), however, the time to process each frame varies considerably and it takes up to 2 seconds (For the record, my code runs in an armv7hf platform, <0.5s is what I would expect). I suppose this happens because of memory allocation/fragmentation issues. I'm also using nnpack...

Any idea what can be done to avoid this issue? Thanks,

Code and an example of the output below (capture of frame outside of loop to take it out of the equation...). It seems that the slow operation is the call to mx.nd.array(frame), however the slowdown won't happen if I remove the call to net(x)...

CODE:

    net = model_zoo.get_model('ssd_512_mobilenet1_0_voc', pretrained=True)
    cam = cv2.VideoCapture(args.src)
    ret, frame = cam.read()
    
    while True:  # fps._numFrames < 120

        t1 = time.time()
        q=mx.nd.array(frame).as_in_context(mx.cpu(0))
        t2 = time.time()
        q=gdata.transforms.image.imresize(q,512,512)
        x=q.reshape(1,3,512,512)
        t3 = time.time()
        class_IDs, scores, bounding_boxs = net(x)
        t4 = time.time()

        print('[INFO] Conversion to NDArray: {:.2f}'.format(t2-t1))
        print('[INFO] Resize and reshape: {:.2f}'.format(t3-t2))
        print('[INFO] Forward pass: {:.2f}'.format(t4-t3))
        print('[INFO] Total time elapsed: {:.2f}'.format(t4-t1))

Output:

[INFO] Conversion to NDArray: 0.03
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.17
[INFO] Total time elapsed: 0.21

[INFO] Conversion to NDArray: 2.06
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.13
[INFO] Total time elapsed: 2.19

[INFO] Conversion to NDArray: 0.84
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.14
[INFO] Total time elapsed: 0.98

[INFO] Conversion to NDArray: 0.63
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.11
[INFO] Total time elapsed: 0.73

[INFO] Conversion to NDArray: 0.57
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.12
[INFO] Total time elapsed: 0.69

[INFO] Conversion to NDArray: 0.25
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.16
[INFO] Total time elapsed: 0.41

[INFO] Conversion to NDArray: 1.98
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.21
[INFO] Total time elapsed: 2.19

[INFO] Conversion to NDArray: 0.81
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.20
[INFO] Total time elapsed: 1.01

[INFO] Conversion to NDArray: 0.50
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.15
[INFO] Total time elapsed: 0.65

[INFO] Conversion to NDArray: 0.69
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.10
[INFO] Total time elapsed: 0.79

[INFO] Conversion to NDArray: 0.06
[INFO] Resize and reshape: 0.00
[INFO] Forward pass: 0.17
[INFO] Total time elapsed: 0.24

**Comment by zhreshold** [comment]
Closing assuming this is done, feel free to ping me if you think it's incomplete.
