### ISSUE TITLE
CIFAR-10 original images

### ISSUE THREAD

**Issue by Will0622** [dmlc/gluon-cv#204]
Hi,

I want to prepare a customized cifar10 dataset for knowledge distillation. There is a list in the http://data.mxnet.io/data/cifar10/ folder while the original images are missing. I am wondering is it possible to find the original images somewhere. Thanks!

**Comment by hetong007** [comment]
The CIFAR10 dataset is originally from https://www.cs.toronto.edu/~kriz/cifar.html .

You can also try our API `mxnet.gluon.data.vision.CIFAR10()` as demonstrated here: https://github.com/hetong007/gluon-cv/blob/master/scripts/classification/cifar/train_cifar10.py#L117
