### ISSUE TITLE
How to provide custom dataset

### ISSUE THREAD

**Issue by alexschultz** [dmlc/gluon-cv#218]
Is there a way to provide your own class names to Pascal VOC so you can fine tune with your own dataset? I see the class names are hardcoded here but I don't see a way to override them with your own custom list.
https://github.com/dmlc/gluon-cv/blob/10cc10788d96b5b9087bc1c211efa19cc8eda200/gluoncv/data/pascal_voc/detection.py#L43

**Comment by ewinterrms** [comment]
I have done this as a temporary solution and it works, just be sure to use
the same names during inference as it changes the structure saved in params.

If anyone has more ideas about this solution, it would be great to know.
I'm happy to contribute code and solutions as well if this is something
helpful for this project.

**Comment by alexschultz** [comment]
You mean you just added your class names to the list?

**Comment by ewinterrms** [comment]
I replaced the list with the objects I setup for detection, but fewer so
the classification vector is saved in paramus, so need to change the list
during inference if using load_parameters.

**Comment by ewinterrms** [comment]
One thought id like to add is that the params file and the inference code both have awareness of the classes... I've got a custom docker running a custom trained model and the params can be introduced via artifacts from a separate file location.  It would be great to also have this ability for inference class definitions.  Happy to be more detailed if it will help...I may also experiment with some solutions if interested in extra coding help on this (I'd prefer not to solve this if it's just going to be solved again by someone else, however)

**Comment by zhreshold** [comment]
I have a plan to write a tutorial about this, stay tuned.

**Comment by alexschultz** [comment]
Awesome [work](https://gluon-cv.mxnet.io/build/examples_detection/finetune_detection.html#sphx-glr-build-examples-detection-finetune-detection-py)! Thanks

**Comment by iphyer** [comment]
@zhreshold  Any luck?

**Comment by zhreshold** [comment]
@iphyer https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html
