### ISSUE TITLE
yolov3 get different mAP at training and eval phase

### ISSUE THREAD

**Issue by ShoufaChen** [dmlc/gluon-cv#238]
I use the yolov3 detection framework, and use my backbone instead of darknet53.  Everything works fine. 

However, when I finished training, and run `eval_yolo.py` script with the **best.params**, I got a result with little drop compared to the **best_map.log**.  i.e.  from `mAP=0.7669720908837704` at  **best_map.log**,  to
`mAP=0.7638073010094124`  at eval phase.

**Comment by ShoufaChen** [comment]
I also triedthe `train_yolov3.py` script.
I use the command:  ` --resume= best.params` and changed the `train_yolov3.py`  as follows:
```
    for epoch in range(args.start_epoch, args.epochs):
        map_name, mean_ap = validate(net, val_data, ctx, eval_metric)
        val_msg = '\n'.join(['{}={}'.format(k, v) for k, v in zip(map_name, mean_ap)])
        logger.info('[Epoch {}] Validation: \n{}'.format(epoch, val_msg))

        tic = time.time()
        btic = time.time()
        mx.nd.waitall()
```
in order to run evaluation process before training the first epoch.  Then , I get the totally same result as use the `eval_yolo.py` script. 

i.e. I can't get the result at the  **best_map.log** again?

**Comment by zhreshold** [comment]
may be you are using different shape at train and eval? 
From my experience, the train and eval can produce same results.

**Comment by hetong007** [comment]
Are you using multiple GPUs? If so, during training the validation is calculated on multiple-GPUs separately. When saving the parameters after training, mxnet will average all parameters across GPUs thus the result could be differernt. 

This can be a possible reason.
