### ISSUE TITLE
Ignore bboxes during training ssd

### ISSUE THREAD

**Issue by allgrom** [dmlc/gluon-cv#257]
Hi!
Is it possible to ignore some bboxes during training ssd? 
Goal - ssd doesn't compute loss from controversial bboxes.

**Comment by zhreshold** [comment]
https://github.com/dmlc/gluon-cv/blob/a7219aee46490343c97d00ac5b92a3bdb731b598/gluoncv/loss.py#L157 
For now, it only computes box loss for positive samples, but you can customize the mask to something not `pos.expand_dims(axis=-1)`

**Comment by allgrom** [comment]
Thank you!
