### ISSUE TITLE
use corner box and center box computer iou

### ISSUE THREAD

**Issue by ShoufaChen** [dmlc/gluon-cv#262]
Hi, 

I don't understand [here](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/yolo/yolo_target.py#L90) , the `shift_anchor_boxes` is  corner box  format,  but the `shift_gt_boxes` is center box format.   and the `box_iou` function default format is corner.

Please tell me if I ignored something.

**Comment by zhreshold** [comment]
The `shift_gt_boxes` still a corner box, but seems like it's left/top corner should be -w/2 and -h/2. I will verify the impact on performance.

**Comment by ShoufaChen** [comment]
Thank  you.

My understanding is that this code:
```
 gtx, gty, gtw, gth = self.bbox2center(gt_boxes)
 shift_gt_boxes = nd.concat(gtx * 0, gty * 0, gtw, gth, dim=-1)
 anchor_boxes = nd.concat(0 * all_anchors, all_anchors, dim=-1)  # zero center anchors
shift_anchor_boxes = self.bbox2corner(anchor_boxes)
ious = nd.contrib.box_iou(shift_anchor_boxes, shift_gt_boxes).transpose((1, 0, 2))
```
is to choose the best batching anchor from 9 (in YOLOv3)  at a specify position.  So just suppose the ground truth is located at (0, 0) for simplify.   

And add a line:
```
 shift_gt_boxes = self.bbox2corner(shift_gt_boxes)
```
will be correct.

Dose my understanding right?

**Comment by zhreshold** [comment]
Correct, seems like this bug caused about 0.6 mAP drop on VOC dataset, I will fix it and test on COCO again.

**Comment by zhreshold** [comment]
#265

**Comment by ShoufaChen** [comment]
Thanks very much.  And in fact, I am quite curious about why this seem serious bug causes tiny performance influence ?  Any reasons account for this ?

**Comment by zhreshold** [comment]
Possibly a good anchor has to be matched and regress toward gt anyway, but it is indeed very strange.
