### ISSUE TITLE
Error when training SSD

### ISSUE THREAD

**Issue by allgrom** [dmlc/gluon-cv#267]
Hi!

SSDDefaultTrainTransform doesn't work if an image doesn't contain bboxes.

`  File "/home/sasha/PycharmProjects/trainSSD/utils/data_loaders.py", line 58, in __call__
    bbox, crop = experimental.bbox.random_crop_with_constraints(bbox, (w, h), max_trial=10)
  File "/home/sasha/.local/lib/python3.5/site-packages/gluoncv-0.3.0-py3.5.egg/gluoncv/data/transforms/experimental/bbox.py", line 99, in random_crop_with_constraints
    new_bbox = bbox_crop(bbox, crop, allow_outside_center=False)
  File "/home/sasha/.local/lib/python3.5/site-packages/gluoncv-0.3.0-py3.5.egg/gluoncv/data/transforms/bbox.py", line 51, in crop
    centers = (bbox[:, :2] + bbox[:, 2:4]) / 2`

**Comment by allgrom** [comment]
@zhreshold, it happened accidentally, when function _load_label returned an empty list (I wrote my dataset class). I don't want the training to stop if function _validate_label throw AssertionError, so I ignore it and return an empty list.

**Comment by zhreshold** [comment]
@allgrom Because VOC won't have invalid labels, so I use assertion error explicitly.
If you want to skip some image, just return np.array([[-1,-1,-1,-1,-1,-1]]) instead.

**Comment by allgrom** [comment]
Thank you!
