### ISSUE TITLE
Yolo error

### ISSUE THREAD

**Issue by theprodev** [dmlc/gluon-cv#279]
Hi, I am trying this example;
https://gluon-cv.mxnet.io/build/examples_detection/demo_yolo.html
but it is giving error.
ValueError: Model yolo3_darknet53_coco is not supported. Available options are

Thanks for your support.

**Comment by LightToYang** [comment]
it may be that the version of your gluoncv is 0.2.0? try pip install gluon==0.3.0b20180827

**Comment by theprodev** [comment]
Thanks a lot. That worked nicely.
