### ISSUE TITLE
change the loss function to predict 8 points instead of 4 points for bounding box

### ISSUE THREAD

**Issue by prashant905** [dmlc/gluon-cv#283]
I am trying out SSD bounding box training example. But in my case, I need 8 points instead of 4 points bounding box. The bounding box I am trying to predict have all the four coordinates of the rectangle. What changes are required to implement this?  
I believe Multiboxprior can only used to predict 4 points.

**Comment by zhanghang1989** [comment]
Is the 8 points for 3D problem? I think dim of 6 should work for 3D problem, (x, y, z) and the length along each dimension.

**Comment by xizi** [comment]
可能是任意四边形的训练
