### ISSUE TITLE
Why not use OpenCV to deal with images?

### ISSUE THREAD

**Issue by chinakook** [dmlc/gluon-cv#291]
As many tests show, pillow is slower than OpenCV. OpenCV will get 1.5~10x faster so I suggest that we should use OpenCV in gluon-cv.
https://github.com/jbohnslav/opencv_transforms

**Comment by zhreshold** [comment]
We are actually using opencv by calling mxnet.image. There are some rare cases the forbid us to do so. Mainly with semantic segmentation part. @zhanghang1989, am I correct about that part?
