### ISSUE TITLE
How to load a custom model?

### ISSUE THREAD

**Issue by theprodev** [dmlc/gluon-cv#292]
Hi, I need to load my custom model for object detection but did not find an example. Can you please help?

**Comment by theprodev** [comment]
That's great. But I have an already trained custom model. The params file
that I got from another library. How to load with pre-trained True?

**Comment by theprodev** [comment]
Sorry for asking possibly dumb questions. I'm very new to this stuff.

**Comment by allgrom** [comment]
What library is it?

**Comment by allgrom** [comment]
Are you sure, that resnet-50 model from https://github.com/knjcode/mxnet-finetuner has the same structure as resnet-50 in gluoncv and the same naming of layers?
And it is different tasks, https://github.com/knjcode/mxnet-finetuner  - classification, ssd_512_resnet50 - detection.

**Comment by zhreshold** [comment]
@theprodev Is there any specific reason why you want to use your pre-trained model rather than imagenet which might be more generic?

**Comment by ewinterrms** [comment]
I personally prefer not to use pre-trained to save docker from having to
load the model file during inference

Erickson Winter
*Data Scientist*
[image: Red Mountain Scientific]

**Comment by zhreshold** [comment]
@theprodev Sorry about the confusion. If I assume your intension is to train a good model on your tiny dataset with 8 classes and 6 images for each.

You can easily start off by transferring from the pre-trained object detection models, with provided API:

```
net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_custom', classes=[str(x) for x in range(8)], transfer='ssd_512_resnet50_v1_coco')
# start training on your own dataset
```

**Comment by wegel** [comment]
FYI, the above fails with:
```
Traceback (most recent call last):
  File "simple_train.py", line 48, in <module>
    net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_custom', classes=[str(x) for x in range(8)], transfer='ssd_512_resnet50_v1_coco')
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/model_zoo/model_zoo.py", line 186, in get_model
    net = _models[name](**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/model_zoo/ssd/ssd.py", line 664, in ssd_512_resnet50_v1_custom
    net = get_model('ssd_512_resnet50_v1_' + str(transfer), pretrained=True, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/model_zoo/model_zoo.py", line 185, in get_model
    raise ValueError(err_str)
ValueError: "ssd_512_resnet50_v1_ssd_512_resnet50_v1_coco" is not among the following model list:

```
The correct way, I guess, would be:
`net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_custom', classes=[str(x) for x in range(8)], transfer='coco')`

**Comment by stereomatchingkiss** [comment]
The way I tried, worked

`net = get_model("yolo3_darknet53_custom", classes = read_classes(args), pretrained_base=True)             net.load_parameters("params_name")`

you can check the details [from my blog](https://qtandopencv.blogspot.com/2019/01/train-detector-based-on-yolo-v3by.html)
