### ISSUE TITLE
Model file is not found.

### ISSUE THREAD

**Issue by ZackLord** [dmlc/gluon-cv#294]
As I attempted to load a pretrained model, the error message "Model file is not found. Downloading" popped up while downloading from a redirected link also failed. The script was provided with the demo_ssd.ipynb file, can anyone explain what is going on here?

**Comment by ZackLord** [comment]
mxnet 1.2.1 by conda
gluoncv 0.2.0 by pip since not available from conda channels
dependency issue?

**Comment by allgrom** [comment]
Install latest mxnet (1.3.0) and gluon-cv (0.3.0)
```
pip install --user mxnet-cu92
pip install --user gluoncv
```

**Comment by ZackLord** [comment]
How to install 0.3.0 gluoncv whereas the latest version I can upgrade to is still 0.2.0 as in here and PyPI? BTW the package manager also prompted me having the latest versions for them.

**Comment by allgrom** [comment]
Sorry, use flag --pre
```
pip install --pre mxnet-cu92
pip install --pre gluoncv
```

**Comment by ZackLord** [comment]
wonderfully solved, thank you dude
