### ISSUE TITLE
anchor.py in ssd.py

### ISSUE THREAD

**Issue by uran209** [dmlc/gluon-cv#302]
Hi. Now i am trying to implement a SSD model using my own images.
    And I think there may be a bug in the anchor.py.

    for r in ratios[1:]:
    must be
    for _ in r[1:]:
    in the _generate_anchors function below?

---------------------------------------------------------------------------------------------------
      def _generate_anchors(self, sizes, ratios, step, alloc_size, offsets):
        """Generate anchors for once."""
        assert len(sizes) == 2, "SSD requires sizes to be (size_min, size_max)"
        anchors = []
        for i in range(alloc_size[0]):
            for j in range(alloc_size[1]):
                cy = (i + offsets[0]) * step
                cx = (j + offsets[1]) * step
                # ratio = ratios[0], size = size_min or sqrt(size_min * size_max)
                r = ratios[0]
                anchors.append([cx, cy, sizes[0], sizes[0]])
                anchors.append([cx, cy, sizes[1], sizes[1]])
                # size = sizes[0], ratio = ...
                for r in ratios[1:]:
                    sr = np.sqrt(r)
                    w = sizes[0] * sr
                    h = sizes[0] / sr
                    anchors.append([cx, cy, w, h])
        return np.array(anchors).reshape(1, 1, alloc_size[0], alloc_size[1], -1)

**Comment by uran209** [comment]
I am sorry. my misunderstanding.
However, cx and cy will overflow beyond sizes[0], sizes[1] during the alloc_size increment.
Is it OK?

**Comment by zhreshold** [comment]
The pre-allocate size can be as large as wanted. It will be cropped according to real input size, so don't worry about that.

**Comment by uran209** [comment]
Thank you for your comment. I confirmed the cropping process.
In the checking process, I found a small bug candidate in coder.py line_177, which does not affect the result in current coding.
I think
        th = F.exp(p[3] * self._stds[3] + self._means[2])
may be
        th = F.exp(p[3] * self._stds[3] + self._means[3])

**Comment by zhreshold** [comment]
@uran209 The anchors are stored in (x, y, w, h) for faster inference. It will be converted to corner format during target generation.

**Comment by uran209** [comment]
@zhreshold 
Nice suggetion. I could understand the anchors are the center mode at this stage and they are converted to the corner mode in the model in modelzoo.ssd.target.py.
I could modify the anchor generation algorithm successfully, thanks to you.

**Comment by uran209** [comment]
resolved #12
