### ISSUE TITLE
many pre-trained models not found

### ISSUE THREAD

**Issue by husonchen** [dmlc/gluon-cv#304]
Here shows many pre-trained models we can use for semantic-segmentation:
https://gluon-cv.mxnet.io/model_zoo/index.html#semantic-segmentation
But when I try to load a pre-trained model from that table. 
`model = gluoncv.model_zoo.get_model('deeplab_resnet101_voc', pretrained=True)`
It gives:
ValueError: Model deeplab_resnet101_voc is not supported. Available options are...
And The shell script is also 404:
https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/segmentation/deeplab_resnet101_voc.sh

**Comment by zhreshold** [comment]
It's now uploaded and you can try again.

**Comment by zhreshold** [comment]
Okay, I double checked it's 404 now.  @zhanghang1989 can you have a look?

**Comment by Thelta** [comment]
yolov3 pretrained files not found too.

``
net = model_zoo.get_model('yolo3_darknet53_voc', pretrained=True)
``
returns
Model yolo3_darknet53_voc is not supported. Available options are: ...

coco versions are also not available.

**Comment by zhreshold** [comment]
@Thelta You could update gluoncv to fix it, with pip: `pip install gluoncv --pre --upgrade``

**Comment by zhanghang1989** [comment]
The shells have been provided.
