### ISSUE TITLE
eval_ssd speed drops with increasing batch size

### ISSUE THREAD

**Issue by davsol** [dmlc/gluon-cv#313]
hi,
I'm evaluating the pre-trained models of ssd_voc, and as I increase the batch-size, the speed drops (the mAP stays the same)
** running on a single machine, 6 cpus, 1xV100, mxnet1.3
tested: 

ssd_512_mobilenet1.0_voc

`python scripts/detection/ssd/eval_ssd.py --data-shape 512 --batch-size 8 --network mobilenet1.0`
 87%|#######################################8         | 4288/4952 [00:27<00:03, 196.41it/s]

`python scripts/detection/ssd/eval_ssd.py --data-shape 512 --batch-size 32 --network mobilenet1.0`
 66%|#################################8                       | 3264/4952 [00:34<00:12, 135.28it/s]

`python scripts/detection/ssd/eval_ssd.py --data-shape 512 --batch-size 64 --network mobilenet1.0`
 68%|#################################2                     | 3392/4952 [00:54<00:19, 80.67it/s]

ssd_512_vgg_reduced_voc:
`python scripts/detection/ssd/eval_ssd.py --data-shape 512 --batch-size 16 --network vgg16_atrous`
 69%|#################################  #9                     | 3440/4952 [00:48<00:17, 87.52it/s]

`python scripts/detection/ssd/eval_ssd.py --data-shape 512 --batch-size 32 --network vgg16_atrous`
 36%|########################5                                            | 1760/4952 [00:38<00:45, 69.46it/s]

`python scripts/detection/ssd/eval_ssd.py --data-shape 512 --batch-size 48 --network vgg16_atrous`
 60%|###############################4                           | 2976/4952 [01:02<00:31, 63.35it/s]

**Comment by zhreshold** [comment]
This should have already been fixed with https://github.com/apache/incubator-mxnet/pull/12118, and is merged to master already. You can update mxnet with --pre
