### ISSUE TITLE
How to run Demo using GPU?

### ISSUE THREAD

**Issue by liuchang8am** [dmlc/gluon-cv#315]
For example, in ssd demo, https://gluon-cv.mxnet.io/build/examples_detection/demo_ssd.html, I think it uses cpu. How to use gpu to run the demo?

**Comment by zhreshold** [comment]
```
net = model_zoo.get_model('ssd_512_resnet50_v1_voc', pretrained=True, ctx=mx.gpu(0))
net(x.as_in_context(mx.gpu(0))
```

**Comment by ievron** [comment]
Sometimes the problem is that the **model** is on the cpu and the data is on the **gpu**.
In that case, one can run

`net.collect_params().reset_ctx([mx.gpu(0), mx.gpu(1)])`

to make the model run on the GPUs as well.

**Comment by waflessnet** [comment]
@ievron @zhreshold , Thanks !!!!!
