### ISSUE TITLE
[Question] What is _voc, _coco or _custom and when to use ?

### ISSUE THREAD

**Issue by gachiemchiep** [dmlc/gluon-cv#321]
Hello.
Thank you for your great work. 

Currently, there are several model available inside gluon-cv model zoo.

```python
   ....
    'ssd_512_vgg16_atrous_voc': ssd_512_vgg16_atrous_voc,
    'ssd_512_vgg16_atrous_coco': ssd_512_vgg16_atrous_coco,
    'ssd_512_vgg16_atrous_custom': ssd_512_vgg16_atrous_custom,
    ...
```

What is the difference between _voc, _coco and _custom model and when to use them ?
As i understand, _voc models were trained with  VOC dataset, _coco models were trained with COCO dataset. But what were used to trained for _custom.
For example, i need to train object detection on custom dataset. Should i go with the _custom dataset or finetune using the _voc, _coco model.

Thank you

**Comment by zhreshold** [comment]
There are no pre-trained weights for `_custom`, it can be any custom datasets. The purpose of custom datasets is to provide easier access to instantiate models:

```python
import gluoncv as gcv
# create a model with default settings and custom classes as a, b, c. 
# Also load pre-trained vgg16 weights.
model = gcv.model_zoo.get_model('ssd_512_vgg16_atrous_custom', ['a', 'b', 'c'], 
    pretrained_base=True)
# start training and save parameters
model.save_parameters('xxx.params')

# during testing you can load the parameters
model.load_parameters('xxx.params')
