### ISSUE TITLE
Bug in the latest CityScapes data preparation script

### ISSUE THREAD

**Issue by d-li14** [dmlc/gluon-cv#327]
In my opinion, `if args.download_dir is None`, before checking sha1 in https://github.com/dmlc/gluon-cv/blob/master/scripts/datasets/cityscapes.py#L28, downloading should be executed with an extra line `filename = download(url, path=download_dir, overwrite=overwrite, sha1_hash=checksum)` like this. Furthermore,  as far as i know, official CityScapes downloading page requires logging, it is not convenient to download with aforementioned default `gluon` API.

**Comment by zhanghang1989** [comment]
Cityscapes dataset has the copyright of the data. The user should login their account and manually download the files.

**Comment by d-li14** [comment]
@zhanghang1989 . I see, the script is just for extracting instead of downloading. Thanks very much！
PS: there exists a minor typo in arguments [description](https://github.com/dmlc/gluon-cv/blob/master/scripts/datasets/cityscapes.py#L13)

**Comment by zhanghang1989** [comment]
Thanks for pointing out the typo!
