### ISSUE TITLE
Values of sizes for anchors

### ISSUE THREAD

**Issue by allgrom** [dmlc/gluon-cv#332]
Which algorithm did you use for computing the values of sizes for anchors?

ssd_512_resnet50_v1_coco:
```
sizes=[51.2, 133.12, 215.04, 296.96, 378.88, 460.8, 542.72]
```
ssd_512_resnet50_v1_voc
```
sizes=[51.2, 102.4, 189.4, 276.4, 363.52, 450.6, 492]
```

**Comment by zhreshold** [comment]
This is based on the statistics of datasets. There's no thumb of rules to be honest. 
In the original paper, the sizes are computed with arange from (0.1 to 0.95) * shape

**Comment by wait1988** [comment]
@zhreshold So how to set the anchor size for other datasets,any sugesstion?
