### ISSUE TITLE
[Question] How to use a MS COCO model finetune to VOC model in gluoncv?

### ISSUE THREAD

**Issue by Angzz** [dmlc/gluon-cv#352]
@zhreshold Hi, I also see '' Our model is pretrained on ImageNet, finetuned on MS COCO, and then finetuned on VOC'' in some papers, can you tell me how to do this with gluoncv? thanks.

**Comment by zhreshold** [comment]
simply train on COCO, then call net.reset_class to voc classes. Again train on VOC.

**Comment by Angzz** [comment]
oh，I see the custom dataset in model_zoo, thanks very much
