### ISSUE TITLE
can train_yolo3.py run without GPU？

### ISSUE THREAD

**Issue by qingzhouzhen** [dmlc/gluon-cv#387]
I want to run train_yolo3.py with my mac, I folowed the tutories, firstly I do: 
```path/gluon-cv/scripts/detection/yolo/python train_yolo3.py --no-random-shape```
it complain:
```mxnet.base.MXNetError: [14:45:58] src/ndarray/ndarray.cc:1270: GPU is not enabled```
then I change the script code:
```
ctx = [mx.gpu(int(i)) for i in args.gpus.split(',') if i.strip()]
ctx = ctx if ctx else [mx.cpu()]
```
to:
```ctx = mx.cpu()```
then it complains:
```
Segmentation fault: 11

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x000000010b325990 libmxnet.so + 14736
[bt] (1) 1   libmxnet.so                         0x000000010ce90b96 MXTVMBridge + 4728950
[bt] (2) 2   libsystem_platform.dylib            0x00007fffa869eb3a _sigtramp + 26
[bt] (3) 3   ???                                 0x0000fffc0000fffb 0x0 + 281457796907003
[bt] (4) 4   libmxnet.so                         0x000000010d1c9a51 MXTVMBridge + 8107825
[bt] (5) 5   libmxnet.so                         0x000000010d0670d5 MXTVMBridge + 6655413
[bt] (6) 6   libmxnet.so                         0x000000010d0680ba MXTVMBridge + 6659482
[bt] (7) 7   libmxnet.so                         0x000000010d04ec9f MXTVMBridge + 6556031
[bt] (8) 8   libmxnet.so                         0x000000010c8efa64 MXNDListFree + 714692
[bt] (9) 9   libmxnet.so                         0x000000010c852234 MXNDListFree + 69524
libc++abi.dylib: terminating
```
I want to know can this train  job do by CPU only?

**Comment by zhreshold** [comment]
The answer is Yes, but you won't be able to train successfully on CPU, may cost you a year.

**Comment by pengzhao-intel** [comment]
> The answer is Yes, but you won't be able to train successfully on CPU, may cost you a year.

 Try to use MKL-DNN build.
> pip install mxnet-mkl

**Comment by liben2018** [comment]
Hi, @zhreshold, @pengzhao-intel,
1, Is there any performance difference between mxnet-cuxxmkl and mxnet-cuxx?
2, For the purpose of inference in mxnet-mkl, which one of mxnet-cuxxmkl and mxnet-cuxx do you suggest to use for training?
Thanks!

**Comment by zhreshold** [comment]
@liben2018 
mkl versions run faster on cpu, that's true for any variant with/without cuxx
cuxx actually depend on what cuda driver version you have on your machine. If you have cuda 10, then go for cu100, cuda 9 for cu90, etc...

**Comment by liben2018** [comment]
@zhreshold，
Thanks for your reply!
Actually, I want to confirm 
1, If there is an accuracy loss for mxnet with mkl?
2, if we train a model on GPU, is mxnet-cuxxmkl same with mxnet-cuxx? in other words, mkl just work for CPU?
Thanks!
