### ISSUE TITLE
object detection speed (fps)

### ISSUE THREAD

**Issue by ShoufaChen** [dmlc/gluon-cv#388]
Hi, @zhreshold 

Do you have a plan to provide the object detection speed at the inference phase, like `fps`.
I am not sure how to determine the inference time, e.g.  before nms or not?

**Comment by Angzz** [comment]
I think the inference time should find the final detections, so I think the nms should be included, note that for two stage framework, the anchor generation time should not be included, what I say may be not right, just a reference.

**Comment by zhreshold** [comment]
Checkout https://gluon-cv.mxnet.io/model_zoo/detection.html, it's based on V100 GPU, but you may get some ideas of the FPS

**Comment by FishYuLi** [comment]
Hi, @zhreshold . Do you mean your training and inference are both based on V100 GPUs? I check out your [training log on VOC](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/faster_rcnn_resnet50_v1b_voc_train.log) and [on coco](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/faster_rcnn_resnet101_v1d_coco_train.log), and find that you can get 12sample/s training speed for res101 on 8 GPUs, and also 12 sample/s  for res50 on 4 GPUs. But I can only get 2.6 samples/s for res101 on 4 k40 and 3.6 samples/s for res50 on 4 k40. I wonder if this is a device problem? Or anything goes run with my configurations?

**Comment by zhreshold** [comment]
@FishYuLi Correct, it's GPU's capability. K40 is pretty dwarfed comparing with Volta GPUs.

**Comment by Jerryzcn** [comment]
4- 8 GPU scaling seems pretty bad though? Maybe CPU bounded?

**Comment by ilyunik** [comment]
Извините что по русски, меня кто-нибудь понимает?
Оцените мой сайт [http://videosektor.net/](url)

**Comment by H2Kimcyber** [comment]
Well Hacking whatsapp should be done like instruction please
