### ISSUE TITLE
Can't use gpu to predict with my own YOLOv3 model .

### ISSUE THREAD

**Issue by KevinNuNu** [dmlc/gluon-cv#390]
![image](https://user-images.githubusercontent.com/34083603/46920060-fc92b400-d01a-11e8-90c1-560684544182.png)

set the parameter of model_zoo.get_model(ctx=mx.gpu(0)), but return value "net" still initialized on cpu.

i read the code find that:
the reason is that model_zoo/yolo/yolo3.py  the 503 line, function darknet53() lack a parameter ctx.
beacuse of this,  model_zoo/yolo/darknet.py the 144 line, net.load_parameters() will only use the default ctx=mx.cpu()!

add the parameter like this, it will be work~!
![image](https://user-images.githubusercontent.com/34083603/46920040-b8071880-d01a-11e8-87d1-a3f2758480d6.png)

@zhreshold

**Comment by zhreshold** [comment]
Right, it's a but, but just passing `**kwargs` to darknet53 should be enough.

**Comment by zhreshold** [comment]
Should be fixed with #393
