### ISSUE TITLE
detect speed gpu slow than gpu, why?

### ISSUE THREAD

**Issue by qingzhouzhen** [dmlc/gluon-cv#394]
I test demo_yolo.py on GPU(K80), got about 0.04second/sample, but I test with CPU, got 0.035 second/sample, is than right? why GPU slow than CPU?

**Comment by zhreshold** [comment]
Are you using batch size 1? Also keep in mind that GPU requires warm up, so make sure you reuse the network in a loop to minimize the initialization time with CUDA.
