### ISSUE TITLE
Can't run demo_yolo.py on GPU

### ISSUE THREAD

**Issue by sherylwang** [dmlc/gluon-cv#420]
Hi, I've try to run the provided yolo tutorial. However after I changed 'net = model_zoo.get_model('yolo3_darknet53_voc', pretrained=True)' to  'net = model_zoo.get_model('yolo3_darknet53_voc', pretrained=True, ctx=mx.gpu(0))' 

The error occured : RuntimeError: Parameter 'darknetv30_conv0_weight' was not initialized on context cpu(0). It was only initialized on [gpu(0)].

How to fix it?

**Comment by zhreshold** [comment]
if network is on GPU, input data must be on GPU as well,
so that's 
```
_ = net(x.as_in_context(mx.gpu(0)))
```

**Comment by sherylwang** [comment]
@zhreshold Thanks for your reply.
