### ISSUE TITLE
The training detail about psp net on cityscapes dataset?

### ISSUE THREAD

**Issue by jiangzhengkai** [dmlc/gluon-cv#422]
Hi, Would you share the training details on cityscapes dataset?

**Comment by zhanghang1989** [comment]
training on `trainval` set, `lr=0.01`, `base_size=2048`, `crop_size=768`, `epochs=180`

**Comment by jiangzhengkai** [comment]
Thanks, Can you kindly add log and command link on Gluon CV website?

**Comment by LcDog** [comment]
Hi, the [shell script](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/segmentation/psp_resnet101_city.sh) and [log](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/segmentation/psp_resnet101_city.log) of `psp_resnet101_citys` on this [segmentation doc page](https://gluon-cv.mxnet.io/model_zoo/segmentation.html) does not exist. Could you kindly update the doc page?

**Comment by bryanyzhu** [comment]
The page is updated, we also add ICNet implementation on Cityscapes dataset. Both implementation has higher mIoU than numbers reported in the original paper.
