### ISSUE TITLE
Cannot transfer learning with pretrained model resnet50_v1d or resnet101_v1d

### ISSUE THREAD

**Issue by jiahuanluo** [dmlc/gluon-cv#425]
I follow the transfer learning tutorial **transfer_learning_minc.py**. When I use the default pretrained model    
 Resnet50_v2 in the tutorial code, it works. But when I change the model to resnet50_v1d or resnet101_v1d. It raised the error

usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py:541: UserWarning: Parameter resnetv1b0_dense1_bias, resnetv1b0_dense1_weight is not used by any computation. Is this intended?
  out = self.forward(*args)
Traceback (most recent call last):
  File "transfer_learning_minc.py", line 347, in <module>
    train()
  File "transfer_learning_minc.py", line 313, in train
    trainer.step(batch_size)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/trainer.py", line 273, in step
    self._init_kvstore()
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/trainer.py", line 187, in _init_kvstore
    arg_arrays = {param.name: param.data(self._contexts[0]) for param in self._params}
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/trainer.py", line 187, in <dictcomp>
    arg_arrays = {param.name: param.data(self._contexts[0]) for param in self._params}
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/parameter.py", line 494, in data
    return self._check_and_get(self._data, ctx)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/parameter.py", line 208, in _check_and_get
    "num_features, etc., for network layers."%(self.name))
mxnet.gluon.parameter.DeferredInitializationError: **Parameter 'resnetv1b0_dense1_weight' has not been initialized yet because initialization was deferred.** Actual initialization happens during the first forward pass. Please pass one batch of data through the network before accessing Parameters. You can also avoid deferred initialization by specifying in_units, num_features, etc., for network layers.

Did I forget anything to change or add?
I am new to mxnet and gluoncv.

**Comment by goodtogood** [comment]
same problem. #406

**Comment by hetong007** [comment]
For ResNet-(B,C,D), the `nn.Dense` layer is named as `net.fc` instead of `net.output`:

1. ResNet: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnet.py#L437
2. ResNet-(B,C,D): https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnetv1b.py#L194

Modify your code accordingly will eliminate the error.

**Comment by YusongLeng** [comment]
Hi hetong007,

Thank you so much for your advice! It works!
