### ISSUE TITLE
slow inference speed of yolo3 ?

### ISSUE THREAD

**Issue by nicklhy** [dmlc/gluon-cv#440]
Hi, I just made a benchmark of `yolo3_darknet53_coco` on V100 and Titan V. The inference speed seems to be much slower than the values on this [page](https://gluon-cv.mxnet.io/model_zoo/detection.html#yolo-v3). The results from V100 is like below:
(input size 416)
* batch size = 1, speed = 18.18 samples/s
* batch size = 8, speed = 6.22 samples/s

Any ideas about the strange results above?

------

MXNet was installed as `pip3 install mxnet_cu92-1.3.1b20181004` and gluoncv was also updated to the lasted version with `pip3`.
The test script is like below:
```
import time
import mxnet as mx
from gluoncv import model_zoo

batch_size = 1
n_batch = 1000
size = 416
ctx = mx.gpu(0)

#  get yolo3 with random initialized parameters
net = model_zoo.yolo.yolo3_darknet53_coco(pretrained=False, ctx=ctx)
net.collect_params().initialize(force_reinit=True, ctx=ctx)
net.hybridize()

#  generate random data
x = mx.nd.random_normal(0, 0.1, (batch_size, 3, size, size))
x = x.as_in_context(ctx)

#  warm up gpu
for _ in range(100):
    class_IDs, scores, bounding_boxs = net(x)
    mx.nd.waitall()

t1 = time.time()
for i in range(n_batch):
    class_IDs, scores, bounding_boxs = net(x)
    mx.nd.waitall()
t2 = time.time()
print('Speed = %.2f samples/s' % (n_batch*batch_size/(t2-t1)))
```

**Comment by nicklhy** [comment]
Just figured out the exact reason after profiling the script with nvprof. The randomly initialized network could produce a huge number of boxes with relatively large scores, which made nms extremely slow. Thus, we can not use randomly initialized network when testing speed.

**Comment by liuchangf** [comment]
> Just figured out the exact reason after profiling the script with nvprof. The randomly initialized network could produce a huge number of boxes with relatively large scores, which made nms extremely slow. Thus, we can not use randomly initialized network when testing speed.

hello nicklhy:
         I meet the same issue , can you please share the experience how you speed up  inference ?
Thank you in advance.

**Comment by nicklhy** [comment]
@liuchangf I need to clarify that I didn't do any "speed up" work first.
As I mentioned above, it is in fact a bug if you test the speed of a randomly initialized object detection model. It could produce a large number of relatively high confidence box predictions which then results a very very slow nms at the end. Thus, this kind of benchmark results just make no sense at all.
