### ISSUE TITLE
Strange error in train_psp.py

### ISSUE THREAD

**Issue by Mut1nyJD** [dmlc/gluon-cv#442]
I am seeing some strange error when using train_psp.py using the Pascal VOC trainingset. It all works well until the training loop where it bails out right away at the for loop statement with an exception:

"ValueError: ctypes objects containing pointers cannot be pickled"

I am running Python 3.5.2 / Anaconda 4.1.1

**Comment by AyaMohamedS** [comment]
i have the same problem with ade20k dataset

**Comment by zhanghang1989** [comment]
This seems to be MXNet error. Do you have problem running other code?

**Comment by Mut1nyJD** [comment]
@zhanghang1989  Not sure if this was directed to me in case it was I have not tried any other of the gluon-cv example code so far. I will have a look. In the meantime I wrote my own training example based on fragments of the example code which however is not using the dataloader object though.
