### ISSUE TITLE
train yolo3 error: IndexError: list index out of range

### ISSUE THREAD

**Issue by hjl240** [dmlc/gluon-cv#447]
I use the mxnet-cu80 1.3.0 and gluoncv 0.3.0.
and I train yolo3 with coco got this error, need your help.
Thank you!

> loading annotations into memory...
> Done (t=1.09s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=0.49s)
> creating index...
> index created!
> loading annotations into memory...
> Done (t=0.24s)
> creating index...
> index created!
> INFO:root:Namespace(batch_size=8, data_shape=608, dataset='coco', epochs=280, gpus='0', label_smooth=True, log_interval=100, lr=0.0001, lr_decay=0.1, lr_decay_epoch='220,250', lr_decay_period=0, lr_mode='step', mixup=True, momentum=0.9, network='darknet53', no_mixup_epochs=20, no_random_shape=False, no_wd=True, num_samples=32663, num_workers=4, resume='', save_interval=10, save_prefix='yolo3_darknet53_coco', seed=233, start_epoch=0, syncbn=True, val_interval=1, warmup_epochs=2, warmup_lr=0.0, wd=0.0005)
> INFO:root:Start training from [Epoch 0]
> INFO:root:[Epoch 0][Batch 99], LR: 1.21E-06, Speed: 5.276 samples/sec, ObjLoss=2796.465, BoxCenterLoss=4.861, BoxScaleLoss=4.548, ClassLoss=103.186
> INFO:root:[Epoch 0][Batch 199], LR: 2.44E-06, Speed: 3.689 samples/sec, ObjLoss=1478.990, BoxCenterLoss=4.814, BoxScaleLoss=4.272, ClassLoss=100.925
> INFO:root:[Epoch 0][Batch 299], LR: 3.66E-06, Speed: 7.585 samples/sec, ObjLoss=1003.068, BoxCenterLoss=4.686, BoxScaleLoss=3.982, ClassLoss=97.406
> (...)
> INFO:root:[Epoch 0][Batch 3899], LR: 4.78E-05, Speed: 5.101 samples/sec, ObjLoss=87.983, BoxCenterLoss=4.207, BoxScaleLoss=2.155, ClassLoss=29.097
> INFO:root:[Epoch 0][Batch 3999], LR: 4.90E-05, Speed: 3.744 samples/sec, ObjLoss=85.984, BoxCenterLoss=4.199, BoxScaleLoss=2.135, ClassLoss=28.602
> INFO:root:[Epoch 0] Training cost: 5043.459, ObjLoss=84.422, BoxCenterLoss=4.194, BoxScaleLoss=2.121, ClassLoss=28.213
> Loading and preparing results...
> Traceback (most recent call last):
>   File "train_yolo3.py", line 396, in <module>
>     train(net, train_data, val_data, eval_metric, ctx, args)
>   File "train_yolo3.py", line 353, in train
>     map_name, mean_ap = validate(net, val_data, ctx, eval_metric)
>   File "train_yolo3.py", line 241, in validate
>     return eval_metric.get()
>   File "/home/xxx/anaconda3/lib/python3.6/site-packages/gluoncv/utils/metrics/coco_detection.py", line 116, in get
>     coco_eval = self._update()
>   File "/home/xxx/anaconda3/lib/python3.6/site-packages/gluoncv/utils/metrics/coco_detection.py", line 94, in _update
>     pred = self.dataset.coco.loadRes(self._filename)
>   File "/home/xxx/.local/lib/python3.6/site-packages/pycocotools/coco.py", line 318, in loadRes
>     if 'caption' in anns[0]:
> IndexError: list index out of range

**Comment by zhreshold** [comment]
Looks like a error trying to load validation coco annotations. Can you confirm validation dataset is properly downloaded and extracted in ~/.mxnet/datasets/coco ?

**Comment by chinagaodali** [comment]
I have also met this situation. And i found  is occurs when self._filename just contaions a empty list ,this means that during  evaluation,the result of  `ids, scores, bboxes = net(x)` have no valid detections,all  element of `ids` is -1. But I don't konw why,have you solved this problem?

**Comment by zhreshold** [comment]
"When you network is totally ruined, e.g. nan occurred somehow, the evaluation results will be empty.
I've updated the master already, when this happens, the validation will return 0 map instead. "

You can update to master or nightly build if this happens, but be sure the root cause is the training not the validation.

**Comment by chinagaodali** [comment]
> "When you network is totally ruined, e.g. nan occurred somehow, the evaluation results will be empty.
> I've updated the master already, when this happens, the validation will return 0 map instead. "
> 
> You can update to master or nightly build if this happens, but be sure the root cause is the training not the validation.

Thanks a lot!
