### ISSUE TITLE
variable name？

### ISSUE THREAD

**Issue by ACkuku** [dmlc/gluon-cv#450]
https://github.com/dmlc/gluon-cv/blob/ee82838fbc32523a572f812d857931672361860a/gluoncv/data/transforms/presets/yolo.py#L195
`self._target_generator` returns `objectness, center_targets, scale_targets, weights, class_targets`,
so the order of this variables name should be `objectness, center_targets, scale_targets, weights, class_targets`, not `center_targets, scale_targets, weights, objectness, class_targets`, @zhreshold  right?

**Comment by zhreshold** [comment]
Good catch. The names are mismatched with the order, thankfully they do not affect the way these values being consumed. @ACkuku Would you like to submit a small PR to fix it?

**Comment by ACkuku** [comment]
yes, https://github.com/dmlc/gluon-cv/pull/461

**Comment by zhreshold** [comment]
Thanks, it's merged.
