### ISSUE TITLE
FTN: The Next Generation Network Design Choice For Two Stages Based Network

### ISSUE THREAD

**Issue by xmyqsh** [dmlc/gluon-cv#451]
Recently, [mmdetection](https://github.com/open-mmlab/mmdetection) and [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) announced they have largely speeded up the training speed on MaskRCNN by implementing it by the Fully Tensor Network(FTN).
It enables all of the operations, including proposal and proposal target layer operations, expressing by tensors, being part of the computational graph, benefiting from the graph optimization and running on GPUs.
FTN is a good design choice. All of the CV tasks will benefit from FTN as long as they are based on the two stages based network.
FTN should also speed up inference more or less.

Will gluon-cv plan to support FTN?

**Comment by zhreshold** [comment]
Thanks, we will take a look.
