### ISSUE TITLE
Has anyone tried to trian faster r-cnn with resnet50_v1d or else?

### ISSUE THREAD

**Issue by WalterMa** [dmlc/gluon-cv#452]
In this PR https://github.com/dmlc/gluon-cv/pull/355 ,
faster rcnn with resnet101 is updated to v1d.

Because it takes me about 3 days to train faster rcnn with resnet 50 🤣 
**Want to know has anyone tried to trian faster r-cnn with resnet50_v1d or else?
Will it be better than resnet50_v1b?**

**Comment by hetong007** [comment]
resnet50_v1d is expected to be better than resnet50_v1b when used as backbone.

**Comment by Angzz** [comment]
I tried faster-rcnn with fpn backbone on resnet101_v1d, and it achieves 83.01% mAP on VOC2007, I think it will benefit more with coco.

**Comment by Angzz** [comment]
I tried faster rcnn with fpn backbone on resnet101_v1d, it achieves 83.01% mAP on VOC2007, I think it will benefit more with COCO.

**Comment by summerZXH** [comment]
> I tried faster rcnn with fpn backbone on resnet101_v1d, it achieves 83.01% mAP on VOC2007, I think it will benefit more with COCO.

hi, do you use the mixup to train in faster?

**Comment by WalterMa** [comment]
Refer to PR https://github.com/dmlc/gluon-cv/pull/634,
now we have FRCNN with resnet50_v1d, thanks for the community's great work.
