### ISSUE TITLE
how to get params and json files?

### ISSUE THREAD

**Issue by yhl41001** [dmlc/gluon-cv#454]
I have compiled the mxnet c++ interface, and the detect.cpp file, but demo does not show how to get yolo3_darknet53_voc-0000.params and yolo3_darknet53-symbol.json.
why does not offer the file urls? I do not understand!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@pluskid @mli

**Comment by yhl41001** [comment]
I have compiled the mxnet c++ interface, and the detect.cpp file, but demo does not show how to get yolo3_darknet53_voc-0000.params and yolo3_darknet53-symbol.json.
why does not offer the file urls? I do not understand!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Angzz** [comment]
Calm down and drink a cup of coffe!
Please try:

```
from gluoncv.model_zoo import get_model
import mxnet as mx

net = get_model("yolo3_darknet53_voc", pretrained=True)
net.hybridize()
x = mx.nd.random.normal(shape=(1, 3, 416, 416))
out = net(x)
net.export("yolo3_darknet53_voc")
```
