### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer When train model

### ISSUE THREAD

**Issue by dmxj** [dmlc/gluon-cv#455]
When I run the train, the following error occurs:
![image](https://user-images.githubusercontent.com/6835981/47995927-de0f6c80-e131-11e8-83b3-73f1c69a5fb7.png)
my train command is :
python train_faster_rcnn.py --gpus 0,1 --network resnet50_v1b，and it from:
[Train Faster-RCNN end-to-end on PASCAL VOC](https://gluon-cv.mxnet.io/build/examples_detection/train_faster_rcnn_voc.html)
my environment is configured as follows::
![image](https://user-images.githubusercontent.com/6835981/47996113-6aba2a80-e132-11e8-94fc-231277001ab7.png)
and This is in the docker container.

**Comment by zhreshold** [comment]
with docker, please add --shm-size=4g when launching, it will allow shared memory to be used be multi workers.

**Comment by zhreshold** [comment]
@dmxj If you cannot enable shared memory in docker, you have to disable multi workers by setting ``-j=0`` , this may however slow down the training because CPU may be the bottleneck.
