### ISSUE TITLE
Training is too slow when set -j to 4 in ssd training

### ISSUE THREAD

**Issue by chinakook** [dmlc/gluon-cv#458]
When set -j to 0, It's has 1.281samples/sec on 2080ti when training with ssd_mobilenet1.0_512.
When set -j to 4, It's more slower.

**Comment by zhreshold** [comment]
Main process may use up to 8 threads when ndarray is processed. 

where the extra workers can only use one thread. This is to avoid thread contention.

**Comment by chinakook** [comment]
If I build mxnet with mkl(not mkldnn), It's slower. However, If I build mxnet with openblas, It's normal. So I think that's some **op** bug when buiding with mkl blas. In both test, I comment out the training and metric code with only dataloader code left.

**Comment by chinakook** [comment]
There is a new problem. The training will be probably stuck in the progress.

**Comment by chinakook** [comment]
It's also too slow when building mxnet whit openblas on some other machine. :-(

**Comment by zhreshold** [comment]
@chinakook  Hmm, yes I agree that the mp is still not a perfect way to handle IO, it has lots of constraints to the shared mem and so on. BTW, why don't you download mxnet from PYPI?

**Comment by chinakook** [comment]
@zhreshold Mxnet-cu100 is not released, but 2080Ti only run on cuda 10.0

**Comment by ZengyuanYu** [comment]
@zhreshold  Now I train SSD on my own data, when size=4032X3024 speed is  0.829 samples/sec, and when size=400X300 speed is 11.588. My GPU  is Titan Xp 12G, install `pip install mxnet-cu90`

**Comment by yanghaojin** [comment]
I got a similar problem, it would be helpful if I set USE_OPENMP=OFF while compiling the project.
