### ISSUE TITLE
why i use the example code and pretrained model on my own test image, the result is very bad?

### ISSUE THREAD

**Issue by mlinxiang** [dmlc/gluon-cv#459]
1070 gpu
mxnet-cu90 1.3.0.post0
gluoncv 0.3.0
use code download from docs as  demo_***.py 
input image 
![image](https://user-images.githubusercontent.com/6283983/48181462-87d54000-e362-11e8-9ae5-b3b4e3cb9b24.png)
 
yolo v3 512 result
![image](https://user-images.githubusercontent.com/6283983/48181488-928fd500-e362-11e8-890a-3330f6969ba3.png)

faster rcnn result:
![image](https://user-images.githubusercontent.com/6283983/48181508-adfae000-e362-11e8-98ed-ce8ed0092d18.png)

**Comment by zhreshold** [comment]
You may expect better results when similar categories are in the training dataset. For example, there's no keyboard class in voc.

**Comment by mlinxiang** [comment]
coco pretrain

**Comment by mlinxiang** [comment]
i make some mistake on modify the pretrained model path of coco
