### ISSUE TITLE
the speed of training mobilenetv2_1.0 is quite slow

### ISSUE THREAD

**Issue by sherylwang** [dmlc/gluon-cv#465]
Hi!  I've tried to reproduce the training of mobilenetv2_1.0 according to the provided shell in the gluoncv classification model zoo. 
However, I found  the training of mobilenetv2_1.0 is quite slow. The log shows only 80 samples per sec is tackled.  But for resnet50, around 2300 samples per sec is tackled in the same server.
My server has 8 P40 cards, cuda version is 8.0 with cudnn7.0. I've already transformed the data in mxnet record format.

**Comment by chinakook** [comment]
Using cuda9.2 can solve this problem, cuda 8 cannot accelerate depthwise conv.

**Comment by sherylwang** [comment]
@chinakook  Thanks for reply. After I switched the cuda from 8.0 to 9.0, the training became faster. But I noted  pytorch0.3.1 supportss depthwise conv better even with cuda8.0, much faster than mxnet1.3.0

**Comment by sherylwang** [comment]
After I disabled "export MXNET_CUDNN_AUTOTUNE_DEFAULT=0", the  speed is about 2300 samples per sec now. I guess the implement of depthwise conv in MXNet is much better than the version provided by the cudnn

**Comment by chinakook** [comment]
That only close autotune but not cudnn.
