### ISSUE TITLE
How to get accuracy metric on eval dataset while finetuning an object detection model?

### ISSUE THREAD

**Issue by wegel** [dmlc/gluon-cv#469]
Following https://gluon-cv.mxnet.io/build/examples_detection/finetune_detection.html to finetune an object detection model (currently using ssd_512_resnet50_v1_coco) with a custom dataset (mxnet RecordIO format) having 12 classes and ~7000 images.

How would I go about evaluating current accuracy while training? This is touched upon in the Image Classification tutorial [here](https://gluon-cv.mxnet.io/build/examples_classification/transfer_learning_minc.html#model-and-trainer), but there don't seem to be an equivalent for Object Detection in the examples. Thanks!

**Comment by wegel** [comment]
I was able to run a validation loop after each epoch using a modified [test_ssd.py](https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/ssd/train_ssd.py). However, I'm using VOC07MApMetric so it doesn't provide IoU metrics. I think the COCODetectionMetric would do what I want, but it needs a gluoncv.data.COCODetection dataset as input, and I have a plain RecordFileDetection dataset. Any idea how to get the Coco metrics (or equivalent) from a RecordFileDetection dataset?

**Comment by boardthatpowder** [comment]
@wegel did you find a workaround/solution for this?  I have the same problem, tried using the `VOC07MApMetric` and `VOCMApMetric` classes but run into a `ValueError: zero-dimensional arrays cannot be concatenated` error so wondering if I'm meant to implement my own `mx.metric.EvalMetric` class?

**Comment by ivanquirino** [comment]
@wegel @boardthatpowder I have the same problem, I am trying to train a custom dataset, but I'm unsure if I can use VOC or COCO metris, or if I should do my own.

**Comment by LewsTherin511** [comment]
@wegel , having your same issue as well.

**Comment by LauLauThom** [comment]
For those coming across this issue, I have started trying to put up an eval metric, to be able to use [train_ssd.py](https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/ssd/train_ssd.py) functions with custom dataset as record file.
It is not functional yet, and I kind of shifted towards converting my dataset to VOC instead, but in case this can be useful to someone :P

**Comment by JustinhoCHN** [comment]
Hi, you can just use the ```VOC07MApMetric``` as your custom metric, just change the classes. For example, my dataset have only one class "person":
```
classes = ['person']
val_metric = VOC07MApMetric(iou_thresh=0.5, class_names=classes)
```
