### ISSUE TITLE
Splitting a RecordFileDetection for training and evaluation at runtime

### ISSUE THREAD

**Issue by wegel** [dmlc/gluon-cv#472]
I would prefer having a single RecordFileDetection file containing all my entries and then dynamically splitting it at runtime between training and evaluation sets, rather than doing so manually. Any idea how to achieve that?

**Comment by WalterMa** [comment]
I would suggest you to inherit `RecordFileDetection` class,  provide you split posistion at `__init__()` methods.

Then override the `__len__()` function in the base class: `RecordFileDataset`:
https://github.com/apache/incubator-mxnet/blob/52116d4d3205361f861141013eb0de40be003e3c/python/mxnet/gluon/data/dataset.py#L165
