### ISSUE TITLE
可扩展性差, 一堆bug,SSD可变输入尺寸效果还是一样差劲, 尽管没有mxnet ssd明显的bug

### ISSUE THREAD

**Issue by ElegantGod** [dmlc/gluon-cv#473]

**Comment by wait1988** [comment]
好多东西写得很死。。

**Comment by ElegantGod** [comment]
1. 在检测的任务中, 加载的数据集需要判断下每个图像的label是不是为空,然后返回不为空的item和label, 如果我的检测目标类只有一类,是不是很多图像的label都是空的? 运行到后面就是报错.
2. 在SSD检测中, 虽然很好的复现了原作者提供的参数, 尤其在anchor的size设置上,做的很完美, assert len(sizes) == num_layers + 1,  sizes = list(zip(sizes[:-1], sizes[1:])), 哇,写的很漂亮, 你考虑过如果我每个anchor设置多个min_size呢,或者没有max_size呢, 可不可以不要耍小聪明,就把作者原始的caffe代码抄过来, mxnet里的ssd写的更没法用.

**Comment by ElegantGod** [comment]
只为了僵硬的复现论文效果,不考虑用户体验...,哎

**Comment by wait1988** [comment]
只训练了自己标注的一个数据集(训练中)，今天上午还在想如果只训练VOC2007里面的一类会不会出问题。。。

**Comment by ElegantGod** [comment]
@wait1988 以voc为例,在VOCDetection的构造函数里对item和label过滤下空的label,就可以了, 你是用哪个检测方法

**Comment by WalterMa** [comment]
Please use English!
And I don't think github issue is a good place to complain.

**Comment by zhanghang1989** [comment]
Please point out specific bugs and provide the code to reproduce. The community will fix that.

**Comment by JackwithWilshere** [comment]
@WalterMa Maybe only complain could be seen of you all.Please have a look at my problem,thanks!
https://github.com/dmlc/gluon-cv/issues/471

**Comment by WalterMa** [comment]
@JackwithWilshere 
I'm not fammilar with segmentation.
But as for me, I'll try to disable hybirdize mode, then figure out which input cause the error.

**Comment by JackwithWilshere** [comment]
@WalterMa Thanks,I'll try it.

**Comment by ElegantGod** [comment]
按照原始caffe-ssd改了下,anchor可以支持多个min_size,和空的max_size, anchor的长度为min_size的数量*ratios的数量+max_size的数量, max_size可以为0或者1个, 验证过没问题
[anchor.py](https://github.com/ElegantGod/gluon-cv-myself/blob/master/gluoncv/model_zoo/ssd/anchor.py)
```
def _generate_anchors(self, sizes, ratios, step, alloc_size, offsets):
        """Generate anchors for once. Anchors are stored with (center_x, center_y, w, h) format."""
        min_size_len = len(sizes[0])
        assert len(sizes[1]) < 2, 'max_size number of anchor should 0 or 1'
        assert ratios[0] == 1, 'first ratio should be 1'
        anchors = []
        for i in range(alloc_size[0]):
            for j in range(alloc_size[1]):
                for min_size in sizes[0]:
                    cy = (i + offsets[0]) * step
                    cx = (j + offsets[1]) * step
                    # ratio = ratios[0], size = size_min or sqrt(size_min * size_max)
                    r = ratios[0]
                    anchors.append([cx, cy, min_size, min_size])
                    # size = sizes[0], ratio = ...
                    if sizes[1]:
                        max_size = np.sqrt(min_size*sizes[1][0])
                        cy = (i + offsets[0]) * step
                        cx = (j + offsets[1]) * step
                        # ratio = ratios[0], size = size_min or sqrt(size_min * size_max)
                        anchors.append([cx, cy, max_size, max_size])
                    for r in ratios:
                        if np.fabs(r-1) < 1e-6:
                            continue
                        sr = np.sqrt(r)
                        w = min_size * sr
                        h = min_size / sr
                        anchors.append([cx, cy, w, h])

        return np.array(anchors).reshape(1, 1, alloc_size[0], alloc_size[1], -1)
```

**Comment by mli** [comment]
@ElegantGod 多谢提供建议，加个微信聊下？我id: cmumuli
