### ISSUE TITLE
Failed to build mxnet cpp package

### ISSUE THREAD

**Issue by wait1988** [dmlc/gluon-cv#474]
When I compile mxnet cpp package following the tutorial in the readme file,the libmxnet.a and libmxnet.so can generate successfully,but  failed in running the script "python OpWrapperGenerator.py",
the error info is as follows:
OSError: ~/incubator-mxnet/lib/libmxnet.so: undefined symbol: _ZN5mxnet2op8CreateOpIN7mshadow3gpuEEEPNS_8OperatorENS0_17InstanceNormParamEi

Anyone knows how to solve it?

**Comment by zhreshold** [comment]
You need to build mxnet with `USE_CPP_PACKAGE=1` to enable c++ interface.

**Comment by wait1988** [comment]
I chang the option choices in the config file,it works.
