### ISSUE TITLE
How to change the output classses?

### ISSUE THREAD

**Issue by Jessespace** [dmlc/gluon-cv#475]
When I change the output number of classes, I got an error.

`net= model_zoo.get_model(net_name, pretrained_base=False,classes=2)`

I got this error:
`TypeError: get_ssd() got multiple values for keyword argument ‘classes’`

Why? And how to change the classes to 2 ?

**Comment by Jessespace** [comment]
gluoncv version:0.4.0
mxnet version:1.3.1

**Comment by ewinterrms** [comment]
2 shouldn't be the correct type...check the API or check out the example (I
think it uses net.classes)

Erickson Winter

CTO

Red Mountain Scientific

**Comment by WalterMa** [comment]
A better way is to write a specific dataset class for your input data which can handle num_class and each class name.
Following this [turitoal](https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html#sphx-glr-build-examples-datasets-detection-custom-py).

Then provide your dataset in the corrsponding script.
For ssd, you could change the `get_dataset()` function in:
https://github.com/dmlc/gluon-cv/blob/aff5c36c0a1985350d32b766df5644e5648f4d13/scripts/detection/ssd/train_ssd.py#L69

**Comment by Jessespace** [comment]
This is the `get_model` function:

def get_model(name, **kwargs):
    """Returns a pre-defined model by name

    Parameters
    ----------
    name : str
        Name of the model.
    pretrained : bool or str
        Boolean value controls whether to load the default pretrained weights for model.
        String value represents the hashtag for a certain version of pretrained weights.
    **classes : int**
        Number of classes for the output layer.
    ctx : Context, default CPU
        The context in which to load the pretrained weights.
    root : str, default '~/.mxnet/models'
        Location for keeping the model parameters.

    Returns
    -------
    HybridBlock
        The model.
    """
    name = name.lower()
    if name not in _models:
        err_str = '"%s" is not among the following model list:\n\t' % (name)
        err_str += '%s' % ('\n\t'.join(sorted(_models.keys())))
        raise ValueError(err_str)
    net = _models[name](**kwargs)
    return net

**This function shows that classes should be int,but actually,it calls ssd_512_resnet18_v1_voc through net = _models[name](**kwargs),and this is ssd_512_resnet18_v1_voc:**

def ssd_512_resnet18_v1_voc(pretrained=False, pretrained_base=True, classes=None,**kwargs):
    `classes = VOCDetection.CLASSES`
    return get_ssd('resnet18_v1', 512,
                   features=['stage3_activation1', 'stage4_activation1'],
                   filters=[512, 512, 256, 256],
                   sizes=[51.2, 102.4, 189.4, 276.4, 363.52, 450.6, 492],
                   ratios=[[1, 2, 0.5]] + [[1, 2, 0.5, 3, 1.0/3]] * 3 + [[1, 2, 0.5]] * 2,
                   steps=[16, 32, 64, 128, 256, 512],
                   classes=classes, dataset='voc', pretrained=pretrained,
                   pretrained_base=pretrained_base, **kwargs)

So,actully the output classes is assigned by  VOCDetection.CLASSES 
and get_ssd need a str type not int type,
Why should design like that ?It is a bug? And How to confirm the output classes is 2 ?

**Comment by Jessespace** [comment]
> A better way is to write a specific dataset class for your input data which can handle num_class and each class name.
> Following this [turitoal](https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html#sphx-glr-build-examples-datasets-detection-custom-py).
> 
> Then provide your dataset in the corrsponding script.
> For ssd, you could change the `get_dataset()` function in:
> 
> [gluon-cv/scripts/detection/ssd/train_ssd.py](https://github.com/dmlc/gluon-cv/blob/aff5c36c0a1985350d32b766df5644e5648f4d13/scripts/detection/ssd/train_ssd.py#L69)
> 
> Line 69 in [aff5c36](/dmlc/gluon-cv/commit/aff5c36c0a1985350d32b766df5644e5648f4d13)
>  def get_dataset(dataset, args):

I overwrite the VOCDetection following the gluoncv demo,something like this .

class VOCLike(gdata.VOCDetection):
    CLASSES = ['normal', 'defect']

    def __init__(self, root, splits, transform=None, index_map=None, preload_label=True):
        super(VOCLike, self).__init__(root, splits, transform, index_map, preload_label)

**Comment by WalterMa** [comment]
Use the custom model insted.
https://github.com/dmlc/gluon-cv/blob/aff5c36c0a1985350d32b766df5644e5648f4d13/gluoncv/model_zoo/ssd/ssd.py#L535

**Comment by JackwithWilshere** [comment]
https://github.com/dmlc/gluon-cv/blob/aff5c36c0a1985350d32b766df5644e5648f4d13/gluoncv/data/pascal_voc/detection.py#L43

**Comment by WalterMa** [comment]
Set `pretrained_base=True`
