### ISSUE TITLE
[WIP] Mask-RCNN inference goes out of GPU memory

### ISSUE THREAD

**Issue by Eric-Zhang1990** [dmlc/gluon-cv#476]
@zhreshold @kuonangzhe  
       When I run mask-rcnn inference, it shows an error about GPU memory, how can I solve this problem now?  
      This is related to issue #343.
      My computer info:
      Ubuntu 16.04
      GPU: 2 GTX 1070, 8G memory.

Thanks a lot.

**Comment by Eric-Zhang1990** [comment]
No one can give an answer to this problem???

**Comment by kuonangzhe** [comment]
Could you mind adding more detailed log or terminal print to help analyze problem? @Eric-Zhang1990

**Comment by Eric-Zhang1990** [comment]
@kuonangzhe  The problem is same as #343, could you find some ways to deal with it?
Thanks a lot.

**Comment by zhreshold** [comment]
This is a duplicate of #343, I am closing this. Feel free to discuss in the original thread.
