### ISSUE TITLE
"Transfer Learning with Your Own Image Dataset tutorial" does not work for multi-GPU

### ISSUE THREAD

**Issue by FuzesiMate** [dmlc/gluon-cv#487]
The script of the tutorial (https://gluon-cv.mxnet.io/build/examples_classification/transfer_learning_minc.html#sphx-glr-build-examples-classification-transfer-learning-minc-py) gets stuck when trying to train with two GPU-s (YOLO3 training works fine on dual GPU). The "trainer.step(batch_size)" method gets stuck with 64Gb of virtual memory usage and 100% CPU usage with local kvstore. 

Inside the trainer the "_allreduce_grads" method runs for a while, then holds forever.

**Comment by FuzesiMate** [comment]
I tried to reduce the batch size to 8 and num_workers to 2. The issue still persists, when I try to stop the process it causes a system crash.

**Comment by zhreshold** [comment]
I guess you might want a threading version rather than a multiprocessing dataloader because it eats shared memory. Try update mxnet to latest nightly build and allow `thread_pool=True` for those dataloaders.
