### ISSUE TITLE
Issue with deeplab_resnet101_coco model

### ISSUE THREAD

**Issue by gmalivenko** [dmlc/gluon-cv#492]
Hello there!

This issue is related to Symbol API that I use to get a model graph. When I apply it to the `deeplab_resnet101_coco` (and any other DeepLab-based model), I get this error:

```
  File "/home/nero/Files/Workspace/env/lib/python3.6/site-packages/gluoncv/model_zoo/deeplabv3.py", line 107, in hybrid_forward
    _, _, h, w = x.shape
AttributeError: 'Symbol' object has no attribute 'shape'
```

**Comment by GYZHikari** [comment]
I have the same issue.

**Comment by Jerryzcn** [comment]
This is due to deeplab not implemented in static graph.
