### ISSUE TITLE
_recursive_fork_recordio could slow down the dataloader quite a bit

### ISSUE THREAD

**Issue by YutingZhang** [dmlc/gluon-cv#496]
https://github.com/dmlc/gluon-cv/blob/48ea65f2570eafc71f9c48a697c4419604b89f21/gluoncv/data/dataloader.py#L132-L143

Recent updates of gluoncv dataloader includes a function called `_recursive_fork_recordio` to better handle RecordIO. It recursively search the whole structure of a dataset object to look for RecordIO. This can slow down the startup of random_worker_loop quite a bit if the dataset has a complicated structure. Especially if loopy reference exists, e.g., `a = ... ; a.ptr=a`, the function can be trapped in an virtually infinite recursion until hit the maximum number of recursions.

I am using a dataset implement by myself (not the gluon dataset). This function slows down the startup of a dataloader iter by > 10min ...

**Comment by YutingZhang** [comment]
>  Especially if loopy reference exists, e.g., `a = ... ; a.ptr=a`, the function can be trapped in an virtually infinite recursion until hit the maximum number of recursions.

Submitted a pull request for fixing this: https://github.com/dmlc/gluon-cv/pull/497

**Comment by zhreshold** [comment]
With #495 you can ignore this
