### ISSUE TITLE
 Assertion `pred_hnd' failed

### ISSUE THREAD

**Issue by wait1988** [dmlc/gluon-cv#499]
// Create Predictor
    MXPredCreate((const char*)json_data.GetBuffer(),
                 (const char*)param_data.GetBuffer(),
                 static_cast<size_t>(param_data.GetLength()),
                 dev_type, dev_id, num_input_nodes, input_keys, input_shape_indptr, input_shape_data, &pred_hnd);
    assert(pred_hnd);

The model is exported from yolov3 following the offical tutorial and works fine with gluon_detect.
@zhreshold

**Comment by wait1988** [comment]
I use c++ version instead.

**Comment by SOWENKIN** [comment]
Meet the same problem, have you solved it?

**Comment by zhreshold** [comment]
See https://github.com/dmlc/gluon-cv/issues/564
