### ISSUE TITLE
Stack can not work  in docker

### ISSUE THREAD

**Issue by likangGit** [dmlc/gluon-cv#504]
#### environment:
gluoncv:0.3.0
mxnet:cu80 1.3.0
#### issue
I am trying to train mobilenet ssd. And Dataloader was used like this:
```
batchify_fn = Tuple(Stack(), Stack(), Stack(), Stack(), Stack(), Stack())
train_dataset = gluon.data.DataLoader(dataset, batch_size=16, batchify_fn=batchify_fn, last_batch='keep', num_workers=6)
```
that can work on my physical host. But when I run this code in docker, the problem has happened.
Two line code was added in the end of "gluoncv/data/batchify.py":
```
        print("test 0:",len(self._fn))
        for i, ele_fn in enumerate(self._fn):
            ret.append(ele_fn([ele[i] for ele in data]))
        print("test 1")
        return tuple(ret)
```
the console will print message likes the follows:
```
test 0: 3
test 1
test 0: 3
test 1
test 0: 3
test 1
test 0: 3
test 1
test 0: 3
test 0: 3
```
as we can see, this code will block here. I edit line 129 of "gluoncv/data/batchify.py":
```
# return _stack_arrs(data, True)
return _stack_arrs(data, False)
```
then the program block in line 170 of "gluon/data/dataloader.py":
```
def worker_loop(.....):
    ........
    data_queue.put((idx, batch))

**Comment by zhreshold** [comment]
Allow some --shm-size when you launch the docker container

**Comment by likangGit** [comment]
@zhreshold  yes ,it can work. --shm-size="2g" thanks!!
