### ISSUE TITLE
where to find F.contrib.SoftmaxOHEMOutput

### ISSUE THREAD

**Issue by hphp** [dmlc/gluon-cv#505]
Hi, gluon-cv is always very powerful !
Since I find FocalLoss and OHEMLoss had built in gluon-cv.loss, I cant find F.contrib.SoftmaxOHEMOutput.
If anyone could give me some clues.

**Comment by hetong007** [comment]
@zhanghang1989 could you help?

**Comment by hphp** [comment]
I get it. Thank u all very much!

**Comment by wsqshiqing** [comment]
@zhanghang1989 I still cannot find F.contrib.SoftmaxOHEMOutput, has the code  been merged?
