### ISSUE TITLE
train_ssd.py the speed is so slow

### ISSUE THREAD

**Issue by ZengyuanYu** [dmlc/gluon-cv#506]
My envs:
Ubuntu16.04 TitanXp 12G  python3.6  mxnet-cu90 1.3.1 
When I run the `train_ssd.py`:
```
python train_ssd.py --batch-size 32 --gpus 1 --num-workers 0 --log-interval 1
```
and the result display as follow:
```
INFO:root:Namespace(batch_size=32, data_shape=300, dataset='voc', epochs=240, gpus='1', log_interval=1, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,200', momentum=0.9, network='vgg16_atrous', num_workers=0, resume='', save_interval=10, save_prefix='ssd_300_vgg16_atrous_voc', seed=233, start_epoch=0, val_interval=1, wd=0.0005)
INFO:root:Start training from [Epoch 0]
[15:53:37] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:[Epoch 0][Batch 0], Speed: 0.624 samples/sec, CrossEntropy=18.200, SmoothL1=8.746
INFO:root:[Epoch 0][Batch 1], Speed: 0.829 samples/sec, CrossEntropy=17.222, SmoothL1=8.626
INFO:root:[Epoch 0][Batch 2], Speed: 0.574 samples/sec, CrossEntropy=16.040, SmoothL1=9.400
INFO:root:[Epoch 0][Batch 3], Speed: 0.740 samples/sec, CrossEntropy=14.938, SmoothL1=9.214
```
My dataset include 267 images and size 4032X3024 about iphone photo. When traning the GPU 7368M / 12212M power 19 W / 250 W compute 0% 

Now I change the data to size 400X300, the train result as follow:
```
INFO:root:[Epoch 18][Batch 0], Speed: 11.588 samples/sec, CrossEntropy=2.514, SmoothL1=3.203
INFO:root:[Epoch 18][Batch 1], Speed: 11.505 samples/sec, CrossEntropy=2.496, SmoothL1=2.903
INFO:root:[Epoch 18][Batch 2], Speed: 11.324 samples/sec, CrossEntropy=2.496, SmoothL1=2.807
INFO:root:[Epoch 18][Batch 3], Speed: 12.029 samples/sec, CrossEntropy=2.473, SmoothL1=2.665
INFO:root:[Epoch 18][Batch 4], Speed: 10.028 samples/sec, CrossEntropy=2.488, SmoothL1=2.634
INFO:root:[Epoch 18] Training cost: 14.221, CrossEntropy=2.488, SmoothL1=2.634
INFO:root:[Epoch 18] Validation:
plate=0.872363408948775
light=0.6636734672556694
car=0.7934994550149087
window=0.5658644307525381
mAP=0.7238501904929727
```
And Now GPU 7946M Power 230W Compute 80%+.
So the images size   important but the speed is more fatser, as 1080 speed to 50 samples/sec. What shoud I do and change it more faster?

**Comment by ZengyuanYu** [comment]
@piiswrong @pluskid @mli Can you tell me how to do it？

**Comment by zhreshold** [comment]
let --num-workers be you cpu cores

**Comment by ZengyuanYu** [comment]
@zhreshold Thank you, it worked for me but I do this compare:

| num-workers | Training cost / epoch size 400X300 | Training cost /epoch size 4032X3024 |
| :------: | :------: | :------: |
| 0 | 31.629 Speed: 9.123 samples/sec | 454.491  Speed: 0.408 samples/sec |
| 4 | 118.637  Speed: 34.339 samples/sec |  466.331  Speed: 34.671 samples/sec |
| 40 | 230  Speed: 34.618 samples/sec |  452.375 34.842 samples/sec |

So I use more cores and cost more time in size 400X300, but size 4032X3024 the cost is the same. How to solve it or it is corret?

**Comment by zhreshold** [comment]
You can try update mxnet (pip install mxnet-cu90 --pre --upgrade) and re-run the benchmark, the number is not reasonable IMO.

**Comment by bloatybo** [comment]
@ZengyuanYu Hi did you solve this issue. I met the exact same issue as yours when training yolov3 using gluoncv. If you solved it can you post your solution? Thanks!

**Comment by ShoufaChen** [comment]
hi, @ZengyuanYu @bloatybo 

Any suggestion? I met the same problem when training yolov3 using gluoncv.
Thank you
