### ISSUE TITLE
How to use a trained params to inference?

### ISSUE THREAD

**Issue by ZengyuanYu** [dmlc/gluon-cv#507]
Hi, I am a new one and Today use Mxnet trained a SSD model for 4 class, Now I have `ssd_300_vgg16_atrous_voc_best.params` etc，How to load it and inference an image or webcame?
Though some issue I am coding like this but no work, How to change it? Thank you.If you think this question too fool please forgive me! Good Day!

```
import mxnet as mx
import mxnet.gluon
import mxnet.ndarray as nd
from mxnet.gluon.model_zoo import vision
import mxnet as mx
from gluoncv.data import VOCDetection

class_num = 4
ctx = [mx.cpu()]
net = model_zoo.get_model('ssd_300_vgg16_atrous_voc', pretrained=False)
net.load_parameters('./ssd_300_vgg16_atrous_voc_best.params', ctx = ctx)
# print(net)
```

**Comment by lsabi** [comment]
Hi,
Are you saying that you would like to take a pretrained model and finetune it to detect your 4 classes? Or do you already have the parameters and would like to load them?

**Comment by ZengyuanYu** [comment]
@lsabi Thanks your replay! I have trained my own data and have some params as like
 `  ssd_300_vgg16_atrous_voc_best.params   ssd_300_vgg16_atrous_voc_0020_0.7365.params `
Now I hope load one params to inference a test image and show the result about 4 classes. How do you some suggestion do it ?

**Comment by ZengyuanYu** [comment]
@zhreshold By the way, do you have any ideas to help me？

**Comment by ZengyuanYu** [comment]
Now I solve load params, Because I train ssd-voc and load ssd-custom, retrain use ssd-custom is ok.

**Comment by ou525** [comment]
@ZengyuanYu  hi, can you tell me how to solve this problem?
