### ISSUE TITLE
Pascal VOC benchmark.tgz download failed.

### ISSUE THREAD

**Issue by hustzxd** [dmlc/gluon-cv#511]
Thanks for the wonderful project. When I [Prepare PASCAL VOC datasets](https://gluon-cv.mxnet.io/build/examples_datasets/pascal_voc.html) , the `benchmark.tgz` cannot be downloaded. I think the url is expired. Hope somebody can share a new url.

I try 
```bash
wget http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz
```
```
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz [following]
20 redirections exceeded.
```

**Comment by zhreshold** [comment]
Seems like it is removed permanently. @zhanghang1989 What is the LICENSE of this particular dataset? If it is public, we can serve it on s3 ourselves.

**Comment by engineer1982** [comment]
also trying to download it... same error :/

**Comment by engineer1982** [comment]
just found it at google drive. here it goes and hope that helps someone :)

https://drive.google.com/file/d/1EQSKo5n2obj7tW8RytYTJ-eEYbXqtUXE/view?usp=sharing

**Comment by wangdach** [comment]
https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz   这可能有用
