### ISSUE TITLE
Stop training issue

### ISSUE THREAD

**Issue by jacky4323** [dmlc/gluon-cv#514]
Hi,
I have some problems when I try to train the ssd model
First,I build mxnet from source and nightly build gluoncv package
try to rum demo code, it looks great. However,  If I tryed to train the model,it will stuck and have printed some information show below .
Moreover, If no use gpu to train, it will not stop training process!!
Any help will be appreciated, Thanks!!

`python train_ssd.py  --gpus 1,2 --batch-size 20 --num-workers 10 --log-interval 20 ` 

![image](https://user-images.githubusercontent.com/31586393/49768744-5ca28f80-fd18-11e8-8216-26ec30985293.png)
![image](https://user-images.githubusercontent.com/31586393/49768964-39c4ab00-fd19-11e8-8424-ea9917aebb23.png)

**Comment by zhreshold** [comment]
You better use pip install mxnet-cuxx, your cudnn version seems not properly configured.
