### ISSUE TITLE
Do you have a plan to pick up cascade_rcnn?

### ISSUE THREAD

**Issue by ZengyuanYu** [dmlc/gluon-cv#522]
@zhreshold  Today I read this paper "Cascade R-CNN:Delving into High Quality Object Detection" and I try to code it reference to Faster R-CNN.But I am so low level generate many bug. So I ask you will update it in the near future ? Thank you! I will give a help If I can do some things for Cascade.

**Comment by zhreshold** [comment]
Checkout https://github.com/zzdang/cascade_rcnn_gluon first

**Comment by ZengyuanYu** [comment]
> Checkout https://github.com/zzdang/cascade_rcnn_gluon first

Thank you! I got it.
