### ISSUE TITLE
'Sequential' object has no attribute 'save_parameters'

### ISSUE THREAD

**Issue by fishman2008** [dmlc/gluon-cv#524]
I have followed the given tutorial here. 
https://beta.mxnet.io/guide/crash-course/4-train.html#
The training is successful. When saving the model using "net.save_parameters('net.params')", it gives the error "AttributeError: 'Sequential' object has no attribute 'save_parameters'". Google it but not able to find the solution. Thanks.

**Comment by hetong007** [comment]
Can you please make sure your MXNet version is at least 1.3.0, and retry?
