### ISSUE TITLE
自己的类voc格式的检测数据集怎么制作成rec格式？

### ISSUE THREAD

**Issue by ronyuzhang** [dmlc/gluon-cv#526]
自己的类voc格式的检测数据集怎么制作成rec格式？
另外，gluoncv能不使用rec格式的数据进行检测方面的训练吗？

**Comment by hetong007** [comment]
1. We have a tutorial on record io format for object detection: https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html
2. Our training scripts read raw images, not record io. For example: https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/ssd/train_ssd.py#L70

**Comment by ZengyuanYu** [comment]
@ronyuzhang  Simply you  only need make your data to PASCAL VOC format, for example: 000001.jpg 000001.xml then When you train like as SSD which only  modfiy VOCDetection input.
