### ISSUE TITLE
Where can I find the labels which correspond to the Ade20k prediction?

### ISSUE THREAD

**Issue by jackdh** [dmlc/gluon-cv#527]
Hey,

So the prediction outputs a NDArray with the pixel predictions.

I would like to know that for instance `11.0` references the pavement. I've only been able to work this out so far by manually comparing.

Even within the "get_color_pallete" it is just numbers and not the labels which they match to.

Is there a master list of which numbers correspond to which labels out there?

**Comment by lgov** [comment]
You can copy them from issue #210, they seem not to be implemented right now.

**Comment by jackdh** [comment]
> You can copy them from issue #210, they seem not to be implemented right now.

Thanks!
