### ISSUE TITLE
Can't get the same AP as yours(77.6) with ssd_300_vgg16

### ISSUE THREAD

**Issue by Hub-Tian** [dmlc/gluon-cv#530]
I trained ssd_300_vgg16 using the train_ssd.py with defaulted parameters (only one gpu is used), and got mAP of about 73.4. I am looking for the potential problems and wish you can give me some advices on the following questiones. @zhreshold 
1: Will the number of gpu affect the performance?
2: Is the same script you used to get the mAP of 77.6? I found there is no accuracy given on training set in my training log, while it is given in yours. 
My log is here [training_log](https://github.com/Hub-Tian/MXnet_SSD_log/blob/master/ssd_300_vgg16_atrous_voc_train.log)

**Comment by zhangwenwen** [comment]
@zhreshold

**Comment by ifeherva** [comment]
Have you tried multiple runs? Sometimes it is just a matter of luck.

**Comment by AceCoooool** [comment]
@Hub-Tian Did you find the reason ?
