### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'prefetch'

### ISSUE THREAD

**Issue by ChaoPei** [dmlc/gluon-cv#532]
When I try to train voc using mobilenet1_0, I got an error from class `_RandomTransformMultiWorkerIter1` in `gluoncv/data/dataloader.py`. It seems that it's parent class [_MultiWorkerIter](https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/data/dataloader.py) doesn't need the arg ?

**Comment by ChaoPei** [comment]
upgrade mxnet to 1.5.0 resolves this issue

**Comment by xizi** [comment]
The newest version of mxnet is 1.3.1, how could you upgrade mxnet to 1.5.0?

**Comment by ChaoPei** [comment]
> The newest version of mxnet is 1.3.1, how could you upgrade mxnet to 1.5.0?

pip install mxnet-cu92 --pre --upgrade

1.3.1 is stable and 1.5.0 is latest features

**Comment by xizi** [comment]
ok, thanks.
