### ISSUE TITLE
Which year and which part of ImageNet are used when training/testing the image classification model?

### ISSUE THREAD

**Issue by yqtianust** [dmlc/gluon-cv#543]
I want to know which year of ImageNet are used when training/testing the image classification model?

For example, you mentioned that for the object detection model using COCO, 

>  training image set is the union of 2007trainval and 2012trainval and validation image set is 2007test

Any similar information of the image classification models?

Thanks.

**Comment by hetong007** [comment]
We use ImageNet 2012 train for training and val for accuracy evaluation.

**Comment by yqtianust** [comment]
Thanks
