### ISSUE TITLE
Label smooth in YOLOv3

### ISSUE THREAD

**Issue by heavengate** [dmlc/gluon-cv#548]
https://github.com/dmlc/gluon-cv/blob/92a92ff646c575427e30e9946361a7ea0a4ac213/gluoncv/model_zoo/yolo/yolo_target.py#L272

I have some doubts about label_smooth in YOLOv3, could anyone help me.
In this line, all values  >-0.5 in class_target are set as 1/class_num,  and also this line will overwrite results from above line. 
1. Why label smooth is change values which > -0.5 to 1/class_num, as 0.0125 in coco datasets? 
2. What the line(269) means, seems can be deleted.
3. How this label smooth benefits YOLOv3 model?

Thanks.

**Comment by linqiaozhou** [comment]
I am confused with the "mixup", do you know the process of the mixup?

**Comment by houweidong** [comment]
I have same problem, could someone help solve the problem?

**Comment by houweidong** [comment]
@zhreshold 
hello, i saw the code in yolo3 has your name, can you help me?
