### ISSUE TITLE
完全不能用～～！！！

### ISSUE THREAD

**Issue by yihchu** [dmlc/gluon-cv#550]
文档中介绍了 怎么制作自己的数据集， 然后 在训练代码以及文档中并没有给除任何关于如何使用的说明

然后尝试使用PascalVoc格式，然而依旧无法跑起来。怀疑是自己数据的问题，然后下载了PascalVoc的数据之后，依旧不行。而且没有任何错误信息。

还有，如果训练时带上--no-random-shape参数，则报错:
mxnet.base.MXNetError: [16:11:33] src/operator/tensor/./matrix_op-inl.h:670: Check failed: b < len (24 vs. 20) slicing with begin[3]=24 exceends limit of 20

**Comment by xjsxujingsong** [comment]
You should put your screenshot here to demonstrate your PascalVOC dataset.

**Comment by sufeidechabei** [comment]
Can you show snippet of your code ?  (it's better to communicate in English)

**Comment by yihchu** [comment]
> You should put your screenshot here to demonstrate your PascalVOC dataset.
