### ISSUE TITLE
Error when run detect.cpp sample

### ISSUE THREAD

**Issue by SOWENKIN** [dmlc/gluon-cv#554]
./gluoncv-detect ../models/yolo3_darknet53_coco ../test-data/TC18056268_43773_20051.bmp --gpu 0

[17:33:09] /home/inuyasha/Develop/suyongjian/mxnet/yolo-detector/src/detect.cpp:77: Using custom names...
[17:33:09] /home/inuyasha/Develop/suyongjian/mxnet/yolo-detector/src/detect.cpp:94: Using GPU(0)...
[17:33:09] src/nnvm/legacy_json_util.cc:204: Warning: loading symbol saved by MXNet version 10500 with lower version of MXNet v10301. May cause undefined behavior. Please update MXNet if you encounter any issue
terminate called after throwing an instance of 'dmlc::Error'
  what():  [17:33:09] /home/inuyasha/Develop/suyongjian/mxnet/yolo-detector/cpp-package/include/mxnet-cpp/symbol.hpp:102: Check failed: MXSymbolCreateFromFile(file_name.c_str(), &(handle)) == 0 (-1 vs. 0) 

Stack trace returned 8 entries:
[bt] (0) ./gluoncv-detect(dmlc::StackTrace[abi:cxx11]()+0x54) [0x4b4cd8]
[bt] (1) ./gluoncv-detect(dmlc::LogMessageFatal::~LogMessageFatal()+0x2a) [0x4b4fa4]
[bt] (2) ./gluoncv-detect(mxnet::cpp::Symbol::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xe0) [0x4b6b18]
[bt] (3) ./gluoncv-detect(LoadCheckpoint(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, mxnet::cpp::Symbol*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::cpp::NDArray, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::cpp::NDArray> > >*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::cpp::NDArray, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::cpp::NDArray> > >*, mxnet::cpp::Context)+0x7b) [0x4c0fc4]
[bt] (4) ./gluoncv-detect(RunDemo()+0x13d) [0x4b01be]
[bt] (5) ./gluoncv-detect(main+0x25) [0x4b0c39]
[bt] (6) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fd97bc94830]
[bt] (7) ./gluoncv-detect(_start+0x29) [0x4adca9]

Aborted (core dumped)

**Comment by nmber5** [comment]
have you solve it ?
