### ISSUE TITLE
Test speed 

### ISSUE THREAD

**Issue by xizi** [dmlc/gluon-cv#556]
`yolo3_mobilenet1.0_320
time used: 0.345012903214
time used: 0.234060049057
time used: 0.201653957367
ssd_mobilenet1.0_320
time used: 0.127684116364
time used: 0.130243062973
time used: 0.124348163605`
The test speed of SSD and YOLO3 in CPU mode repeat 3 times and the image size is 320*320.  Why the speed of YOLO3 is slower than SSD?

**Comment by zhreshold** [comment]
Did you benchmark it or is it a single batch single image speed?
