### ISSUE TITLE
How to load  pre-trained model params from model_zoo when  define a network by inheriting

### ISSUE THREAD

**Issue by zhangwenwen** [dmlc/gluon-cv#560]
For example, I want to define a network based on SSD model, so I define it as 

```
class ImprovedSSD(SSD):
    def __init__():
         pass
    def hybrid_forward():
        pass
```

Now I want to load pre-trained SSD model params for ImprovedSSD to initialize  the inherited layers from SSD, any ideas?

**Comment by zhangwenwen** [comment]
How can I load  the pre-trained model params from model_zoo when I  define a network by inheriting an existed model from the model_zoo?

**Comment by lsabi** [comment]
Is this what you mean?

https://gluon-cv.mxnet.io/build/examples_detection/finetune_detection.html

**Comment by bryanyzhu** [comment]
Seems the link can solve this issue, close the issue due to inactive. Besides, you can write your own function to load the pre-trained weights to your new network layer by layer. A bit trouble, but always works.
