### ISSUE TITLE
Assertion `pred_hnd' failed in MXPredCreate step

### ISSUE THREAD

**Issue by SOWENKIN** [dmlc/gluon-cv#564]
Version: mxnet C++: 1.3.1, mxnet-cu90: 1.3.1, gluonCV: 0.4.0b20181228
Model: yolo3_darknet53_coco-symbol.json and yolo3_darknet53_coco-0000.params are exported from python script.
Code:
`     const std::string json_file = "../models/yolo3_darknet53_coco-symbol.json";
    const std::string param_file = "../models/yolo3_darknet53_coco-0000.params";

    BufferFile json_data(json_file);
    BufferFile param_data(param_file);

    // Parameters
    int dev_type = 1;  // 1: cpu, 2: gpu
    int dev_id = 0;  // arbitrary.
    mx_uint num_input_nodes = 1;  // 1 for feedforward
    const char* input_key[1] = {"data"};
    const char** input_keys = input_key;

    // Image size and channels
    int width = 512;
    int height = 512;
    int channels = 3;

    const mx_uint input_shape_indptr[2] = { 0, 4 };
    const mx_uint input_shape_data[4] = { 1, static_cast<mx_uint>(channels), static_cast<mx_uint>(height), static_cast<mx_uint>(width)};
    PredictorHandle pred_hnd = 0;

    if (json_data.GetLength() == 0 || param_data.GetLength() == 0) {
        return -1;
    }

    // Create Predictor
    MXPredCreate((const char*)json_data.GetBuffer(),
                 (const char*)param_data.GetBuffer(),
                 static_cast<size_t>(param_data.GetLength()),
                 dev_type, dev_id, num_input_nodes, input_keys, input_shape_indptr, input_shape_data, &pred_hnd);
    assert(pred_hnd);`

**Comment by zhreshold** [comment]
Please see https://github.com/apache/incubator-mxnet/issues/13810#issuecomment-452825267
