### ISSUE TITLE
Mixup for yolov3

### ISSUE THREAD

**Issue by linqiaozhou** [dmlc/gluon-cv#566]
I have read the code and  I am confused with the "mixup". How does the label mixup?  If image1 has 3 labels and image2 has 4 label, after "mixup" , how many labels will keep in the "mixup" image?

**Comment by hetong007** [comment]
It will have 7 labels: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/mixup/detection.py#L74

**Comment by linqiaozhou** [comment]
> It will have 7 labels: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/mixup/detection.py#L74

but, how to process the coefficient of imgs, how to use it? cv/blob/master/gluoncv/data/mixup/detection.py#L72

**Comment by linqiaozhou** [comment]
> It will have 7 labels: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/mixup/detection.py#L74

but, how to process the coefficient of imgs, how to use it? 
 https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/mixup/detection.py#L72

**Comment by linqiaozhou** [comment]
> It will have 7 labels: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/mixup/detection.py#L74

I tried mixup tow images, and it will result  a image that lost most information
