### ISSUE TITLE
ModuleNotFoundError: No module named 'gluoncv'

### ISSUE THREAD

**Issue by KyrieHee** [dmlc/gluon-cv#567]
when I import
`
from gluoncv import utils
from gluoncv.model_zoo import get_model
`
ModuleNotFoundError: No module named 'gluoncv', How can I slove it?  Thx.

**Comment by zhangwenwen** [comment]
[https://gluon-cv.mxnet.io/#install-gluoncv](https://gluon-cv.mxnet.io/#install-gluoncv)
```
pip install gluoncv --upgrade

# if you are eager to try new features, try nightly build instead

pip install gluoncv --pre --upgrade
```

**Comment by KyrieHee** [comment]
OK, Thx

**Comment by FIPAS-project** [comment]
안되잖아 시발럼아

**Comment by FIPAS-project** [comment]
안됳잖앍 싥밝럼앍
