### ISSUE TITLE
Have you ever tested last_gamma in ResidualBlockV2?

### ISSUE THREAD

**Issue by PistonY** [dmlc/gluon-cv#568]
I found you implement last_gamma in ResidualBlockV2,so I tested it with [AttentionNet](https://github.com/PistonY/ResidualAttentionNetwork),but not work for me?
And I didn't find any ResidualBlockV2 script in Gluon-CV model_zoo training with last_gamma,Have you ever tested it?

**Comment by hetong007** [comment]
Can you specify what does "not work" mean? It breaks your accuracy, or just not helpful? It is expected to be helpful when you are training with large batches.

We haven't tested it on ResNetv2 since it is not used as the backbone for other models in GluonCV yet.

**Comment by PistonY** [comment]
Ok,when I using it in ResNetV2 block with last gamma ,It’s only got 90% acc finally.So I’m now training just ResNetV2 not AttentionNet.I opened an issue for I don’t know my implement is right or other issus caused the problem, and if you tested it you may give me some advice.
