### ISSUE TITLE
Model conversion from mxnet to caffe 

### ISSUE THREAD

**Issue by xizi** [dmlc/gluon-cv#570]
Hi, @zhanghang1989 , @zhreshold , i have trained a yolo3-mobilenet detection model, how can i converse it to caffemodel?  Can you provide some conversion tool...

**Comment by Mut1nyJD** [comment]
Why not export it to ONNX?

**Comment by zhreshold** [comment]
We are working on export to TVM for better deployment.

**Comment by Mut1nyJD** [comment]
@zhreshold 

I thought TVM already can already read MXNet networks?

**Comment by Mut1nyJD** [comment]
@zhreshold 
I see thanks. Hmm is that true just for importing MXNet models into TVM or in general independent of the source type? 

If so that kind of plugs a bit of a hole in a current project I am doing and I might have to look for an alternative deployment solution.

**Comment by Mut1nyJD** [comment]
> Why not export it to ONNX?

Except you can't because both the YOLOOutput3 and YOLOV3 use a Slice operator with an end as NONE which is not supported in ONNX :(

**Comment by pengzhao-intel** [comment]
BTW, why export it to Caffe? Anything MXNet/Gluon is missed?

**Comment by Mut1nyJD** [comment]
I certainly don't want to export it to Caffe. 

I wanted to export to ONNX but it seems it is a major headache there are too many operators that simply are not supported in ONNX, you can fix the slice operator with the NONE end easily, but after that you just get to the next thing (OP.arange and OP.slice_like).

**Comment by pengzhao-intel** [comment]
> I certainly don't want to export it to Caffe.
> 
> I wanted to export to ONNX but it seems it is a major headache there are too many operators that simply are not supported in ONNX, you can fix the slice operator with the NONE end easily, but after that you just get to the next thing (OP.arange and OP.slice_like).

Exactly, it's the major problem of ONNX :(
