### ISSUE TITLE
How to get NDArray data from a Symbol in a training iter

### ISSUE THREAD

**Issue by heavengate** [dmlc/gluon-cv#573]
APIs such as asnumpy() didn't implements in a Symbol object, How to get the data in a training iter.
<img width="738" alt="2019-01-14 6 04 17" src="https://user-images.githubusercontent.com/12605721/51106481-dbfb1580-1826-11e9-9e96-137fe96034dd.png">
   Thanks

**Comment by zhreshold** [comment]
You cannot get intermediate data in symbol unless you cut the computational graph in half. You have can simply disable hybridize.

In old days, you can insert a monitor https://mxnet.incubator.apache.org/api/python/module/module.html?highlight=monitor#mxnet.module.Module.install_monitor, but it's another story for symbol modules.

**Comment by heavengate** [comment]
Thank you @zhreshold
