### ISSUE TITLE
Using `~` in code

### ISSUE THREAD

**Issue by ChristianKniep** [dmlc/gluon-cv#580]
I am working on containerizing ML/AI workloads within docker and to allow POSIX data access is to enforce the UID:GID of the calling (external) user onto the container.
An initial implementation might not change the authentication provider (/etc/passwd) within the container, which implies that the user-name does not exists.
```
$ docker run -ti --rm -v /home/docker --user=$(id -u):$(id -g) ubuntu id
uid=1001 gid=1001 groups=1001
$ docker run -ti --rm -v /home/docker --user=$(id -u):$(id -g) ubuntu whoami
whoami: cannot find name for user ID 1001
```
No problem for POSIX access to mapped in file-systems as this is done via UID:GID(s), but internally that imposes a problem to gluoncv, as the default within the code uses `~`.

```
$ cat -n  /usr/local/lib/python3.6/dist-packages/gluoncv/data/imagenet/classification.py |grep "~"
    16	    root : str, default '~/.mxnet/datasets/imagenet'
    25	    def __init__(self, root=path.join('~', '.mxnet', 'datasets', 'imagenet'),
```

**Comment by zhreshold** [comment]
There are two options IMO

- Override the default path with explicit paths when instantiate the datasets
- Replace `os.path.expanduser` which failed to replace user-name by a customized function with capability to parse user-name correctly, for example, there are multiple solutions on SO: https://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python
