### ISSUE TITLE
Issue Derive from PASCAL VOC format

### ISSUE THREAD

**Issue by Owenscu** [dmlc/gluon-cv#587]
I have a custom dataset fully comply with the Pascal VOC object detection format. But I meet a problem when i transfer it to GluonCV format. The label of dataset i get is empty.
![image](https://user-images.githubusercontent.com/23129979/51458363-e4f06780-1d8f-11e9-9ff1-b6c342facd6f.png)

**Comment by zhreshold** [comment]
what does a sample xml file of your dataset looks like?

**Comment by jjprincess** [comment]
@Owenscu Hello, i met the same problem. Could you please tell me your solution? Thanks!

**Comment by zhreshold** [comment]
Make sure CLASSES contains your classes in xml files.

**Comment by Owenscu** [comment]
> @Owenscu Hello, i met the same problem. Could you please tell me your solution? Thanks!
![image](https://user-images.githubusercontent.com/23129979/53212107-9b40b880-367e-11e9-9ba9-e8a20c7b5e79.png)
I just change 'AB' to 'dog', and it works. But i dont know the reason.

**Comment by Owenscu** [comment]
@jjprincess 
![image](https://user-images.githubusercontent.com/23129979/53212160-dcd16380-367e-11e9-867d-9f3133511205.png)
I just changed the class name 'AB' to 'dog' or 'person', and it works. But i dont know the reason.

**Comment by jjprincess** [comment]
> @jjprincess
> ![image](https://user-images.githubusercontent.com/23129979/53212160-dcd16380-367e-11e9-867d-9f3133511205.png)
> I just changed the class name 'AB' to 'dog' or 'person', and it works. But i dont know the reason.

I solved this problem by changing the classes in gluoncv/data/pascal_voc.

**Comment by jjprincess** [comment]
> > @jjprincess
> > ![image](https://user-images.githubusercontent.com/23129979/53212160-dcd16380-367e-11e9-867d-9f3133511205.png)
> > I just changed the class name 'AB' to 'dog' or 'person', and it works. But i dont know the reason.
> 
> I solved this problem by changing the classes in gluoncv/data/pascal_voc.

detection.py
