### ISSUE TITLE
When train Faster_rcnn with mixup aug,there is some error.

### ISSUE THREAD

**Issue by baolinhu** [dmlc/gluon-cv#588]
When train Faster_rcnn with mixup aug,there is some error.
![image](https://user-images.githubusercontent.com/16516384/51479954-b93ea300-1dca-11e9-8fc7-a2e76001a8d6.png)
AttributeError: '_LazyTransformDataset' object has no attribute 'set_mixup'

**Comment by jjprincess** [comment]
> When train Faster_rcnn with mixup aug,there is some error.
> ![image](https://user-images.githubusercontent.com/16516384/51479954-b93ea300-1dca-11e9-8fc7-a2e76001a8d6.png)
> AttributeError: '_LazyTransformDataset' object has no attribute 'set_mixup'

Did you solve the problem?

**Comment by pangpanghuahuamaomi** [comment]
> > When train Faster_rcnn with mixup aug,there is some error.
> > ![image](https://user-images.githubusercontent.com/16516384/51479954-b93ea300-1dca-11e9-8fc7-a2e76001a8d6.png)
> > AttributeError: '_LazyTransformDataset' object has no attribute 'set_mixup'
> 
> Did you solve the problem?
 '' train_data._dataset.set_mixup''  is changed to  '' train_data._dataset._data.set_mixup'' ,  that's working!

**Comment by jjprincess** [comment]
> > > When train Faster_rcnn with mixup aug,there is some error.
> > > ![image](https://user-images.githubusercontent.com/16516384/51479954-b93ea300-1dca-11e9-8fc7-a2e76001a8d6.png)
> > > AttributeError: '_LazyTransformDataset' object has no attribute 'set_mixup'
> > 
> > 
> > Did you solve the problem?
> > '' train_data._dataset.set_mixup''  is changed to  '' train_data._dataset._data.set_mixup'' ,  that's working!

Thanks! It was so amazing!!!!
