### ISSUE TITLE
AssertionError: Invalid input format when train faster rcnn

### ISSUE THREAD

**Issue by TreeDream** [dmlc/gluon-cv#589]
I use the lst description file to make my own training set. 
There's no problem running a loop, but then there were problems.

INFO:root:Namespace(batch_size=2, dataset='camera', epochs=30, gpus='0,1', log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='13,20,24', lr_warmup=-1, mixup=False, momentum=0.9, network='resnet50_v1b', no_mixup_epochs=20, num_workers=2, resume='', save_interval=1, save_prefix='faster_rcnn_resnet50_v1b_camera', seed=233, start_epoch=0, val_interval=1, verbose=False, wd=0.0005)
INFO:root:Start training from [Epoch 0]
INFO:root:[Epoch 0] Training cost: 19.745, RPN_Conf=0.434,RPN_SmoothL1=0.026,RCNN_CrossEntropy=0.512,RCNN_SmoothL1=0.058
INFO:root:[Epoch 0] Validation:
camera=0.00146627565982
mAP=0.00146627565982
INFO:root:[Epoch 0] mAP 0.00146627565982 higher than current best [0] saving to faster_rcnn_resnet50_v1b_camera_best.params
INFO:root:[Epoch 0] Saving parameters to faster_rcnn_resnet50_v1b_camera_0000_0.0015.params
Traceback (most recent call last):
  File "train_faster_rcnn.py", line 463, in <module>
    train(net, train_data, val_data, eval_metric, ctx, args)
  File "train_faster_rcnn.py", line 377, in train
    cls_pred, box_pred, roi, samples, matches, rpn_score, rpn_box, anchors = net(data, gt_box)
  File "/home/users/xxxx/anaconda2/lib/python2.7/site-packages/mxnet/gluon/block.py", line 541, in __call__
    out = self.forward(*args)
  File "/home/users/xxxx/anaconda2/lib/python2.7/site-packages/mxnet/gluon/block.py", line 908, in forward
    return self._call_cached_op(x, *args)
  File "/home/users/xxxx/anaconda2/lib/python2.7/site-packages/mxnet/gluon/block.py", line 801, in _call_cached_op
    assert fmt == self._in_format, "Invalid input format"
AssertionError: Invalid input format

**Comment by TreeDream** [comment]
I didn't rewrite the training set and the verification set to hybridize.

**Comment by szza** [comment]
do you resolve the problem?
