### ISSUE TITLE
 how to set rescale_grad and weight  in yolov3 fp16?

### ISSUE THREAD

**Issue by mutouoa** [dmlc/gluon-cv#593]
training yolov3 in fp16 ,  I can't get the same mAP as in fp32 did, how to set rescale_grad and weight  in yolov3 fp16?

**Comment by mutouoa** [comment]
@zhreshold

**Comment by zhreshold** [comment]
You can simply rescale loss and learning rate accordingly in a global setting.
Besides, I would also like to keep the bounding box regression branch in fp32 intact, because it requires higher precision compared to classification.

**Comment by mutouoa** [comment]
> You can simply rescale loss and learning rate accordingly in a global setting.
> Besides, I would also like to keep the bounding box regression branch in fp32 intact, because it requires higher precision compared to classificat

**Comment by mutouoa** [comment]
> You can simply rescale loss and learning rate accordingly in a global setting.
> Besides, I would also like to keep the bounding box regression branch in fp32 intact, because it requires higher precision compared to classification

Classification and bounding box regression are calculated together, how to get the bounding box regression branch ?

**Comment by mutouoa** [comment]
> You can simply rescale loss and learning rate accordingly in a global setting.
> Besides, I would also like to keep the bounding box regression branch in fp32 intact, because it requires higher precision compared to classification.

Classification and bounding box regression are calculated together, how to get the bounding box regression branch ? @zhreshold
