### ISSUE TITLE
Object Tracking Feature

### ISSUE THREAD

**Issue by lsabi** [dmlc/gluon-cv#599]
Hi,

Is there any plan about implementing object tracking by extending object detection?

Thanks

**Comment by zhreshold** [comment]
Yes, we are targeting videos right now, the release date is still TBD.

**Comment by lsabi** [comment]
Awesome, thanks!

Just to avoid redundancies in questions, is there a roadmap available?

**Comment by bryanyzhu** [comment]
We start to add object tracking now, the first PR is #1139 . 

Right now, it supports SiamRPN inference only. We will add training part asap. We will add more SOTA algorithms like SiamRPN++ and SiamMask to GluonCV in the next four months.
