### ISSUE TITLE
Cannot download yolo3_mobilenet1_0_voc

### ISSUE THREAD

**Issue by stereomatchingkiss** [dmlc/gluon-cv#602]
gluoncv                            0.4.0b20190128
mxnet-cu92                      1.5.0b20190128

Try to download yolo3_mobilenet1_0_voc with following codes

```
from gluoncv import model_zoo

model_zoo.get_model('yolo3_mobilenet1.0_voc', pretrained=True)
```

But the scirpts always give me error messages

**ValueError: Pretrained model for yolo3_mobilenet1_0_voc is not available.**

**Comment by zhreshold** [comment]
We are uploading models to s3 right now, may take a while until they are online.

**Comment by zhreshold** [comment]
It's now online 😺
