### ISSUE TITLE
Documented and actual output of DataParallelModel do not match, and why tuple of tuple of NDArray output??

### ISSUE THREAD

**Issue by oliverclimaterisk** [dmlc/gluon-cv#603]
The documentation for DataParallelModel says `...Inputs and outputs are both list of NDArrays in different contexts...` however the output is a tuple of tuples of NDArrays. The first tuple seems to correspond to different devices, the second tuple always seems to have length 1 and be superfluous. Is the documentation wrong or the output of DataParallelModel? If the former, what do the nested tuples correspond to?

**Comment by OliverColeman** [comment]
Oh maybe other items in the nested tuples are for auxiliary output?
