### ISSUE TITLE
Improved `detection_custom.py` tutorial

### ISSUE THREAD

**Issue by sharmalakshay93** [dmlc/gluon-cv#608]
Hi,

I've been using the "Prepare custom datasets for object detection" [tutorial](https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html) that references the [`detection_custom.py`](https://github.com/dmlc/gluon-cv/blob/428ee05d7ae4f2955ef00380a1b324b05e6bc80f/docs/tutorials/datasets/detection_custom.py) script. While this was a very helpful tutorial, I feel that it could be re-written to be more generalizable and could use fewer hard-coded values. Since I've very recently done this, I'd like to contribute with an improved version.

Also, I haven't made open source contributions before, and so was wondering if there are any pointers for contributing to GluonCV that I could look at? Would making a change to the Git repository reflect in changes to the documentation of the tutorial on the GluonCV site ([link](https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html))?

Thanks

**Comment by lsabi** [comment]
Hi,

Have you tried following the how-to instructions ([contribute](https://gluon-cv.mxnet.io/how_to/contribute.html)) ?

**Comment by sharmalakshay93** [comment]
@lsabi  Didn't come across that, I'll take a look at it; thanks!

**Comment by sharmalakshay93** [comment]
Closing this and will submit a PR once I have finished working on the improvements
