### ISSUE TITLE
what is the  small constant ε used in models（COCO and VOC）？

### ISSUE THREAD

**Issue by jinxuan777** [dmlc/gluon-cv#623]
I try to reproduce “label smooth” in paper “Bag of Freebies for Training Object Detection Neural Networks”，but can not find constant ε in details.

**Comment by zhreshold** [comment]
it's 0.01 in experiment

**Comment by jinxuan777** [comment]
@zhreshold thx for your reply
I confused by code in yolo_target.py
![image](https://user-images.githubusercontent.com/23650957/53325155-93527400-391d-11e9-87ba-06cf8e709890.png)
1. constant ε = 1.0 in yolov3 ?
2. As class_targets is a one-hot vector for classification, np.where(class_targets<-.5) causes [smooth_weight,.....,smooth_weight] in final label

**Comment by leoluopy** [comment]
may i ask that where is the image preprocess details or training howTo in paper “Bag of Freebies for Training Object Detection Neural Networks”

**Comment by jinxuan777** [comment]
> may i ask that where is the image preprocess details or training howTo in paper “Bag of Freebies for Training Object Detection Neural Networks” @jinxuan777 @zhreshold

[gluon-cv/gluoncv/data/mixup/detection.py](url)
