### ISSUE TITLE
run train_yolo3.py error 

### ISSUE THREAD

**Issue by haihaixia** [dmlc/gluon-cv#626]
Hi.When I run the train_yolo3.py,I get the error which is AttributeError: "'_RandomTransformMultiWorkerIter' object has no attribute '_shutdown'".Then I try to upgrade the mxnet with 'pip install mxnet --upgrade'.And now I get the error:mxnet.base.MXNetError: [16:49:27] src/ndarray/ndarray.cc:1233: GPU is not enabled.What's the problems?My mxnet's version is 1.3.1.
Thanks!

**Comment by zhreshold** [comment]
To use gluoncv master, you should use mxnet master as well. And you are installing cpu version of mxnet.

Try:
```
pip uninstall mxnet -y
pip install mxnet-cu100 --pre --upgrade
```

**Comment by haihaixia** [comment]
I'm sorry it's still not working after two commands:
pip uninstall mxnet -y
pip install mxnet-cu90 --pre --upgrade
(I use CUDA90&cuDNN7.0)

I get another error:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/anaconda3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 400, in _worker_fn
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/home/user/anaconda3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 400, in <listcomp>
    batch = batchify_fn([_worker_dataset[i] for i in samples])
TypeError: 'NoneType' object is not subscriptable

**Comment by zhreshold** [comment]
the new error is related to #630, update to master should solve the problem

**Comment by haihaixia** [comment]
According to yours guidance,my problem has been solved.Thanks very much.

**Comment by dreamhighchina** [comment]
> Hi.When I run the train_yolo3.py,I get the error which is AttributeError: "'_RandomTransformMultiWorkerIter' object has no attribute '_shutdown'".Then I try to upgrade the mxnet with 'pip install mxnet --upgrade'.And now I get the error:mxnet.base.MXNetError: [16:49:27] src/ndarray/ndarray.cc:1233: GPU is not enabled.What's the problems?My mxnet's version is 1.3.1.
> Thanks!

where is the train_yolo3.py?

**Comment by haihaixia** [comment]
Do you mean how to find train_yolo3.py? 
The path to this file is gluon-cv/scripts/detection/yolo/train_yolo3.py
And you can also use the 'Find file' botton in github.
