### ISSUE TITLE
Is re-id a pre-trained result?

### ISSUE THREAD

**Issue by bigbao9494** [dmlc/gluon-cv#633]
Is re-id a pre-trained result?
Not found in the project, other MARSK-RCNN have these

**Comment by zhreshold** [comment]
No, only training scripts are provided so far.

**Comment by bigbao9494** [comment]
@zhreshold 
"No, only training scripts are provided so far."
why??

**Comment by zhreshold** [comment]
This is user contributed feature, we are yet to cover all these examples
