### ISSUE TITLE
GPU is not enabled.

### ISSUE THREAD

**Issue by jjprincess** [dmlc/gluon-cv#641]
When I run the train_faster_rcnn.py following the tutorials, I got the error:
![image](https://user-images.githubusercontent.com/22324091/53174269-66a01300-3624-11e9-9903-03598963ebd5.png)

Does anybody know how to solve it?Thanks!

I have solved this problem~

**Comment by 1453042287** [comment]
@zhreshold i meet the same problem, can you give me some hints? thanks a lot !

**Comment by Jerryzcn** [comment]
@1453042287 MXNet is probably not compile with CUDA

**Comment by zhanghang1989** [comment]
please install gpu version mxnet, follow the mxnet.io instructions

**Comment by jjprincess** [comment]
> please install gpu version mxnet, follow the mxnet.io instructions

Thanks，I solved this problem,(●ˇ∀ˇ●).
