### ISSUE TITLE
Can't use mixup in training faster rcnn.

### ISSUE THREAD

**Issue by jjprincess** [dmlc/gluon-cv#645]

**Comment by whitesockcat** [comment]
cannot import name 'MixupDetection' from 'gluoncv.data.mixup'

**Comment by whitesockcat** [comment]
just solve it.
change
` from gluoncv.data.mixup import MixupDetection`
` train_dataset = MixupDetection(train_dataset)`
to
`from gluoncv.data.mixup import detection`
`train_dataset = detection.MixupDetection(train_dataset)`

and change
`train_data._dataset.set_mixup`
to 
`train_data._dataset._data.set_mixup`

hope this can help you!
