### ISSUE TITLE
multiple GPU training problem when running train_yolo3.py

### ISSUE THREAD

**Issue by haihaixia** [dmlc/gluon-cv#646]
My server,ubuntu16.0, has eight gpus. When running train_yolo3.py, I set up the running script with '--gpus 1,2,3,4',which means I want to train the model with gpu 1,2,3,4.But in fact,except for gpu1,2,3,4,it also takes up the gpu0(421 MiB),gpu5(10MiB),gpu6(10MiB),gpu7(10MiB). I'm not running other programs at the same time.Why would this happen?

Sat Feb 23 16:37:33 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 27%   50C    P2    52W / 250W |    **421MiB** / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 35%   63C    P2   186W / 250W |    **8611MiB** / 11172MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
| 33%   60C    P2   194W / 250W |   **8609MiB** / 11172MiB |     18%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 32%   57C    P2   194W / 250W |   **8607MiB** / 11172MiB |     31%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  Off  | 00000000:85:00.0 Off |                  N/A |
| 30%   55C    P2   200W / 250W |   **8609MiB** / 11172MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  Off  | 00000000:86:00.0 Off |                  N/A |
| 25%   42C    P8    12W / 250W |     **10MiB** / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  Off  | 00000000:89:00.0 Off |                  N/A |
| 25%   41C    P8    11W / 250W |     **10MiB** / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  Off  | 00000000:8A:00.0 Off |                  N/A |
| 26%   45C    P8    13W / 250W |     **10MiB** / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     13760      C   /home/user/anaconda3/bin/python3.6            409MiB |
|    1     13760      C   /home/user/anaconda3/bin/python3.6           8599MiB |
|    2     13760      C   /home/user/anaconda3/bin/python3.6           8597MiB |
|    3     13760      C   /home/user/anaconda3/bin/python3.6           8595MiB |
|    4     13760      C   /home/user/anaconda3/bin/python3.6           8597MiB |
+-----------------------------------------------------------------------------+

**Comment by zhreshold** [comment]
Did you compile with opencv that compiled with cuda? (USE_CUDA=ON)
Or did you use pin_memory in dataloader?
