### ISSUE TITLE
Need a configuration system!

### ISSUE THREAD

**Issue by Beginc** [dmlc/gluon-cv#658]
A configuration system is needed when we want to train several models with different hyperparams simutaniously without changing the source code.

**Comment by zhreshold** [comment]
have you checked the argparse options?

**Comment by Beginc** [comment]
What I mean is changing the hyperparams for a specific model with configuration.For example, if I want to change scales in Faster RCNN, I have to changing the params fixed in function get_faster_rcnn_voc, which is not convenient.
