### ISSUE TITLE
may i ask that where is the image preprocess details or training howTo in paper “Bag of Freebies for Training Object Detection Neural Networks”

### ISSUE THREAD

**Issue by leoluopy** [dmlc/gluon-cv#659]
from paper  “Bag of Freebies for Training Object Detection Neural Networks” , we have learned that by preprocessing images and some other tricks , 5 mAPs can be obtained  without changing network , do any one know where is the details of this paper ?

**Comment by zhreshold** [comment]
This repo contains all the details you needed

**Comment by leoluopy** [comment]
@zhreshold  thanks for responding
