### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'norm_layer'

### ISSUE THREAD

**Issue by 1453042287** [dmlc/gluon-cv#660]
when i use multi-gpu and set syncbn=True ,i meet the problem as the title, but it's fine with singel gpu ,any suggestions?
thanks a lot !

**Comment by 1453042287** [comment]
BTW, i use the train_yolo3.py : )

**Comment by bloatybo** [comment]
same problem here

**Comment by 1453042287** [comment]
Maybe it's caused by the python‘s version, now it works fine now : )

**Comment by GhitaCristian** [comment]
> Maybe it's caused by the python‘s version, now it works fine : )

Can you please specify which version should be used? I get the norm_layer error using python 3.7.2

**Comment by 1453042287** [comment]
@GhitaCristian python 3.5 with the nightly released version
