### ISSUE TITLE
How to generate results on mscoco test dataset for evaluation ?

### ISSUE THREAD

**Issue by LightToYang** [dmlc/gluon-cv#665]
I train YOLOv3 on MSCOCO, can only evaluate on val dataset. But I want to generate the detection results of test dataset, what can I do ?

**Comment by gachiemchiep** [comment]
@LightToYang 
Which dataset are you talking to ? Is that 2017 ? 

![image](https://user-images.githubusercontent.com/2300329/54097827-3b277180-43f5-11e9-8a34-e2548a53bcf2.png)

**Comment by LightToYang** [comment]
It is 2017 Test or 2014 Testing which do not exist annotation files

**Comment by gachiemchiep** [comment]
@LightToYang 

> I want to generate the detection results of test dataset
> It is 2017 Test or 2014 Testing which does not exist annotation files

The only method is to used detection script at [demo_yolo.py](https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/yolo/demo_yolo.py) 
The demo_yolo.py script only write out detection result for one image, so you need to re-write a little bit to make it work for several images.

**Comment by tlind** [comment]
How are the COCO AP results computed which are listed in the model zoo at https://gluon-cv.mxnet.io/model_zoo/detection.html?

The "Box AP" numbers listed there (e.g. for faster_rcnn_fpn_resnet101_v1d_coco) do not correspond to the best validation APs from the respective training logs, so I assume they were computed on coco2017-test. Is that correct?

Which transform is used for computing test results? `transform_test`, which also does rescaling based upon shortest image side and allows non-square input dimensions while retaining aspect ratio, or `YOLO3DefaultValTransform`, which e.g. in the `train_yolo3.py` script scales the input image to a square (e.g. 416x416)?

**Comment by gachiemchiep** [comment]
@tlind 
The code is fine man.

But their train log is messed up.
Some train log is missing, you should add authors for corresponding train log.

For example, from https://gluon-cv.mxnet.io/model_zoo/detection.html we could see the
following model's train log is pointed to wrong location

```bash
faster_rcnn_fpn_resnet50_v1b_coco :  https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/faster_rcnn_resnet101_v1d_coco_train.log

faster_rcnn_fpn_resnet101_v1d_coco : https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/faster_rcnn_resnet101_v1d_coco_train.log

faster_rcnn_fpn_bn_resnet50_v1b_coco : https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/faster_rcnn_resnet101_v1d_coco_train.log
```

**Comment by Jerryzcn** [comment]
I forgot to change the logs' link when i commit. Will be updated in the RCNN enhancement PR.
