### ISSUE TITLE
Train_yolo.py : indexError: too many indices for array

### ISSUE THREAD

**Issue by vincentJCE** [dmlc/gluon-cv#666]
I simply run the train_yolo.py from the tutorial.  It gives IndexError: too many indices for array. I read other issues with similar description, but cannot solve the problem. some says that this may come from images with no bounding box. But I simply use the voc2007 to train.
![image](https://user-images.githubusercontent.com/23130831/53940923-c81ab400-40f1-11e9-90bd-6e080a7fd576.png)

**Comment by zhreshold** [comment]
Do you have shared memory enabled?
