### ISSUE TITLE
terminate called after throwing an instance of 'dmlc::Error'

### ISSUE THREAD

**Issue by vincentJCE** [dmlc/gluon-cv#667]
I simply run train_yolo.py, however raise the flollowing error:
terminate called after throwing an instance of 'dmlc::Error'
  what():  [17:54:40] /home/ubuntu/mxnet-distro/mxnet-build/3rdparty/mshadow/mshadow/./stream_gpu-inl.h:198: Check failed: e == cudaSuccess CUDA: out of memory

Stack trace returned 9 entries:
[bt] (0) /NIS_home/chongen.ji/.conda/envs/gluon2/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x42831a) [0x7fdf1fafd31a]
[bt] (1) /NIS_home/chongen.ji/.conda/envs/gluon2/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x428931) [0x7fdf1fafd931]
[bt] (2) /NIS_home/chongen.ji/.conda/envs/gluon2/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2cd52a2) [0x7fdf223aa2a2]
[bt] (3) /NIS_home/chongen.ji/.conda/envs/gluon2/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2cee6ba) [0x7fdf223c36ba]
[bt] (4) /NIS_home/chongen.ji/.conda/envs/gluon2/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2cee9b6) [0x7fdf223c39b6]
[bt] (5) /NIS_home/chongen.ji/.conda/envs/gluon2/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2ce7cc4) [0x7fdf223bccc4]
[bt] (6) /NIS_home/chongen.ji/.conda/envs/gluon2/bin/../lib/libstdc++.so.6(+0xb8678) [0x7fdfc12a6678]
[bt] (7) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fdfc5fff6db]
[bt] (8) /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7fdfc5d2888f]

Aborted (core dumped)
---------------------------------------------------------------------------

It seems related to the GPU usage. However, I check with nvidia-smi, only a small portion of my 8 GPUs are being used.
Well, I tried another gluon demo demo_cifar10.py, there is no such problem.

**Comment by zhreshold** [comment]
What's your computer setup and what's the training command you used?

**Comment by faisalshahbaz** [comment]
Add these lines in your code.

```
import mxnet as mx
mx.nd.waitall()
```
