### ISSUE TITLE
what detector do you use in pose estimation?There is a slight spelling error on the gluoncv page

### ISSUE THREAD

**Issue by baolinhu** [dmlc/gluon-cv#680]
What detector do you use in pose estimation?How about AP？
There is a slight spelling error on the [gluoncv page](https://gluon-cv.mxnet.io/model_zoo/pose.html).
![image](https://user-images.githubusercontent.com/16516384/54260292-79629380-45a3-11e9-83b7-484332192fe2.png)
It should be OKS AP not OSK,right?

**Comment by hetong007** [comment]
Thanks for the catch, will update soon.

Here we report the results from COCO python API, which provides the ground truth bounding boxes. As a two-stage estimator it is more useful to know how the estimator performs.

**Comment by baolinhu** [comment]
@hetong007 Thanks for reply. But if you use gt bboxes,the mAP will a little higher about 2 points. Gt bboxes are not used in most papers.And for test-dev  there is no gt bboxes.

**Comment by hetong007** [comment]
Thanks, we will mark our table as using gt bboxes. 

It is an issue that among all detectors in GluonCV, the best person AP is only 52.9. and for the sake of pose estimation we may need to add something specifically good at person detection.

**Comment by baolinhu** [comment]
OK,thanks.
I used gluon to reimplement CPN recently.There is no Upsample function in gluon.nn like pytoch  torch.nn.Upsample()?How to implement that(like fpn structure) use gluon?

**Comment by hetong007** [comment]
@baolinhu is  [`BilinearResize2D`](http://mxnet.incubator.apache.org/api/python/ndarray/contrib.html?highlight=bilinear#mxnet.ndarray.contrib.BilinearResize2D) something that you are looking for ?
