### ISSUE TITLE
Why pool_size=1 in resnetv1b avg_down

### ISSUE THREAD

**Issue by gathierry** [dmlc/gluon-cv#683]
Hi, I am a little confused by [this avg pooling](https://github.com/dmlc/gluon-cv/blob/02d2d17c4d7eedde6eb2684fb49edefb801d8dd6/gluoncv/model_zoo/resnetv1b.py#L212)  in resnetv1b. Why the pool_size is 1? Does that means doing nothing but only a ceil operation?

**Comment by zhanghang1989** [comment]
It is identical operation, for network dilation.

**Comment by gathierry** [comment]
ok, I get the idea, thanks.
