### ISSUE TITLE
How Prepare custom datasets for object detection on gluonCV and MXNet?

### ISSUE THREAD

**Issue by essalahsouad** [dmlc/gluon-cv#685]
I would like to know how to prepare custom data sets for object detection for fine tuning a pretrained detection model in reference to this site "https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html#derive-from-pascal-voc-format" But it seems difficult so i need some help ..

**Comment by lsabi** [comment]
Hi,

It's quite simple once you get the key idea. Try to follow my instructions.

1) Create a folder, name it "myDataset".

2) Inside the folder you just created, create another folder, this time call it "VOC2019".

3) Inside the folder you just created (yeah, again), create three folders: "Annotations", "ImageSets" and "JPEGImages".

4) Inside the folder Annotations, put the annotation files structured as in the link you mentioned, while in the folder JPEGImages,  put the images in JPEG format. Note that the image name corresponds to the  annotation file with the same name.

5) In the folder ImageSets, create a folder (yep, another one) name "Main".

6) Inside the folder you just created, create a file "train.txt" with a list of names (one per line) corresponding to the images you want to be used for training (it will be taken from the folders Annotations and JPEGImages).

Following a code snippet that shows how to read your custom dataset.

```
classes = ['class1', class2', 'class3']

class VOCLike(VOCDetection):
    CLASSES = classes

    def __init__(self, root, splits, transform=None, index_map=None, preload_label=True):
        super(VOCLike, self).__init__(root, splits, transform, index_map, preload_label)

voc_dataset =VOCLike(root='/my/path/myDataset', splits=[(2019, 'train')])
```

And now have fun with your custom dataset!

**Comment by essalahsouad** [comment]
thank you Sir.

**Comment by essalahsouad** [comment]
@Isabi 
i have made a mistake in url .what I really use is  a dataset with yolo format not a dataset with a VOC (i know that i can convert the format )But I wonder if you have an idea how creat dataset reference to this site
[https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html#preferred-object-detection-format-for-gluoncv-and-mxnet](url)
I appreciate your help.

**Comment by lsabi** [comment]
Hi,

The link has two dataset formats: LST and RecordFileDetection. Which one do you mean?

**Comment by essalahsouad** [comment]
I have problem with the both of them ...
So if you can help me with one of them I'll be grateful

**Comment by lsabi** [comment]
In order to prepare the LST format, you have to write to a file lines containing the following:

- ID (usuallly it is sequential, based on the number of lines that will be printed to the file)
- Header Length which is 2 in our case
- Label Length which is 5 in our case
- Object which is made up of 5 elements: label id, xmin, ymin, xmax, ymax
- Image Path the path to the image

For the RecordFileDetection, there is a script to download that takes as input an LST file and outputs a file in the RecordFileDetection format.

Hope it is clear, though the tutorial is very easy to follow and code snippets can be reused.

**Comment by essalahsouad** [comment]
Thank you for your reply. 
when i was trying to flow this site [https://mxnet.incubator.apache.org/versions/master/faq/recordio.html]() 
to prepare the LST format i got as input file .lst
![54530177-61fc1f80-4982-11e9-8fe2-d58cb9540bc2](https://user-images.githubusercontent.com/34586193/54612080-80cce580-4a58-11e9-8d63-d626a6d1b5c7.png)
my question is  isn't normal that the label_index all of them are 0000
But i don't know if my output is it correct??
**my data**
![Capture du 2019-03-19 14-55-18](https://user-images.githubusercontent.com/34586193/54612154-b1148400-4a58-11e9-870c-e888de9e3820.png)

**Comment by lsabi** [comment]
In your case you are labeling the images to perform classification, which is different from object detection.

If you want to perform object detection, follow the gluon-cv link you linked.

If you follow tutorials of mxnet, then this is the wrong repository where to ask these kind of questions.

**Comment by ou525** [comment]
> Hi,
> 
> It's quite simple once you get the key idea. Try to follow my instructions.
> 
> 1. Create a folder, name it "myDataset".
> 2. Inside the folder you just created, create another folder, this time call it "VOC2019".
> 3. Inside the folder you just created (yeah, again), create three folders: "Annotations", "ImageSets" and "JPEGImages".
> 4. Inside the folder Annotations, put the annotation files structured as in the link you mentioned, while in the folder JPEGImages,  put the images in JPEG format. Note that the image name corresponds to the  annotation file with the same name.
> 5. In the folder ImageSets, create a folder (yep, another one) name "Main".
> 6. Inside the folder you just created, create a file "train.txt" with a list of names (one per line) corresponding to the images you want to be used for training (it will be taken from the folders Annotations and JPEGImages).
> 
> Following a code snippet that shows how to read your custom dataset.
> 
> ```
> classes = ['class1', class2', 'class3']
> 
> class VOCLike(VOCDetection):
>     CLASSES = classes
> 
>     def __init__(self, root, splits, transform=None, index_map=None, preload_label=True):
>         super(VOCLike, self).__init__(root, splits, transform, index_map, preload_label)
> 
> voc_dataset =VOCLike(root='/my/path/myDataset', splits=[(2019, 'train')])
> ```
> And now have fun with your custom dataset!

I have trained the results according to this method, there is an error, how can I solve it?

Traceback (most recent call last):
  File "demo_yolo.py", line 26, in <module>
    net.load_parameters('/home/ou/workplace/gluon-cv/scripts/detection/yolo/yolo3_darknet53_voc_best.params')
  File "/usr/local/lib/python2.7/dist-packages/mxnet/gluon/block.py", line 404, in load_parameters
    params[name]._load_init(loaded[name], ctx)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/gluon/parameter.py", line 237, in _load_init
    self.name, str(self.shape), str(data.shape))
AssertionError: Failed loading Parameter 'yolov30_yolooutputv32_conv0_weight' from saved params: shape incompatible expected (24L, 0L, 1L, 1L) vs saved (75L, 256L, 1L, 1L)

**Comment by lsabi** [comment]
Hi @ou525,

without the code it is difficult to say what the problem could be.

You should check that you are using the network with the same settings as when you trained it. The error seems from that.

**Comment by ou525** [comment]
at yolo_demo.py, i load the trained model.,as
net = model_zoo.get_model('yolo3_darknet53_custom', classes=['person', 'car', 'motorbike'],pretrained=False,ctx=mx.gpu(0))

net.load_parameters('/home/ou/workplace/gluon-cv/scripts/detection/yolo3_darknet53_voc_0040_0.7694.params',ctx=mx.gpu(0))

In the training script train_yolo3.py, the main changes are:
Class VOCLike(VOCDetection):
     CLASSES = ['person', 'car', 'dog']
     Def init(self, root, splits, transform=None, index_map=None, preload_label=True):
         Super(VOCLike, self).init(root, splits, transform, index_map, preload_label)

Def get_dataset1(dataset, args):
     Train_dataset = VOCLike(root='VOCtemplate', splits=((2018, 'trainval'),))
     Val_dataset = VOCLike(root='VOCtemplate', splits=((2018, 'test'),))
     Val_metric = VOC07MApMetric(iou_thresh=0.5, class_names=val_dataset.classes)
train command:
python train_yolo3.py --mixup --epochs 400 --lr 0.0001 --gpu 0 --batch-size 8 --num-workers 8
@lsabi

**Comment by lsabi** [comment]
In yolo_demo.py, you have three classes: 'person', 'car', 'motorbike' which do not match the classes of train_yolo3.py 'person', 'car', 'dog'

By changing the classes it should work

**Comment by ou525** [comment]
Sorry, these two are the same, it is a mistake when filling out the issue. Can you help me see it again? Thank you！@lsabi

**Comment by lsabi** [comment]
At line 26 og demo_yolo.py you are running the following line
`net.load_parameters('/home/ou/workplace/gluon-cv/scripts/detection/yolo/yolo3_darknet53_voc_best.params')`

but you are loading
`/home/ou/workplace/gluon-cv/scripts/detection/yolo3_darknet53_voc_0040_0.7694.params`

**Comment by ou525** [comment]
I tried it, but I still have the same error and can't work.@lsabi
Traceback (most recent call last):
  File "demo_yolo.py", line 27, in <module>
    net.load_parameters('/home/ou/workplace/gluon-cv/scripts/detection/yolo3_darknet53_voc_best.params',ctx=mx.gpu(0))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/gluon/block.py", line 404, in load_parameters
    params[name]._load_init(loaded[name], ctx)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/gluon/parameter.py", line 237, in _load_init
    self.name, str(self.shape), str(data.shape))
AssertionError: Failed loading Parameter 'yolov30_yolooutputv32_conv0_weight' from saved params: shape incompatible expected (24L, 0L, 1L, 1L) vs saved (75L, 256L, 1L, 1L)

**Comment by lsabi** [comment]
Which file have you modified? It seems that yolo3_darknet53_voc_best.params has been generated from a different network.

In the file train_yolo3.py, do you download the custom model and reset the classes of the net to the ones you need?

**Comment by ou525** [comment]
Thanks for the reply, the train_yolo3.py code is as follows, please help me to check the problem.@lsabi

"""Train YOLOv3 with random shapes."""
import argparse
import os
import logging
import time
import warnings
import numpy as np
import mxnet as mx
from mxnet import nd
from mxnet import gluon
from mxnet import autograd
import gluoncv as gcv
from gluoncv import data as gdata
from gluoncv import utils as gutils
from gluoncv.model_zoo import get_model
from gluoncv.data.batchify import Tuple, Stack, Pad
from gluoncv.data.transforms.presets.yolo import YOLO3DefaultTrainTransform
from gluoncv.data.transforms.presets.yolo import YOLO3DefaultValTransform
from gluoncv.data.dataloader import RandomTransformDataLoader
from gluoncv.utils.metrics.voc_detection import VOC07MApMetric
from gluoncv.utils.metrics.coco_detection import COCODetectionMetric
from gluoncv.utils import LRScheduler, LRSequential

from gluoncv.data import VOCDetection

class VOCLike(VOCDetection):
    CLASSES = ['person', 'car','motorbike']
    def __init__(self, root, splits, transform=None, index_map=None, preload_label=True):
        super(VOCLike, self).__init__(root, splits, transform, index_map, preload_label)

def parse_args():
    parser = argparse.ArgumentParser(description='Train YOLO networks with random input shape.')
    parser.add_argument('--network', type=str, default='darknet53',
                        help="Base network name which serves as feature extraction base.")
    parser.add_argument('--data-shape', type=int, default=416,
                        help="Input data shape for evaluation, use 320, 416, 608... " +
                             "Training is with random shapes from (320 to 608).")
    parser.add_argument('--batch-size', type=int, default=64,
                        help='Training mini-batch size')
    parser.add_argument('--dataset', type=str, default='voc',
                        help='Training dataset. Now support voc.')
    parser.add_argument('--num-workers', '-j', dest='num_workers', type=int,
                        default=4, help='Number of data workers, you can use larger '
                        'number to accelerate data loading, if you CPU and GPUs are powerful.')
    parser.add_argument('--gpus', type=str, default='0',
                        help='Training with GPUs, you can specify 1,3 for example.')
    parser.add_argument('--epochs', type=int, default=200,
                        help='Training epochs.')
    parser.add_argument('--resume', type=str, default='',
                        help='Resume from previously saved parameters if not None. '
                        'For example, you can resume from ./yolo3_xxx_0123.params')
    parser.add_argument('--start-epoch', type=int, default=0,
                        help='Starting epoch for resuming, default is 0 for new training.'
                        'You can specify it to 100 for example to start from 100 epoch.')
    parser.add_argument('--lr', type=float, default=0.001,
                        help='Learning rate, default is 0.001')
    parser.add_argument('--lr-mode', type=str, default='step',
                        help='learning rate scheduler mode. options are step, poly and cosine.')
    parser.add_argument('--lr-decay', type=float, default=0.1,
                        help='decay rate of learning rate. default is 0.1.')
    parser.add_argument('--lr-decay-period', type=int, default=0,
                        help='interval for periodic learning rate decays. default is 0 to disable.')
    parser.add_argument('--lr-decay-epoch', type=str, default='160,180',
                        help='epochs at which learning rate decays. default is 160,180.')
    parser.add_argument('--warmup-lr', type=float, default=0.0,
                        help='starting warmup learning rate. default is 0.0.')
    parser.add_argument('--warmup-epochs', type=int, default=0,
                        help='number of warmup epochs.')
    parser.add_argument('--momentum', type=float, default=0.9,
                        help='SGD momentum, default is 0.9')
    parser.add_argument('--wd', type=float, default=0.0005,
                        help='Weight decay, default is 5e-4')
    parser.add_argument('--log-interval', type=int, default=100,
                        help='Logging mini-batch interval. Default is 100.')
    parser.add_argument('--save-prefix', type=str, default='',
                        help='Saving parameter prefix')
    parser.add_argument('--save-interval', type=int, default=10,
                        help='Saving parameters epoch interval, best model will always be saved.')
    parser.add_argument('--val-interval', type=int, default=1,
                        help='Epoch interval for validation, increase the number will reduce the '
                             'training time if validation is slow.')
    parser.add_argument('--seed', type=int, default=233,
                        help='Random seed to be fixed.')
    parser.add_argument('--num-samples', type=int, default=-1,
                        help='Training images. Use -1 to automatically get the number.')
    parser.add_argument('--syncbn', action='store_true',
                        help='Use synchronize BN across devices.')
    parser.add_argument('--no-random-shape', action='store_true',
                        help='Use fixed size(data-shape) throughout the training, which will be faster '
                        'and require less memory. However, final model will be slightly worse.')
    parser.add_argument('--no-wd', action='store_true',
                        help='whether to remove weight decay on bias, and beta/gamma for batchnorm layers.')
    parser.add_argument('--mixup', action='store_true',
                        help='whether to enable mixup.')
    parser.add_argument('--no-mixup-epochs', type=int, default=20,
                        help='Disable mixup training if enabled in the last N epochs.')
    parser.add_argument('--label-smooth', action='store_true', help='Use label smoothing.')
    args = parser.parse_args()
    return args

def get_dataset(dataset, args):
    if dataset.lower() == 'voc':
        train_dataset = gdata.VOCDetection(
            splits=[(2007, 'trainval'), (2012, 'trainval')])
        val_dataset = gdata.VOCDetection(
            splits=[(2007, 'test')])
        val_metric = VOC07MApMetric(iou_thresh=0.5, class_names=val_dataset.classes)
    elif dataset.lower() == 'coco':
        train_dataset = gdata.COCODetection(splits='instances_train2017', use_crowd=False)
        val_dataset = gdata.COCODetection(splits='instances_val2017', skip_empty=False)
        val_metric = COCODetectionMetric(
            val_dataset, args.save_prefix + '_eval', cleanup=True,
            data_shape=(args.data_shape, args.data_shape))
    else:
        raise NotImplementedError('Dataset: {} not implemented.'.format(dataset))
    if args.num_samples < 0:
        args.num_samples = len(train_dataset)
    if args.mixup:
        from gluoncv.data import MixupDetection
        train_dataset = MixupDetection(train_dataset)
    return train_dataset, val_dataset, val_metric

def get_dataset1(dataset, args):
    if dataset.lower() == 'voc':
        train_dataset = VOCLike(root='VOCtemplate', splits=((2018, 'trainval'),))
        val_dataset = VOCLike(root='VOCtemplate', splits=((2018, 'test'),))
        val_metric = VOC07MApMetric(iou_thresh=0.5, class_names=val_dataset.classes)
    elif dataset.lower() == 'coco':
        train_dataset = gdata.COCODetection(splits='instances_train2017', use_crowd=False)
        val_dataset = gdata.COCODetection(splits='instances_val2017', skip_empty=False)
        val_metric = COCODetectionMetric(
            val_dataset, args.save_prefix + '_eval', cleanup=True,
            data_shape=(args.data_shape, args.data_shape))
    else:
        raise NotImplementedError('Dataset: {} not implemented.'.format(dataset))
    if args.num_samples < 0:
        args.num_samples = len(train_dataset)
    if args.mixup:
        from gluoncv.data import MixupDetection
        train_dataset = MixupDetection(train_dataset)
    return train_dataset, val_dataset, val_metric

def get_dataloader(net, train_dataset, val_dataset, data_shape, batch_size, num_workers, args):
    """Get dataloader."""
    width, height = data_shape, data_shape
    batchify_fn = Tuple(*([Stack() for _ in range(6)] + [Pad(axis=0, pad_val=-1) for _ in range(1)]))  # stack image, all targets generated
    if args.no_random_shape:
        train_loader = gluon.data.DataLoader(
            train_dataset.transform(YOLO3DefaultTrainTransform(width, height, net, mixup=args.mixup)),
            batch_size, True, batchify_fn=batchify_fn, last_batch='rollover', num_workers=num_workers)
    else:
        transform_fns = [YOLO3DefaultTrainTransform(x * 32, x * 32, net, mixup=args.mixup) for x in range(10, 20)]
        train_loader = RandomTransformDataLoader(
            transform_fns, train_dataset, batch_size=batch_size, interval=10, last_batch='rollover',
            shuffle=True, batchify_fn=batchify_fn, num_workers=num_workers)
    val_batchify_fn = Tuple(Stack(), Pad(pad_val=-1))
    val_loader = gluon.data.DataLoader(
        val_dataset.transform(YOLO3DefaultValTransform(width, height)),
        batch_size, False, batchify_fn=val_batchify_fn, last_batch='keep', num_workers=num_workers)
    return train_loader, val_loader

def save_params(net, best_map, current_map, epoch, save_interval, prefix):
    current_map = float(current_map)
    if current_map > best_map[0]:
        best_map[0] = current_map
        net.save_parameters('{:s}_best.params'.format(prefix, epoch, current_map))
        with open(prefix+'_best_map.log', 'a') as f:
            f.write('{:04d}:\t{:.4f}\n'.format(epoch, current_map))
    if save_interval and epoch % save_interval == 0:
        net.save_parameters('{:s}_{:04d}_{:.4f}.params'.format(prefix, epoch, current_map))

def validate(net, val_data, ctx, eval_metric):
    """Test on validation dataset."""
    eval_metric.reset()
    # set nms threshold and topk constraint
    net.set_nms(nms_thresh=0.45, nms_topk=400)
    mx.nd.waitall()
    net.hybridize()
    for batch in val_data:
        data = gluon.utils.split_and_load(batch[0], ctx_list=ctx, batch_axis=0, even_split=False)
        label = gluon.utils.split_and_load(batch[1], ctx_list=ctx, batch_axis=0, even_split=False)
        det_bboxes = []
        det_ids = []
        det_scores = []
        gt_bboxes = []
        gt_ids = []
        gt_difficults = []
        for x, y in zip(data, label):
            # get prediction results
            ids, scores, bboxes = net(x)
            det_ids.append(ids)
            det_scores.append(scores)
            # clip to image size
            det_bboxes.append(bboxes.clip(0, batch[0].shape[2]))
            # split ground truths
            gt_ids.append(y.slice_axis(axis=-1, begin=4, end=5))
            gt_bboxes.append(y.slice_axis(axis=-1, begin=0, end=4))
            gt_difficults.append(y.slice_axis(axis=-1, begin=5, end=6) if y.shape[-1] > 5 else None)

        # update metric
        eval_metric.update(det_bboxes, det_ids, det_scores, gt_bboxes, gt_ids, gt_difficults)
    return eval_metric.get()

def train(net, train_data, val_data, eval_metric, ctx, args):
    """Training pipeline"""
    net.collect_params().reset_ctx(ctx)
    if args.no_wd:
        for k, v in net.collect_params('.*beta|.*gamma|.*bias').items():
            v.wd_mult = 0.0

    if args.label_smooth:
        net._target_generator._label_smooth = True

    if args.lr_decay_period > 0:
        lr_decay_epoch = list(range(args.lr_decay_period, args.epochs, args.lr_decay_period))
    else:
        lr_decay_epoch = [int(i) for i in args.lr_decay_epoch.split(',')]
    lr_decay_epoch = [e - args.warmup_epochs for e in lr_decay_epoch]
    num_batches = args.num_samples // args.batch_size
    lr_scheduler = LRSequential([
        LRScheduler('linear', base_lr=0, target_lr=args.lr,
                    nepochs=args.warmup_epochs, iters_per_epoch=num_batches),
        LRScheduler(args.lr_mode, base_lr=args.lr,
                    nepochs=args.epochs - args.warmup_epochs,
                    iters_per_epoch=num_batches,
                    step_epoch=lr_decay_epoch,
                    step_factor=args.lr_decay, power=2),
    ])

    trainer = gluon.Trainer(
        net.collect_params(), 'sgd',
        {'wd': args.wd, 'momentum': args.momentum, 'lr_scheduler': lr_scheduler},
        kvstore='local')

    # targets
    sigmoid_ce = gluon.loss.SigmoidBinaryCrossEntropyLoss(from_sigmoid=False)
    l1_loss = gluon.loss.L1Loss()

    # metrics
    obj_metrics = mx.metric.Loss('ObjLoss')
    center_metrics = mx.metric.Loss('BoxCenterLoss')
    scale_metrics = mx.metric.Loss('BoxScaleLoss')
    cls_metrics = mx.metric.Loss('ClassLoss')

    # set up logger
    logging.basicConfig()
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    log_file_path = args.save_prefix + '_train.log'
    log_dir = os.path.dirname(log_file_path)
    if log_dir and not os.path.exists(log_dir):
        os.makedirs(log_dir)
    fh = logging.FileHandler(log_file_path)
    logger.addHandler(fh)
    logger.info(args)
    logger.info('Start training from [Epoch {}]'.format(args.start_epoch))
    best_map = [0]
    for epoch in range(args.start_epoch, args.epochs):
        if args.mixup:
            # TODO(zhreshold): more elegant way to control mixup during runtime
            try:
                train_data._dataset.set_mixup(np.random.beta, 1.5, 1.5)
            except AttributeError:
                train_data._dataset._data.set_mixup(np.random.beta, 1.5, 1.5)
            if epoch >= args.epochs - args.no_mixup_epochs:
                try:
                    train_data._dataset.set_mixup(None)
                except AttributeError:
                    train_data._dataset._data.set_mixup(None)

        tic = time.time()
        btic = time.time()
        mx.nd.waitall()
        net.hybridize()
        for i, batch in enumerate(train_data):
            batch_size = batch[0].shape[0]
            data = gluon.utils.split_and_load(batch[0], ctx_list=ctx, batch_axis=0)
            # objectness, center_targets, scale_targets, weights, class_targets
            fixed_targets = [gluon.utils.split_and_load(batch[it], ctx_list=ctx, batch_axis=0) for it in range(1, 6)]
            gt_boxes = gluon.utils.split_and_load(batch[6], ctx_list=ctx, batch_axis=0)
            sum_losses = []
            obj_losses = []
            center_losses = []
            scale_losses = []
            cls_losses = []
            with autograd.record():
                for ix, x in enumerate(data):
                    obj_loss, center_loss, scale_loss, cls_loss = net(x, gt_boxes[ix], *[ft[ix] for ft in fixed_targets])
                    sum_losses.append(obj_loss + center_loss + scale_loss + cls_loss)
                    obj_losses.append(obj_loss)
                    center_losses.append(center_loss)
                    scale_losses.append(scale_loss)
                    cls_losses.append(cls_loss)
                autograd.backward(sum_losses)
            trainer.step(batch_size)
            obj_metrics.update(0, obj_losses)
            center_metrics.update(0, center_losses)
            scale_metrics.update(0, scale_losses)
            cls_metrics.update(0, cls_losses)
            if args.log_interval and not (i + 1) % args.log_interval:
                name1, loss1 = obj_metrics.get()
                name2, loss2 = center_metrics.get()
                name3, loss3 = scale_metrics.get()
                name4, loss4 = cls_metrics.get()
                logger.info('[Epoch {}][Batch {}], LR: {:.2E}, Speed: {:.3f} samples/sec, {}={:.3f}, {}={:.3f}, {}={:.3f}, {}={:.3f}'.format(
                    epoch, i, trainer.learning_rate, batch_size/(time.time()-btic), name1, loss1, name2, loss2, name3, loss3, name4, loss4))
            btic = time.time()

        name1, loss1 = obj_metrics.get()
        name2, loss2 = center_metrics.get()
        name3, loss3 = scale_metrics.get()
        name4, loss4 = cls_metrics.get()
        logger.info('[Epoch {}] Training cost: {:.3f}, {}={:.3f}, {}={:.3f}, {}={:.3f}, {}={:.3f}'.format(
            epoch, (time.time()-tic), name1, loss1, name2, loss2, name3, loss3, name4, loss4))
        if not (epoch + 1) % args.val_interval:
            # consider reduce the frequency of validation to save time
            map_name, mean_ap = validate(net, val_data, ctx, eval_metric)
            val_msg = '\n'.join(['{}={}'.format(k, v) for k, v in zip(map_name, mean_ap)])
            logger.info('[Epoch {}] Validation: \n{}'.format(epoch, val_msg))
            current_map = float(mean_ap[-1])
        else:
            current_map = 0.
        save_params(net, best_map, current_map, epoch, args.save_interval, args.save_prefix)

if __name__ == '__main__':
    args = parse_args()
    # fix seed for mxnet, numpy and python builtin random generator.
    gutils.random.seed(args.seed)

    # training contexts
    ctx = [mx.gpu(int(i)) for i in args.gpus.split(',') if i.strip()]
    ctx = ctx if ctx else [mx.cpu()]

    # network
    net_name = '_'.join(('yolo3', args.network, args.dataset))
    args.save_prefix += net_name
    # use sync bn if specified
    if args.syncbn and len(ctx) > 1:
        net = get_model(net_name, pretrained_base=True, norm_layer=gluon.contrib.nn.SyncBatchNorm,
                        norm_kwargs={'num_devices': len(ctx)})
        async_net = get_model(net_name, pretrained_base=False)  # used by cpu worker
    else:
        net = get_model(net_name, pretrained_base=True)
        async_net = net
        print(2222222)
    if args.resume.strip():
        net.load_parameters(args.resume.strip())
        async_net.load_parameters(args.resume.strip())
    else:
        with warnings.catch_warnings(record=True) as w:
            warnings.simplefilter("always")
            net.initialize()
            async_net.initialize()

    # training data
    train_dataset, val_dataset, eval_metric = get_dataset1(args.dataset, args)
    train_data, val_data = get_dataloader(
        async_net, train_dataset, val_dataset, args.data_shape, args.batch_size, args.num_workers, args)

    # training
    train(net, train_data, val_data, eval_metric, ctx, args)

use command
python train_yolo3.py --mixup --epochs 400 --lr 0.0001 --gpu 0 --batch-size 8 --num-workers 8

**Comment by lsabi** [comment]
The problem lies at line

net_name = '_'.join(('yolo3', args.network, args.dataset))

I don't remember the exact parameter names, but it would be easier to use as net name "yolo3_darknet53_custom" and when loading the net, defining the custom classes. In your case, you are downloading the yolo network with the default classes (should be 80).

The error you get when loading the parameters is due to the fact that the trained parameters has 80 output classes, while the network you load in "demo_yolo.py" has only 3 output classes.

**Comment by ou525** [comment]
You mean that my training network should not use yolo3_darknet53_voc, but should use yolo3_darknet53_custom directly, can you specifically explain how to modify the code?@lsabi

**Comment by ou525** [comment]
I tried to modify it, but this error occurred.
    # net_name = '_'.join(('yolo3', args.network, args.dataset))
    net_name = 'yolo3_darknet53_custom'
TypeError: yolo3_darknet53_custom() takes at least 1 argument (1 given)

**Comment by lsabi** [comment]
Try with the following, though I did not test it since I never use this training script, but I use one that I wrote myself for other networks

# training contexts
ctx = [mx.gpu(int(i)) for i in args.gpus.split(',') if i.strip()]
ctx = ctx if ctx else [mx.cpu()]

# network
#net_name = '_'.join(('yolo3', args.network, args.dataset))
net_name = 'yolo3_darknet53_custom'
args.save_prefix += net_name
# use sync bn if specified
if args.syncbn and len(ctx) > 1:
    net = get_model(net_name, pretrained_base=True, norm_layer=gluon.contrib.nn.SyncBatchNorm,
                    norm_kwargs={'num_devices': len(ctx)}, **transfer='voc', classes=my_classes**)
    async_net = get_model(net_name, pretrained_base=False, **classes=my_classes**)  # used by cpu worker
else:
    net = get_model(net_name, pretrained_base=True, **transfer='voc', classes=my_classes**)
    async_net = net
    print(2222222)

**Comment by ou525** [comment]
I try to do it. thank you very mach
