### ISSUE TITLE
train mask_rcnn with fpn

### ISSUE THREAD

**Issue by HannibalAPE** [dmlc/gluon-cv#694]
I met  a few problems when training the mask_rcnn with fpn:

1. when I initialized stage_anchor_generator( in class RPN __init__  ) with s for s in scales, my training loss is really starnge( very huge numbers). Then, I changed scales with:
    1) scales=[2, 4, 8, 16, 32, 64, 128]
    2) scales = tuple(zip(scales[:-2], scales[1:-1], scales[2:]))
  and the loss looks common. Does it make sense? 

2. I tried to load params of mask_rcnn_fpn_resnet50_v1b_coco, but got an error: 
AssertionError: Parameter 'box_featueres.1.weight' is missing in file './models/mask_rcnn_fpn_resnet50_v1b_coco-1364d0af.params', which contains parameters: 'features.resnetv1b_conv0_weight', 'features.resnetv1b_batchnorm0_gamma', 'features.resnetv1b_batchnorm0_beta', ..., 'mask.deconv.8.weight', 'mask.deconv.8.bias', 'mask.mask.weight', 'mask.mask.bias'. Set allow_missing=True to ignore missing parameters.

3. Even I set net.hybridize(static_alloc=False), my training sometimes stops with 'cudaMalloc failed: out of memory' as well.

Thanks in advance!

**Comment by Jerryzcn** [comment]
1. Probably because there are only 5 level of features in FPN, so the extra scales probably has no where to go.
2. I uploaded the wrong model. Will fix soon.
3. We trained the model on 16GB of vram. you can try turn hybridization off. MaskRCNN does take quite a lot of memory. One possible solution is to write RCNN target generator on CPU instead of on GPU to save memory.

**Comment by Jerryzcn** [comment]
@HannibalAPE Which version of mxnet are you using? I was able to load mask_rcnn_fpn_resnet50_v1b_coco using 
``net = gcv.model_zoo.faster_rcnn_fpn_resnet50_v1b_coco(pretrained=True)``

**Comment by Jerryzcn** [comment]
@HannibalAPE which version of mxnet are you using? I was able to load the pretrained model using
``net = gcv.model_zoo.mask_rcnn_fpn_resnet50_v1b_coco(pretrained=True)``

**Comment by HannibalAPE** [comment]
@Jerryzcn mxnet==1.5.0b20181215, I may change to a new version?

**Comment by Jerryzcn** [comment]
Can you try loading it under source directory

**Comment by HannibalAPE** [comment]
I tried under source directory, and loaded the model successfully. I'll check my code later.
Another question confused me a lot. why is the training memory not a fix size using gluon.
Thanks a lot. sorry to bother you.

**Comment by HannibalAPE** [comment]
@Jerryzcn This issue can be closed. Thanks.

**Comment by Jerryzcn** [comment]
Because the input size is different for each example. eg. image resolution as well as number of targets.
