### ISSUE TITLE
OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by essalahsouad** [dmlc/gluon-cv#698]
when i was trying to prepare voc dataset for training pre trained model [https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html#derive-from-pascal-voc-format](url)
 i got this error
    OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory
`from gluoncv.data import VOCDetection class VOCLike(VOCDetection): 
CLASSES = ['iris'] 
def __init__(self, root, splits, transform=None, index_map=None, preload_label=True): super(VOCLike, self).__init__(root, splits, transform, index_map, preload_label) 
dataset = VOCLike(root='/home/dell/Bureau/myDataset', splits=((2019, 'train'),)) print(dataset[0][1])`
Knowing that I can't use cuda or gpu because i haven't a graphic card nvidia
python 3.6
os ubuntu 18
Pillow-5.4.1 gluoncv-0.4.0 scipy-1.2.1 tqdm-4.31.1

**Comment by Jerryzcn** [comment]
Are you trying to train on CPU?

**Comment by essalahsouad** [comment]
yes

**Comment by PistonY** [comment]
make sure you cuda version is 9.0.
And add below to ~/.bashrc.
```
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```
run
```bash
source  ~/.bashrc
```
Add below to /etc/ld.so.conf.d/cuda.conf
```
/usr/local/cuda/lib64
```
run
```bash
sudo ldconfig
```

**Comment by essalahsouad** [comment]
@PistonY 
can i use cuda and i don't have nvidia graphic card????

**Comment by Jerryzcn** [comment]
what is the command you are using?

**Comment by essalahsouad** [comment]
@Jerryzcn 
i'm not using a cmd command i just try to run a python code 
![Capture du 2019-03-22 `14-18-38](https://user-images.githubusercontent.com/34586193/54825255-68a1d400-4cad-11e9-86db-4def18e351e2.png)
[https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html#derive-from-pascal-voc-format](url)

**Comment by Jerryzcn** [comment]
which version of mxnet did you install?  You might have installed the version that's built with CUDA. Try install the cpu version, or build from source and set CUDA to 0

**Comment by essalahsouad** [comment]
@Jerryzcn
mxnet  '1.4.0'
no i have already installed the version compatible with Inux and cpu
[https://mxnet.apache.org/versions/master/install/index.html?platform=Linux&language=Python&processor=CPU](url)

**Comment by xinyu-intel** [comment]
@essalahsouad try "import mxnet as mx", does this work well?

**Comment by essalahsouad** [comment]
@xinyu-intel 
yes, it does work

**Comment by Jerryzcn** [comment]
did you install gluoncv using pip or build from source

**Comment by essalahsouad** [comment]
@Jerryzcn 
I have installed with pip

**Comment by Jerryzcn** [comment]
Could you try install from source?

**Comment by SaidaSaad** [comment]
Hello i have the same problem and i am using nvidia rtx 2080

**Comment by Jerryzcn** [comment]
our default pip install package assume GPU support. So you will probably need to install from source to use non-gpu version. If you encounter this issue while using GPU, it is likely that your CUDA path is not added correctly, or your mxnet version is incompatible with the CUDA version.
