### ISSUE TITLE
export_block, should it export data_shape in json file?

### ISSUE THREAD

**Issue by jnorwood** [dmlc/gluon-cv#701]
I'm trying out the exercise from [https://gluon-cv.mxnet.io/build/examples_deployment/export_network.html#sphx-glr-build-examples-deployment-export-network-py](url)

I noticed one of the parameters to export_block is data_shape, and so I tried it in my example. I was expecting to see this shape for the data somewhere in the exported json file, but I don't see it, and If I load this model in netron, the input data has no defined shape.  Is it intended that this shape be exported in the json file?  If so, it seems to be broken.

I'm working from the nightly build.

`
import mxnet as mx

import gluoncv as gcv

from gluoncv.utils import export_block

model_name = 'MobileNetV2_1.0' 

net = gcv.model_zoo.get_model(model_name, pretrained=True)

export_block('./exported/'+model_name, net,data_shape=(224, 224, 3), preprocess=True, layout='HWC')

print('Done.')

`

**Comment by amr-elsehemy** [comment]
I've the same problem and can't proceed with the model after exporting it with the following error : 
**operands could not be broadcast together with shapes [1,3,512,512] [1,1,1,3]**

below is my code snippet
`
ctx = mx.gpu() if mx.test_utils.list_gpus() else mx.cpu()
classes = ['gauge', 'needle'] 
net = gcv.model_zoo.get_model('ssd_512_mobilenet1.0_voc', pretrained=True)
net.reset_class(classes)
net.load_parameters('ssd_512_mobilenet1.0_my_custom_model.params')
export_block('test', net, data_shape=(512,512,3), layout="CHW")
net = gluon.nn.SymbolBlock.imports("test-symbol.json", ['data'], "test-0000.params", ctx=ctx)
x, image = gcv.data.transforms.presets.ssd.load_test('street_small.jpg', 512)
cid, score, bbox = net(x)
`
