### ISSUE TITLE
mixup error!

### ISSUE THREAD

**Issue by lucheng07082221** [dmlc/gluon-cv#710]
when I use this command:

python3 train_yolo3.py --network darknet53 --dataset voc --gpus 0 --batch-size 4 -j 4 --log-interval 100 --lr-decay-epoch 80,90 --epochs 100 --warmup-epochs 2 --mixup --no-mixup-epochs 20 --label-smooth --no-wd
 
but i found the code enter this part:

        if lambd >= 1:
            weights1 = np.ones((label1.shape[0], 1))
            label1 = np.hstack((label1, weights1))
            return img1, label1

I very curious why don't enter the rest part？:

  # second image
        idx2 = np.random.choice(np.delete(np.arange(len(self)), idx))
        img2, label2 = self._dataset[idx2]

        # mixup two images
        height = max(img1.shape[0], img2.shape[0])
        width = max(img1.shape[1], img2.shape[1])
        mix_img = mx.nd.zeros(shape=(height, width, 3), dtype='float32')
        mix_img[:img1.shape[0], :img1.shape[1], :] = img1.astype('float32') * lambd
        mix_img[:img2.shape[0], :img2.shape[1], :] += img2.astype('float32') * (1. - lambd)
        mix_img = mix_img.astype('uint8')
        y1 = np.hstack((label1, np.full((label1.shape[0], 1), lambd)))
        y2 = np.hstack((label2, np.full((label2.shape[0], 1), 1. - lambd)))
        mix_label = np.vstack((y1, y2))
        print("mixup done!")
        return mix_img, mix_label

**Comment by lucheng07082221** [comment]
change this code for i, batch in enumerate(train_data): to

for i, batch in enumerate(train_data._dataset):
this can solve problem

**Comment by zhreshold** [comment]
mixup ratio is explicitly set during training time.

**Comment by zimenglan-sysu-512** [comment]
hi @zhreshold 
does u mean that the weights in `mix_label` in `MixupDetection` do not use, instead, it uses `mixup_ratio` to balance the losses?

**Comment by zh-plus** [comment]
Because the lambd variable is valid only if lambd is in (0, 1). Mixup is roughly getting the mixture of two images using lambd and (1 - lambd) weights. Thus, it makes no sense to let lambd >= 1.
