### ISSUE TITLE
how to use my trained model

### ISSUE THREAD

**Issue by ou525** [dmlc/gluon-cv#711]
Thanks for the contribution. I want to train my model in voc dataset format. I tried modifying gluon-cv/gluoncv/data/pascal_voc/detection.py, reducing some of the categories and starting training. I would like to ask how to use the trained params file to export the json file to be able to be used in a C++ project.@zhreshold

**Comment by zhreshold** [comment]
I don't understand, are you using voc to train a network with less than 20 classes?

If you want to reduce number of categories, you don't need to train actually:

```python
net = gcv.model_zoo.get_model('yolo3_darkenet53_voc', pretrained=True)
net.reset_class(['person', 'dog', 'cat', 'car'], reuse_weights=['person', 'dog', 'cat', 'car'])
gcv.utils.export_block('customized_net', net)
```

**Comment by ou525** [comment]
Thanks Reply. Sorry, maybe I didn't make it clear. I will use my own sample of images to train the yolov3 network in the voc dataset format, not just to reduce the classification. Also ask if the reuse pretrain model will affect the detection performance.@zhreshold

**Comment by zhreshold** [comment]
Check this for finetuning https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html

**Comment by ou525** [comment]
I read the tutorial, but it does not explain how the trained model is used in C++.

**Comment by ou525** [comment]
Sorry, ask again. I used the official website tutorial to train my own data set, but the result was wrong when used: AssertionError: Failed loading Parameter 'yolov30_yolooutputv32_conv0_weight' from saved params: shape incompatible expected (24L, 0L, 1L, 1L) vs saved (75L, 256L, 1L, 1L).
In the training script train_yolo3.py, the main changes are:
Class VOCLike(VOCDetection):
     CLASSES = ['person', 'car', 'dog']
     Def __init__(self, root, splits, transform=None, index_map=None, preload_label=True):
         Super(VOCLike, self).__init__(root, splits, transform, index_map, preload_label)

Def get_dataset1(dataset, args):
     Train_dataset = VOCLike(root='VOCtemplate', splits=((2018, 'trainval'),))
     Val_dataset = VOCLike(root='VOCtemplate', splits=((2018, 'test'),))
     Val_metric = VOC07MApMetric(iou_thresh=0.5, class_names=val_dataset.classes)

How can I solve this problem?@zhreshold
