### ISSUE TITLE
freeze_support() issue on Windows for training on GPU

### ISSUE THREAD

**Issue by JacobusS** [dmlc/gluon-cv#715]
Hi,

When I run a training model from 2. Dive Deep into Training with CIFAR10
(https://gluon-cv.mxnet.io/build/examples_classification/dive_deep_cifar10.html#sphx-glr-download-build-examples-classification-dive-deep-cifar10-py)

I get the error below.
I have found an unrelated forum where someone said I should include the code in a 

def main():

and call 
if __name__ == "__main__":
     main()

This didn't give me an error but it seems that mxnet then runs on my CPU and not the GPU.

any suggestions?

**I'm running** 
-Windows 10
-Anaconda python 3 environment 
-Cuda compilation tools, release 9.0, V9.0.176
-mxnet-cu90

**ERROR**: 

_File "C:\Users\User-PC\Anaconda3\envs\glu\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe_

Thanks,

**Comment by zhreshold** [comment]
please wrap you training script in
```
if __name__ == '__main__':
```
due the the fact windows are using spawn rather than fork.

**Comment by JacobusS** [comment]
Thanks zhreshold, it works now. 
Thanks for your help, mush appreciated.

**Comment by kalcohol** [comment]
> please wrap you training script in
> 
> ```
> if __name__ == '__main__':
> ```
> due the the fact windows are using spawn rather than fork.

@zhreshold hi, i am new to python, i do not get the point "please wrap you training script in", could u explain some more detials?
