### ISSUE TITLE
Fine-tuning and train on my own dataset

### ISSUE THREAD

**Issue by FAFACHR** [dmlc/gluon-cv#716]
Hello, 
I'm doing instance segmentation for a specific data. I prepared my own dataset similar to coco format because gluoncv just support coco and my dataset contain just 3 classes, I trained my data from scratch and it works. I would like to do a fine-tuning because I don't have enough data and not to encounter overfitting. Is there any way to replace the output layer of the pre-trained model "mask_rcnn_resnet50_v1b_coco" to fit the right number of classes for my own images? @zhreshold

**Comment by zhreshold** [comment]
try this:

```python
net = gcv.model_zoo.get_model('mask_rcnn_resnet50_v1b_coco', pretrained=True)
net.reset_class(['your_class1', 'your_class2', 'your_class3'])
```

**Comment by fouadchacccour** [comment]
Thank you for your reply,
I should try this in training code or inference ? 
If i use this function ''reset_class'' in training code and inference code i got this error : 
"Failed loading Parameter 'maskrcnn0_dense1_weight' from saved params: shape incompatible expected (320, 0) vs saved (8L, 2048L)"
and if i use it just in the inference code i got this error : 
"Cannot reset context for Parameter 'maskrcnn0_maskrcnn0_dense0_weight' because it has not been initialized."
Do you have any solution please ? @zhreshold

**Comment by zhreshold** [comment]
![image](https://user-images.githubusercontent.com/3307514/55424652-9e5c7d80-5535-11e9-96af-38c279af0798.png)
If you have problems with it, try update gluoncv first. 

You can use it either in training or inference, but for inference you need to load parameters trained by you own otherwise it's random weights for the outpout

**Comment by FAFACHR** [comment]
Forgive me if I'm asking dumb questions, I updated gluoncv package and I tried to reset my classes with "net.reset_class" as you said, but I got an error : 
"mxnet.base.MXNetError: [08:27:47] src/ndarray/ndarray.cc:253: Check failed: shape_.Size() == shape.Size() (2007040 vs. 50176) NDArray.Reshape: target shape must have the same size as current shape when recording with autograd.". Is this because my image size or is it another matter?

**Comment by zhreshold** [comment]
@FAFACHR are you reset_class in autograd.record mode? You should only reset once before training

**Comment by FAFACHR** [comment]
I'm using the reset_class function before the training process and it gives me the same error.
This is the train_mask_rcnn.py and i reset the classes after the get_model in the main function @zhreshold 

![Screenshot from 2019-04-10 09-01-26](https://user-images.githubusercontent.com/34231991/55858182-5231be80-5b6f-11e9-8481-9bf3c29988cd.png)

**Comment by zhreshold** [comment]
Ok, I think it's because dataset still generates training targets for entire 80 classes in COCO, which is a bug from reset_class.

The fix has been pushed: https://github.com/dmlc/gluon-cv/pull/733

**Comment by FAFACHR** [comment]
Thank you so much @zhreshold it works and all is good now.

**Comment by YuhanLiu11** [comment]
@FAFACHR Hi! I am wondering how you launch the model using three classes because I could not get it run. Do you have some code examples or steps to follow to use customized dataset in coco format?

**Comment by FAFACHR** [comment]
Hello @YuhanLiu11, first thing you need to have the labels of your dataset (The mask and the bounding box) in a json file in coco format, for this you can use COCO annotator, this tool is good and you can generate the labels in the coco format. Find the link below for the annotator:

> https://github.com/jsbroks/coco-annotator

Second step you need to know how the mask rcnn script and gluon read the dataset and replace the coco dataset with your own dataset and labels.
After doing these 2 steps you need to add to mask rcnn training script your classes, to do this you can use:

> net.reset_class(['your_class1', 'your_class2', 'your_class3'])

**Comment by YuhanLiu11** [comment]
> Hello @YuhanLiu11, first thing you need to have the labels of your dataset (The mask and the bounding box) in a json file in coco format, for this you can use COCO annotator, this tool is good and you can generate the labels in the coco format. Find the link below for the annotator:
> 
> > https://github.com/jsbroks/coco-annotator
> 
> Second step you need to know how the mask rcnn script and gluon read the dataset and replace the coco dataset with your own dataset and labels.
> After doing these 2 steps you need to add to mask rcnn training script your classes, to do this you can use:
> 
> > net.reset_class(['your_class1', 'your_class2', 'your_class3'])

Hi thanks for your help! However, I used COCO dataset format and replaced the dataset, and then when I use net.reset_class , there is an error 

Traceback (most recent call last):
  File "/srv/home/yliu/mxnet2/train_mask_rcnn.py", line 519, in <module>
    net.reset_class(['111','bd','100'])
  File "/srv/home/yliu/mxnet2/gluon/gluoncv/model_zoo/mask_rcnn/mask_rcnn.py", line 322, in reset_class
    super(MaskRCNN, self).reset_class(classes=classes, reuse_weights=reuse_weights)
  File "/srv/home/yliu/mxnet2/gluon/gluoncv/model_zoo/faster_rcnn/faster_rcnn.py", line 245, in reset_class
    super(FasterRCNN, self).reset_class(classes, reuse_weights)
  File "/srv/home/yliu/mxnet2/gluon/gluoncv/model_zoo/rcnn/rcnn.py", line 217, in reset_class
    ctx = list(old_class_pred.params.values())[0].list_ctx()
  File "/srv/home/yliu/anaconda3/envs/mxnet3/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 588, in list_ctx
    raise RuntimeError("Parameter '%s' has not been initialized"%self.name)
RuntimeError: Parameter 'maskrcnn0_dense0_weight' has not been initialized

Have you encountered problems like this? 

Thanks so much!!

**Comment by mobguang** [comment]
Hi @FAFACHR @zhreshold ,

Thanks for your explanation. I want to train my own dataset (I annotated the images by 'labelme'), but I don't know how to set the training parameters for my training.

Could you please kindly provide a sample of the parameter setting for customer dataset training?

Thanks in advance!
