### ISSUE TITLE
Unable to export SSD model to ONNX

### ISSUE THREAD

**Issue by Rmwak** [dmlc/gluon-cv#718]
I'm trying to convert a gluon SSDmodel from the model zoo to the ONNX format. In the documentation, it seems that the steps should be:

1. Get / train a gluon model
2. Hybridize the model
3. Export to mxnet
4. Convert to ONNX

But after those steps, this error is thrown:

`ValueError: invalid literal for int() with base 10: 'None'`

I have tried this with multiple combinations of versions from gluon(0.4-0.5), mxnet(from 1.3 to 1.5) and onnx(from 1.2 to 1.4).

The Mxnet tutorial [here](https://mxnet.incubator.apache.org/versions/master/tutorials/onnx/export_mxnet_to_onnx.html) works correctly with those exact library versions and model, but seems that a gluon one fails.

Minimal steps to reproduce:

```
from gluoncv import model_zoo
import mxnet as mx
import numpy as np
from mxnet.contrib import onnx as onnx_mxnet

net = model_zoo.get_model('ssd_512_resnet50_v1_voc', pretrained=True)
net.hybridize()
fake_image = mx.nd.random.uniform(shape=(1,3,512,512), ctx=mx.cpu())
result = net(fake_image)
net.export('default_net')
sym = 'default_net-symbol.json'
params = 'default_net-0000.params'
input_shape = (1,3,512,512)
onnx_file = 'default_net.onnx'
converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file, verbose=True)
```

**Comment by Xie-Xiaopu** [comment]
You are not alone. ONNX is not support all MXNet OP.

In ssd, the 'None' is a parameter in [MultiClassDecoder](https://github.com/dmlc/gluon-cv/blob/0dbd05c5eb8537c25b64f0e87c09be979303abf2/gluoncv/nn/coder.py#L252).

**Comment by Rmwak** [comment]
Thanks Xie.

Should I open a feature request for this? Is it worth it?

**Comment by leacornelio** [comment]
Were you able to solve this?

**Comment by CoinCheung** [comment]
It seem that it even does not support the resnet18 in the model zoo. There would be errors associated with batchnorm.

**Comment by zhreshold** [comment]
@Rmwak  workaround: 

```python
net.set_nms(-1)
```

Than you can try export to onnx or something else. The drawback is that you have to perform NMS youself.
