### ISSUE TITLE
How do you prune resnet? 

### ISSUE THREAD

**Issue by zhch-sun** [dmlc/gluon-cv#719]
Hi guys, thanks for the awesome work! I want to know how do you prune ResNet? Are you going to open-source the pruning code?

**Comment by hetong007** [comment]
The code and writing are contributed by AWS and they are undergoing through the internal approval process to publish them. Once it is done we will have link to these materials.

**Comment by zhch-sun** [comment]
thank you

**Comment by leejiajun** [comment]
I am searching a model resnet50_v1d_0.75 or resnet50_v1d_0.65.
