### ISSUE TITLE
'ParameterDict' object has no attribute 'get_constant'

### ISSUE THREAD

**Issue by universewill** [dmlc/gluon-cv#72]
i run command 'model_zoo.ssd.ssd_512_resnet152_v2_voc(pretrained=True)' and get this error.
Command 'model_zoo.ssd.ssd_512_resnet50_v1_voc(pretrained=True)' also get this error

**Comment by piiswrong** [comment]
you need to update mxnet. Use pip install --pre mxnet

**Comment by likangGit** [comment]
I also encountered this problem. After using `pip install --pre mxnet` update mxnet to version 0.12.1, the problem is still there. @piiswrong  Did you solve this problem？ @universewill
