### ISSUE TITLE
GPU error

### ISSUE THREAD

**Issue by haihaixia** [dmlc/gluon-cv#724]
while running training file，I set the GPU to gpu(1), I got this error I know its GPU error but I dont know how to resolve it can you help me out? If the starting gpu number must be 0 ?
mxnet.base.MXNetError: [13:48:30] src/engine/threaded_engine.cc:330: Check failed: exec_ctx.dev_id < device_count_ (1 vs. 1) Invalid GPU Id: 1, Valid device id should be less than device_count: 1

**Comment by anirudh2290** [comment]
This error is caused by number of GPUs available on your machine being less than 2. If this is the case please use gpu(0).

**Comment by haihaixia** [comment]
Actually,I have 4 gpus on my machine.There is no error when I use gup(0),I'm just meet this error when I use one or some of gpu(1) 、gpu(2)、gpu(3),but not starting using gpu(0).I suspect if it only start with gpu0?

**Comment by hetong007** [comment]
First make sure you see 4 GPUs when executing `nvidia-smi`. If not, it means your system cannot see all of your GPUs.

**Comment by bryanyzhu** [comment]
Please add `CUDA_VISIBLE_DEVICES=0,1,2,3` before running your python script, this will explicitly force the code to see all of your GPUs. The problem should be solved. 

Otherwise, the code is default to see only the first GPU, which is gpu(0). When you call gpu(1), you will get this error.
