### ISSUE TITLE
How to use gluoncv's pretrained classification model as the backbone of detection?

### ISSUE THREAD

**Issue by mrbulb** [dmlc/gluon-cv#729]
Hello, I'm a freshman to Gluon and not very familiar with this framework. I want to ask a question about detection part in gluon-cv
Gluon-cv has provided many pretrained model for us to load. But it seems can only load the whole model which contains both the feature extraction part(base network or backbone) and the left detection part.
I want to test the performance of detction alogrithm(e.g. yolo ssd) under **different backbone**(e.g. vgg, resnet.). 
Is there any way I can easy load gluon-cv's pretrained classification model as a backbone and integrate it to detection model?

**Comment by lgov** [comment]
Gluon-CV already provides quite some pre-defined and pre-trained combinations for SSD:
'ssd_300_vgg16_atrous_voc',
           'ssd_300_vgg16_atrous_coco',
           'ssd_300_vgg16_atrous_custom',
           'ssd_512_vgg16_atrous_voc',
           'ssd_512_vgg16_atrous_coco',
           'ssd_512_vgg16_atrous_custom',
           'ssd_512_resnet18_v1_voc',
           'ssd_512_resnet18_v1_coco',
           'ssd_512_resnet18_v1_custom',
           'ssd_512_resnet50_v1_voc',
           'ssd_512_resnet50_v1_coco',
           'ssd_512_resnet50_v1_custom',
           'ssd_512_resnet101_v2_voc',
           'ssd_512_resnet152_v2_voc',
           'ssd_512_mobilenet1_0_voc',
           'ssd_512_mobilenet1_0_coco',
           'ssd_512_mobilenet1_0_custom'

You pick the one you want in the get_model call:
net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_voc', pretrained=True, ctx=None)

If you want to use another classification network with SDD, you can do so too. Have a look at the get_ssd calls in model_zoo/ssd/ssd.py. If you want to use a classification network of another type than in the above list, you will need to know which feature layers to use and decide all the parameters of the anchor boxes. Also, you'll need to train the SSD layers from scratch.


For Yolo it's similar. Pre-defined and pretrained networks:
           'yolo3_darknet53_voc',
           'yolo3_darknet53_coco',
           'yolo3_darknet53_custom',
           'yolo3_mobilenet1_0_coco',
           'yolo3_mobilenet1_0_voc',
           'yolo3_mobilenet1_0_custom'


Using your own classification network can be done by constructing your own get_yolov3 call based on the examples here: model_zoo/yolo/yolo3.py

L.

**Comment by mrbulb** [comment]
> Gluon-CV already provides quite some pre-defined and pre-trained combinations for SSD:
> 'ssd_300_vgg16_atrous_voc',
> 'ssd_300_vgg16_atrous_coco',
> 'ssd_300_vgg16_atrous_custom',
> 'ssd_512_vgg16_atrous_voc',
> 'ssd_512_vgg16_atrous_coco',
> 'ssd_512_vgg16_atrous_custom',
> 'ssd_512_resnet18_v1_voc',
> 'ssd_512_resnet18_v1_coco',
> 'ssd_512_resnet18_v1_custom',
> 'ssd_512_resnet50_v1_voc',
> 'ssd_512_resnet50_v1_coco',
> 'ssd_512_resnet50_v1_custom',
> 'ssd_512_resnet101_v2_voc',
> 'ssd_512_resnet152_v2_voc',
> 'ssd_512_mobilenet1_0_voc',
> 'ssd_512_mobilenet1_0_coco',
> 'ssd_512_mobilenet1_0_custom'
> 
> You pick the one you want in the get_model call:
> net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_voc', pretrained=True, ctx=None)
> 
> If you want to use another classification network with SDD, you can do so too. Have a look at the get_ssd calls in model_zoo/ssd/ssd.py. If you want to use a classification network of another type than in the above list, you will need to know which feature layers to use and decide all the parameters of the anchor boxes. Also, you'll need to train the SSD layers from scratch.
> 
> For Yolo it's similar. Pre-defined and pretrained networks:
> 'yolo3_darknet53_voc',
> 'yolo3_darknet53_coco',
> 'yolo3_darknet53_custom',
> 'yolo3_mobilenet1_0_coco',
> 'yolo3_mobilenet1_0_voc',
> 'yolo3_mobilenet1_0_custom'
> 
> Using your own classification network can be done by constructing your own get_yolov3 call based on the examples here: model_zoo/yolo/yolo3.py
> 
> L.

Wow, thank you for your help, I will try to modiy `get_yolov3` to get my custom yolov3 version :smile:
