### ISSUE TITLE
the new pretrained model se_resnext50, is not as fast as the gluoncv homepage show

### ISSUE THREAD

**Issue by lichun-wang** [dmlc/gluon-cv#731]
as the gluoncv homepage show,  the speed of se-resnext50 is similar to resnet101-v1d. But after i test the speed of resnet101-v1d and se-resnext50,  I found se-resnext50 will cost 1/3 more time than resnet101-v1d.  resnet101-v1d cost less than  20ms,  but se-resnext50 cost about 30ms,  what's wrong?

**Comment by hetong007** [comment]
There are a few factors affecting the speed performance: hardware configuration, batch size, image size, etc. It will be more helpful if you can specify your environment before we can identify and look into the issue.
