### ISSUE TITLE
Can SimplePose support HandPoseEstimation?

### ISSUE THREAD

**Issue by momo1986** [dmlc/gluon-cv#732]
I use the demo from 
https://gluon-cv.mxnet.io/build/examples_pose/demo_simple_pose.html#sphx-glr-download-build-examples-pose-demo-simple-pose-py

I load my own picture with hands, no human faces.

It intrigues the error-warning:

> Shape of pre-processed image: (1, 3, 683, 512)
> Traceback (most recent call last):
>   File "demo_simple_pose.py", line 87, in <module>
>     predicted_heatmap = pose_net(pose_input)
>   File "C:\Python\Python37\lib\site-packages\mxnet\gluon\block.py", line 540, in __call__
>     out = self.forward(*args)
>   File "C:\Python\Python37\lib\site-packages\mxnet\gluon\block.py", line 921, in forward
>     "Symbol or NDArray, but got %s"%type(x)
> AssertionError: HybridBlock requires the first argument to forward be either Symbol or NDArray, but got <class 'NoneType'>
Looks like no hand pose support before, file the star for confirm.

Thanks!
Momo

**Comment by zhreshold** [comment]
You will need a hand pose dataset and a hand detector, but the algorithms may still be the same. 
Since this is not an issue, I am closing this. If you have ideas to contribute, you can open a new issue
