### ISSUE TITLE
Exported faster_rcnn_fpn_bn_resnet50_v1b_coco has many duplicate layer names

### ISSUE THREAD

**Issue by hongliu104** [dmlc/gluon-cv#736]
Exported faster_rcnn_fpn_bn_resnet50_v1b_coco has many duplicate layer names. 
When imports the exported model. Error occurs:
ValueError: There are multiple outputs with name "fasterrcnn0_rpn0_rpnhead0_relu0_fwd_output"

**Comment by Jerryzcn** [comment]
hmm... id don't have issues importing. Could you try reinstall gluoncv and use mxnet1.4+?
