### ISSUE TITLE
Demo for the paper of Bag of Freebies for Training Object Detection Neural Networks

### ISSUE THREAD

**Issue by momo1986** [dmlc/gluon-cv#738]
Looks the idea from Gluon team is very exciting.
https://arxiv.org/pdf/1902.04103.pdf
However, i am not sure whether there is public API or demos for such tricks.

Maybe it is an enhancement issue, not a bug issue.

Thanks & Regards!
Best Wishes！
Momo

**Comment by zhreshold** [comment]
https://gluon-cv.mxnet.io/model_zoo/detection.html the model zoo includes models trained with tricks, so you can play with these models, alongside the existing tutorials and demos.
