### ISSUE TITLE
CPU memory leak when running train_yolov3.py

### ISSUE THREAD

**Issue by houweidong** [dmlc/gluon-cv#739]
The cpu memory occupation is about 21G When i run train_yolov3.py at epoch 0,  but at the end of every epoch, the cpu memory will increase about 1G~2G. And the cpu memory can hit 50G when the epochs is about 30!!!
How can i solve this porblem?

train with option: 
`--batch-size 16    -j 8   --dataset coco  --syncbn`

version:
```
ubuntu 18.04
mxnet   (1.5.0b20190411  and 1.5.0b20180305)
gluoncv (0.5.0b20190411  and 0.4.0b20190227)
10 1080ti
cuda 9.0
```

**Comment by zhreshold** [comment]
Gluoncv is pure python package so if memory leak does happen, it's a better idea to file an issue with mxnet.

**Comment by houweidong** [comment]
thanks for zhang da lao de jian yi @zhreshold
