### ISSUE TITLE
xmin must in [0,width.0) error during inheriting from VOCDetection.

### ISSUE THREAD

**Issue by EternalSaga** [dmlc/gluon-cv#741]
I maked my own voc dataset and followed the tutorial[Prepare custom datasets for object detection](https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html) 
However, when I executing this line 
`dataset = VOCLike(root='VOCtemplate', splits=((2018, 'train'),))`
Python complains that 
xmin must in [0,width.0) but given -1.0.
I checked my xml files and I found that the xmin value is 0. I changed it to 1 and this error could be avoid.
However, it should be allowed.
`<bndbox>
<xmin>0</xmin>
<ymin>412</ymin>
<xmax>14</xmax>
<ymax>421</ymax>
</bndbox>`

**Comment by EternalSaga** [comment]
It has the same problem on all sides:xmin ymin xmax ymax

**Comment by ylh071032** [comment]
There is xmin =0 in your annotations.

**Comment by EternalSaga** [comment]
> 
> 
> There is xmin =0 in your annotations.

But 0 is between [0,width.0).

**Comment by Lxh1992** [comment]
In gluoncv/data/pascal_voc/detection.py, it is the following code that causes the problem.
`           xmin = (float(xml_box.find('xmin').text) - 1 )
            ymin = (float(xml_box.find('ymin').text) - 1 )
            xmax = (float(xml_box.find('xmax').text) - 1)
            ymax = (float(xml_box.find('ymax').text) - 1)`

**Comment by jpizarrom** [comment]
I think It is because the voc dataset follows the matlab convention of arrays, first position is 1
