### ISSUE TITLE
YOLOv3 mAP always around 5%

### ISSUE THREAD

**Issue by Ze-Yang** [dmlc/gluon-cv#742]
I followed the tutorial of the GluonCV toolkit to conduct the experiment named Training YOLOv3 on Pascal VOC. However, I found that the validation map is always around 5% (result attached below) even after more than one hundred epoches  training. The command I ran is "python train_yolo3.py --gpus 0,1,2,3,4,5,6,7 --network darknet53 --syncbn --mixup -j 16 --no-random-shape --no-wd --label-smooth". Plus, the warmup epoches was set to 5, other args remained default.

![result](https://user-images.githubusercontent.com/42920710/56104266-bd153800-5f69-11e9-88f7-1c2b9613a354.png)

**Comment by zhreshold** [comment]
The recommended batch size is 64, do you have enough memory to launch as https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/detection/yolo3_darknet53_coco.sh ?

**Comment by Ze-Yang** [comment]
I follow your guidance to launch as follows.

python3 train_yolo3.py --network darknet53 --dataset voc --gpus 0,1,2,3,4,5,6,7 --batch-size 64 -j 32 --log-interval 10 --lr-decay-epoch 160,180 --epochs 200 --syncbn --warmup-epochs 2 --mixup --no-mixup-epochs 20 --label-smooth --no-wd

I do have enough memory for batch_size = 64 (run on 8 GTX1080TI), but it just remain the same result around 5% mAP. Note that I set the env variable MXNET_CUDNN_AUTOTUNE_DEFAULT = 0, and I am not sure whether it would be the issue.

**Comment by zhreshold** [comment]
no worry, let me check

**Comment by zhreshold** [comment]
@Ze-Yang https://github.com/dmlc/gluon-cv/pull/745

**Comment by Ze-Yang** [comment]
Many thanks. It works for me.
