### ISSUE TITLE
Transfer learning on resnet50_v1b

### ISSUE THREAD

**Issue by FAFACHR** [dmlc/gluon-cv#746]
Hello @zhreshold, I'm trying to transfer learning or fine tune the classifier 'resnet50_v1b' on my own dataset that contain less classes than ImageNet. I tried to use the finetune_minc.py script to do this job by following the transfer_learning tutorial, but I got this error:
![Screenshot from 2019-04-17 14-33-11](https://user-images.githubusercontent.com/34231991/56287886-d0690480-611d-11e9-8a51-b246ff657e7d.png)
is there any solution?

**Comment by zhreshold** [comment]
the error indicate that you haven't fully loaded the pre-trained weights

**Comment by FAFACHR** [comment]
but I'm using the "get_model" of gluoncv so I think resnet50_v1b is loaded well. @zhreshold

**Comment by FAFACHR** [comment]
but I'm using the "get_model" of gluoncv model_zoo so I think resnet50_v1b is loaded well. @zhreshold

**Comment by zhreshold** [comment]
Did you modify the script? If so, can you post the changes here?

**Comment by FAFACHR** [comment]
No i didn’t modify the script, I just modify the model name, instead of “ResNet50_v2” I wrote “resnet50_v1b”. Also I used the same dataset in the gluoncv documentation @zhreshold

**Comment by zhreshold** [comment]
Ok, this is due to the inconsistency of the last fc layer, the solution is to replace `finetune_net.output` to `finetune_net.fc`:

```python
with finetune_net.name_scope():
    finetune_net.fc = nn.Dense(classes)
finetune_net.fc.initialize(init.Xavier(), ctx = ctx)
```

If you are not aware of the internal names of the networks, you can simply print it

```python
print(finetune_net)
```

@hetong007 We might need to explain this.

**Comment by hetong007** [comment]
@zhreshold To make things easier, can we have two names for the same block (like pointers)? So that we can have more consistent naming across differently implemented networks.

**Comment by FAFACHR** [comment]
Thank you @zhreshold it works now, but when the training finish, where can I find the new model that I did it ? or it will overwrite the model downloaded from gluoncv model_zoo?

**Comment by FAFACHR** [comment]
Thank you @zhreshold it works now, but when the training finish, where can I find the new model that I did it ? or it will overwrite the same model downloaded from gluoncv model_zoo?

I saved it with this method but I don't know if it is correct:
I added finetune_net.save_parameters and I used the .params files as my new model 
Is that fine or there is another way to do it ?

**Comment by zhreshold** [comment]
@FAFACHR yes
