### ISSUE TITLE
cpp-inference  run detect.cpp error at symbol.hpp 

### ISSUE THREAD

**Issue by abner2015** [dmlc/gluon-cv#752]
vs 2017
mxnet 1.3
windows 7

### **run detect.cpp at symol.hpp** :
` CHECK_EQ(MXSymbolInferShape(GetHandle(), keys.size(), keys.data(),
                              arg_ind_ptr.data(), arg_shape_data.data(),
                              &in_shape_size, &in_shape_ndim, &in_shape_data,
                              &out_shape_size, &out_shape_ndim, &out_shape_data,
                              &aux_shape_size, &aux_shape_ndim, &aux_shape_data,
                              &complete),
           0);`
`MXSymbolInferShape() return -1 ` what done this  mean ?

**Comment by zhreshold** [comment]
Without further infomation I cannot provide any diagnose to this problem. Either file path on the disk, network shape, input shape can be wrong.
