### ISSUE TITLE
confusion about SE-block in ResNet

### ISSUE THREAD

**Issue by murphypei** [dmlc/gluon-cv#759]
```
        if use_se:
            self.se = nn.HybridSequential(prefix='')
            self.se.add(nn.Dense(channels // 4, use_bias=False))
            self.se.add(nn.Activation('relu'))
            self.se.add(nn.Dense(channels * 4, use_bias=False))
            self.se.add(nn.Activation('sigmoid'))
```
Is the number of channel in the second fully connected layer should be `channels` ? In SE-net paper, the first fc reduce the number of channel and the second fc restore the number of channel equal to GAP ?

**Comment by zhreshold** [comment]
@hetong007

**Comment by hetong007** [comment]
The input conv layer has `channels * 4`: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnext.py#L75
