### ISSUE TITLE
data.COCODetection transform parameter issue  

### ISSUE THREAD

**Issue by ahmedmsoliman96** [dmlc/gluon-cv#762]
i want to resize the images and labels of coco data set as shown below: 

import matplotlib.pyplot as plt
from gluoncv import data, utils
from mxnet.gluon.data.vision import transforms

w = int(input ("Enter width of new images : "))
h = int(input("Enter height of new images : "))

cocodir = r'D:\Coco\fast-ai-coco'

trainDataset = data.COCODetection(root=cocodir,splits=['instances_train2017'],transform=transforms.Resize(size=(w,h)))
valDataset = data.COCODetection(root=cocodir,splits=['instances_val2017'],transform=transforms.Resize(size=(w,h)))
print('Num of training images:', len(trainDataset))
print('Num of validation images:', len(valDataset))

print ("finished")
print("traindatasets: ", trainDataset[0])

trainImage, trainLabel = trainDataset[0]

print ("train label : ", trainLabel)
bounding_boxes = trainLabel[:, :4]
class_ids = trainLabel[:, 4:5]
print('Image size (height, width, RGB):', trainImage.shape)
print('Num of objects:', bounding_boxes.shape[0])
print('Bounding boxes (num_boxes, x_min, y_min, x_max, y_max):\n',
      bounding_boxes)
print('Class IDs (num_boxes, ):\n', class_ids)

utils.viz.plot_bbox(trainImage.asnumpy(), bounding_boxes, scores=None,
                    labels=class_ids, class_names=trainDataset.classes)
plt.show() 

but when i run the code i get this issue :

Enter width of new images : 300
Enter height of new images : 300
loading annotations into memory...
Done (t=21.52s)
creating index...
index created!
loading annotations into memory...
Done (t=0.80s)
creating index...
index created!
Num of training images: 117266
Num of validation images: 4952
finished

Traceback (most recent call last):
  File "C:/Users/ahmed/PycharmProjects/annotation parser/AnnotationParser.py", line 34, in <module>
    print("traindatasets: ", trainDataset[0])
  File "C:\Users\ahmed\Anaconda3\lib\site-packages\gluoncv\data\mscoco\detection.py", line 129, in __getitem__
    return self._transform(img, label)
  File "C:\Users\ahmed\Anaconda3\lib\site-packages\mxnet\gluon\block.py", line 540, in __call__
    out = self.forward(*args)
TypeError: forward() takes 2 positional arguments but 3 were given

Process finished with exit code 1

is this the right way to resize both images and labels or am i doing something wrong ? 

i tried to make a new list and use the  imresize and bbox.resize  that exists in gluoncv.data.transforms  but i dont have enough memory to have both original and resized list 
so what is the right way to have 1 list of resized images and labels

**Comment by zhreshold** [comment]
You mean slice the dataset? try slice the `_items` in datasets

**Comment by ahmedmsoliman96** [comment]
no i want to resize the images and the bounding boxes for example if the original image size is 600 * 400 i want it to be 300*300.also i want to resize the bounding boxes accordingly. so  is there anyway to do this while loading the data ?

**Comment by zhreshold** [comment]
It's usually handled by transform functions, where image and label will be resized altogether.
