### ISSUE TITLE
nms problem

### ISSUE THREAD

**Issue by ou525** [dmlc/gluon-cv#763]
When I tested the pre-training yolo3 model, I found that the same type of target appeared highly coincident. Where can I find the nms value? I can't find it.@lsabi @zhreshold

**Comment by lsabi** [comment]
You mean this ?

[https://gluon-cv.mxnet.io/api/model_zoo.html?highlight=nms#gluoncv.model_zoo.YOLOV3.set_nms](https://gluon-cv.mxnet.io/api/model_zoo.html?highlight=nms#gluoncv.model_zoo.YOLOV3.set_nms)

**Comment by ou525** [comment]
Thank you for the link provided, but this is only the python interface, I use the c interface code, forgive me for not understanding mxnet@lsabi

**Comment by ou525** [comment]
I tried testing with the python interface code and found that the same error occurred. Two overlapping boxes, one of which is completely inside the other

**Comment by zhreshold** [comment]
@ou525 check out `force_nms` option, by default it's false to allow different category to appear at the same location.

**Comment by ou525** [comment]
Sorry, I didn't find the force_nms option. But my problem is that the objects of the same category are stacked, not different categories. I tried to set the set_nms function to 0 in the python interface, and there are a lot of overlapping boxes, indicating that the original default setting nms is turned on, I don't know what is going on.@zhreshold

**Comment by zhreshold** [comment]
if you set nms to 0 it will disable it. The threshold means how much overlap to suppress it. Try nms_thresh=0.01 for example to enable maximum suppression.

**Comment by ou525** [comment]
I used the nms function alone to calculate the iou value of the two target boxes, and found that the nms threshold is valid, just less than the threshold, so there is a target 2 detection boxes.
