### ISSUE TITLE
For Simple pose, how can my own data be fit?

### ISSUE THREAD

**Issue by momo1986** [dmlc/gluon-cv#765]
Hello, I have some pose data with such format with relative coordinate stored.
![image](https://user-images.githubusercontent.com/34225874/57193168-1bcb4180-6f6b-11e9-9aad-dbbe145d30e2.png)
Looks the demo is very excellent:
https://gluon-cv.mxnet.io/model_zoo/pose.html#simple-pose-with-resnet
How can I fit it to my own data instead of using MSCOCO?

Thanks & regards!

**Comment by zhreshold** [comment]
You can convert your data to coco format, what gluoncv expect is a coco like xxx.json file.
