### ISSUE TITLE
Fasterrcnn validate problem

### ISSUE THREAD

**Issue by yuyijie1995** [dmlc/gluon-cv#766]
I can use my own  dataset like voc format to train the Fasterrcnn,but when the first epoch completed,this error happened.
 14 Start training from [Epoch 0]
    map_name, mean_ap = validate(net, val_data, ctx, eval_metric, args)  File "train_faster_rcnn.py", line 292, in validate
    return eval_metric.get()  File "/home/users/yijie.yu/mxnet/python/gluoncv/utils/metrics/voc_detection.py", line 57, in get
    self._update()  # update metric at this time  File "/home/users/yijie.yu/mxnet/python/gluoncv/utils/metrics/voc_detection.py", line 175, in _update
    recall, precs = self._recall_prec()  File "/home/users/yijie.yu/mxnet/python/gluoncv/utils/metrics/voc_detection.py", line 191, in _recall_prec
    n_fg_class = max(self._n_pos.keys()) + 1
 Can u give me some suggestions?

**Comment by zhreshold** [comment]
I guess you might be missing some categories in your data or you are using wrong class categories in the dataset
