### ISSUE TITLE
Is it possible to add negative samples(images without annotations) to mxnet version yolov3?

### ISSUE THREAD

**Issue by shadyatscu** [dmlc/gluon-cv#772]
In original yolov3 implementation, we could easily add negative samples(images without annotations) to training dataset. In mxnet version yolov3, i tried to do the same thing, e.g. for preset module 'yolo3_darknet53_coco' i have to create coco format data without annotation information. The coco data api of glouncv[https://github.com/dmlc/gluon-cv/blob/bc77dcb42f0549d5389e6b7fece358e12c820a83/gluoncv/data/mscoco/detection.py#L33](url), there is an option: ' skip_empty : bool, default is True Whether skip images with no valid object. This should be `True` in training, otherwise it will cause undefined behavior.' what is the meaning of 'undefined behavior'? In  cpp version yolov3 repo https://github.com/AlexeyAB/darknet it is said that: 'desirable that your training dataset include images with non-labeled objects that you do not want to detect - negative samples without bounded box (empty .txt files) - use as many images of negative samples as there are images with objects', has anybody try out this strategy? thanks a lot!

**Comment by ivanquirino** [comment]
+1

**Comment by chinakook** [comment]
This is important function to reduce false positive. [mmdetection](https://github.com/open-mmlab/mmdetection/pull/1531) add this function to its base. So I suggest that gluon-cv can also add images without annotations to its detection base.
