### ISSUE TITLE
Performance CPU Cause slowdown between batch runs on GPU

### ISSUE THREAD

**Issue by evorta** [dmlc/gluon-cv#774]
HI,

Versions:

mxnet                        1.4.0.post0
gluoncv                     0.4.0    
Ubuntu                     16.04.6 LTS
Kernel                       4.15.0-47-generic
GPU                          2 X 1080 TI 
Xeon-E5V2               32 Cores.

When training SSD - 512 - Mobilenet 1.0 

I can see : ~110 Samples / Sec

However I can see the system spends most of it's time CPU bound, num-workers is already max 32 cores of the box.

I basically am bottlenecked on CPU the process that occurs between each run takes forever, I was hoping anyone could point me to what is so slow? A way of maybe seeing how each call in the stack is using resources? I assume there is a simple way that would point me at the code that probably is slow because I am not using maybe the MKL-DNN libaries, etc.

Is there any recommendations to speed this part up as my CPU's are 100% maxed out yet I spend more time between processing than the bit that measures the 110 samples/sec.

Thanks all.

**Comment by zhreshold** [comment]
data augmentation part in SSD is very cpu intensive, and E5v2 CPU has low frequency. 110 samples/sec seems not too bad, what's you GPU utilization ratio?
