### ISSUE TITLE
Any other parameters that make training time shorter(different epochs, decay epoch)?

### ISSUE THREAD

**Issue by zhoulukuan** [dmlc/gluon-cv#785]
The models in gluoncv perform very well, but the training parameters given in the shell script require a lot of time to train. For example, coco has to train 26 epochs, and this time will be longer if the GPU is insufficient.
![image](https://user-images.githubusercontent.com/16110591/58480146-4a17f780-818c-11e9-98ef-05059ee46007.png)
When I used detectron, two different training parameters (1x, 2x) are provided. The training time of the former is less but it does not harm much performance.
Does gluoncv have more experiments in this area? Can you provide some parameters that make training faster for people who are  lack of gpu such as me ?

**Comment by zhreshold** [comment]
Did I answered the question before? You can try reduce num epoch and adjust lr decay epoch numbers proportionlly.

**Comment by zhoulukuan** [comment]
> Did I answered the question before? You can try reduce num epoch and adjust lr decay epoch numbers proportionlly.

Yes. You answer me the same questions on the forum. At that time, nobody answers this questions. Thank you very me and I will close this issue.
