### ISSUE TITLE
[minor improvement] Obtaining anchors on SSD is undocumented and can be misleading

### ISSUE THREAD

**Issue by ThomasDelteil** [dmlc/gluon-cv#789]
Currently to get the anchors of the SSD network we need to do:

```
    with autograd.train_mode():
        _, _, anchors = net(mx.nd.zeros((1, 3, height, width)))
```

This is confusing because apart from the context it is the same syntax as obtaining bounding box predictions. I actually had to ask @hetong007 (thank you!) for assistance because I didn't know how we could trust the predictions of an empty images to be the anchor boxes.

https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/ssd/ssd.py#L203

solves the mystery. 

I believe a `def get_anchors(self, width, height):` function would be more appropriate and clear. I understand what the author meant with the `train_mode` scope but this is undocumented and not discoverable. At the very least it would be great to add it to the documentation of the SSD network if you truly believe that it's the best way to expose the anchors.

Thanks!

**Comment by hetong007** [comment]
@zhreshold could you share any thoughts?

**Comment by zhreshold** [comment]
Is there any specific reason to expose anchors to user except (demo, illustration) purposes before we move forward adding a new function?

My only **tiny** concern is that it we are going to differentiate object detection models with unique member functions. My original plan is to provide smooth transition experience across models.

**Comment by ThomasDelteil** [comment]
Thanks @zhreshold. The main reason for me is the clarity of the training script. If the user doesn't know about the internal implementation, it seems to be a bug: predicted bounding boxes are used instead of anchor boxes. Especially since the steps of pre-generating targets is a performance improvements step that doesn't follow the usual flow of the training. (get data -> process data -> compute loss). It is in my opinion in that case especially helpful if this step is well documented and easy to understand.

I think all the available object detection models differ in some respect, and I think it's a great idea to have a common set of interface functions that they all adhere to. However I think it's ok to expose some particularities of each family of detector by adding extra functions to make the code more clear and specific.

**Comment by zhreshold** [comment]
Agree, maybe we can move https://github.com/dmlc/gluon-cv/blob/a990c2f148efccd3f7dc0cc0ccd81c03a0f91dd5/gluoncv/model_zoo/ssd/ssd.py#L193-L202 to a new member function named `forward_predict` for example.
