### ISSUE TITLE
[Windows-10-CUDA-10] Inference speed slow with pre-trained MRCNN model

### ISSUE THREAD

**Issue by momo1986** [dmlc/gluon-cv#790]
Thanks for Gluon guys,

I used the pre-trained model of GLUON-Mask-RCNN.

I did not change the script from below web-page:
https://gluon-cv.mxnet.io/build/examples_instance/demo_mask_rcnn.html

The inference result is exciting and excellent.

Since I have CUDA-10 installed in Win-10 with one 1080 GPU, the inference time is about 1.5min. I calculate before image reading and after inference complement. It looks like the default inference speed is slow. 

How can I enable the GPU speed-up in program? Is there any possibility?

Thanks & Regards!
Momo

**Comment by zhreshold** [comment]
have you specified context = mx.gpu(0) ?
