### ISSUE TITLE
Where can I found the generation scripts of quantized ssd models ?

### ISSUE THREAD

**Issue by TriLoo** [dmlc/gluon-cv#791]
I found that the `gluoncv/model_zoo/quantized/quantized.py` only download the already quantized  ssd models, like `ssd_512_mobilenet1.0_voc_int8-symbol.json` or `ssd_300_vgg16_atrous_voc_int8-symbol.json`. Now I want to generate my own ssd model implemented based on Gluon-CV, and i am not sure  the contents of `ecluded_sym_names`, any advise ?

**Comment by pengzhao-intel** [comment]
In the next release, we will improve the script to make quantization flow more convenience :)
Did you try already quantized model and how much perf you can gain from INT8?

@xinyu-intel can help you for the customized model

**Comment by TriLoo** [comment]
@pengzhao-intel 
Thanks for reply.

I just resolved my problem and obtained the quantized model (quantization mode: *entropy*). However, the time used by quantized model is much more than non-quantized model using `MKLDNN_QUANTIZE` as backend.  

During the quantization, only conv layers were quantized and all other layers, including `flatten`, `concat`, 
 *etc.*, were put into `excluded_sym_names`  parameter.  Now, I am working on the latency problem, though not sure how to fix it yet.  Generally, mobilent ssd 300, the latency between quantized and non-quantized models is: 33.4 vs 6.7.

**Comment by xinyu-intel** [comment]
@TriLoo can you please give more details of SW&HW like CPU, mxnet version, gluoncv version, etc. BTW, is throughput of your model ok?

**Comment by TriLoo** [comment]
@xinyu-intel 
Sure.
CPU: Intel Xeon CPU E5-2650 v4 @2.2GHz, 
OS: CentOS 7.2.1511
MXNet: 1.5.0, git commit head: `5fc4fc53df74f`
GluonCV: 0.4.0.post0 (pip installed)
MKLDNN: v0.19.0, git hash: `41bee20d7eb4a`
MKL:  2019.0 Update 5
Python: Anaconda python 3.6.8
Environment Variable: OMP_NUM_THREADS=1,   MXNET_SUBGRAPH_BACKEND=MKLDNN

I didn't test the throughput of quantized model yet. Note that, only one thread (OMP_NUM_THREADS=1) is allowed in out applications, and I found the when `unset OMP_NUM_THREADS`, the latency of quantized and non-quantized models get very similar, no speedup found from quantization one.

In fact, my model is very similar to `ssd_mobilenet1.0_512` from `GluonCV`, except that BatchNorm is fused into convolution layers and `bias` was added (Verified, correct). I can provide my `json` and `params` files to you to reproduce the above speedup results.

Thanks for reply.

**Comment by xinyu-intel** [comment]
@TriLoo Thanks for your info, special instructions like avx512-bw or VNNI are needed to speedup quantized models. Can you try a skylake machine?

**Comment by TriLoo** [comment]
@xinyu-intel 
Sorry, only `Xeon E5 2650v4` I have, which micro architecture is broadwell.  I am not sure if I should install other libraries, like `Intel System Studio` ?

**Comment by xinyu-intel** [comment]
@TriLoo Broadwell Xeon will not bring good speedup for quantized models but the accuracy is good for reference.

**Comment by TriLoo** [comment]
However,  I am not sure why my quantized model can be 5 times slower than non-quantization model. Could you please give me some advices? I can send my scripts to you.  @xinyu-intel

**Comment by xinyu-intel** [comment]
maybe some int8 kernel haven't be optimized on avx2 machine, which will be slower than fp32 ones.

**Comment by TriLoo** [comment]
So it is possible that 5 times larger latency ? How can I verify this ?  thank you very much.

**Comment by TriLoo** [comment]
What's more, the `ssd_vgg16_reudced` example from `incubator-mxnet/example/ssd/` run time is as below:

*  Non-quantized model : **1.061404 img/sec**
*  Quantized model        :   **0.558333 img/sec **

**Comment by xinyu-intel** [comment]
If you want to get better speedup, you need to launch the quantized inference on a xeon skylake machine.

**Comment by TriLoo** [comment]
Thanks for your advise.

Now, I'm working on a new machine, which is equipped with `Xeon Silver 4114 CPU` (Skylake microarchitecture). If I have the results, I will paste here.

**Comment by TriLoo** [comment]
I just test the quantized model `incubator-mxnet/example/ssd/`, although all CPU is busy, the results are shown below:

* Non quantized:   0.508 img/sec
* Quantized       :    ~ 0.955 img/sec

**Comment by TriLoo** [comment]
@xinyu-intel 

You can close this issue. I have worked through my program, and finally got about 2.3x speedup on `Xeon Siliver 4114` though all cpus are very busy. 

Looks like `concat` layers can raise a segment fault even through `MKLDNN` support INT8 `concat` layers' inference, so all `concat` layers should be excluded during quantization.

**Comment by pengzhao-intel** [comment]
@TriLoo  Very cool! It's great to hear you get the nice speedup on SKX.
It should be fixed if there's a segment fault. 

Would you mind provide more details for us?

**Comment by TriLoo** [comment]
Sure, what details do you need ? I can provide two quantized `json` file, one of which is correct, and the other can raise segment fault. In the latter one,  I only excluded layers endwith `_weight, _bias, _data, _workspace`,  because I think that the quantization API can select those layers which are supported by `MKLDNN Quantization INT8 inference`.

I have not figure out the cause of `Segment Fault`, but after I excluded all `flatten, concat, reshape, element_sub, element_add` layers, the problem was fixed.

**Comment by xinyu-intel** [comment]
@TriLoo Try to exclude flatten only to see if segmentfault exists.

**Comment by TriLoo** [comment]
OK, I will try it later. @xinyu-intel

**Comment by TriLoo** [comment]
I just finished the quantization of mobilenet SSD based on GluonCV and mxnet. The `segment falut` reproduction experiments are listed as below:

quantization mode: `none`   or `entropy`
input dtype: `fp32`
output dtype: `int8`
platform: `Xeon Siliver 4114`, CentOS 6.9
MXNet: `5fc4fc53df7`
GluonCV:  0.4.0.post0
MKLDNN: `v0.19.0`
MKL: `2018.0 Update 1` or `2019 Update 1`

*  Only `fatten` layers are excluded:  can raise `Segment Fault`
*  Only  `concat` layers are excluded: can raise `Segment Fault`
*  Both `flatten` and `concat` layers are excluded:  No `Segment Fault`

My final quantization results are:
Speedup:~2.3x
mAP:     decrease about 0.12 % only

One thing more: 
The `DetRecordIter` class in `incubator-mxnet/example/ssd/dataset/iterator.py` can be confused with `gluoncv.data.RecordFileDetection` class. Because the former did not divide the data by std values (only subtract the input image by mean valuse), and this can lead to a bad `mAP` if one use `RecordFileDetection`  in model training, and use `DetRecordIter` to load data when quantizing model.

**Comment by pengzhao-intel** [comment]
@TriLoo really great results and thanks to pointing out the potential issues in our flow. 
We will fix the bug and continuously improve the usability in GluonCV.

Regarding avx2, YES, OpenVINO has the supports at now, as below link.
https://www.intel.ai/introducing-int8-quantization-for-fast-cpu-inference-using-openvino/#gs.h4qann

If you're using desktop CPU, you can try to run model by OpenVINO too.

**Comment by TriLoo** [comment]
Ok, thanks for your advise, @pengzhao-intel .

I will try to add some custom layers to OpenVINO to run my INT8 `Mobilenet SSD 300` on `Xeon E5-2650v4`.

**Comment by pengzhao-intel** [comment]
@TriLoo Could you let us know when you get the results by OpenVINO?

**Comment by TriLoo** [comment]
@pengzhao-intel 
Sure, I found one drawback of GluonCV SSD implementation that the example re-implemented the `MultiBoxPrior` and `MultiBoxDetection`, leading to OpenVINO can not understand some layers, but OpenVNIO can handle `MultiBoxPrior` and `MultiBoxDetection` very well. 

I added some custom layers to OpenVNIO based on this tutorial: [Add custom mxnet layer to OpenVNIO](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_customize_model_optimizer_Extending_MXNet_Model_Optimizer_with_New_Primitives.html). However, I can not find enough docs to work through with OpenVNIO. Now, I changed the implementation of GluonCV SSD detection head part to `MultiBoxPrior` and `MultiBoxDetection` and just get the OpenVNIO `xml` and `.bin` files. I have not ran the test of these two files (next **Monday** might have a results).   I am not sure about whether I should finetune my model because of the changes of implementation.  Can you give me some advises to    implement MXNet custom layers within OpenVNIO ? 

I am also learning the C++ source code of MXNet to find the possibility of implement INT8 kernel using AVX2. My main purpose is to obtain a good inference speed on Skylake **and** Broadwell microarchitecture CPUs.

**Comment by pengzhao-intel** [comment]
Thanks, the GluonCV or framework will be more flexible while OpenVINO is based on a group of fixed model and OPs.
Thus, there're some gaps between them.  We're also thinking about the combination of them together, but in the brainstorming stage :) The real experience from the user is very important for us.

**Comment by TriLoo** [comment]
@pengzhao-intel 
Ok, I have successfully convert the gluoncv implemented SSD model to the IR representation (*.bin, *.xml), However, When I use 'plugin.load()', an error happed:

> RuntimeError: Unsupported primitive of type: PriorBox name: ssd0_5_anchor

I don't have any idea to do with this error.

**Comment by TriLoo** [comment]
I updated my results.

@pengzhao-intel

**Comment by pengzhao-intel** [comment]
Thanks, looks good :) It's slight better than MXNet. 
Do you try quantization from OpenVINO?
