### ISSUE TITLE
Possible bug in RCNNTargetSampler

### ISSUE THREAD

**Issue by Mooonside** [dmlc/gluon-cv#803]
Hi, some lines in RCNNTargetSampler look weird to me:
https://github.com/dmlc/gluon-cv/blob/49056d4892382fca067216d6271d1633d869cb8d/gluoncv/model_zoo/faster_rcnn/rcnn_target.py#L105-L107

'mask' stores positive and negative samples disorderly, so slicing it directly seems to be incorrect. The sliced part may also contain negative samples that should be included in the later sampling of negative ROIs. Although negative samples are numerous and ignoring several of them during sampling may not cause great harm, it can still be quite confusing for readers like me.

**Comment by zhreshold** [comment]
`index` is already sorted: https://github.com/dmlc/gluon-cv/blob/49056d4892382fca067216d6271d1633d869cb8d/gluoncv/model_zoo/faster_rcnn/rcnn_target.py#L88, and `mask` is taken according to the order of `index`. 

Or am I missing something you mentioned?

**Comment by Mooonside** [comment]
@zhreshold 
The line you noted:
https://github.com/dmlc/gluon-cv/blob/49056d4892382fca067216d6271d1633d869cb8d/gluoncv/model_zoo/faster_rcnn/rcnn_target.py#L85-L88
 'index' is used to shuffle masks, it has nothing to do with the sorting of positive and negative samples.

**Comment by zhreshold** [comment]
@Mooonside 
checkout these two sections you will better understand how pos and neg samples are selected: https://github.com/dmlc/gluon-cv/blob/49056d4892382fca067216d6271d1633d869cb8d/gluoncv/model_zoo/faster_rcnn/rcnn_target.py#L92-L119

Basically positive samples are shuffled and sorted to be on top of the array, and negative samples similarly will stack to the bottom of the array.

**Comment by Mooonside** [comment]
@zhreshold 
I agree with you on the selection of ```top_k``` positive samples, what confuses me is the slice operation before selecting negative samples. In ```index[0:self._max_pos]``` before L105, there still exists negative samples. And slicing it means to discard negative samples in ```[0:self._max_pos]``` during the later selection of ```bottom_k``` negative samples.

**Comment by zhreshold** [comment]
yes, discarding some of the negative samples are expected, since they are sorted with random order, discarding some of them will not make any difference.

**Comment by Mooonside** [comment]
@zhreshold 
Well, a proper random sampling should include all possible samples, instead of discarding some of them first and sample from the left.

**Comment by lizhen2017** [comment]
@zhreshold @Mooonside I'm also confused about the issue.

> yes, discarding some of the negative samples are expected, since they are sorted with random order, discarding some of them will not make any difference.

I think if we sort the nagative firstly, and slice the next, nagative ones are still in random order, maybe slice first will reduce the cost of sort. Looking forward to your reply.
