### ISSUE TITLE
Possible bug - got multiple values for keyword argument 'width' when initializing PSPNet and DeeplabV3

### ISSUE THREAD

**Issue by cygerts** [dmlc/gluon-cv#805]
gluonCV version - '0.4.0'

When you initialize PSPNet or DeepLabV3 net so to get custom width and height of the neural network input (and output):
`net = gluoncv.model_zoo.PSPNet(output_labels, backbone='resnet50', aux=True, ctx=mx.cpu(0), pretrained_base=True, height = 360, width = 640)`
you get an error:
 type object got multiple values for keyword argument 'width'
this is because of the line
```
self.head = _PSPHead(nclass, height=self._up_kwargs['height']//8,
                                  width=self._up_kwargs['width']//8, **kwargs)
```
so in _PSPHEad function height (and width) are passed as well as named parameter and as well as kwarg.

Note that FCN works fine with that initializition. Looks to me as the arguments in _PSPHead function should have a different name

**Comment by cygerts** [comment]
Added pull request for fixing FCNNet https://github.com/dmlc/gluon-cv/pull/826

**Comment by zhanghang1989** [comment]
Thanks for the contribution. Resolved in https://github.com/dmlc/gluon-cv/pull/826
