### ISSUE TITLE
Fix a bug caused by API changed.

### ISSUE THREAD

**Issue by PistonY** [dmlc/gluon-cv#808]
https://github.com/dmlc/gluon-cv/blob/49056d4892382fca067216d6271d1633d869cb8d/gluoncv/model_zoo/residual_attentionnet.py#L50
Please change this line as follow.
```python
return F.contrib.BilinearResize2D(x, height=self.size, width=self.size)
```

**Comment by zhreshold** [comment]
Is this from mxnet1.5?

**Comment by PistonY** [comment]
Yeah,Sorry I use nightly version of mxnet so I found this.You may not fix it now.
