### ISSUE TITLE
Network architecture search implementations

### ISSUE THREAD

**Issue by bermanmaxim** [dmlc/gluon-cv#812]
Hello, are there any MXnet implementations of network architecture search (NAS) approaches, e.g. Proxyless NAS (https://arxiv.org/abs/1812.00332) and MNasNet (https://arxiv.org/abs/1807.11626)? If not, is somebody working on it? Thank you.

**Comment by hetong007** [comment]
We have a NASNet implementation at: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/nasnet.py

In general, NAS is a hot research field and there are a lot of works on going. We have limited bandwidth thus may want to pause for now and start to add models when it cools down a bit. Of course, contribution from the community is always welcome!

**Comment by bryanyzhu** [comment]
@bermanmaxim We have people working on NAS, and we recently open sourced AutoGluon at https://github.com/awslabs/autogluon. Please check that website for our most recent updates.
