### ISSUE TITLE
Why gluon-cv SSD is using absolute values for bounding boxes instead ratios like in zhreshold/mxnet-ssd

### ISSUE THREAD

**Issue by jpizarrom** [dmlc/gluon-cv#815]
Why gluon-cv SSD is using absolute values for bounding boxes instead ratios like in zhreshold/mxnet-ssd?

cc @zhreshold

https://github.com/zhreshold/mxnet-ssd/blob/821a1c5049679f798976c8bf58b460ffaa098458/dataset/pascal_voc.py#L192-L197
```
                xml_box = obj.find('bndbox')
                xmin = float(xml_box.find('xmin').text) / width
                ymin = float(xml_box.find('ymin').text) / height
                xmax = float(xml_box.find('xmax').text) / width
                ymax = float(xml_box.find('ymax').text) / height
                label.append([cls_id, xmin, ymin, xmax, ymax, difficult])
```

https://github.com/dmlc/gluon-cv/blob/8a2f220b0aac954fd242bbab029692876317e6dd/gluoncv/data/pascal_voc/detection.py#L116-L119

Thanks & Regards!

**Comment by zhreshold** [comment]
Using absolute coordinates can ease many transformations in augmentation, plus, it also helps fixing anchor values in SSD/FRCNN models so we can store static anchors in model without re-compute it during inference.
