### ISSUE TITLE
Error rate decrease in CIFAR-10 due to transforms.RandomResizedCrop(32)

### ISSUE THREAD

**Issue by gauravrele87** [dmlc/gluon-cv#816]
Hello All,

I tried to work though the example that is given on this page: https://gluon-cv.mxnet.io/build/examples_classification/dive_deep_cifar10.html and it gave me really bad accuracy (65% after 10 epochs for training accuracy) as compared to using the example here: https://github.com/dmlc/gluon-cv/tree/master/scripts/classification/cifar (80+% after 10 epochs for training accuracy)

The reason this is happening is because of this line: transforms.RandomResizedCrop(32) in both transform_train and transform_test attributes. 

Please check and update the tutorial 

How to reproduce: Go through the tutorial above to check the bad accuracy 
Solution: Remove the line from both transform_train and trainsform_test to improve it

let me know if you have any questions

**Comment by hetong007** [comment]
Thanks for the catch! Will patch it.
