### ISSUE TITLE
The training speed of mask-rcnn not scale on multiple gpu

### ISSUE THREAD

**Issue by arcadiaphy** [dmlc/gluon-cv#820]
I've test the gluon mask-rcnn on 1/2/4 gpus, but the training speed remains about 1 images/second no matter how many gpus are used, and the gpu usage in nvidia-smi is very low too.

Don't know why the training speed doesn't scale with gpus, maybe there are some similar problems just like in #85?

## Setup
I've used the [official script](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/instance/mask_rcnn_fpn_resnet101_v1d_coco.sh) to run experiments, but cannot reproduce the training speed in [log](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/instance/mask_rcnn_fpn_resnet101_v1d_coco_train.log).

## Environment
Operator System: Centos 7
GPU: TITAN X (Pascal) 12G
Python: 2.7.5
MXNet: 1.4.0
GluonCV: latest

**Comment by zhreshold** [comment]
have you tried multi worker to speed up data loading?
