### ISSUE TITLE
Cannot reproduce accuracy when training Mobilenet0.25 on Imagenet

### ISSUE THREAD

**Issue by titikid** [dmlc/gluon-cv#822]
I couldn't reproduce Imagenet's accuracy of Mobilenet model. For example with mobilenet0.25 model. I use those parameters:
```
python train_imagenet.py \
  --model mobilenet0.25 --mode hybrid \
  --lr 0.4 --lr-mode cosine --num-epochs 120 --batch-size 128 --num-gpus 1 -j 8 \
  --dtype float16 --warmup-epochs 5 --no-wd --label-smoothing \
  --save-dir params_mobilenet0.25 \
  --logging-file mobilenet0.25.log
```
and i got the output like [this](https://github.com/titikid/gluon-cv/blob/master/scripts/classification/imagenet/mobilenet0.25.log). After 5 epoches, i only got 15.6% top-1 accuracy on Imagenet's val set, which is much lower than 23.6% report [here](https://raw.githubusercontent.com/dmlc/web-data/master/gluoncv/logs/classification/imagenet/mobilenet0.25.log). Further more, after 56 epoches, it got only 21.6% top-1 accuracy

This is the lastest gluoncv v5.0 that i checked out today. I also check my Imagenet dataset, it contain 1281167 images which is the same as reported number for Imagenet 2012. So the code and the dataset should be OK. Can anyone help me?

**Comment by hetong007** [comment]
You need to linearly scale the learning rate with regard to the number of GPUs. Please try with `--lr 0.05` again.

**Comment by titikid** [comment]
@hetong007 you's right. I could get similar result after 10 epoches. Closed
