### ISSUE TITLE
Excessive memory  consumption when training Mask-RCNN-Res50-FPN

### ISSUE THREAD

**Issue by Mooonside** [dmlc/gluon-cv#825]
Hi, I am using the scripts in gluon-cv to train the Mask-RCNN model based on Resnet-50 with FPN turned on. I noticed that the memory consumption goes up to ~11G. However, the reported memory consumption is only ~4G in [mmdetection](https://github.com/open-mmlab/mmdetection/blob/master/MODEL_ZOO.md). Is that normal or do I misconfigure the environment so that excessive memory is used?

**Comment by zhreshold** [comment]
Gluon/mxnet uses gpu memory pool to reduce alloc/de-alloc time so measuring accurate gpu consumption is not available. It's especially important when training some networks with arbitrary input sizes(RCNN series).

**Comment by Mooonside** [comment]
@zhreshold 
So does it means that if I resize all inputs to the same size and set MXNET_CUDNN_AUTOTUNE_DEFAULT to 1, the gpu consumption will become much smaller?

**Comment by zhreshold** [comment]
constant input shape will draw much less memory AFAIK

**Comment by chinakook** [comment]
I have a test. When training a ```mask rcnn resnet 50 fpn``` on a 2080Ti, gluoncv cannot succesfully train a model because ```out of memory```. Even as ```mask rcnn resnet 50 w/o fpn```.
However, mmdetection's ```mask_rcnn_r50_fpn_instaboost_4x``` script only consume 6GB memory when use the same network and same size (1333, 800) and batch_size set to 2 (more than gluoncv's batch_size one).
Can we improve it?

**Comment by zhreshold** [comment]
@szha Will the new memory profiler drop in and help diagnose the issue in this case?

**Comment by chinakook** [comment]
It's bug with that line: https://github.com/dmlc/gluon-cv/blob/96abb97dc9cadf8d2f0eaff25eb0588ec0fab15c/scripts/instance/mask_rcnn/train_mask_rcnn.py#L651
I've comment out all net train code and found that the executor.put (horovod is not availabel) will eat all GPU memory until the training program get crashed.

**Comment by chinakook** [comment]
https://github.com/dmlc/gluon-cv/pull/1249
