### ISSUE TITLE
'module' object has no attribute 'BilinearResize2D'

### ISSUE THREAD

**Issue by jizhishou** [dmlc/gluon-cv#83]
I want to train my own dataset for semantic segmentation. So I just want FCN model to test. My code as follow:
```
from gluoncv.model_zoo.fcn import FCN
model = FCN(19,backbone='resnet50')
x = mx.nd.random.uniform(shape=(1,3,224,224))
preditct = model.forward(x)
```
but I got the error:

> 'module' object has no attribute 'BilinearResize2D'

My mxnet version is 1.1.0.
Is there any solution?

**Comment by jizhishou** [comment]
I have solve the problem
the "BilinearResize2D" api is just in master version
So you need to build mxnet from source. Then it worked.

**Comment by zhanghang1989** [comment]
You can also install nightly version of MXNet ``pip install --pre mxnet``.
