### ISSUE TITLE
possible bug of nms in faster_rcnn?

### ISSUE THREAD

**Issue by alphashuo** [dmlc/gluon-cv#830]
The box_nms operator takes the first dim as batch size when the shape of input is **(C, N, 6)**, which will result in **C** separate nms forward.  Coincidentally, as the **C** dim equals the number of target classes, the final results look like nms (force_suppress = False and id_index is provided) applied to boxes belongs to the same category.  But actually the wrong input format blocks real force_suppress in bbox_nms.

I don't know if I misunderstand the code? @zhreshold 

https://github.com/dmlc/gluon-cv/blob/49056d4892382fca067216d6271d1633d869cb8d/gluoncv/model_zoo/faster_rcnn/faster_rcnn.py#L404-L415

[BoxNMSForward/bounding_box-inl.h](https://github.com/apache/incubator-mxnet/blob/f44f6cfbe752fd8b8036307cecf6a30a30ad8557/src/operator/contrib/bounding_box-inl.h#L349-L353)
[nms_impl/bounding_box-common.h](https://github.com/apache/incubator-mxnet/blob/f44f6cfbe752fd8b8036307cecf6a30a30ad8557/src/operator/contrib/bounding_box-common.h#L89-L92)

besides, I tested pretrained faster rcnn model under the below code, got the same mAP with offical code
```
for rpn_box, cls_id, score, box_pred in zip(rpn_boxes, cls_ids, scores, box_preds):
       # box_pred (C, N, 4) rpn_box (1, N, 4) -> bbox (C, N, 4)
       bbox = self.box_decoder(box_pred, self.box_to_center(rpn_box))
       # res (C, N, 6)
       #res = F.concat(*[cls_id, score, bbox], dim=-1).reshape((1, -1, 6))
       res = F.concat(*[cls_id, score, bbox], dim=-1).reshape((-3, 0))
       # res (C, self.nms_topk, 6)
       res = F.contrib.box_nms(
                res, overlap_thresh=self.nms_thresh, topk=self.nms_topk, valid_thresh=0.01,
                id_index=0, score_index=1, coord_start=2, force_suppress=False)
       # res (C * self.nms_topk, 6)
       #res = res.reshape((-3, 0))
       results.append(res)
```

**Comment by zhreshold** [comment]
@alphashuo  Thanks for catching, the bug has been fixed
