### ISSUE TITLE
WaitToRead function cost too much time

### ISSUE THREAD

**Issue by HouBiaoLiu** [dmlc/gluon-cv#841]
![image](https://user-images.githubusercontent.com/13248587/60323406-9ab18900-99b4-11e9-82ab-80c8c634598c.png)
Here is my test code:
            void RunDemo() {
    // context
    Context ctx = Context::cpu();
    if (args::gpu >= 0) {
        ctx = Context::gpu(args::gpu);
        if (!args::quite) {
          LOG(INFO) << "Using GPU(" << args::gpu << ")...";
        }
    }

    // load symbol and parameters
    Symbol net;
    std::map<std::string, NDArray> args, auxs;
    LoadCheckpoint(args::model, args::epoch, &net, &args, &auxs, ctx);
    std::string filepath = args::image;
    readFileList((char* )filepath.c_str());
    for (int i = 0; i<all_count; i++)
    {

        char one_filename[2000];
        memset(one_filename, '\0', sizeof(one_filename));
        strcpy(one_filename, all_filepath[i]);

        strcat(one_filename, "/");
        strcat(one_filename, all_filename[i]);
        printf("%s\n",one_filename);

        Mat image = imread(one_filename, 1);
        if (!image.data)
            continue;
        image = ResizeShortWithin(image, args::min_size, args::max_size, args::multiplier);
        if (!args::quite) {
            LOG(INFO) << "Image shape: " << image.cols << " x " << image.rows;
        }
    
        // set input and bind executor
        auto data = AsData(image, ctx);
        args["data"] = data;
        Executor *exec = net.SimpleBind(
        ctx, args, std::map<std::string, NDArray>(),
        std::map<std::string, OpReqType>(), auxs);
        
    
        // begin forward
     //   NDArray::WaitAll();
        auto start = std::chrono::steady_clock::now();
        exec->Forward(false);
        auto ids = exec->outputs[0].Copy(Context(kCPU, 0));
        auto scores = exec->outputs[1].Copy(Context(kCPU, 0));
        auto bboxes = exec->outputs[2].Copy(Context(kCPU, 0));
       // NDArray::WaitAll();
       auto end = std::chrono::steady_clock::now();
       if (!args::quite) {
            LOG(INFO) << "Elapsed time {Forward->Result}: " << std::chrono::duration<double, std::milli>(end - start).count() << " ms";
        }
        start = std::chrono::steady_clock::now();
        bboxes.WaitToRead();
     //   scores.WaitToRead();
//        ids.WaitToRead();
        end = std::chrono::steady_clock::now();
        if (!args::quite) {
            LOG(INFO) << "Elapsed time {WaitToRead}: " << std::chrono::duration<double, std::milli>(end - start).count() << " ms";
        }

        int num = bboxes.GetShape()[1];
        std::vector<std::string> class_names = synset::CLASS_NAMES;
        float thresh = args::viz_thresh;
        for (int j = 0; j < num; ++j) {
            float score = scores.At(0, 0, j);
            float label = ids.At(0, 0, j);
            if (score < thresh) continue;
            if (label < 0) continue;
            int x1 = bboxes.At(0, j, 0);
            int y1 = bboxes.At(0, j, 1);
            int x2 = bboxes.At(0, j, 2);
            int y2 = bboxes.At(0, j, 3);
            int cls_id = static_cast<int>(label);
            LOG(INFO) << x1 << " "<<y1<<" "<<x2<< " " << y2;
            if (!args::quite) {
            if (cls_id >= class_names.size()) {
                LOG(INFO) << "id: " << cls_id << ", scores: " << score;
            } else {
                LOG(INFO) << "id: " << class_names[cls_id] << ", scores: " << score;
            }

            }
        }

            
            
        // draw boxes
        //auto plt = viz::PlotBbox(image, bboxes, scores, ids, args::viz_thresh, synset::CLASS_NAMES, std::map<int, cv::Scalar>(), !args::quite);
    
        // display drawn image
        //if (!args::no_display) {
        //    cv::imshow("plot", plt);
        //    cv::waitKey();
        //}
    
        // output image
       // if (!args::output.empty()) {
       //     cv::imwrite(args::output, plt);
        //}
        delete exec;
    }
    

    
}

**Comment by zhreshold** [comment]
checkout mxnet profiler for how to measure time:
https://mxnet.incubator.apache.org/versions/master/tutorials/python/profiler.html

**Comment by lgov** [comment]
Hi HouBiaoLiu, 

the Forward call that you are using is actually a non-blocking call, it just puts data on a queue of operations that then get executed in parallel. It's only when you need the output, or when you explicitly call WaitToRead, that MXNet will wait for all operations to finish. 

L.
