### ISSUE TITLE
transfer learning squeezenet1

### ISSUE THREAD

**Issue by FAFACHR** [dmlc/gluon-cv#842]
Hello @zhreshold, 
I was trying to do a transfer learning for squeezenet1.0 and squeezenet1.1 and with the to cases I got this error : 

> Changing attribute type for output from <class 'mxnet.gluon.nn.basic_layers.HybridSequential'> to <class 'mxnet.gluon.nn.basic_layers.Dense'>is not allowed.

Can you explain to me why I got this error or how can I solve it ? 
Thank you in advanced.

**Comment by zhreshold** [comment]
Print the net if you don't know the structure. For example, squeezenet1.0:

```
...
(output): HybridSequential(
    (0): Conv2D(None -> 1000, kernel_size=(1, 1), stride=(1, 1))
    (1): Activation(relu)
    (2): AvgPool2D(size=(13, 13), stride=(13, 13), padding=(0, 0), ceil_mode=False)
    (3): Flatten
  )
```
There's activate(relu), AvgPool2D and Flatten for the output block, here's how I play with it
```python
>>> type(net.output)
<class 'mxnet.gluon.nn.basic_layers.HybridSequential'>
>>> x = nn.HybridSequential()
>>> x.add(nn.Conv2D(10, 1, strides=1))
>>> x.add(net.output[1])
>>> x.add(net.output[2])
>>> x.add(net.output[3])
>>> x
HybridSequential(
  (0): Conv2D(None -> 10, kernel_size=(1, 1), stride=(1, 1))
  (1): Activation(relu)
  (2): AvgPool2D(size=(13, 13), stride=(13, 13), padding=(0, 0), ceil_mode=False)
  (3): Flatten
)
>>> net.output = x
>>> net.output
HybridSequential(
  (0): Conv2D(None -> 10, kernel_size=(1, 1), stride=(1, 1))
  (1): Activation(relu)
  (2): AvgPool2D(size=(13, 13), stride=(13, 13), padding=(0, 0), ceil_mode=False)
  (3): Flatten
)
```

**Comment by FAFACHR** [comment]
Thank you so much @zhreshold. I understood how to play with the networks.
