### ISSUE TITLE
Failed loading Parameter

### ISSUE THREAD

**Issue by narutobns** [dmlc/gluon-cv#844]
I have trained yolov3 on my own dataset and got params,and i have read some issues like #229,but still failed loading Parameter
In my training script train_yolo3.py, i added the following lines:

class VOCLike(VOCDetection):
       CLASSES=['number']
       def __init__(self,root,splits,transform=None,index_map=None,preload_label=True):
            super(VOCLike,self).__init__(root,splits,transform,index_map,preload_label)

and changes as follows:

def get_dataset(dataset, args):
     if dataset.lower() == 'voc':
         train_dataset = VOCLike(root='/VOCtemplate', splits=((2018, 'train'),))
         val_dataset = VOCLike(root='/VOCtemplate', splits=((2018, 'val'),))
         val_metric = VOC07MApMetric(iou_thresh=0.5, class_names=val_dataset.classes)

and my inference code as follow:

from gluoncv import model_zoo,data,utils
net=model_zoo.get_model('yolo3_darknet53_custom',classes=['number'],pretrained=False)
net.load_parameters('yolo3_darknet53_voc_best.params')

the error log:
Traceback (most recent call last):
  File "inference_yolo_v3.py", line 13, in <module>
    net.load_parameters('yolo3_darknet53_voc_best.params')
  File "/home/user/anaconda3/envs/gluoncv/lib/python3.6/site-packages/mxnet/gluon/block.py", line 405, in load_parameters
    params[name]._load_init(loaded[name], ctx, cast_dtype=cast_dtype)
  File "/home/user/anaconda3/envs/gluoncv/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 251, in _load_init
    self.name, str(self.shape), str(data.shape))
AssertionError: Failed loading Parameter 'yolov30_yolooutputv30_conv0_weight' from saved params: shape incompatible expected (18, 0, 1, 1) vs saved (75, 1024, 1, 1)

Thanks for any help.

**Comment by thinkinds** [comment]
hi, @narutobns , I'm facing the same problem now. Have you solved it now? Can you share your experience? Thx

**Comment by narutobns** [comment]
@thinkinds  change code in train_yolo3.py line 308 net_name = '_'.join(('yolo3', args.network, args.dataset)) to net_name = '_'.join(('yolo3', args.network, 'custom'))

**Comment by gittjob** [comment]
你好！ 这是什么原因呢？我先遇到同样的问题。
