### ISSUE TITLE
The training speed of gluon-ssd is slower than that of mxnet-ssd (39 vs 120 images / second)

### ISSUE THREAD

**Issue by wkcn** [dmlc/gluon-cv#85]
Hi,
It's a great work.
The mAP of ssd_300_vgg16_atrous_voc reaches 0.77.

However, I found the training speed of gluon-ssd is slower than that of [mxnet-ssd](https://github.com/zhreshold/mxnet-ssd).
 
I use Tesla M40 24GB to train SSD(VGG16, 300 x 300) model.

# Environment
Operator System: Ubuntu 14.04
GPU: Tesla M40 24GB
Python: 2.7.12
MXNet: 1.2.0 (installed by pip)
GluonCV: 0.1.0 (installed by pip)

# Performance
Name | #GPUS|Training Speed(images / second)
---------|-----------|-----------
SSD in GluonCV|1|30
SSD in GluonCV|2|37
SSD in GluonCV|4|39
SSD in GluonCV|8|40
mxnet-ssd|4|120
SSD in Caffe|4|40

Reading 32 images takes 5e-5 second in #worker is 32.
It seems that the bottleneck is [data parallel](https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/ssd/train_ssd.py#L175).

[net.target_generator](https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/ssd/train_ssd.py#L183) takes 0.13~0.8 sec times the number of devices. It is not parallel due to [python loop](https://github.com/dmlc/gluon-cv/blob/master/scripts/detection/ssd/train_ssd.py#L175).

**Comment by wkcn** [comment]
@zhreshold Thank you! I will try to replace Block with Hybrid-Block too.

**Comment by wkcn** [comment]
Great. Thank you!

**Comment by zhreshold** [comment]
See #99 

Since synchronization is still required, it won't get linear speed-up, but definitely getting faster.

**Comment by wkcn** [comment]
@zhreshold I will try it.
Thank you!

**Comment by zhreshold** [comment]
The synchronization in loss is preferred, without it, mAP is reduced by ~1%.
The sampler is now pushed to multiple CPU worker.

**Comment by wkcn** [comment]
@zhreshold 
Hi.
In [loss.py line 133](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/loss.py#L133),
Change
```
        for cp, bp, ct, bt in zip(*[cls_pred, box_pred, cls_target, box_target]):
            pos_samples = (ct > 0)
            num_pos.append(pos_samples.sum().asscalar())
        num_pos_all = sum(num_pos)
```
to
```
        for cp, bp, ct, bt in zip(*[cls_pred, box_pred, cls_target, box_target]):
            pos_samples = (ct > 0)
            num_pos.append(pos_samples.sum())
        nd.waitall()
        num_pos_all = sum([p.asscalar() for p in num_pos])
```
I think the latter is faster.

**Comment by zhreshold** [comment]
Sounds good, but I think nd.waitall() may not be necessary.
Do you have numbers regarding this? @wkcn

**Comment by wkcn** [comment]
@zhreshold I do an experiment and found that nd.waitall() is not necessary.
When an asscalar() is called, computational flow graph in all devices will be computed.

**Comment by wkcn** [comment]
The speed of the latest implementation is 102 samples / sec in M40 x 4.
Great! Thank you!
