### ISSUE TITLE
AttributeError: 'AxesSubplot' object has no attribtue 'copy'

### ISSUE THREAD

**Issue by dojinkimm** [dmlc/gluon-cv#852]
Hello, 
I was trying '09. Run an object detection model on your webcam'
which is in tutorial and I have the error as below:

`AttributeError: 'AxesSubplot' object has no attribute 'copy'`

I am using 
`gluoncv 0.4.0, mxnet 1.4.1`

also in the example code
`gcv.utils.viz.cv_plot_bbox `
`gcv.utils.viz.cv_plot_image` are used but it seems that it was updated and 'cv_' should be removed such as `gcv.utils.viz.plot_image`

**Comment by szza** [comment]
update the version of gluoncv to 0.5.0, then the demo ' Run an object detection model on your webcam' can work well

**Comment by dojinkimm** [comment]
Thank you it works well. I will close the issue
