### ISSUE TITLE
It seems that you never use se in resnet and the last fc channels of se is not right.

### ISSUE THREAD

**Issue by PistonY** [dmlc/gluon-cv#855]
https://github.com/dmlc/gluon-cv/blob/5f5ce87d9a1df1623e15d39d1d2dc65317337652/gluoncv/model_zoo/resnet.py#L555

In this line you didn't set `se` status to `resnet_class`, it should be replaced as:
```
net = resnet_class(block_class, layers, channels, use_se=use_se, **kwargs)
```
And the last `fc` in `se` should not multiply by 4

https://github.com/dmlc/gluon-cv/blob/5f5ce87d9a1df1623e15d39d1d2dc65317337652/gluoncv/model_zoo/resnet.py#L90

@hetong007 @piiswrong

**Comment by hetong007** [comment]
It is indeed misleading that we have `se_resnet*` definition in both files:
- https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/se_resnet.py
- https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnet.py

So actually you are using the `se_resnet.py` definition. Will patch a fix to remove redundant definitions.

**Comment by PistonY** [comment]
Good idea.
