### ISSUE TITLE
Feature request: pretrained GoogLeNet

### ISSUE THREAD

**Issue by ifeherva** [dmlc/gluon-cv#856]
In deep metric learning the typical baseline is a pretrained GoogLeNet model. I would like to reproduce some of the older papers that are still relevant, but could not find an mxnet model trained on ImageNet.

Any chance someone trains it and adds to gluoncv?

**Comment by ifeherva** [comment]
I managed to convert the model from ONNX using this:
https://github.com/onnx/models/tree/master/vision/classification/inception_and_googlenet/googlenet

**Comment by bryanyzhu** [comment]
The pretrained GoogleNet is included now. You can check it in the model zoo. 

https://gluon-cv.mxnet.io/model_zoo/classification.html

**Comment by notabigfish** [comment]
> The pretrained GoogleNet is included now. You can check it in the model zoo.
> 
> https://gluon-cv.mxnet.io/model_zoo/classification.html

Hi, I met the following error when trying to load the pretrained googlenet model using `net = gluoncv.model_zoo.get_model("googlenet", pretrained=True)`

```sh
ValueError: "googlenet" is not among the following model list:
	alexnet
	alpha_pose_resnet101_v1b_coco
	cifar_residualattentionnet452
        ...
```

 it seems that the pretrained model is not uploaded?
