### ISSUE TITLE
Can not run classification experiment on docker

### ISSUE THREAD

**Issue by ksellesk** [dmlc/gluon-cv#86]
Seems that in docker process always failed to create tensor on "cpu_shared". While the same experiment runs fine on the host machine.

The simplest code will fail:

```
import mxnet as mx
from mxnet import gluon
from mxnet.gluon.data.vision import transforms

data_dir = './cv/val'

transform_train = transforms.Compose([
    transforms.Resize(480),
    transforms.RandomResizedCrop(224),
    transforms.ToTensor()
])

train_data = gluon.data.DataLoader(
    gluon.data.vision.ImageFolderDataset(data_dir).transform_first(transform_train),
    batch_size=4, shuffle=True, last_batch='discard', num_workers=1)

for batch in train_data:
    print(type(batch))
```

it will stuck here:
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/gluon/data/dataloader.py#L101

**Comment by zhreshold** [comment]
You might need to specify ``--shm-size=500m`` to allow multi process workers to share data.
