### ISSUE TITLE
Question about mixup in faster rcnn?

### ISSUE THREAD

**Issue by keineahnung2345** [dmlc/gluon-cv#861]
I tried to trace the code of faster rcnn and want to find out how it works in mixup mode. In the following code snippet:
https://github.com/dmlc/gluon-cv/blob/5f5ce87d9a1df1623e15d39d1d2dc65317337652/scripts/detection/faster_rcnn/train_faster_rcnn.py#L383-L418
`label` is an array of shape (1, ?, 7) where the last column is `lambd` from `MixupDetection`. But from above, it seems only the first 5 columns of `label` are used.

What I expected is that the last column of `label` will be the weight which will be multiplied to the one-hot encoded class label. CMIIW. Thanks!

**Comment by claytonzhu** [comment]
same doubt here, what dose the ratio use for?

**Comment by lolongcovas** [comment]
same doubt here!

I dont understand what [lambd](https://github.com/dmlc/gluon-cv/blob/f9a8a284b8222794bc842453e2bebe5746516048/gluoncv/data/mixup/detection.py#L72) value is used for.
