### ISSUE TITLE
[bug] code wrong in gluon-cv/docs/tutorials/pose/cam_demo.py 

### ISSUE THREAD

**Issue by mrbulb** [dmlc/gluon-cv#876]
for https://github.com/dmlc/gluon-cv/blob/master/docs/tutorials/pose/cam_demo.py
it seems not a python code

**Comment by hetong007** [comment]
It is on purpose. We build the tutorial for every update to the repo thus we wrap the entire python script into `rst` format comment to save the building time, as well as the non-accessible webcam for our CI machine.
