### ISSUE TITLE
For re-id model, is there a demo to use it on video?

### ISSUE THREAD

**Issue by momo1986** [dmlc/gluon-cv#878]
My current step:
1. Train market1501-based re-id model.
2. Extract the features of some person-id based photo.
3. During video playing, extract the features of current frame from video.
4. Compare current features to person-id based image features and choose the most similar images' id as the predicted id.

However, it looks like not a very good plan and I test with some unexpected returned result.

I am not sure, whether there is  a demo to use it on video. Compared with test.py under the directory of re-id/baseline,  this may looks more engineering-style rather than academics-style.

If a little demo or some pseudo-code described with algorithms could be provided, it would be very beneficial in real application.

Thanks & Regards!
Neo

**Comment by hetong007** [comment]
When computing the feature, did you detect human from the image first and only pass the boxed area into the re-id model, or did you pass the entire image into the re-id model?

The first case is the correct way to do that. 

In terms of the script, we currently don't have the bandwidth to support many demos for re-id, but probably can add a initial script to get users started with simple examples.

**Comment by HieronymusLex** [comment]
@hetong007 I’ve been struggling with this same use case. Would you be able to provide an initial script or just some rough sample code for how to:
1. Extract a feature vector after running the model against an image 
2. Compare this feature vector with another one

**Comment by hetong007** [comment]
@HieronymusLex Here's a script I played with Re-ID a while ago: https://gist.github.com/hetong007/b350102f4f98fa1bd92464a1250cd208. It basically read pictures from input folder and crop detected humans, then save the detected-and-cropped human into output folder. Finally all images in the output folder are used as both querys and keys. 

The resnet definition should be identical to https://github.com/dmlc/gluon-cv/blob/master/scripts/re-id/baseline/networks/resnet.py

If interested, you are very welcome to clean up the code and contributed a tutorial.

**Comment by HieronymusLex** [comment]
@hetong007 great stuff!! I'll look at submitting a PR for a tutorial. I imagine this issue could probably be closed now
