### ISSUE TITLE
the image  preprocess details in Bag of Freebies for Training Object Detection Neural Networks 

### ISSUE THREAD

**Issue by XuChunqiao** [dmlc/gluon-cv#879]
In paper, the image preprocess is :

> 4. Scale **hue, saturation, and brightness** with coefficients uniformly drawn from [0:6; 1:4].

![1](https://user-images.githubusercontent.com/43721132/61687647-882d3400-ad55-11e9-8b00-e79513dbf604.png)

However, in released code:
Scale **contrast, saturation, and brightness** with coefficients uniformly drawn from [0:6; 1:4].
![code](https://user-images.githubusercontent.com/43721132/61687749-b7dc3c00-ad55-11e9-8f69-797b30318cc3.png)

**Comment by zhreshold** [comment]
@XuChunqiao  the code you referenced is for image classification

**Comment by XuChunqiao** [comment]
> @XuChunqiao the code you referenced is for image classification

Thanks for your answer, but I don't understand. The paper _Bag of Freebies for Training Object Detection Neural Networks_ is also for image classification， isn’t it？
![LYPC6X`PN8G6RD1V59%3K83](https://user-images.githubusercontent.com/43721132/61918833-7a5df580-af85-11e9-9324-ce24fbfb04a1.png)
However， in the released code it scales **contrast**， and in the paper it scales **hue**. They are different.

**Comment by zhreshold** [comment]
No, the corresponding code is in YOLOv3/Faster-RCNN examples, not in image classification part.
