### ISSUE TITLE
Using your trained pose detection my own photo 

### ISSUE THREAD

**Issue by carolynenewman** [dmlc/gluon-cv#884]
Hello, I am trying to run Gluon's pretrained pose detection inference on my own photo. The photo is a PIL image. I have tried to run the pose detection tutorial on the PILimage, converted the image to a numpy array, a mx.ndarray, and a PIL raw image (PNG). None of these seem to work. When I run the code on the mx.ndarray version, which I think is correct, I get the error:

raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:20:36] src/io/image_io.cc:223: Check failed: file.is_open(): Imread: '
[[25. 27. 39.]
 [24. 26. 38.]
 [23. 25. 37.]
 ...
 [18. 23. 45.]
 [20. 22. 45.]
 [20. 22. 45.]]
<NDArray 640x3 @cpu(0)>' couldn't open file: No such file or directory

If anyone knows how I can successfully run pose detection on my own photo, and what type I need to convert my photo to, I would really appreciate the help!

**Comment by hetong007** [comment]
Hi @carolynenewman , have you read through this tutorial: https://gluon-cv.mxnet.io/build/examples_pose/demo_simple_pose.html ? 

Please first try to convert your image to an `mx.NDArray`, then replace this line in the tutorial
```python
x, img = data.transforms.presets.ssd.load_test(im_fname, short=512)
```
with 
```python
x, img = data.transforms.presets.ssd.transform_test(im_fname, short=512)
```

It then should successfully transform your image.

Here `load_test` loads an image from disk, while `transform_test` takes the image from an existing variable. From your partial error log I suspect this is the cause.

**Comment by carolynenewman** [comment]
Thank you so much for your suggestion! Unfortunately, this did not work. I converted my numpy array image to a md.NDarray, and included your line below via:

im_fname = mx.ndarray.array(image)
x, img = data.transforms.presets.ssd.transform_test(im_fname, short=512)

Now, I have the error:

Shape of pre-processed image: (1, 3, 512, 910)
Traceback (most recent call last):
  File "seeVideo.py", line 22, in <module>
    poseAlg(image)
  File "/Users/cnewman/Anki/vector-python-sdk/examples/project/MaskRCNN/pose.py", line 24, in poseAlg
    predicted_heatmap = pose_net(pose_input)
  File "/Users/cnewman/Anki/lib/python3.7/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/Users/cnewman/Anki/lib/python3.7/site-packages/mxnet/gluon/block.py", line 929, in forward
    "Symbol or NDArray, but got %s"%type(x)
AssertionError: HybridBlock requires the first argument to forward be either Symbol or NDArray, but got <class 'NoneType'>

So this time, it seems like was not able to detector(x). What do you think?

**Comment by hetong007** [comment]
The conversion seems invalid. You may try 

```python
img = mx.ndarray.array(numpy.array(image))
x, img = data.transforms.presets.ssd.transform_test(img, short=512)
```

**Comment by carolynenewman** [comment]
Thanks for your help. I tried this and it yielded the same error. Anything else you think it might be?

**Comment by hetong007** [comment]
it helps more if you could provide a piece of code which reproduces the issue.

i looked at the err message again, and seems it is from this call: `predicted_heatmap = pose_net(pose_input)`. `pose_input` seems to be empty, while it is supposed to be the detected human from the input image by the object detector.

so it is either the human detection didn't detected human on the input, or the input image doesn't have any human to be detected.

**Comment by carolynenewman** [comment]
Interesting... Let me try something and get back to you!

**Comment by carolynenewman** [comment]
All is working, I just needed a human in the photo! Thank you so much for your help and patience.
