### ISSUE TITLE
AttributeError: 'list' object has no attribute 'asnumpy' if no gt_difficults given.

### ISSUE THREAD

**Issue by kohillyang** [dmlc/gluon-cv#89]
https://github.com/dmlc/gluon-cv/blob/fa33ede0832f3560ad752599d0046c44ea3b0bc8/gluoncv/utils/metrics/voc_detection.py#L93

I think gt_difficults should be NDArray here, not list.

**Comment by zhreshold** [comment]
Fixed in #94
