### ISSUE TITLE
MonileNet V3 counterintuitive training configurations

### ISSUE THREAD

**Issue by CanyonWind** [dmlc/gluon-cv#909]
When trying to reproduce the MobileNet V3 training results, the configuration is found quite different compared to what original paper proposed (this is actually acceptable) / but also not aligned with GluonCV's own MobileNet V2 configuration. 

The current configuration is assumed to be kind of the 'optimal' one. Could anyone consult me about, **based on what consideration**,  MobileNetV3 setting is:
`--lr 2.6 (accumulated batch size: 256 * 8, float 16 ),  --wd 0.00003 and --num-epochs 360  etc.`

While MobileNet V2 1.0 setting is:
`--lr 0.05 (accumulated batch size: 64 * 4, float 32) --wd 0.00004 and --num-epochs 150 etc.`

For example here are three counterintuitive settings for me:
1. Shouldn't the LR be proportional to the batch size? Maybe 0.05 * (256 * 8) / (64 * 4) = 0.4 ?
2. Why wd is smaller? MobileNet v3 large actually has more parameters than v2 1.0, shouldn't it be larger for stronger regularization?
3. Even though larger batch size results in less parameter update frequency, the LR has already be increased, even more than what it is supposed to be. Why # of epochs is set larger?

Thanks

**Comment by CanyonWind** [comment]
Anyone to help please?

**Comment by hetong007** [comment]
MobileNet V3 is a difficult one to reproduce. Following MobileNet V2/V3 settings we can only get to somewhere around 74.7%.

We did random search for MobileNet V3 training and eventually you see the results.

**Comment by CanyonWind** [comment]
@hetong007 I see. Appreciate your help
