### ISSUE TITLE
Combine datasets in a single dataloader

### ISSUE THREAD

**Issue by douglas125** [dmlc/gluon-cv#910]
I would like to experiment with combining multiple datasets to retrain object detection but I am unable to find an easy way to do so.

Using https://gluon-cv.mxnet.io/build/examples_detection/train_yolo_v3.html as a base example, my first idea would be to change 

`       for i, batch in enumerate(train_data):`

to handle train_data as a list of dataloaders. That, however, would prevent mixup of data from the different datasets in the minibatch.

I was wondering if there is an easy way to combine the datasets before creating the dataloader, i.e., before this line, for example:

`    val_loader = gluon.data.DataLoader(
        val_dataset.transform(YOLO3DefaultValTransform(width, height)),
        batch_size, False, batchify_fn=val_batchify_fn, last_batch='keep', num_workers=num_workers)`

It seems to me that the structure should be quite similar to `class ArrayDataset(Dataset):` that combines dataset-like objects.

Any suggestions?

**Comment by zhreshold** [comment]
something similar to this
```python
class CombineDataset(object):
    def __init__(self, datasets):
        self._datasets = datasets
        self._lens = [len(x) for x in self._datasets]
        self._total_len = sum(self._lens)
        self._indices = np.cumsum(self._lens)
    
    def __len__(self):
        return self._total_lens

    def __getitem__(self, idx):
        assert idx < self._total_lens
        i = np.nonzero(self._indices < idx)[0]
        return self._datasets[i][idx - self._indices[i]]

```
