### ISSUE TITLE
Bug? net.reset_class fails to reset classes

### ISSUE THREAD

**Issue by douglas125** [dmlc/gluon-cv#911]
Hi;

It looks like reset_classes has a bug when rebuilding the internal class mapping.

Code to reproduce the issue:

```
import gluoncv as gcv
net = gcv.model_zoo.get_model('ssd_512_mobilenet1.0_coco', pretrained=True)

classes = ['bench', 'bicycle', 'bus', 'car', 'cat']
classes_dict = dict(zip(classes, classes))

net.reset_class(classes, reuse_weights = classes_dict )
```

It looks like the problem is the in-place chance of the dictionary:

Cmd:
`dict(zip(classes, classes))`
Output:
`{'bench': 'bench',
 'bicycle': 'bicycle',
 'bus': 'bus',
 'car': 'car',
 'cat': 'cat'}`

Cmd:
`classes_dict`
Output:
`{'bicycle': 'bicycle', 0: 13, 2: 5, 3: 2, 4: 15}`

I am using the latest gluoncv installed with --pre --upgrade.

**Comment by zhreshold** [comment]
there's a bug for str-> str mapping, I will fix it.
Currently you can use list of str since you are not renaming any of these classes.

```python
net.reset_class(classes, reuse_weights=classes)
```

**Comment by douglas125** [comment]
This PR should fix the issue https://github.com/dmlc/gluon-cv/pull/914
