### ISSUE TITLE
AttributeError: module 'gluoncv.utils.viz' has no attribute 'cv_plot_bbox'

### ISSUE THREAD

**Issue by kunal732** [dmlc/gluon-cv#918]
I get the following issue:
`/usr/local/lib/python2.7/site-packages/mxnet/gluon/block.py:1159: UserWarning: Cannot decide type for the following arguments. Consider providing them as input:
	data: None
  input_sym_arg_type = in_param.infer_type()[0]
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    img = gcv.utils.viz.cv_plot_bbox(frame, bounding_boxes[0], scores[0], class_IDs[0], class_names=net.classes)`

`AttributeError: 'module' object has no attribute 'cv_plot_bbox'`

whenever I try to run the object detection from webcam tutorial here: [https://gluon-cv.mxnet.io/build/examples_detection/demo_webcam.html](https://gluon-cv.mxnet.io/build/examples_detection/demo_webcam.html)

Has anyone seen this issue before ?

**Comment by zhreshold** [comment]
Please update gluoncv to master
```
pip install gluoncv --upgrade --pre
```

**Comment by prashan** [comment]
I also get a similar error(shown below) and the command "pip install gluoncv --upgrade --pre" doesn't solve the problem.

AttributeError: module 'gluonnlp.utils' has no attribute 'check_version'

**Comment by zhreshold** [comment]
@prashan Your error shows it's from gluonnlp package

**Comment by prashan** [comment]
yeah i did the upgrades for the nlp package and I am trying to run this tutorial : https://gluon-nlp.mxnet.io/master/examples/sentence_embedding/bert.html
pip install --upgrade mxnet>=1.5.0
pip install gluonnlp --upgrade --pre
