### ISSUE TITLE
Remove "ignore value" underscore for Mask RCNN demo.

### ISSUE THREAD

**Issue by jpilorget** [dmlc/gluon-cv#920]
The "ignore value" underscore at line 49 of script "demo_mask_rcnn,py" (file path: scripts/instance/mask_rcnn/demo_mask_rcnn.py) gives an error for "too many values to unpack". It should be removed in order to make the code work.

**Comment by Jerryzcn** [comment]
Are you sure you are using the latest version of gluon-cv? Mine works w/o exception.
