### ISSUE TITLE
Please make sure source and target networks have the same prefix.

### ISSUE THREAD

**Issue by kunal732** [dmlc/gluon-cv#925]
Trained an object detection model with a base net set as resnet50 on aws. Trying to load that in gluoncv for real time object detection. Using the code from this tutorial:
https://gluon-cv.mxnet.io/build/examples_detection/demo_webcam.html

Getting an issue where the prefixes aren't the same. Can someone point me in the right direction so I can run this model ?

Here is my code where I load the model:

```
net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_custom', classes=my_classes, pretrained=True)
net.load_parameters('model_algo_1-0000.params')
```

Here is the output after running my program:

`AssertionError: Parameter 'resnetv10_conv0_weight' is missing in file 'model_algo_1-0000.params', which contains parameters: 'ssd0_stage1_unit3_bn2_moving_var', 'ssd0_stage1_unit1_bn2_gamma', 'ssd0_stage4_unit3_bn3_gamma', ..., 'ssd0_stage2_unit4_conv3_weight', 'ssd0_conv0_weight', 'ssd0_stage1_unit3_bn3_moving_mean', 'ssd0_stage2_unit3_bn2_gamma'. `

`Please make sure source and target networks have the same prefix.`

It looks like I have the right parameter but it just has ssd0 as the prefix instead of resnetv10. 

**resnetv10_conv0_weight
ssd0_conv0_weight**

Any idea on how I can fix this ?

**Comment by hetong007** [comment]
Would you try

```python
net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_custom', classes=my_classes, pretrained=False)
net.load_parameters('model_algo_1-0000.params')
```
?

Note that `pretrained=True` loads the official pretrained model and that may contain a different set of parameter names.

**Comment by kunal732** [comment]
Same error :/

**Comment by hetong007** [comment]
@zhreshold would you share any insight?

**Comment by kunal732** [comment]
@hetong007 @zhreshold would it help if I attached the model? Just trying to run it in https://gluon-cv.mxnet.io/build/examples_detection/demo_webcam.html

**Comment by zhreshold** [comment]
@kunal732 Wondering where did you get the `model_algo_1-0000.params` file?

**Comment by kunal732** [comment]
@zhreshold this was created in SageMaker.

**Comment by svpino** [comment]
I'm having exactly the same issue as @kunal732. I trained my model in SageMaker and got the .params file. Then, I try to load that model.params in GluonCV and get the following error:


`Parameter 'resnetv10_conv0_weight' is missing in file 'model.params', which contains parameters: 'ssd2_multi_feat_3_conv_1x1_conv_weight', 'ssd2_stage2_unit3_bn3_gamma', 'ssd2_stage1_unit1_sc_weight', ..., 'ssd2_stage4_unit1_bn3_moving_mean', 'ssd2_stage1_unit2_conv3_weight', 'ssd2_stage3_unit4_bn1_beta', 'ssd2_multi_feat_5_conv_1x1_conv_weight'. Please make sure source and target networks have the same prefix.`

**Comment by zhreshold** [comment]
Sagemaker might be using the deprecated model serialization method. You can try load the params using `net.load_params` instead of `net.load_parameters' or vise versa

**Comment by svpino** [comment]
I was using `net.load_parameters` before. This is the error I get when trying to use `net.load_params`:

```
AssertionError                            Traceback (most recent call last)
<ipython-input-45-77b1a7b1b54d> in <module>()
      8 #net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_coco', classes=object_categories, pretrained_base=False)
      9 net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_custom', classes=object_categories, pretrained_base=False)
---> 10 net.load_params('model.params')
     11 x, image = gcv.data.transforms.presets.ssd.load_test('mytest.jpg', 512)
     12 cid, score, bbox = net(x)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/gluon/block.py in load_params(self, filename, ctx, allow_missing, ignore_extra)
    419         """
    420         warnings.warn("load_params is deprecated. Please use load_parameters.")
--> 421         self.load_parameters(filename, ctx, allow_missing, ignore_extra)
    422 
    423     def register_child(self, block, name=None):

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/gluon/block.py in load_parameters(self, filename, ctx, allow_missing, ignore_extra)
    384             del loaded
    385             self.collect_params().load(
--> 386                 filename, ctx, allow_missing, ignore_extra, self.prefix)
    387             return
    388 

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/gluon/parameter.py in load(self, filename, ctx, allow_missing, ignore_extra, restore_prefix)
    909                     "Parameter '%s' is missing in file '%s', which contains parameters: %s. " \
    910                     "Please make sure source and target networks have the same prefix."%(
--> 911                         name[lprefix:], filename, _brief_print_list(arg_dict.keys()))
    912         for name in arg_dict:
    913             if name not in self._params:

AssertionError: Parameter 'resnetv10_conv0_weight' is missing in file 'model.params', which contains parameters: 'ssd4_multi_feat_3_conv_1x1_conv_weight', 'ssd4_stage2_unit3_bn3_gamma', 'ssd4_stage1_unit1_sc_weight', ..., 'ssd4_stage4_unit1_bn3_moving_mean', 'ssd4_stage1_unit2_conv3_weight', 'ssd4_stage3_unit4_bn1_beta', 'ssd4_multi_feat_5_conv_1x1_conv_weight'. Please make sure source and target networks have the same prefix.
```

**Comment by zhreshold** [comment]
Can you provide the json file saved by sagemaker?

**Comment by svpino** [comment]
Yes. You can download it from here: 

https://nee-inventory-management.s3.amazonaws.com/DEMO-ObjectDetection/output/object-detection-2019-11-10-16-49-47-697/output/model_algo_1-0000.params

**Comment by zhreshold** [comment]
@svpino sorry, I mean the json file instead of the params file

**Comment by svpino** [comment]
Here is the JSON file: https://nee-inventory-management.s3.amazonaws.com/DEMO-ObjectDetection/output/object-detection-2019-11-10-16-49-47-697/output/model_algo_1-symbol.json

**Comment by zhreshold** [comment]
Thanks, after chekcing the json I found that the implementation of SSD is using the symbolic implementation as in https://github.com/apache/incubator-mxnet/tree/master/example/ssd.
You can use the symbolic example to load the sagemaker model. 
For reference, GluonCV uses new way to implement SSD and removed usage of many contrib operators so it's more versatile and export friendly.

**Comment by svpino** [comment]
Thanks, Joshua! I'm not quite sure I know right away how to load the model because I'm not familiar with the "symbolic implementation" and how it differs from what I currently have. It seems that I'll need to spend more time to make that leap, but I also want to be respectful of your time.

**Comment by kunal732** [comment]
@svpino just curious if you were able to get it working.

**Comment by svpino** [comment]
Not yet, no. I haven't had the time to look into it.

**Comment by djaym7** [comment]
Use net.load_parameters() and net.save_parameters() to load and save.

**Comment by ALLUPRASAD** [comment]
> Here is the JSON file: https://nee-inventory-management.s3.amazonaws.com/DEMO-ObjectDetection/output/object-detection-2019-11-10-16-49-47-697/output/model_algo_1-symbol.json

that prefix issue solved?

**Comment by ALLUPRASAD** [comment]
> Trained an object detection model with a base net set as resnet50 on aws. Trying to load that in gluoncv for real time object detection. Using the code from this tutorial:
> https://gluon-cv.mxnet.io/build/examples_detection/demo_webcam.html
> 
> Getting an issue where the prefixes aren't the same. Can someone point me in the right direction so I can run this model ?
> 
> Here is my code where I load the model:
> 
> ```
> net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_custom', classes=my_classes, pretrained=True)
> net.load_parameters('model_algo_1-0000.params')
> ```
> 
> Here is the output after running my program:
> 
> `AssertionError: Parameter 'resnetv10_conv0_weight' is missing in file 'model_algo_1-0000.params', which contains parameters: 'ssd0_stage1_unit3_bn2_moving_var', 'ssd0_stage1_unit1_bn2_gamma', 'ssd0_stage4_unit3_bn3_gamma', ..., 'ssd0_stage2_unit4_conv3_weight', 'ssd0_conv0_weight', 'ssd0_stage1_unit3_bn3_moving_mean', 'ssd0_stage2_unit3_bn2_gamma'. `
> 
> `Please make sure source and target networks have the same prefix.`
> 
> It looks like I have the right parameter but it just has ssd0 as the prefix instead of resnetv10.
> 
> **resnetv10_conv0_weight ssd0_conv0_weight**
> 
> Any idea on how I can fix this ?

did you fixed this issue?I am aslo facing same

**Comment by Jonathan995** [comment]
Hi,
Did you fix the issue? I am trying to do exactly the same thing and facing the same error.

**Comment by ALLUPRASAD** [comment]
Yup..Need to modify model parameters names in wieghts file

**Comment by LewsTherin511** [comment]
Hi there, having the same problem. I used a "ssd_512_resnet50_v1_coco" model for finetuning and now I'm trying to load the .params file by:

`	classes = ["CML_mug", "person"]
	net = gcv.model_zoo.get_model('ssd_512_resnet50_v1_custom',
							  classes=classes,
							  pretrained_base=False,
							  ctx=ctx)
	net.load_params("saved_weights/CML_00/-0070.params", ctx=ctx)
`

but I'm getting the error:

`AssertionError: Parameter 'resnetv10_conv0_weight' is missing in file: saved_weights/CML_00/-0070.params, which contains parameters: 'ssd1_ssd0_resnetv10_conv0_weight', 'ssd1_ssd0_resnetv10_batchnorm0_gamma', 'ssd1_ssd0_resnetv10_batchnorm0_beta', ..., 'ssd1_ssd0_ssdanchorgenerator2_anchor_2', 'ssd1_ssd0_ssdanchorgenerator3_anchor_3', 'ssd1_ssd0_ssdanchorgenerator4_anchor_4', 'ssd1_ssd0_ssdanchorgenerator5_anchor_5'. Please make sure source and target networks have the same prefix.
`

@ALLUPRASAD , what do you mean by "modify model parameters names in weights file"? I assume I should remove the 'ssd1_ssd0' part before the network parameters names in the .params file, but I cannot open it to modify it.

**Comment by ALLUPRASAD** [comment]
Yes you should remove ssd1_ssd0 .
Load the parama file using- nd.load(model.parameters) ,remove the ssd1_ssd0
and save  nd.save(modified.params)

**Comment by LewsTherin511** [comment]
Btw, I fixed it in another way, I don't know if it can be useful. When finetuning the model, I was using:

`net.export`

to save the .param file, and loading it for inference by:

`net.load_parameters`

It seems that this was leading to the different names in the weights names...if I replace net.export with:

`net.save_parameters`

I don't have the problem anymore.

**Comment by zhreshold** [comment]
Adding to 

> Btw, I fixed it in another way, I don't know if it can be useful. When finetuning the model, I was using:
> 
> `net.export`
> 
> to save the .param file, and loading it for inference by:
> 
> `net.load_parameters`
> 
> It seems that this was leading to the different names in the weights names...if I replace net.export with:
> 
> `net.save_parameters`
> 
> I don't have the problem anymore.
> Just, at this point I wonder which is the right way to load the parameters saved by net.export...

THe exported model is a symbolic model which is good for (deployment, converter, graph representation), but it's not a good fit for python network, if you are still playing with python, the good serialization trick is

```
net.save_parameters('xxx.params')
net.load_parameters('xxx.params')
```
