### ISSUE TITLE
train simplepose heatmap_accuracy is very low

### ISSUE THREAD

**Issue by jinfei3459** [dmlc/gluon-cv#929]
```
Namespace(batch_size=32, data_dir='~/.mxnet/datasets/coco', dtype='float32', input_size='256,192', last_gamma=False, log_interval=100, logging_file='simple_pose_resnet18_v1b.log', lr=0.001, lr_decay=0.1, lr_decay_epoch='90,120', lr_decay_period=0, lr_mode='step', mean='0.485,0.456,0.406', mode='hybrid', model='simple_pose_resnet18_v1b', no_wd=False, num_epochs=140, num_gpus=8, num_joints=17, num_workers=60, save_dir='params_simple_pose_resnet18_v1b', save_frequency=1, std='0.229,0.224,0.225', use_pretrained=False, use_pretrained_base=True, warmup_epochs=0, warmup_lr=0.0, wd=0.0)
```
ENV: python 3.5.2, mxnet1.5.0, cuda10.0, ubuntu16.04 ,nvidia rtx2080
train data is coco train2017,
after 31 epoch, heatmap_accuracy only is  around 0.153,and after the second iteration, heatmap_accuracy is around 0.155
my training steps is follow the gluoncv simplepose code,
could you give me some advice?

**Comment by hetong007** [comment]
Have you modified the training script, and what is the gluoncv version that you are working with?

**Comment by jinfei3459** [comment]
> Have you modified the training script, and what is the gluoncv version that you are working with?

I didn't modify the training scrpt, gluoncv version is 0.5.0
