### ISSUE TITLE
Error while ssd inference: kernel size exceed input

### ISSUE THREAD

**Issue by sodadi** [dmlc/gluon-cv#938]
Hi, I trained a _ssd_512_vgg16_atrous_custom_ model and saved the params file.

When running the model, I am making sure that all images are 3 channel images. But for a few images, where the max_size is of length 1024 and the resize is not done.
I get an error:
**_C:\Jenkins\workspace\mxnet-tag\mxnet\src\operator\nn\convolution.cc:203: Check failed: dilated_ksize_y <= AddPad(dshape[2], param_.pad[0]) (4 vs. 3) : kernel size exceed input_**

The image for which it fails is of size: (3, 184, 1024).
The resize, x, img = data.transforms.presets.ssd.load_test(file_path, short=512), doesnt occur for the images, since the maxsize is capped at 1024.

What is the workaround if any for this error?
if the size is at 1024, why does inference fail?

Thanks,
Adi

**Comment by rondogency** [comment]
Hi, I came across the similar error, and I resolved it by resizing all images to be 512x512. Did you resolve this in the end?
