### ISSUE TITLE
VOCMApMetric.update() fails when the first element of gt_difficults is None

### ISSUE THREAD

**Issue by muhyun** [dmlc/gluon-cv#939]
VOCMApMetric.update() fails when the first element of gt_difficults is None;

```
Traceback (most recent call last):
  File "gluoncv-lab1.3-transfer-learning.py", line 357, in <module>
    train(net, train_data, val_data, eval_metric, ctx, args)
  File "gluoncv-lab1.3-transfer-learning.py", line 306, in train
    map_name, mean_ap = validate(net, val_data, ctx, eval_metric)
  File "gluoncv-lab1.3-transfer-learning.py", line 187, in validate
    eval_metric.update(det_bboxes, det_ids, det_scores, gt_bboxes, gt_ids, gt_difficults)
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluoncv/utils/metrics/voc_detection.py", line 112, in update
    if len(gt_difficults) * gt_difficults[0].shape[0] != \
AttributeError: 'NoneType' object has no attribute 'shape'
```
A possible fix is to check the type of the first element, and the change will be from

`if len(gt_difficults) * gt_difficults[0].shape[0] != \`

to

`if gt_difficults[0] == None or len(gt_difficults) * gt_difficults[0].shape[0] != \`

**Comment by schneider128k** [comment]
I see to be have a very similar issue. I have made a comment on the relevant commit before I saw that you opened this issue.

https://github.com/dmlc/gluon-cv/commit/5b81f849af31bd914365e660d2fd8434dfb7cc51

**Comment by sodadi** [comment]
got it resolved by changing voc_detection:
        if isinstance(gt_labels, list):
            gt_diff_shape = gt_difficults[0].shape[0] if hasattr(gt_difficults[0], 'shape') else 0
            if len(gt_difficults) * gt_diff_shape != \
                    len(gt_labels) * gt_labels[0].shape[0]:
                gt_difficults = [None] * len(gt_labels) * gt_labels[0].shape[0]

Or you can just update gloun
