### ISSUE TITLE
Set ctx=mx.gpu(0) but all demo code run full cpu

### ISSUE THREAD

**Issue by solua** [dmlc/gluon-cv#943]
Hi,

I try gluoncv example code " Run an object detection model on your webcam".

> ctx = mx.gpu(0)
> net = gcv.model_zoo.get_model('ssd_512_mobilenet1.0_voc', pretrained=True,ctx = ctx)
> .....
> rgb_nd = rgb_nd.as_in_context(ctx)
> class_IDs, scores, bounding_boxes = net(rgb_nd)

Demo run but when I check in htop all cpu full load, but nvidia-smi show no GPU resource use.

My pc specs:
Cuda 10.1
mxnet-cu101mkl
gluoncv (0.5.0)
Ubuntu 18.04 
python3.6

I try both virtualenv and normal env.
Thanks

**Comment by caishanli** [comment]
use mxnet.context.num_gpus() to check your mxnet env with cuda is ok or not

**Comment by solua** [comment]
Hi caishanli,
mxnet.context.num_gpus()  return 2
I seem normal, because I still can run other mxnet model normal except gluoncv
