### ISSUE TITLE
Data Parallel Fails with Single GPU

### ISSUE THREAD

**Issue by zhanghang1989** [dmlc/gluon-cv#95]
Keeping track of the issue reported by @mylxiaoyi 
https://github.com/dmlc/gluon-cv/pull/93#discussion_r186594692

*"I have only one GPU, when used with aux=True in FCN, the outputs is a tuple, and the length of the outputs is 2, so cause the assert error, because the len(self.ctx_list) is 1. If used with aux=False in FCN, the length of the outputs is the batch_size, e.g. 4, and also cause assert error."*

**Comment by mylxiaoyi** [comment]
https://github.com/dmlc/gluon-cv/blob/af5ff238b3b9ea5073c80b54619b1331578c79da/scripts/segmentation/train.py#L161

When used with one GPU,  the outputs from `self.evaluator(data, target)` is a tuple and the length of it is 4, the elements within it are `numpy.float32, numpy.float32, numpy.ndarray, numpy.ndarray ` respectively, so cause error

```python
TypeError: 'numpy.float32' is not iterable
```
