### ISSUE TITLE
Reduce the inference cost of Faster R-CNN with FPN

### ISSUE THREAD

**Issue by wkcn** [dmlc/gluon-cv#952]
Hi, there.

In the implementation of Faster R-CNN with FPN, it takes much time in RoIPooling.
The reason is that RoIPooling computes the feature of duplicated proposals.
https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/faster_rcnn/faster_rcnn.py#L298

There are some procedures to reduce the inference cost.
1. Modify the implementation of RoIPooling and RoIAlign
https://github.com/apache/incubator-mxnet/blob/master/src/operator/roi_pooling.cc#L75
For invalid indexes, we should ignore its output and gradient.

2. Change some indexes of `rpn_rois` to `-1` when they are not in the specific `roi_level`
RoIPooling only computes the feature of proposals, which are in the specific roi level.

3. Use assigment rather than sum to aggregate pooled features
`pooled_roi_feats = F.ElementWiseSum(*pooled_roi_feats)` need extra addition to aggregate features.

**Comment by zhreshold** [comment]
@Jerryzcn is working on speeding up that.

**Comment by Jerryzcn** [comment]
The main reason FPN is slower is actually the num of RCNN samples. FPN network uses 512, whereas non-FPN version uses 128. That being said, I have modified ROIAlign, here, the gain is not significant.

**Comment by Jerryzcn** [comment]
Regarding #3, the issue is that the number of rois for each level is dynamic, so it is tricky to use assignment.

**Comment by Jerryzcn** [comment]
The change for ROIAlign is in https://github.com/apache/incubator-mxnet/pull/16215
