### ISSUE TITLE
How to add color legend for predicted masks in semantic segmentation? 

### ISSUE THREAD

**Issue by CWen001** [dmlc/gluon-cv#963]
Thank you very much for this great work. The tools and tutorials are really great to follow, and they encourage people from a non-technical background like me to enjoy CV and get a taste of deep learning.

May I have a question about plotting predicted masks in the semantic segmentation, please. I was following [this official tutorial](https://gluon-cv.mxnet.io/build/examples_segmentation/demo_psp.html). After predicting using a pre-trained model, I want to plot the masks together with a legend bar to indicate which color represents what class. Like a blue square with the text "water". Is there an easy way to add the legend bar and associated texts? I found a [repo](https://github.com/RomRoc/deeplab_retrain_ade20k_colab) that may provide a solution by hard coding a lot, but it looks difficult for me so far.

Since there is a handy function `get_color_pallete(predict, 'ade20k')` to help transform the mask color to 'ade20k', is it possible to enhance one of the utility functions to add a color legend with text?

**Comment by dai-ichiro** [comment]
I'm not sure if it will help, but try this code once.

```
import numpy as np
from matplotlib import pyplot as plt
import gluoncv.utils.viz.segmentation as seg

pallete = seg.vocpallete

label = [
    "aeroplane", "bicycle", "bird", "boat", "bottle",
    "bus", "car", "cat", "chair", "cow",
    "diningtable", "dog", "horse", "motorbike", "person",
    "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

left = np.array(range(20))
height = np.ones(20)

col = []
for i in range(1,21):
    col.append([x/255 for x in pallete[(i*3):(i*3+3)]])

plt.barh(left, height, tick_label=label, align="center",color=col)
plt.show()
```
