### ISSUE TITLE
test two times during one epoch in train_cifar10.py

### ISSUE THREAD

**Issue by ShoufaChen** [dmlc/gluon-cv#964]
In [train_cifar10.py](https://github.com/dmlc/gluon-cv/blob/master/scripts/classification/cifar/train_cifar10.py) script,  it seem that in [line 173](https://github.com/dmlc/gluon-cv/blob/master/scripts/classification/cifar/train_cifar10.py#L173) and [line181](https://github.com/dmlc/gluon-cv/blob/master/scripts/classification/cifar/train_cifar10.py#L181).  the `test()`function executes two times during one epoch. Is it necessary?

Thank you!

**Comment by hetong007** [comment]
Good catch! it has been fixed.
