### ISSUE TITLE
How to modify FasterRCNN for training on custom dataset

### ISSUE THREAD

**Issue by SengCheong** [dmlc/gluon-cv#967]
Hello,

I apologize if this is the wrong place to post an issue, but I have tried asking this question on StackOverflow and on the MXnet forums [discuss.mxnet.io](url) without success and I have run out of locations to ask.

For reference, the following posts at StackOverflow & MXNet respectively are provided, so i can keep my posts short and brief:
[https://discuss.mxnet.io/t/how-to-modify-fasterrcnn-for-training-on-custom-dataset/4828/4](https://discuss.mxnet.io/t/how-to-modify-fasterrcnn-for-training-on-custom-dataset/4828/4)
[https://stackoverflow.com/questions/58147330/how-to-train-gluoncvs-faster-rcnn-on-a-custom-dataset](https://stackoverflow.com/questions/58147330/how-to-train-gluoncvs-faster-rcnn-on-a-custom-dataset)

To summarize, I am trying to train the FasterRCNN on a custom dataset. The custom dataset is built using the tutorial from [https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html](https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html). I had no issue adapting the SSD model onto my dataset from [https://gluon-cv.mxnet.io/build/examples_detection/finetune_detection.html](https://gluon-cv.mxnet.io/build/examples_detection/finetune_detection.html), and had no issue modifying the script for YoloV3.

However, I have errors when trying to train the FasterRCNN model, as I could not enumerate over my dataset with the provided batchify function: `train_bfn = batchify.Tuple(*[batchify.Append() for _ in range(5)]) `. I managed to find a new batchify function by searching this repo and discovered: `train_bfn = batchify.FasterRCNNTrainBatchify(net)` but I could only return a single example despite specifying the batch size, and it threw a new error.

Would someone kindly advise me on a possible solution?

Thank you.

**Comment by zhreshold** [comment]
@SengCheong Sounds like you need to modify the get_dataset and get_dataloader part of this script: https://github.com/dmlc/gluon-cv/blob/c2f6aa15af55dd33fe8af691e685fee5bc2ed9c6/scripts/detection/faster_rcnn/train_faster_rcnn.py#L139-L177

**Comment by SengCheong** [comment]
Hi @zhreshold , thank you for your reply. I actually was referencing that script to customize my training script, but I ran into an error while using the script. There is an incorrect dimension error 
when the ground truth label is being extracted inside the ForwardBackward Task, which i discovered
was most likely due to an incorrect number of examples in the supplied batch. I declared a batch size
of 4 but only received 1 example.

I also noticed that your script is customized for COCODetection or VOCDetection classes.
Can the script accept LSTDetection format? It seems unlikely from the script and there is no
clear way of modifying it to make it compatible.

```
def get_dataloader(net, train_dataset, batch_size, num_workers):

    aspect_ratios = [None] * len(train_dataset)
    for image, label in train_dataset:
        w, h = image.shape[0], image.shape[1]
        aspect_ratios[i] = 1.0 * w / h

    #train_bfn = batchify.Tuple(*[batchify.Append() for _ in range(5)]) 
    train_bfn = batchify.FasterRCNNTrainBatchify(net, 1) #the train_bfn discovered from the gluoncv repos which ba
    
    #derived from script
    train_sampler = gcv.nn.sampler.SplitSortedBucketSampler(aspect_ratios,
                                                           batch_size,
                                                           num_parts=1,
                                                           part_index=0,
                                                           shuffle=False)    
    train_loader = mx.gluon.data.DataLoader(train_dataset.transform(FasterRCNNDefaultTrainTransform(net.short, net.max_size, net, ashape=net.ashape, multi_stage=True)),
                                            batch_size, batch_sampler=None, batchify_fn=train_bfn,
                                            last_batch='rollover', num_workers=num_workers)
    return train_loader
  
def split_and_load(batch, ctx_list):
    """Split data to 1 batch each device."""
    num_ctx = len(ctx_list)
    new_batch = []
    for i, data in enumerate(batch):
        new_data = [x.as_in_context(ctx) for x, ctx in zip(data, ctx_list)]
        new_batch.append(new_data)
    return new_batch
```

Training Loop:
```
#report status for training
print(f"Starting Training @ {start_epoch+1}/{end_epoch} Epochs. Reporting loss every {batch_reporter} batch")

start_time = time.time()
for epoch in range(start_epoch, end_epoch):
    rcnn_task = ForwardBackwardTask(net, trainer, rpn_cls_loss, rpn_box_loss, rcnn_cls_loss, rcnn_box_loss)
    executor = Parallel(1, rcnn_task)  
    #metrics
    for metric in rcnn_losses:
        metric.reset()
    tic = time.time()
    btic = time.time()
    #timers
    tic = time.time() #currently unused
    btic = time.time() #batch time
    #setup the network into static computation graph for faster computation
    net.hybridize(static_alloc=True, static_shape=True)
    #main training loop, batch
    for i, batch in enumerate(train_batcher):
        #get batch size  
        batch = split_and_load(batch, ctx_list=ctx)
        batch_size = len(batch[0])
        print("declared batch size: ", declared_batch_size, "recieved batch_size", batch_size)
        metric_losses = [[] for _ in metrics]
        add_losses = [[] for _ in metrics2]
        #load the gpu context into the data, class targets and box targets
        for data in zip(*batch):
          executor.put(batch)
        #iterate over the contexts
        for j in range(len(ctx)):
            result = executor.get()
            for k in range(len(metric_losses)):
                metric_losses[k].append(result[k])
            for k in range(len(add_losses)):
                add_losses[k].append(result[len(metric_losses) + k])
        for metric, record in zip(metrics, metric_losses):
            metric.update(0, record)
        for metric, records in zip(metrics2, add_losses):
            for pred in records:
                metric.update(pred[0], pred[1])
        trainer.step(batch_size)
        
        if i % batch_reporter == 0:
            msg = ','.join(
                ['{}={:.3f}'.format(*metric.get()) for metric in metrics + metrics2])
            logger.info('[Epoch {}][Batch {}], Speed: {:.3f} samples/sec, {}'.format(
                epoch, i, batch_size / (time.time() - btic), msg))
            btic = time.time()
    #save after every #save_epoch , excluding the first
    if (epoch + 1) % save_epoch == 0:
        save_chkpt(net,net_name,trainer, epoch, end_epoch, chkpt_dir)    
        print(f"Saved training checkpoint: {epoch+1}/{end_epoch} Epochs")
```

Error:
```
Starting Training @ 1/100 Epochs. Reporting loss every 20 batch
declared batch size:  4 recieved batch_size 1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-55-23384cfcf3f0> in <module>()
     59         #load the gpu context into the data, class targets and box targets
     60         for data in zip(*batch):
---> 61           executor.put(batch)
     62         #iterate over the contexts
     63         for j in range(len(ctx)):

1 frames
<ipython-input-53-75351ee148b5> in forward_backward(self, x)
     18 
     19         with autograd.record():
---> 20             gt_label = label[:, :, 4:5]
     21             gt_box = label[:, :, :4]
     22             cls_pred, box_pred, roi, samples, matches, rpn_score, rpn_box, anchors = net(

TypeError: list indices must be integers or slices, not tuple
```

**Comment by Jerryzcn** [comment]
I would recommend you writing your own custom batchify function
