### ISSUE TITLE
Transfer learning for semantic segmentation

### ISSUE THREAD

**Issue by roy6324** [dmlc/gluon-cv#969]
Hello @zhreshold ,
I read the Transfer Learning for Classification Issue which is why I tagged you :).

Using Gluoncv, I'm trying to finetune the deeplab_resnet101_voc model on my custom dataset, I edited the number of classes in Gluoncv/data/pascal_voc/segmentation.py to match my dataset's classes number. Whenever I try to load the original params file (saved in gluoncv for deeplab_resnet101_voc) , it fails because the number of classes have changed (the last Conv2d layer in the Deeplab_head doesn't accept that[weight and bias shapes]),what I did is I loaded the old model (21 classes) with its pre-trained weights, then re-initialized the Conv2d layer(last layer of DeepLab_head) with the number of channels matching my number of classes.
It actually worked and gave perfect results, but I was wondering if there's any easier way to do that. 
Appreciate your help !

**Comment by zhreshold** [comment]
Actually this is exactly the process of doing transfer learning from pretrained model. I will repeat the same steps as you did but might to make a convenient wrapper like the case of object detection models: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/ssd/presets.py#L736 and the reset_class is simply a wrapper which reinitialize the last layers: https://github.com/dmlc/gluon-cv/blob/c2f6aa15af55dd33fe8af691e685fee5bc2ed9c6/gluoncv/model_zoo/ssd/ssd.py#L226

**Comment by roy6324** [comment]
Hello @zhreshold , 
Thank you for your answer it was really helpful ! :)
I actually have one more question. What's the difference between the v1s resnets and the v1b ?
I really appreciate your time and your help!

**Comment by bryanyzhu** [comment]
Hi, the difference is at the first convolutional layer. 

For v1b, we have a single conv layer with kernel size 7x7, as defined [here](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnetv1b.py#L159). This is the standard way of doing resnet. 

For v1s, we change the single conv layer to three conv layers with kernel size 3x3. This is a good practice to improve performance. You can see the changes [here](https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/resnetv1b.py#L162-L172)
