### ISSUE TITLE
Print out label with confidence no bbox

### ISSUE THREAD

**Issue by jayabrams** [dmlc/gluon-cv#974]
Hi!
I'm using the `demo_ssd.py` object detection script to do a simple detection on an image and it works great. 
I'd like to, however, simply print out a list of the class labels and the confidences associated with each detection (maybe as a tuple?). Instead of using `utils.viz.plot_bbox()` to create a plotted bbox overlayed on the img I just want to print out the results to stdout. Looked through the docs and didn't find this specifically, just wondering if there's anything in the api already written to do this?

thank u

**Comment by zhreshold** [comment]
you can print out the scores and cls_ids rather than visualize them

**Comment by dai-ichiro** [comment]
This might be helpful:
[https://discuss.mxnet.io/t/print-detected-objects-in-object-detection-algorithm/4570](https://discuss.mxnet.io/t/print-detected-objects-in-object-detection-algorithm/4570)
