### ISSUE TITLE
cpp prebuilt binaries with CUDA 10.1 and mkl support for linux

### ISSUE THREAD

**Issue by djaym7** [dmlc/gluon-cv#980]
Hi, 
I tested the yolov3-darknet53 model on cpp inference and on mxnet hybridized/symbolic graph.
mxnet python on cuda101mkl - 4.03ms
cpp on cuda9 for linux - 854ms
cpp on cpu  - 1585ms 

All these is on amazon aws ec2 p2.16x instance.

These results show that cpp inference is worse than the python or suggest that cuda 10.1 is ~5x better than cuda 9. 

Is there a way i can make cpp inference use cuda 10 and intel mkl (cuda101mkl) ?

**Comment by zhreshold** [comment]
the provided library is not optimized and just used for demo purpose. You can build your own cuda 10 and mkl lib from source.

**Comment by djaym7** [comment]
I built my own using the tutorials using the guides below but the cpp performance (inference time in ms - ) is always slower than the python. Here is the table for that 

Python,   GPU | 3.61   ms +/- 106 microsec per loop. (mean +/- stdev of 100 runs, 100 loops each
-- | --
Python,   CPU | 3.39   ms +/- 6.05 microsec per loop. (mean +/- stdev of 100 runs, 100 loops each
C++,   GPU, CUDA 10 | 370   ms avg. of 5 runs
C++,   GPU, CUDA9 | 854   ms, avg. of 5 runs
C++,   CPU, CUDA 9 | 1585   ms, avg. of 5 runs

AWS EC2 instances p2.16xlarge for everything. Is cpp supposed to be better than python inference or i am doing something wrong here ?


https://mxnet.apache.org/get_started/ubuntu_setup.html

**Comment by djaym7** [comment]
On hold for now..
