### ISSUE TITLE
run demo_ssd.py gets error

### ISSUE THREAD

**Issue by ghost** [dmlc/gluon-cv#998]
----------Python Info----------
Version      : 3.5.6
Compiler     : GCC 7.3.0
Build        : ('default', 'Aug 26 2018 21:41:56')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 10.0.1
Directory    : /home/z440/miniconda3/envs/mxnet/lib/python3.5/site-packages/pip
----------MXNet Info-----------
Version      : 1.6.0
Directory    : /home/z440/miniconda3/envs/mxnet/lib/python3.5/site-packages/mxnet
Commit Hash   : b1932c027ba8df081ca398dd8b5d3a893c5bc61d
Library      : ['/home/z440/miniconda3/envs/mxnet/lib/python3.5/site-packages/mxnet/libmxnet.so']

**Comment by coltzwz** [comment]
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Invalid Parameter format for clip expect float but value='None', in operator _contrib_box_decode(name="", format="center", std3="0.2", std2="0.2", clip="None", std1="0.1", std0="0.1")
